### ISSUE TITLE
Bayesian Base Class

### ISSUE THREAD

**Issue by snigam3112** [pgmpy/pgmpy#1]
This must include basics as shown in README.md

**Comment by ankurankan** [comment]
Networkx node structure example:

``` python
G = nx.Graph()

G.add_nodes_from([1,2,3,4])

G.node[1]
Out[54]: {}

G.node
Out[55]: {1: {}, 2: {}, 3: {}, 4: {}}

G.node[1]['cpd'] = [[1],[2],[3]]

G.node
Out[57]: {1: {'cpd': [[1], [2], [3]]}, 2: {}, 3: {}, 4: {}}

G.node[1]['states'] = ['A', 'B', 'C']

G.node
Out[59]: {1: {'cpd': [[1], [2], [3]], 'states': ['A', 'B', 'C']}, 2: {}, 3: {}, 4: {}}
```

**Comment by snigam3112** [comment]
Since the states A,B,C will also require a boolean attached to them, we would be required to use a dictionary, right?
But, if we use a dictionary, we will lose the "ordering" of the states.
Thoughts?

**Comment by ankurankan** [comment]
We can use OrderedDicts. What do you think?

**Comment by snigam3112** [comment]
Yes. Just reading through it. They are supported Py2.7+

**Comment by snigam3112** [comment]
Do I add checks for correct data type passed in each function?

**Comment by ankurankan** [comment]
Yes..

**Comment by snigam3112** [comment]
Also, to maintain the relationship between the internal alphabetical order of states and user-defined order, will I map:
1. state-name from alphabetical order and index from user-defined order
2. index from alphabetical order and index from user-defined order

If 2 then, we can't use OrderedDict as it does not allow indexing. If 2, we will have to use tuples.
