### ISSUE TITLE
Using BaseEstimator class for learning parameters of DBN

### ISSUE THREAD

**Issue by danalvi** [pgmpy/pgmpy#1009]
Hello!

Hope everyone in the pgmpy development team is doing great. It is a great tool which helped me a lot in my final year project.

pgmpy did not support structure learning Dynamic Bayesian Networks. However, it seems that if one wants to learn parameters, one can use BaseEstimator class and create an implementation of CPD estimation. I do not understand how that is possible and it would be great if someone could post a MWE for that.

Thank you so much!

**Comment by khalibartan** [comment]
@DanishAmjadAlvi As of now pgmpy support structure learning and parameter learning for Discrete Bayesian Models (Bayesian Models with TabularCPD). You can look at the notebook at [here](https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/9.%20Learning%20Bayesian%20Networks%20from%20Data.ipynb)

**Comment by danalvi** [comment]
I am very sorry, I entirely forgot mentioning that I am talking about Dynamic Bayesian Networks.

**Comment by ankurankan** [comment]
@DanishAmjadAlvi The `BaseEstimator` class basically gives you access to the variables of the network and some generic methods. You can have a look at it here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/estimators/base.py#L9. And for writing a new estimator algorithm you will just need to extend the `BaseEstimator` class and you can write your methods using the variables and methods in BaseEstimator.

**Comment by danalvi** [comment]
Thank you so much @ankurankan. I will get back to you in case I have an issue writing the estimator.

**Comment by ankurankan** [comment]
Parameter estimation has been implemented now. Closing.
