### ISSUE TITLE
Support for networkx 2.1

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#1011]
### Subject of the issue
Breaking changes in networkx from 1.11 to 2.1. 

### Your environment
* pgmpy version: dev latest
* Python version: 2.7, 3.4, 3.5, 3.6
* Operating System: Linux, Mac, Windows

### Steps to reproduce
Run the tests

### Expected behaviour
All tests should pass

### Actual behaviour
93 errors and 33 fails

**Comment by alirezaomidi** [comment]
Any plan to resolve this issue?

**Comment by Erotemic** [comment]
Does anyone have any idea how difficult this issue would be to address / how many places in pgmpy would need to be modified?

**Comment by ankurankan** [comment]
@Erotemic This isn't particularly hard but requires quite a bit of change. Most of the changes will be in the tests.

**Comment by ankurankan** [comment]
Fixed.
