### ISSUE TITLE
Learning parameters from data: Unexpected results of given example

### ISSUE THREAD

**Issue by michalisfrangos** [pgmpy/pgmpy#1012]
### Your environment
* pgmpy version : 0.1.6 (installed with conda)
* Python version: 3.5.5
* Operating System: windows

### Steps to reproduce
Run the last example given for learning the CPT from data [here](https://github.com/pgmpy/pgmpy/blob/dev/examples/Learning%20from%20data.ipynb)

This is the example for Learning with Bayesian Estimator using dirichlet prior for each variable.

### Expected behaviour
Since the data was randomly generated with equal probabilities for each state, the data tries to bring the posterior probabilities close to 0.5. But because of the prior we will get the values in between the prior and 0.5.

### Actual behaviour
CPD of L and CPD of S   obtain exactly the same values as the priors (repeated the example  several times).

**Comment by ankurankan** [comment]
@michalisfrangos I think the values are correct. In the case of `L` the values are near to 0.5 as we have the prior at 0.5 and the data is randomly generated. In the case of `S` the change from the prior is not much (it does move slightly towards 0.5) because we are dealing with a variable having a parent because of which we have a smaller data for each state (remember that the prior is still with 1000 samples). This is one of the drawbacks of bayesian networks that the we end up with very small datasets for variables having lots of parents.

**Comment by michalisfrangos** [comment]
Hi Ankan, 

Thanks for the response. My concern is that these values remain exactly the same as the prior at numerical precision. This example is small enough , and I would have expected to see some changes (as shown in the results you've got on github). 

Here is a screenshot to clarify...

![pgm](https://user-images.githubusercontent.com/17205240/39194711-3bdd1952-47d6-11e8-89a8-369e2d1aa28b.png)

Thanks, 
M

**Comment by michalisfrangos** [comment]
Hi Ankur,

I was just wondering, were you able to reproduce the results in the example above (with pgmpy 0.1.6, conda install) as given on your git ? Or do you get the same results as the ones I posted above? 

Many thanks,
Michalis

**Comment by Yanjiayork** [comment]
Hi , I have also met a similar problem today with the given example that I use MaximumLikelihoodEstimator to estimate the parameters of the Bayesian model (D, I, G, S, L). I randomly generated a (1000, 5) dataset. I always get the CPD for S and L are 0.5(see the pic below). Even I change to generate 100 or 10 or 10000 rows dataset, the CPDs for S and L never change. 
<img width="681" alt="screen shot 2019-01-16 at 21 04 40" src="https://user-images.githubusercontent.com/36036634/51278681-23260980-19d3-11e9-8297-db4e76f97870.png">

**Comment by ankurankan** [comment]
@Yanjiayork The problem was because of using pandas > 0.2. This has been fixed in version 0.1.7 which you can install through pip or the dev branch.

**Comment by Yanjiayork** [comment]
@ankurankan Hi Ankur, Thank you very much for the quick reply. I just tried to update the version by using $ git clone https://github.com/pgmpy/pgmpy 
$ cd pgmpy/
$ pip install -r requirements.txt
$ python setup.py install
 but met the problem at the last step that _**Removing pgmpy 0.1.6 from easy-install.pth file
Adding pgmpy 0.1.7 to easy-install.pth file
error: [Errno 13] Permission denied: '/Users/yan/anaconda/lib/python3.5/site-packages/easy-install.pth**_

**Comment by ankurankan** [comment]
@Yanjiayork Seems like a permission issue with your system. So, either the user with which you are logged into the system doesn't have the permission to change the files or maybe you initially used sudo to install 0.1.6.

**Comment by Yanjiayork** [comment]
@ankurankan  I used **$** conda install -c ankurankan pgmpy **installed** it.  Is there a way that I can uninstall it and then install the latest version or there are some other options? Thanks.

**Comment by ankurankan** [comment]
@Yanjiayork I am not really sure how to fix it, posting on stackoverflow might help. The easiest way would be to create a new conda env and install there.

**Comment by Yanjiayork** [comment]
@ankurankan Hi ankurankan, thank you very much for the advice. I did just create a new conda environment and problem sorted. Thank you very much again.
