### ISSUE TITLE
Score-based Structure Learning: Error in Example

### ISSUE THREAD

**Issue by EricMibu** [pgmpy/pgmpy#1018]
### Subject of the issue

I tried to reproduce your exact Score-based Structure Learning "scoring functions" code here. 

https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/9.%20Learning%20Bayesian%20Networks%20from%20Data.ipynb

And this is the error that I got:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-b6a10151d702> in <module>()
      6 model2 = BayesianModel([('X', 'Z'), ('X', 'Y')])  # Y <- X -> Z
      7 
----> 8 print(bdeu.score(model1))
      9 print(k2.score(model1))
     10 print(bic.score(model1))

/anaconda2/lib/python2.7/site-packages/pgmpy/estimators/StructureScore.pyc in score(self, model)
     68         score = 0
     69         for node in model.nodes():
---> 70             score += self.local_score(node, model.predecessors(node))
     71         score += self.structure_prior(model)
     72         return score

/anaconda2/lib/python2.7/site-packages/pgmpy/estimators/BdeuScore.pyc in local_score(self, variable, parents)
     51         var_states = self.state_names[variable]
     52         var_cardinality = len(var_states)
---> 53         state_counts = self.state_counts(variable, parents)
     54         num_parents_states = float(len(state_counts.columns))
     55 

/anaconda2/lib/python2.7/site-packages/pgmpy/estimators/base.pyc in state_counts(self, variable, parents, complete_samples_only)
    115             parents_states = [self.state_names[parent] for parent in parents]
    116             # count how often each state of 'variable' occured, conditional on parents' states
--> 117             state_count_data = data.groupby([variable] + parents).size().unstack(parents)
    118 
    119             # reindex rows & columns to sort them and to add missing ones

TypeError: can only concatenate list (not "dictionary-keyiterator") to list

### Your environment
* pgmpy version: 0.1.6
* Python version: 2.7
* Operating System: MacOs High Sierra

### Steps to reproduce

Run using jupyter notebook the Score-based Structure Learning "scoring functions" code provided at this link. 

https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/9.%20Learning%20Bayesian%20Networks%20from%20Data.ipynb

### Expected behaviour

Was expecting the output shown on the example i.e.
"-13936.101051153362
-14326.88012027081
-14292.1400887
-20902.744280734016
-20929.567083476162
-20946.7926535"

### Actual behaviour

I get a "TypeError: can only concatenate list (not "dictionary-keyiterator") to list"

**Comment by ankurankan** [comment]
Error because of networkx. Fixed now.
