### ISSUE TITLE
Estimators for Parameter and Structure Learning: ConstraintBasedEstimator Error

### ISSUE THREAD

**Issue by bridgettripp** [pgmpy/pgmpy#1021]
### Subject of the issue
I am following the Estimators for Parameter and Structure Learning example and encounter an error whenever a ConstraintBasedEstimator function is called. 

### Your environment
* pgmpy 0.1.6
* Python 3.6
* Linux

### Steps to reproduce
I am following the Estimators for Parameter and Structure Learning example. http://pgmpy.org/estimators.html#hill-climb-search

The error starts with the fourth block of code and is carried through whenever a ConstraintBasedEstimator function is called.

### Expected behaviour
skel, sep_sets = ConstraintBasedEstimator.build_skeleton("ABCD", ind)
print(skel.edges())
[('A', 'D'), ('B', 'D'), ('C', 'D')]

### Actual behaviour
Here is the error messages I receive when working with examples that use functions from ConstraintBasedEstimator

TypeError                                 Traceback (most recent call last)
<ipython-input-32-5fd98f1dad41> in <module>()
      4 # admit a faithful representation:
      5 ind = ind.closure()
----> 6 skel, sep_sets = ConstraintBasedEstimator.build_skeleton("ABCD", ind)
      7 print(skel.edges())

~/.conda/envs/py36/lib/python3.6/site-packages/pgmpy/estimators/ConstraintBasedEstimator.py in build_skeleton(nodes, independencies)
    520         lim_neighbors = 0
    521         separating_sets = dict()
--> 522         while not all([len(graph.neighbors(node)) < lim_neighbors for node in nodes]):
    523             for node in nodes:
    524                 for neighbor in graph.neighbors(node):

~/.conda/envs/py36/lib/python3.6/site-packages/pgmpy/estimators/ConstraintBasedEstimator.py in <listcomp>(.0)
    520         lim_neighbors = 0
    521         separating_sets = dict()
--> 522         while not all([len(graph.neighbors(node)) < lim_neighbors for node in nodes]):
    523             for node in nodes:
    524                 for neighbor in graph.neighbors(node):

TypeError: object of type 'dict_keyiterator' has no len()

**Comment by ankurankan** [comment]
@bridgettripp Downgrading networkx to 1.11 should fix the issue.
