### ISSUE TITLE
BIFReader function parsing model in unexpected way

### ISSUE THREAD

**Issue by asdfgeoff** [pgmpy/pgmpy#1022]
I am trying to follow the structure of the example notebook [Creating a Bayesian Network](https://github.com/pgmpy/pgmpy/blob/dev/examples/Creating%20a%20Bayesian%20Network.ipynb) using the [earthquake.bif](http://www.bnlearn.com/bnrepository/earthquake/earthquake.bif.gz) dataset. I am using the code below to load the model into a jupyter notebook.

```py
! curl -O http://www.bnlearn.com/bnrepository/earthquake/earthquake.bif.gz
! gzip -qd earthquake.bif.gz
from pgmpy.readwrite import BIFReader
reader = BIFReader('earthquake.bif')
model = reader.get_model()

for cpd in model.get_cpds():
    print(cpd)
```

It appears that `BIFReader` expects the CPDs to be in a particular order and parses them as such. The snippet below is taken from the `earthquake.bif` file. 

```
probability ( JohnCalls | Alarm ) {
  (True) 0.9, 0.1;
  (False) 0.05, 0.95;
}
```

However the output of the parsed cpd is:
```
╒═════════════╤═════════╤═════════╕
│ Alarm       │ Alarm_0 │ Alarm_1 │
├─────────────┼─────────┼─────────┤
│ JohnCalls_0 │ 0.9     │ 0.05    │
├─────────────┼─────────┼─────────┤
│ JohnCalls_1 │ 0.1     │ 0.95    │
╘═════════════╧═════════╧═════════╛
```

Is this a bug? Given this is an example dataset from bnlearn, I would expect it is in a standard format.  How can I get `BIFReader` to parse the file correctly, without manually modifying the file to fit the expected format?

**Comment by ankurankan** [comment]
@asdfgeoff pgmpy automatically assigns the first-mentioned state to be state 0 and then state 1. So, in this case pgmpy assigns 0 to True state and 1 to False state. If we consider that, I think the values of the CPD are correct.
