### ISSUE TITLE
ModuleNotFoundError: No module named 'pgmpy' in jupyter notebook

### ISSUE THREAD

**Issue by essie-chiang** [pgmpy/pgmpy#1024]
### Subject of the issue
After I follow the instructions at page https://github.com/pgmpy/pgmpy/blob/dev/README.md
I open jupyter notebook, run code in example, get the error "ModuleNotFoundError: No module named 'pgmpy' "

### Your environment
* pgmpy version 0.1.6
* Python version 3.6 3.5 (I tried them both)
* Operating System macos High Sierra 10.13.6

### Steps to reproduce
Tell us how to reproduce this issue. Please provide the complete code if possible.
I tried all the three kinds install steps in README, and check pgmpy from conda list and pip list.
I check ipython from command line, no error for import pgmpy. Also I download the ipython as py file, works well.

But I run jupyter notebook of example ipython files. get error "ModuleNotFoundError: No module named 'pgmpy' "

**Comment by ankurankan** [comment]
@sphinx-jiang Could you please give us more information on how did you install pgmpy?

**Comment by essie-chiang** [comment]
create --name pgm35 python=3.5
source activate pgm35
gift:pgmpy admin$ source activate pgm35
(pgm35) gift:pgmpy admin$ conda install -c ankurankan pgmpy
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/admin/anaconda3/envs/pgm35:

The following NEW packages will be INSTALLED:

    blas:            1.0-mkl              https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    decorator:       4.1.2-py35_0         https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    mkl:             2017.0.3-0           https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    networkx:        1.11-py35_0          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    numpy:           1.13.1-py35_0        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pandas:          0.20.3-py35_0        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pgmpy:           0.1.6-py35h8fcecb5_0 ankurankan
    pyparsing:       2.2.0-py35_0         https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    python-dateutil: 2.6.1-py35_0         https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pytz:            2017.2-py35_0        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    scipy:           0.19.1-np113py35_0   https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    six:             1.10.0-py35_0        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    wrapt:           1.10.11-py35_0       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

Proceed ([y]/n)? y

(pgm35) gift:pgmpy admin$ which conda
/Users/admin/anaconda3/envs/pgm35/bin/conda
(pgm35) gift:pgmpy admin$ conda list | grep pgm
# packages in environment at /Users/admin/anaconda3/envs/pgm35:
pgmpy                     0.1.6            py35h8fcecb5_0    ankurankan

(pgm35) gift:pgmpy admin$ cd examples/
(pgm35) gift:examples admin$ jupyter notebook
------------------------------------------
open ipython file in example
http://localhost:8888/notebooks/Creating%20a%20Bayesian%20Network.ipynb

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-af83d6e4f870> in <module>()
      1 # Starting with defining the network structure
----> 2 from pgmpy.models import BayesianModel
      3 
      4 cancer_model = BayesianModel([('Pollution', 'Cancer'), 
      5                               ('Smoker', 'Cancer'),

ModuleNotFoundError: No module named 'pgmpy'

**Comment by ankurankan** [comment]
@sphinx-jiang This might be happening because you don't have jupyter installed in the environment. So, it falls back to the root jupyter. Please try installing jupyter in your pgm35 env.

**Comment by sangam-r** [comment]
@ankurankan I had the same problem. Followed the instructions as explained above, I can import bnlearn but when I try to use the methods of bnlearn such as bnlearn.import_DAG, bn.structure_learning.fit it gives an error as 

AttributeError: module 'bnlearn' has no attribute 'import_DAG'
AttributeError: module 'bnlearn' has no attribute 'structure_learning'

![Screen Shot 2020-11-08 at 1 59 28 PM](https://user-images.githubusercontent.com/55857672/98483002-bc3a9b80-21ca-11eb-880c-a83ce1e082d2.png)

**Comment by Pipe-Runner** [comment]
> @ankurankan I had the same problem. Followed the instructions as explained above, I can import bnlearn but when I try to use the methods of bnlearn such as bnlearn.import_DAG, bn.structure_learning.fit it gives an error as
> 
> AttributeError: module 'bnlearn' has no attribute 'import_DAG'
> AttributeError: module 'bnlearn' has no attribute 'structure_learning'
> 
> ![Screen Shot 2020-11-08 at 1 59 28 PM](https://user-images.githubusercontent.com/55857672/98483002-bc3a9b80-21ca-11eb-880c-a83ce1e082d2.png)

Let me try to help you out with this. I'll have to recreate the problem on my end first, so could you please tell me how exactly u ended up installing pgmpy and jupyter notebook? 
Did you install both on a fresh conda env ?

**Comment by sangam-r** [comment]
Ok.

These are the steps:

conda create -n env_bnlearn python=3.8
conda activate env_bnlearn
conda install -c ankurankan pgmpy

Then I deactivated this env and again activated the env_bnlearn

Then I installed bnlearn as- pip install bnlearn

Then installed jupyter as conda install jupyter

Deactivated the env_bnlearn and activated again and opened jupyter typing jupyter-notebook. Then I opened new python notebook and tried the above commands. Still it is showing the same error. 

Thanks

**Comment by sangam-r** [comment]
Ok.

These are the steps:

conda create -n env_bnlearn python=3.8
conda activate env_bnlearn
conda install -c ankurankan pgmpy

Then I deactivated this env and again activated the env_bnlearn

Then I installed bnlearn as- pip install bnlearn

Then installed jupyter as conda install jupyter

Deactivated the env_bnlearn and activated again and opened jupyter typing
jupyter-notebook. Then I opened new python notebook and tried the above
commands. Still it is showing the same error.

Thanks

**Comment by Pipe-Runner** [comment]
@sangam-r Hi, I followed the exact steps that u did and everything worked fine for me. Please check if you have installed things in the correct env.

![screenshot-localhost_8888-2020 11 09-13_29_36](https://user-images.githubusercontent.com/19551058/98514616-c07cbc80-228f-11eb-94ed-099b54459e57.png)

**Comment by ankurankan** [comment]
@sangam-r If the installation of packages went through without any errors, this mostly happens because of jupyter not using the correct environment. There are two common reasons for that: 1) jupyter wasn't installed in the current environment and it's falling back to the system one 2) jupyter has selected the python kernel to be something other than the current environment. You can fix this simply by either installing jupyter inside the environment or changing the kernel settings.

Also, if you want to verify if the packages were correctly installed in your environment, you can just open the python interpreter and try importing the packages.

**Comment by sangam-r** [comment]
Hi Ankur,

I installed jupyter after activating the bnlearn environment and it works.
Uh hu. thank you very much for your help.
