### ISSUE TITLE
Documentation Small Typo

### ISSUE THREAD

**Issue by cruyffturn** [pgmpy/pgmpy#1027]
Hello just wanted to correct a small typo,
In documentation ->Estimators for Parameter and Structure Learning->Contraint Based 

In the title it is written as "Contraint Based", I think it should be "Constraint Based" 
You can find the relevant section in the doc in the following link:

http://pgmpy.org/_modules/pgmpy/estimators/ConstraintBasedEstimator.html#ConstraintBasedEstimator

Thank you for this library and it's very friendly your presentation at SciPy and documentation.

**Comment by ankurankan** [comment]
@cruyffturn Thanks for pointing it out. Would you like to open a pull request for that?

**Comment by ankurankan** [comment]
Fixed in c5ba23a8f7891c0f32df56b24fa2dc5fc0ddbc85

**Comment by ankurankan** [comment]
Fixed in 6568e44
