### ISSUE TITLE
The pgmpy syntax and output needs to be documented more in detail

### ISSUE THREAD

**Issue by nav9** [pgmpy/pgmpy#1036]
When new users see code like this:
```
cpd_smoke = TabularCPD(variable='Smoker', variable_card=2, values=[[0.3], [0.7]])
cpd_b = TabularCPD('B', 2, [[0.3, 0.7], [0.7, 0.3]], evidence=['A'], evidence_card=[2])
```
One of the first questions that come to their minds is what variable_card and evidence_card are. There is no documentation anywhere that explains the meaning of these. Why is the value of evidence card 2? Why is variable_card 2? Why is evidence for A written in a list ['A'] but B is written differently?
These are very obvious explanations that should have been included in the documentation.

There are also other questions that come up. For example:
```
model.get_cpds()

Out[5]:

[<TabularCPD representing P(D:2) at 0x518fef0>,
 <TabularCPD representing P(I:2) at 0x518feb8>,
 <TabularCPD representing P(G:3 | I:2, D:2) at 0x50fcb70>,
 <TabularCPD representing P(L:2 | G:3) at 0x518fe80>,
 <TabularCPD representing P(S:2 | I:2) at 0x7a4bbe0>]
```

What is a user supposed to do with such outputs (there are many)? Is there a way to access each individual CPD using a dot operator? What's the point of showing me an address 0x518fef0 when all I wanted to see is the CPD?

Even when I wanted to view the graph I created, I had to figure it out [through an issue](https://github.com/pgmpy/pgmpy/issues/1016). How-come these basic explanations aren't available in the documentation?

I'd appreciate it if the authors/contributors of pgmpy could begin their tutorials by explaining the syntax and new terms and outputs first, and then move on the the concept explanation. If you need help, I can be a contributor too, and I can help add some of this information into the documentation. But first I need to understand this library too.

If resolving this issue would take some time, then could you at least answer by means of a comment, about what the variable_card and evidence_card are?

**Comment by khalibartan** [comment]
We have thoroughly documented everything. You can have a look at pgmpy.org
for documentation. There you will see description what each fields in
function call means and their output. Same documentation is present in the
codebase.

**Comment by khalibartan** [comment]
We have thoroughly documented everything. You can have a look at pgmpy.org
for documentation. There you will see description what each fields in
function call means and their output. Same documentation is present in the
codebase.

If you want to see table representation of a cpd you can print the cpd. Simply do `print(cpd)` , it will give the table representation.  `evidence_card`  is cardinality of list of evidences, since a cpd can have multiple evidences hence `evidence` is a list.  `variable_card` is cardinality of variable. You can see documentation of tabular cpd at [here](http://pgmpy.org/factors.html#module-pgmpy.factors.discrete.CPD)

**Comment by nav9** [comment]
Thanks, but it was after seeing the documentation and many other online tutorials of pgmpy and the pdf's y'all have released, that I raised this issue.
For the example you just pointed to, 
```
cpd = TabularCPD('grade',3,[[0.1,0.1,0.1,0.1,0.1,0.1],
                                [0.1,0.1,0.1,0.1,0.1,0.1],
                                [0.8,0.8,0.8,0.8,0.8,0.8]],
                                evidence=['diff', 'intel'], evidence_card=[2,3])
```
A user can eventually figure out what the 3 next to 'grade' is. But what is the `[2,3]` for? If anyone tries to figure out that `2` represents `'diff'` and `'intel'`, then is the `3` for matching it with the 3 rows of grade? Now if we are having to specify the cardinality of rows, then why aren't we specifying cardinality of columns. Besides, why do I need to specify cardinality of rows in the first place? When I pass `[[0.1,0.1,0.1,0.1,0.1,0.1], [0.1,0.1,0.1,0.1,0.1,0.1],  [0.8,0.8,0.8,0.8,0.8,0.8]] `to a function, couldn't the function automatically figure out the number of rows and columns?

These are what still confuse me and I'm sure people who go through pgmpy documentation for the first time will struggle with it too. It's easy for the creators to know what the syntax means. Any other person would eventually figure it out too, but my (humble) insistence is that more explanation is needed so that people won't have to struggle with understanding it.

ps: On a side note, you can also use the [uptack](https://en.wikipedia.org/wiki/Up_tack) instead of `_|_`. I had initially got confused on seeing `_|_`.


**UPDATE 5th Nov 2018:** 
I've created a small tutorial for PGMPy now: http://nrecursions.blogspot.com/2018/11/a-simple-tutorial-showing-some-basic.html. Hope it helps newbies.

**Comment by apcode** [comment]
User says documentation is not clear or even present. Developer tells him he's wrong and it is very well documented. Developer needs to listen to what users tell him. The documentation is meant to be of use to users, so when they don't find it or it is not clear to them, then it has failed.

I too find the documentation severely lacking.

Some examples in addition to those mentioned above:
Many descriptions just repeat the method name:
E.g. TabularCPD.normalize(): normalizes the cpd table.
Or not clear: TabularCPD.reduce() - Reduces the cpd table to the context of given variable values.

Many methods have no documentation of the return type. Often I've just had to run code and examine the types, methods available etc. Which is a failure of documentation.

E.g.
BaysianModel.predict_probabilities(),
VariableElimination.query()

The return types are not always obvious, e.g. for VariableElimination.

**Comment by ankurankan** [comment]
@apcode Sorry about that. I have created a new issue (#1122) for listing all the shortcomings in the documentation. It would help us if you could add any other issues that you have been facing.
