### ISSUE TITLE
A suspicious error condition 

### ISSUE THREAD

**Issue by deplay** [pgmpy/pgmpy#1037]
https://github.com/pgmpy/pgmpy/blob/6568e448a1f753364a89000f2c5394327c223267/pgmpy/models/BayesianModel.py#L283

Hi, guys.
I noticed that the line above may has a suspicious error condition:"if node:".
If I load or generate data which has no column labels,this library will employ integers as the names of nodes like [0,1,2,...]. 

if node==0 , the flow will go to the "else：" code block.But 0 is a valid key to get a cpd from cpds.
Maybe the condition should be changed to "if node!=None:"

**Comment by ankurankan** [comment]
@deplay Yes, you are right. Would you like to create a PR for fixing it?

**Comment by deplay** [comment]
Dear Ankur Ankan:
    It's a tiny error and the pull request process is a little complex. If you don't mind,just fix it in your next commits. 
Deplay

**Comment by ankurankan** [comment]
Not fixed in the c5ba23a
