### ISSUE TITLE
How to read a single result (phi) from query?

### ISSUE THREAD

**Issue by pievalentin** [pgmpy/pgmpy#1038]
### Subject of the issue
I would like to use pgmpy inside my pipeline of inference. Everything work fine, the inference work as expected. 
instead of the complete table, now I would like to access a single data point (phi) from the query I make.
I did not find a way to pipe the output of queries to my other functions.

### Environment
* pgmpy version = 0.1.6
* Python version = 3.6
* Operating System = Linux Fedora 28

### Steps to reproduce
Lets say I reproduce this notebook : https://github.com/pgmpy/pgmpy/blob/dev/examples/Inference%20in%20Bayesian%20Networks.ipynb

At the end of the example, we can print the table with the probabilities (phi) using :

`` print(q['bronc'])``
+---------+--------------+
| bronc   |   phi(bronc) |
|---------+--------------|
| bronc_0 |       0.6000 |
| bronc_1 |       0.4000 |
+---------+--------------+

It's perfect. 

But now lets say I want to easily access phi of bronc_0
I can't as the result use the custom class DiscreteFactor
In the source code I did not see a way to access it easily

### Expected behaviour
The best would be to have something like 
`` phi = q['bronc'][0]``
``print(phi)``
-> 0.6000

Is it possible to access a single phi as a string or int? 
It would really help me, I don't want to use a complex regex to access it :sweat_smile: 

Otherwise thanks for the great library!

**Comment by ankurankan** [comment]
@focom The `TabularCPD` has an attribute `values` where all the values of the CPD are stored. And the individual values can be accessed as:
```
In [15]: print(q['bronc'])
+---------+--------------+
| bronc   |   phi(bronc) |
+=========+==============+
| bronc_0 |       0.6000 |
+---------+--------------+
| bronc_1 |       0.4000 |
+---------+--------------+

In [16]: print(q['bronc'].values[0])
0.6
```

**Comment by pievalentin** [comment]
Great! Maybe I should do a PR updating the example with it?

**Comment by ankurankan** [comment]
@focom Sure, that would be great. Thanks.

**Comment by LikhithaNagahanumaiah** [comment]
> @focom The `TabularCPD` has an attribute `values` where all the values of the CPD are stored. And the individual values can be accessed as:
> 
> ```
> In [15]: print(q['bronc'])
> +---------+--------------+
> | bronc   |   phi(bronc) |
> +=========+==============+
> | bronc_0 |       0.6000 |
> +---------+--------------+
> | bronc_1 |       0.4000 |
> +---------+--------------+
> 
> In [16]: print(q['bronc'].values[0])
> 0.6
> ```

did not work for me

**Comment by ankurankan** [comment]
@LikhithaNagahanumaiah Could you share your code, so that I can see what's going wrong?

**Comment by DaniFra** [comment]
And how can i access the variable which generates the maximum phi value (in this case bronc_0)?

**Comment by ankurankan** [comment]
@DaniFra If you want the state with maximum probability, you can use the `map_query` method instead of `query`. It should return a dict of {variable: state} which have the highest probability.

**Comment by sheldamohan** [comment]
Hi - Is there any way I can get the query variables values from the result of belief propagation query in below example : values of D1(0), D2(0), S1(0), S2(0), then phi; Many thanks in advance
D1    | D2    | S1    | S2    |   phi(D1,D2,S1,S2) |
+=======+=======+=======+=======+====================+
| D1(0) | D2(0) | S1(0) | S2(0) |             0.0250 |
+-------+-------+-------+-------+--------------------+
| D1(0) | D2(0) | S1(0) | S2(1) |             0.0625 |
+-------+-------+-------+-------+--------------------+
| D1(0) | D2(0) | S1(0) | S2(2) |             0.0375
