### ISSUE TITLE
BayesianEstimator pseudo_counts inconsistency using dirichlet prior

### ISSUE THREAD

**Issue by ghost** [pgmpy/pgmpy#1042]
pgmpy version: 0.1.6

```python
data = pd.DataFrame(data={'A': [1, 1, 1], 'B': [1, 1, 1], 'C': [1, 1, 0]})
model = BayesianModel([('A', 'C'), ('B', 'C')])
estimator = BayesianEstimator(model, data)
cpd_C = estimator.estimate_cpd('C', prior_type="dirichlet", pseudo_counts=[[10, 20, 10, 10], [10, 10, 10, 10]]) 
print(cpd_C)
```

Produces the error:
Unable to coerce to DataFrame, shape must be (2, 1): given (2, 4)

Apparently every combination of state has to be present in the data to estimate with bayesian estimator since this code works:
```python
data = pd.DataFrame(data={'A': [1, 1, 1], 'B': [1, 1, 1], 'C': [1, 1, 0]})
model = BayesianModel([('A', 'C'), ('B', 'C')])
estimator = BayesianEstimator(model, data)
cpd_C = estimator.estimate_cpd('C', prior_type="dirichlet", pseudo_counts=[[10], [10]]) 
print(cpd_C)
```

But gives a cpd table limited to A=1 and B=1, C from {0,1}.
However I would expect that the pseudo_count is used as prior to determine the probabilities of combinations which do not occur in the dataset.
Therefore P(C=1|A=0,B=0) = 0.5 in the example with  
pseudo_counts=[[10, 20, 10, 10], [10, 10, 10, 10]]

**Comment by ankurankan** [comment]
@hcl734 The error occurs because the data doesn't have all the possible states of variables. For variables `A` and `B` in the data the only state is `1` and pgmpy constructs the CPDs by counting the unique values in the data. But for missing states you can pass an extra parameter `state_name` to the estimator to consider missing states.

```python
In [3]: data = pd.DataFrame(data={'A': [1, 1, 1], 'B': [1, 1, 1], 'C': [1, 1, 0]})
   ...: model = BayesianModel([('A', 'C'), ('B', 'C')])
   ...: estimator = BayesianEstimator(model, data, state_names={'A': [0, 1], 'B': [0, 1], 'C': [0, 1]})
   ...: cpd_C = estimator.estimate_cpd('C', prior_type="dirichlet", pseudo_counts=np.array([[10, 20, 10, 10], [10, 10, 10, 10]])) 
   ...: print(cpd_C)
   ...: 
+------+------+--------------------+------+--------------------+
| A    | A(0) | A(0)               | A(1) | A(1)               |
+------+------+--------------------+------+--------------------+
| B    | B(0) | B(1)               | B(0) | B(1)               |
+------+------+--------------------+------+--------------------+
| C(0) | 0.5  | 0.6666666666666666 | 0.5  | 0.4782608695652174 |
+------+------+--------------------+------+--------------------+
| C(1) | 0.5  | 0.3333333333333333 | 0.5  | 0.5217391304347826 |
+------+------+--------------------+------+--------------------+
```

**Comment by Yanjiayork** [comment]
sigh, since I installed the new pgmpy version: 0.1.7 today. 
I met another problem that I tried and there's no problem in version 0.1.6. 
When I try out the example 
```
import numpy as np
import pandas as pd
raw_data = np.array([0] * 30 + [1] * 70) # Representing heads by 0 and tails by 1
data = pd.DataFrame(raw_data, columns=['coin'])
print(data)
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator, BayesianEstimator
model = BayesianModel()
model.add_node('coin')
model.fit(data, estimator=BayesianEstimator, prior_type='dirichlet', pseudo_counts={'coin': [50, 50]})
print(model.get_cpds('coin'))
```
There is an error 
```
  **File "/Users/yan/anaconda/lib/python3.5/site-packages/pgmpy-0.1.7-py3.5.egg/pgmpy/estimators/BayesianEstimator.py", line 74, in get_parameters
    pseudo_counts=_pseudo_counts)

  File "/Users/yan/anaconda/lib/python3.5/site-packages/pgmpy-0.1.7-py3.5.egg/pgmpy/estimators/BayesianEstimator.py", line 142, in estimate_cpd
    shape=str(cpd_shape)))

ValueError: The shape of pseudo_counts must be: (2, 1)**
```

somehow it seems can't use dirichlet prior any more.

**Comment by ankurankan** [comment]
@hcl734 As the error message says your `pseudo_counts` variable should be of shape (2, 1). Try passing `pseudo_counts={'coin': [[50], [50]]}`

**Comment by Yanjiayork** [comment]
@ankurankan  Hi Ankur, follow what you suggested, the problem  is sorted now. although I do notice that for the new version pgmpy version: 0.1.7, the way to pass pseudo_counts parameters is different from the old version. Anyway, I like the new version. Thank you very much for the help, appreciated. Yan
