### ISSUE TITLE
pgmpy unhashable type: 'dict' when using BeliefPropagation

### ISSUE THREAD

**Issue by UTUnex** [pgmpy/pgmpy#1045]
### Subject of the issue
Describe your issue here.
When I try to use the  BeliefPropagation() to my Markov model, the error : unhashable type: 'dict' was produced.
### Your environment
* pgmpy version latest
* Python version latest
* Operating System windows 10

### Steps to reproduce
Tell us how to reproduce this issue. Please provide the complete code if possible.
#coding=utf-8
from pgmpy.models import MarkovModel
from pgmpy.factors.discrete import TabularCPD
from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import VariableElimination
from pgmpy.inference import BeliefPropagation
G = MarkovModel()
G.add_nodes_from(['C','D','G','I','S'])
#print(len(G))
G.add_edges_from([('C','D'),('D','I'),('D','G'),('G','I'),('I','S')])
# The representation of CPD in pgmpy is a bit different than the CPD shown in the above picture. In pgmpy the colums
# are the evidences and rows are the states of the variable. So the grade CPD is represented like this:
#
#    +---------+---------+---------+---------+---------+
#    | diff    | intel_0 | intel_0 | intel_1 | intel_1 |
#    +---------+---------+---------+---------+---------+
#    | intel   | diff_0  | diff_1  | diff_0  | diff_1  |
#    +---------+---------+---------+---------+---------+
#    | grade_0 | 0.3     | 0.05    | 0.9     | 0.5     |
#    +---------+---------+---------+---------+---------+
#    | grade_1 | 0.4     | 0.25    | 0.08    | 0.3     |
#    +---------+---------+---------+---------+---------+
#    | grade_2 | 0.3     | 0.7     | 0.02    | 0.2     |
#    +---------+---------+---------+---------+---------+
cpd_c = TabularCPD(variable='C', variable_card=2, values=[[3, 7]])
#print(cpd_c)
cpd_d = TabularCPD('D', 2, [[2,3],[8,7]],evidence=['C'], evidence_card=[2])
#print(cpd_d)
cpd_i = TabularCPD('I', 2, [[2,6],[2,2]],evidence=['D'], evidence_card=[2])
#cpd_i = TabularCPD('I', 1, [[2,6]],evidence=['D'], evidence_card=[2])
cpd_g = TabularCPD('G', 3, [[1,4,3,7],[4,4,4,2],[5,2,3,1]],evidence=['D','I'], evidence_card=[2,2])
#cpd_g = TabularCPD('G', 3, [[1,3],[4,4],[5,3]],evidence=['D','I'], evidence_card=[2,2])
#cpd_g = TabularCPD('G', 1, [[1,4,3,7]],evidence=['D','I'], evidence_card=[2,2])
#print(cpd_g)
#cpd_s = TabularCPD('S', 2, [[2,8]],evidence=['I'], evidence_card=[1])
cpd_s = TabularCPD('S', 2, [[2,8],[8,2]],evidence=['I'], evidence_card=[2])
factor_1 = cpd_c.to_factor()
#print(factor_1)
factor_2 = cpd_d.to_factor()
#print(factor_2)
factor_3 = cpd_i.to_factor()
factor_4 = cpd_g.to_factor()
factor_5 = cpd_s.to_factor()
'''
# we can add factors one by one using syntax like G.add_factors(factor_1)
G.add_factors(factor_1)
G.add_factors(factor_2)
G.add_factors(factor_3)
G.add_factors(factor_4)
G.add_factors(factor_5)
'''
'''
# Or we can also add a factors list like G.add_factors(*factors)
factors = [factor_1,factor_2,factor_3,factor_4,factor_5]
G.add_factors(*factors)
#print(G.get_partition_function())

infer = VariableElimination(G)
#infer.query(['G'], evidence={'I': 1})
print(infer.query(['G'],evidence={'I':0})['G'] )
print(infer.query(['S'],evidence={'G':0})['S'] )

'''
#G.add_cpds(cpd_c, cpd_d, cpd_i, cpd_g, cpd_s)
factor_3_update = factor_3 * factor_4
factors = [factor_1,factor_2,factor_3_update,factor_5]
G.add_factors(*factors)
factor_graph = G.to_factor_graph()
bp = BeliefPropagation(G)
#bp.calibrate()

### Expected behaviour
Tell us what should happen
I think at least the belief propagation algorithm should work fine to the markov model
### Actual behaviour
Tell us what happens instead
The typeerror occured
[graphical model3.zip](https://github.com/pgmpy/pgmpy/files/2626293/graphical.model3.zip)

**Comment by ankurankan** [comment]
@UTUnex Could you please double check if you are using networkx 1.11?

**Comment by UTUnex** [comment]
> @UTUnex Could you please double check if you are using networkx 1.11?

Hi, thank you so much that after downgrading to the 1.11 version, it does work now. I wonder whether you will update this great library to fit the newest networkx version in the future ? Anyway please keep updating if possible :)

**Comment by khalibartan** [comment]
@UTUnex If you want to, then you can send in a PR for the change. I don't think it will too difficult change.

**Comment by UTUnex** [comment]
> @UTUnex If you want to, then you can send in a PR for the change. I don't think it will too difficult change.

Hi, thank you very much for your reply but I 'm a newbie here and I feel sorry that I 'm not able to complete this update task. If possible, I hope that you can keep updating this. Anyway I will follow this great library and look forward for more updates :)
