### ISSUE TITLE
Hill climb search taking too long even after LRU cache

### ISSUE THREAD

**Issue by karnatapu** [pgmpy/pgmpy#1049]
### Subject of the issue
Hill climb search takes too long. My data set is 25k and 30 features. It took close to 4 hours even after it changed to LRU cache on Base, Bic files . Do we have any implementation of multithreading. Or do I have to set any method parameters?

data = pd.DataFrame(np.random.randint(0, 15, size=(25000, 30)))
hc = HillClimbSearch(data, scoring_method=BicScore(data))
best_model = hc.estimate()
print(best_model.edges())

### Your environment
* pgmpy latest
* Python 3.6
* Operating System windows

### Steps to reproduce
25 k rows and 30 features with states around 20.

### Expected behaviour
Should finish less than 10 mins

**Comment by kbe206** [comment]
Why do I have problems when ruinning ‘best_model = hc.estimate()’，it shows that  'unsupported operand type(s) for +: 'OutEdgeView' and 'list''
Have you ever had a problem like this?? Thank you

**Comment by ankurankan** [comment]
@karnatapu lru_cache improvement is merged to dev. Now it takes around 26s to run on my machine.

**Comment by karnatapu** [comment]
Looks like LRU_cache improvements are not been merged into dev branch.

**Comment by ankurankan** [comment]
It's merged but hasn't been released yet. https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/estimators/base.py#L67
