### ISSUE TITLE
query methods should accept state names in evidence

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#1052]
### Subject of the issue
query methods of inference algorithms only accept states as `int` in evidence. Instead, it should also accept state names.

### Your environment
* pgmpy version: 0.1.7
* Python version: All
* Operating System: All

**Comment by karnatapu** [comment]
Just curious, is there any ETA on this issue. Hoping to be fixed soon.

**Comment by ankurankan** [comment]
@karnatapu Not really. I don't have the bandwidth to work on this right now. But if someone else wants to give this a try, it shouldn't involve any major changes.
