### ISSUE TITLE
 ImportError: No module named 'pgmpy'

### ISSUE THREAD

**Issue by nagaraja993** [pgmpy/pgmpy#1055]
ImportError Traceback (most recent call last)
in ()
1 # Defining the network structure
----> 2 from pgmpy.models import BayesianModel
3 valve_model = BayesianModel([('V0','V1'),
4 ('V1','V2'),
5 ('V2','V3')])

ImportError: No module named 'pgmpy'

I installed the pgmpy using the command conda install -c ankurankan pgmpy making sure I have all the requirements still I am getting the error

I also checked using nose and it is fine, I tried installing multiple times it doesn't show any error while installing but the module is not being imported.

I also checked all the requirements and they all are satisfied. I also installed the jupyter on the environment and it still didn't work

**Comment by nagaraja993** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-1-88e4f1c33322> in <module>()
      1 # Defining the network structure
----> 2 from pgmpy.models import BayesianModel
      3 valve_model = BayesianModel([('V0','V1'),
      4                              ('V1','V2'),
      5                              ('V2','V3')])

ImportError: No module named 'pgmpy'

I installed the pgmpy using the command conda install -c ankurankan pgmpy making sure I have all the requirements still I am getting the error

**Comment by ankurankan** [comment]
@nagaraja993 Could you double check if you are using jupyter in the same env as you installed pgmpy? Also, make sure that you need to install jupyter in the same env otherwise it will fallback to the default one (if you have one) in which case you won't be able to import. I can't really think of any other reason this might be happening.
