### ISSUE TITLE
Error while reading BIF file

### ISSUE THREAD

**Issue by shivani1401** [pgmpy/pgmpy#1067]
### Subject of the issue
Error 'list assignment index out of range' obtained while trying to read the bif file.

### Your environment
* pgmpy version commit 9277002
* Python version 3.5
* Operating System Ubuntu16.04

### Steps to reproduce
[water.bif.zip](https://github.com/pgmpy/pgmpy/files/2869061/water.bif.zip)

The command:
reader = BIFReader('water.bif')

gives the following error:
   reader = BIFReader('../benchmarks/water.bif')
  File "/home/shivani/.local/lib/python3.5/site-packages/pgmpy-0.1.7-py3.5.egg/pgmpy/readwrite/BIF.py", line 65, in __init__
    self.variable_cpds = self.get_values()
  File "/home/shivani/.local/lib/python3.5/site-packages/pgmpy-0.1.7-py3.5.egg/pgmpy/readwrite/BIF.py", line 258, in get_values
    arr[i][offset] = val
IndexError: list assignment index out of range

**Comment by ankurankan** [comment]
@shivani1401 Thanks for reporting this. Should be fixed in latest dev.

**Comment by JonathanOase** [comment]
Has this problem been solved?

**Comment by ankurankan** [comment]
@JonathanOase Yes, this is fixed now.
