### ISSUE TITLE
Shouldn't map_query return state of Maximum Probability?

### ISSUE THREAD

**Issue by adityalahiri** [pgmpy/pgmpy#1069]
### Subject of the issue
In the example notebook, [here](https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/2.%20Bayesian%20Networks.ipynb)
infer.map_query('G') returns 2. However, the probability of G_0 Is higher than G_2 when infer.query(['G']) ['G'] is printed. Isn't map_query supposed to return the most probable state of the Random Variable passed?
### Your environment
* pgmpy version 0.1.6
* Python version 3
* Operating System Ubuntu 18.04

### Steps to reproduce
Just running the example notebook linked in the description reproduces the result. 

### Expected behaviour
Map_query should print the most probable state of G,ie G_0

### Actual behaviour
Map_Query returns 2

**Comment by ankurankan** [comment]
@arrayslayer This works fine on my machine. Could you please try upgrading to the latest pgmpy version?

**Comment by adityalahiri** [comment]
Yes works. I installed pgmpy first from conda. Could you please update the version there too if possible?

Thanks!

**Comment by ankurankan** [comment]
@arrayslayer Yes, I will do it as soon as possible.
