### ISSUE TITLE
Wrong index for evidence in inference

### ISSUE THREAD

**Issue by daanknoope** [pgmpy/pgmpy#1071]
### Subject of the issue
When using evidence for a map_query in Variable Elimination, PGMPY interprets the evidence to be an array index instead of an observed variable. This causes out of bound errors as well as possible incorrect results (due to the selection of wrong evidence).

### Your environment
* pgmpy version 0.1.7
* Python version 3.7.1
* Operating System Ubuntu 18.04.2

### Steps to reproduce
Tell us how to reproduce this issue. Please provide the complete code if possible.

Run the following code:

```python
from pgmpy.inference import VariableElimination
from pgmpy.models import BayesianModel
import numpy as np
import pandas as pd
values = pd.DataFrame(np.random.randint(low=2, high=4, size=(1000, 5)),
                      columns=['A', 'B', 'C', 'D', 'E'])
model = BayesianModel([('A', 'B'), ('C', 'B'), ('C', 'D'), ('B', 'E')])
model.fit(values)
inference = VariableElimination(model)
phi_query = inference.map_query(['A'], evidence={'B':3})
print(phi_query)
```

**NB: there will only be two possible values (_2_ or _3_), and _3_ is selected as evidence**

### Expected behaviour
The MAP value of A given B=3

### Actual behaviour
Error:

```python
>>> phi_query = inference.map_query(['A'], evidence={'B':3})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daan/anaconda3/lib/python3.7/site-packages/pgmpy/utils/state_name.py", line 167, in __call__
    return f(*args, **kwargs)
  File "/home/daan/anaconda3/lib/python3.7/site-packages/pgmpy/inference/ExactInference.py", line 204, in map_query
    elimination_order=elimination_order)
  File "/home/daan/anaconda3/lib/python3.7/site-packages/pgmpy/utils/state_name.py", line 167, in __call__
    return f(*args, **kwargs)
  File "/home/daan/anaconda3/lib/python3.7/site-packages/pgmpy/inference/ExactInference.py", line 56, in _variable_elimination
    factor_reduced = factor.reduce([(evidence_var, evidence[evidence_var])], inplace=False)
  File "/home/daan/anaconda3/lib/python3.7/site-packages/pgmpy/utils/state_name.py", line 167, in __call__
    return f(*args, **kwargs)
  File "/home/daan/anaconda3/lib/python3.7/site-packages/pgmpy/factors/discrete/DiscreteFactor.py", line 434, in reduce
    phi.values = phi.values[tuple(slice_)]
IndexError: index 3 is out of bounds for axis 1 with size 2
```

**Comment by daanknoope** [comment]
I suspect that it is due to the following assumption in state_name.py (ln 147:152):
```python
if arg_format == self.is_dict_of_states:
    if not any([isinstance(i, str) for i in arg_val.values()]):
        # If the input parameter is consistent with the internal
        # state names architecture
        if not self.return_val:
            return arg_val
```

_This basically assumes that categories are always a string_, and that if they are not, they can be used as indices because they have already been transformed. Converting everything to strings does indeed fix the issue, but that is not a good fix, since PGMPY is otherwise fine with using ints for values everywhere else (this is extensively demonstrated in the examples).

It often accidentally goes right when the values are _0-indexed_, but it is potentially dangerous behavior as having `state_names= {'x':[2,1,0]}` but providing `x=0` as evidence will actually internally mean `x=2`. It also does not work when the range is not 0-indexed.

**Comment by ankurankan** [comment]
Related #1052
