### ISSUE TITLE
Wrong cpt printing when Bayesian network read from bif files

### ISSUE THREAD

**Issue by Tianyangg** [pgmpy/pgmpy#1073]
### Subject of the issue
The output table of bn.get_cpts('<node>') gives values in wrong order.

### Your environment
* pgmpy version 0.1.6?
* Python version 3.7
* Operating System macOS

### An example of the output
Read in file survey.bif from http://www.bnlearn.com/bnrepository/survey/survey.bif.gz
print(survey_model.get_cpds('E'))

this is the probability table
probability ( E | A, S ) {
  (young, M) 0.75, 0.25;
  (adult, M) 0.72, 0.28;
  (old, M) 0.88, 0.12;
  (young, F) 0.64, 0.36;
  (adult, F) 0.7, 0.3;
  (old, F) 0.9, 0.1;
}

### Expected behaviour
╒═════╤══════╤══════╤══════╤══════╤═════╤═════╕
│ A   │ A_0  │ A_0  │ A_1  │ A_1  │ A_2 │ A_2 │
├─────┼──────┼──────┼──────┼──────┼─────┼─────┤
│ S   │ S_0  │ S_1  │ S_0  │ S_1  │ S_0 │ S_1 │
├─────┼──────┼──────┼──────┼──────┼─────┼─────┤
│ E_0 │ 0.75 │ **0.64** │ **0.72** │ **0.7** │ **0.88** │ **0.9** │
├─────┼──────┼──────┼──────┼──────┼─────┼─────┤
│ E_1 │ 0.25 │ 0.36 │ 0.28 │ 0.3 │ 0.12 │ 0.1 │
╘═════╧══════╧══════╧══════╧══════╧═════╧═════╛

### Actual behaviour
╒═════╤══════╤══════╤══════╤══════╤═════╤═════╕
│ A   │ A_0  │ A_0  │ A_1  │ A_1  │ A_2 │ A_2 │
├─────┼──────┼──────┼──────┼──────┼─────┼─────┤
│ S   │ S_0  │ S_1  │ S_0  │ S_1  │ S_0 │ S_1 │
├─────┼──────┼──────┼──────┼──────┼─────┼─────┤
│ E_0 │ 0.75 │ 0.72 │ 0.88 │ 0.64 │ 0.7 │ 0.9 │
├─────┼──────┼──────┼──────┼──────┼─────┼─────┤
│ E_1 │ 0.25 │ 0.28 │ 0.12 │ 0.36 │ 0.3 │ 0.1 │
╘═════╧══════╧══════╧══════╧══════╧═════╧═════╛

**Comment by ankurankan** [comment]
@txs799 I am actually getting correct values on my machine:

```
In [5]: model.get_cpds('E')                                                                                                                                                                                                                    
Out[5]: <TabularCPD representing P(E:2 | A:3, S:2) at 0x7fe83404b0b8>

In [6]: print(_)                                                                                                                                                                                                                               
+-----+------+------+------+-----+------+-----+
| A   | A_0  | A_0  | A_1  | A_1 | A_2  | A_2 |
+-----+------+------+------+-----+------+-----+
| S   | S_0  | S_1  | S_0  | S_1 | S_0  | S_1 |
+-----+------+------+------+-----+------+-----+
| E_0 | 0.75 | 0.64 | 0.72 | 0.7 | 0.88 | 0.9 |
+-----+------+------+------+-----+------+-----+
| E_1 | 0.25 | 0.36 | 0.28 | 0.3 | 0.12 | 0.1 |
+-----+------+------+------+-----+------+-----+
```
Could you please check that you have the latest `dev` branch installed?
