### ISSUE TITLE
ImportError: cannot import name GibbsSampling

### ISSUE THREAD

**Issue by Fangwq** [pgmpy/pgmpy#1079]
I use the code Examples for GibbsSampling. But get the import error-- ImportError: cannot import name. What's the problem here? thank you!

my environment:
* pgmpy version: 0.1.6
* Python version: 2.7.10
* Operating System: macOS Sierra

The code is as follows:
>from pgmpy.inference import GibbsSampling
from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import BayesianModel
intel_cpd = TabularCPD('intel', 2, [[0.7], [0.3]])
sat_cpd = TabularCPD('sat', 2, [[0.95, 0.2], [0.05, 0.8]], evidence=['intel'], evidence_card=[2])
student = BayesianModel()
student.add_nodes_from(['intel', 'sat'])
student.add_edge('intel', 'sat')
student.add_cpds(intel_cpd, sat_cpd)
gibbs_chain = GibbsSampling(student)

print gibbs_chain.sample(size=3)

**Comment by Fangwq** [comment]
I figure out the problem. Sorry to bother

**Comment by khalibartan** [comment]
Can you also send a PR? This [line](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/sampling/Sampling.py#L262) in docs needs to be fixed.

**Comment by Fangwq** [comment]
just revise the first line of the code to be:
`from pgmpy.sampling import GibbsSampling`
