### ISSUE TITLE
How to do inference with gbbis sampling?

### ISSUE THREAD

**Issue by Fangwq** [pgmpy/pgmpy#1080]
According to the example in **class GibbsSampling(MarkovChain)**, I write the code in the following. And the generated samples are changing every times. I am a little confused. It seems that it can't set the fixed evidence in gbbis sampling method. If it is true, then how to do inference with gbbis sampling? Can you show me some reference code? 

Also, I do not understand the input variable **evidence_card** for 
TabularCPD function. It means the number for intel can take or other ?

Thank you very much!

`# -*- coding: utf-8 -*- 
from pgmpy.sampling import GibbsSampling
from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import BayesianModel

intel_cpd = TabularCPD('intel', 2, [[0.7], [0.3]])
sat_cpd = TabularCPD('sat', 2, [[0.95, 0.2], [0.05, 0.8]], evidence=['intel'], evidence_card=[2])
diff_cpd = TabularCPD('diff', 2, [[0.95, 0.2], [0.05, 0.8]], evidence=['intel'], evidence_card=[2])

student = BayesianModel()
student.add_nodes_from(['intel', 'sat', 'diff'])
student.add_edges_from([('intel', 'sat'), ('intel', 'diff')])
student.add_cpds(intel_cpd, sat_cpd, diff_cpd)
gibbs_chain = GibbsSampling(student)

print gibbs_chain.sample(size=3)

The output(run for four times):
   diff  intel  sat
0     0      0    1
1     0      1    1
2     1      1    0

   diff  intel  sat
0     0      0    1
1     0      1    1
2     1      1    1

   diff  intel  sat
0     1      1    1
1     1      1    1
2     1      1    1

0     1      0    0
1     0      0    0
2     0      0    0
`

**Comment by ankurankan** [comment]
@Fangwq Yeah, there is no option to set an evidence in `GibbsSampling` (I have created an issue for it now). Although a simple way to do it right now would be to modify the model (call `reduce` on all child nodes of the evidence and remove the evidence node from the model) and then do sampling on it.

Have a look at documentation here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/factors/discrete/CPD.py#L21 for details on how `TabularCPD` should be defined.

**Comment by Fangwq** [comment]
Ok, I will try it. Thank you for your answer.

**Comment by Fangwq** [comment]
I have question about parameter learning method. It seems that it can't set all the value a node variable can have, then the CPT of the node will be incomplete and it doesn't contain all the possible value of each node(**all possibilities**). So when I do inference(**likelihood_weighted_sample**) after learning parameter with the new data, if the node evidence  has new state value(for example: State('angle', **some new value**)), the code will be wrong. Any suggestions to deal with this situation ? I think this is not the data problem. It is common in time series data problem to predict node value  in next time.

`sampled['_weight'][i] *= weights[i][evidence_dict[node]]
IndexError: index 4 is out of bounds for axis 0 with size 4`

**Comment by ankurankan** [comment]
Dup #1081

**Comment by frMitola** [comment]
Hello @ankurankan, I see that the issue was solved, so is the update of `GibbsSampling` available before the release? I need it for my project

**Comment by ankurankan** [comment]
@fmitola4 Unfortunately, this hasn't been fixed yet. The other duplicate issue is still open. Although, the simplest way to do sampling with evidence is to just select the samples which satisfy your evidence. For example, let's say you have some samples `df` (without any evidence) from a network on variables: `A`, `B`, `C`, and `D`,  If you would like to get samples from this network with the evidence `D=1`, you can simply select those samples using `df[df.D == 1]`, and this would be samples consistent with specifying the evidence. The only problem with this method is that it would reduce the sample size as it would reject some of the samples.

Also, do you want to specifically use GibbsSampling? Because the BayesianNetwork class also has a simulate method for generating samples and is much more versatile.

**Comment by frMitola** [comment]
@ankurankan ok nice thank you, eventually I choose likelihood weighting that allows to insert the evidence. I have another question: GibbsSampling or other sampling methods for Bayesian Network technically allow to do inference, i.e. to calculate the posterior probability P(Q|E) where Q is conjuction of query variables (e.g. X,Y) and E is set of evidence, and that would be another thing that interests me for my project, but it is not available among the functions of this library. Do you have any ideas on how this is done too? With likelihood weighting, I calculated P(Q|E) like this: after generating samples, for each possible combination of domain values ​​of each query variable, I searched occurrence in the samples and added the corresponding weights, dividing everything by the sum of the weights of all the samples.
For example, given the variables X,Y,Z all with domain={0,1} and given the query P(X,Y|Z=1), after generating samples with fixed Z, I searched all occurrences of X= 0, Y= 0 then all occurences X=1, Y =0, ecc.. in samples, I added all corresponding weights of matched samples and I divided it for sum of the weights of all samples

**Comment by ankurankan** [comment]
@fmitola4 Yes, you are right. Methods to directly compute the probabilities from the samples are missing right now. It should be a wrapper class over the Sampling module and should directly output the probabilities of queries. I have created a new issue for adding that: #1455.
I think your method of computing the probabilities from the likelihood-weighted samples is correct. You can follow the same approach for other sampling methods as well. In the other cases, the weight of each sample would just be set to 1. Here's an example using the simulate method:
```python
In [1]: from pgmpy.utils import get_example_model                                                                                                                                                                  
                                                                                                                                                                                                                   
In [2]: alarm = get_example_model('alarm')

# Joint distribution: P(HISTORY, EXPCO2)      
In [4]: samples = alarm.simulate(n_samples=int(1e4))
Generating for node: BP: 100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 151.35it/s]

In [5]: samples.groupby(['HISTORY', 'EXPCO2']).size() / samples.shape[0]
Out[5]:                                             
HISTORY  EXPCO2                                     
FALSE    HIGH      0.0357                           
         LOW       0.8176                           
         NORMAL    0.0513                           
         ZERO      0.0402                           
TRUE     HIGH      0.0022                           
         LOW       0.0475                           
         NORMAL    0.0037                           
         ZERO      0.0018                           
dtype: float64 

# Conditional distribution: P(HISTORY, EXPCO2 |  SHUNT=NORMAL)
In [6]: samples_evidence = alarm.simulate(n_samples=int(1e4), evidence={'SHUNT': 'NORMAL'})
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 25882.12it/s]

In [8]: samples_evidence.groupby(['HISTORY', 'EXPCO2']).size() / samples_evidence.shape[0]
Out[8]: 
HISTORY  EXPCO2
FALSE    HIGH      0.0301
         LOW       0.8415
         NORMAL    0.0347
         ZERO      0.0405
TRUE     HIGH      0.0016
         LOW       0.0464
         NORMAL    0.0025
         ZERO      0.0027
dtype: float64

# And we can also compute the conditional distribution from `samples` without specifying evidence while generating them. 
# This can be used for methods which don't have an option to specify evidence e.g. GibbsSampling. For the conditional 
# distribution: P(HISTORY, EXPCO2 | SHUNT=NORMAL)
In [12]: samples[samples.SHUNT == 'NORMAL'].groupby(['HISTORY', 'EXPCO2']).size() / samples[samples.SHUNT == 'NORMAL'].shape[0]
Out[12]: 
HISTORY  EXPCO2
FALSE    HIGH      0.030867
         LOW       0.838642
         NORMAL    0.035556
         ZERO      0.040831
TRUE     HIGH      0.001731
         LOW       0.048066
         NORMAL    0.002037
         ZERO      0.002270
dtype: float64

# The values in the last two distributions are almost the same as expected but computed with and without specifying the evidence.
```
