### ISSUE TITLE
inference problem for new data

### ISSUE THREAD

**Issue by Fangwq** [pgmpy/pgmpy#1082]
I have question about parameter learning method. It seems that it can't set all the value a node variable can have, then the CPT of the node will be incomplete and it doesn't contain all the possible value of each node(**all possibilities**). So when I do inference(**likelihood_weighted_sample**) after learning parameter with the new data, if the node evidence  has new state value(for example: State('angle', **some new value**)), the code will be wrong. Any suggestions to deal with this situation ? I think this is not the data problem. It is common in time series data problem to predict node value  in next time.

`sampled['_weight'][i] *= weights[i][evidence_dict[node]]
IndexError: index 4 is out of bounds for axis 0 with size 4`

_Originally posted by @Fangwq in https://github.com/pgmpy/pgmpy/issues/1080#issuecomment-475099169_

**Comment by ankurankan** [comment]
@Fangwq I am not sure if I exactly understand the issue but my best guess is that you are looking for `state_names` argument (https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/estimators/base.py#L26). You can specify all the possible states of the variable before learning in case some states don't appear in the data.

Could you please give a small example in case you weren't looking for the `state_names` thing?

**Comment by Fangwq** [comment]
Yeah, that's what I mean. Thank you for your response!

**Comment by Fangwq** [comment]
It solves my problem. Thank you very much! @ankurankan
