### ISSUE TITLE
Some thing wrong with ProbModelXMLWriter

### ISSUE THREAD

**Issue by leidawt** [pgmpy/pgmpy#1083]
* pgmpy version 0.1.7
* Python version py3.5 jupyter notebook
* Operating System windows

Trying to save my BN model with:

from pgmpy.readwrite import ProbModelXMLReader,ProbModelXMLWriter,get_probmodel_data
model_data = get_probmodel_data(model)
writer = ProbModelXMLWriter(model_data=model_data)
writer.write_file('./titanic.pgmx')
#model = ProbModelXMLReader('./titanic.pgmx').get_model()

but these occurs:

KeyError                                  Traceback (most recent call last)
<ipython-input-85-2c2dca14d477> in <module>
      2 #model = ProbModelXMLReader('./titanic.pgmx').get_model()
      3 model_data = get_probmodel_data(model)
----> 4 writer = ProbModelXMLWriter(model_data=model_data)
      5 writer.write_file('./titanic.pgmx')

c:\users\wxh\appdata\local\programs\python\python35\lib\site-packages\pgmpy\readwrite\ProbModelXML.py in __init__(self, model_data, encoding, prettyprint)
    349         # Add variables
    350         for variable in sorted(self.data['probnet']['Variables']):
--> 351             self._add_variable(variable)
    352 
    353         # Add edges

c:\users\wxh\appdata\local\programs\python\python35\lib\site-packages\pgmpy\readwrite\ProbModelXML.py in _add_variable(self, variable)
    383         variable_data = self.data['probnet']['Variables'][variable]
    384         variable_element = etree.SubElement(self.variables, 'Variable', attrib={'name': variable,
--> 385                                                                                 'type': variable_data['type'],
    386                                                                                 'role': variable_data['role']})
    387 

KeyError: 'type'

**Comment by ankurankan** [comment]
@leidawt Thanks for reporting this. Could you please also share your model so that we can reproduce this error?

**Comment by leidawt** [comment]
@ankurankan 
Thanks for your reply!
I built this BN model
*********
from pgmpy.models import BayesianModel
from pgmpy.estimators import BayesianEstimator

model = BayesianModel([('Age', 'Survived'), ('Sex', 'Survived'),('Fare','Pclass'),('Pclass','Survived'),('Cabin','Survived')])
**********
and filled the cpds useing the 'fit' function.This BN model works just fine, it could reach 77% accuracy in the kaggle titanic task.
Full jupyter notebook is here:
link: https://pan.baidu.com/s/1lR3-tiSt-NJgogg4al8u-w 
password: 2yc1

**Comment by ankurankan** [comment]
@leidawt I am sorry I am still unable to reproduce it. Are you doing some kind of preprocessing on the dataset? I am also unable to access the notebook on the link. Would it be possible for you to share the full code (maybe on google colab, or github gist)?

**Comment by leidawt** [comment]
Sorry for the links. I re-uploaded the notebook and  data to google drive, here is the link:
https://drive.google.com/open?id=1sH96q9pVUXBRlJM4truAz21bIZO4FKMO

**Comment by pascal-schetelat** [comment]
Hi, 

I am stuck with the same issue : 
- pgmpy version 'v0.1.8.dev36'
- Python version 3.6
- Operating System windows 7 64 bit 

steps to reproduce (slightly adapted from notebook "2.Bayesian Network") : 

```python
model = BayesianModel([('X', 'Y'), ('Y', 'Z')])

cpd_x = TabularCPD(variable='X', variable_card=2, values=[[0.6, 0.4]])

cpd_y = TabularCPD(variable='Y', variable_card=2, 
                   values=[[0.6, 0.05],
                           [0.4, 0.95],
                           ],
                  evidence=['X'],
                  evidence_card=[2])

cpd_z = TabularCPD(variable='Z', variable_card=2, 
                   values=[[0.1, 0.4],
                           [0.9, 0.6]],
                   evidence=['Y'],
                   evidence_card=[2])
model.add_cpds(cpd_x,cpd_y,cpd_z)

model_data = get_probmodel_data(model)
writer = ProbModelXMLWriter(model_data)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-51-f444c3f72a09> in <module>()
     18 
     19 model_data = get_probmodel_data(model)
---> 20 writer = ProbModelXMLWriter(model_data)

C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\pgmpy-0.1.8.dev36-py3.6.egg\pgmpy\readwrite\ProbModelXML.py in __init__(self, model_data, encoding, prettyprint)
    360         # Add variables
    361         for variable in sorted(self.data["probnet"]["Variables"]):
--> 362             self._add_variable(variable)
    363 
    364         # Add edges

C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\pgmpy-0.1.8.dev36-py3.6.egg\pgmpy\readwrite\ProbModelXML.py in _add_variable(self, variable)
    398             attrib={
    399                 "name": variable,
--> 400                 "type": variable_data["type"],
    401                 "role": variable_data["role"],
    402             },

KeyError: 'type'

```
Funy enought, using the definition of the asia model -(in the read write documentation notebook) does not lead to the same error.

I looked in get_probmodel_data and the issue is that nodes data is empty : 

```python 
model_data 
{'probnet': {'type': 'BayesianNetwork',
  'Variables': {'X': {}, 'Y': {}, 'Z': {}},
  'edges': {"('X', 'Y')": {'weight': None}, "('Y', 'Z')": {'weight': None}},
  'Potentials': [{'Variables': {'X': []},
    'type': 'Table',
    'role': 'conditionalProbability',
    'Values': '0.6 0.4 '},
   {'Variables': {'Y': ['X']},
    'type': 'Table',
    'role': 'conditionalProbability',
    'Values': '0.6 0.05 0.4 0.95 '},
   {'Variables': {'Z': ['Y']},
    'type': 'Table',
    'role': 'conditionalProbability',
    'Values': '0.1 0.4 0.9 0.6 '}]}}
```
Which is caused by model.node

 ```python 
model.node
{'X': {}, 'Y': {}, 'Z': {}}
 ```

Seems that model instanciation using only cpds is at fault here.

I also cannot load the asia model I managed to save : 

 ```python 
writer.write_file('asia.pgmx')
reader_string = ProbModelXMLReader('asia.pgmx')
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-45-929d321cf643> in <module>()
----> 1 reader_string = ProbModelXMLReader('asia.pgmx')

C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\pgmpy-0.1.8.dev36-py3.6.egg\pgmpy\readwrite\ProbModelXML.py in __init__(self, path, string)
    795             raise ValueError("Must specify either 'path' or 'string' as kwarg.")
    796 
--> 797         self.create_probnet()
    798 
    799     def create_probnet(self):

C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\pgmpy-0.1.8.dev36-py3.6.egg\pgmpy\readwrite\ProbModelXML.py in create_probnet(self)
    833         self.probnet["edges"] = {}
    834         for edge in probnet_elem.findall("Links/Link"):
--> 835             self.add_edge(edge)
    836 
    837         # Add CPD

C:\ProgramData\Anaconda2\envs\py36\lib\site-packages\pgmpy-0.1.8.dev36-py3.6.egg\pgmpy\readwrite\ProbModelXML.py in add_edge(self, edge)
    983         >>> reader.add_edge(edge)
    984         """
--> 985         var1 = edge.findall("Variable")[0].attrib["name"]
    986         var2 = edge.findall("Variable")[1].attrib["name"]
    987         self.probnet["edges"][(var1, var2)] = {}

IndexError: list index out of range

 ```
Is there a prefered save backend ?

**Comment by loudly-soft** [comment]
Yeah, I had the same issue with ProbModelXMLWriter as @pascal-schetelat 

My workaround is to use Bip to save and load the model (see code below).  However, for that to work, I needed to:

1. patch the code suggested by @bramson in #38
2. changed my state values to string.  Numeric states seem to cause #1221

```
from pgmpy.models import BayesianModel
from pgmpy.estimators import BayesianEstimator
from pgmpy.readwrite import BIFWriter, BIFReader
import pandas as pd

# define data
df_data = pd.DataFrame([{'A': '1', 'B': '2', 'C': '1'}], columns=['A', 'B', 'C'])

# train
model = BayesianModel([('A', 'B'), ('A', 'C')])
model.fit(df_data, state_names={'A':['1', '2'], 'B':['1', '2'], 'C':['1', '2']}, estimator=BayesianEstimator, prior_type='K2')

# save model
writer = BIFWriter(model)
writer.write_bif("bif_test.bif")

# load model
reader = BIFReader("bif_test.bif")
model = reader.get_model()

# predict
df_test = pd.DataFrame([{'B': '2', 'C': '2'}], columns=['B', 'C'])
print(model.predict_probability(df_test))
```
