### ISSUE TITLE
learn from continuous variable

### ISSUE THREAD

**Issue by Fangwq** [pgmpy/pgmpy#1084]
I have get some data from continuous variable. Can pgmpy learn structure and parameter from continuous variable just like discrete data? How to do it ? I don't find any reference. Thank you very much!

**Comment by khalibartan** [comment]
@Fangwq pgmpy currently doesn't support learning from continuous variables.

**Comment by Fangwq** [comment]
OK, thank you very much!

**Comment by defzhangaa** [comment]
Hi! Is this feature currently available?  3/17/2024

**Comment by ankurankan** [comment]
@defzhangaa Structure learning on continuous data is supported now using the PC algorithm with the argument `ci_test='pearsonr'`. Parameter Learning is unfortunately still not supported.
