### ISSUE TITLE
Minor documentation error on ContinuousFactor.divide

### ISSUE THREAD

**Issue by djinnome** [pgmpy/pgmpy#1091]
### Subject of the issue
The `divide` documentation claims contradictory information about the return type and the operation on the other factor.

`divide(other, inplace=True)`
Gives the ContinuousFactor divide with the other factor.
**Parameters: | other: ContinuousFactor**
       The ContinuousFactor to be ~~multiplied~~ (should be divided).
**Returns:** . ContinuousFactor or None:
             if inplace=True (default) returns None if inplace=False returns a new *~~DiscreteFactor~~* instance. (should be *ContinuousFactor*)

#### Proof the return type is `ContinuousFactor` not `DiscreteFactor`
```python
>>> from scipy.stats import multivariate_normal
>>> sn_pdf1 = lambda x: multivariate_normal.pdf([x], [0], [[1]])
>>> sn_pdf2 = lambda x1,x2: multivariate_normal.pdf([x1,x2], [0,0], [[1,0],[0,1]])
>>> sn1 = ContinuousFactor(['x2'], sn_pdf1)
>>> sn2 = ContinuousFactor(['x1', 'x2'], sn_pdf2)
>>> sn3 = sn2.divide(sn1, inplace=False)
>>> type(sn3)
pgmpy.factors.continuous.ContinuousFactor.ContinuousFactor
```

#### Proof the operation is divide, not multiply
```python
>>> sn1.assignment(0)
0.3989422804014327 
>>> sn2.assignment(0,0)
0.15915494309189535
>>> sn3.assignment(0,0)
0.3989422804014327  
>>> sn4 = sn1.product(sn2)
>>> sn4.assignment(0,0)
0.06349363593424098
```

**Comment by ankurankan** [comment]
@djinnome Thanks for pointing this out.
