### ISSUE TITLE
Error in reading .bif file

### ISSUE THREAD

**Issue by shivani1401** [pgmpy/pgmpy#1093]
### Subject of the issue
Error in reading .bif file
[alarm.bif.zip](https://github.com/pgmpy/pgmpy/files/3088052/alarm.bif.zip)

### Your environment
* pgmpy version pgmpy-0.1.7-py3.5.egg
* Python version python3.5
* Operating System ubuntu 16.04

### Steps to reproduce
reader = BIFReader('alarm.bif')
model = reader.get_model()
infer = VariableElimination(model)

### Expected behaviour
The model looks consistent but the program shows an error.

probability ( PRESS | INTUBATION, KINKEDTUBE, VENTTUBE ) {
  (NORMAL, TRUE, ZERO) 0.97, 0.01, 0.01, 0.01;
  (ESOPHAGEAL, TRUE, ZERO) 0.01, 0.30, 0.49, 0.20;
  (ONESIDED, TRUE, ZERO) 0.01, 0.01, 0.08, 0.90;
  (NORMAL, FALSE, ZERO) 0.01, 0.01, 0.01, 0.97;
  (ESOPHAGEAL, FALSE, ZERO) 0.97, 0.01, 0.01, 0.01;
  (ONESIDED, FALSE, ZERO) 0.10, 0.84, 0.05, 0.01;
  (NORMAL, TRUE, LOW) 0.05, 0.25, 0.25, 0.45;
  (ESOPHAGEAL, TRUE, LOW) 0.01, 0.15, 0.25, 0.59;
  (ONESIDED, TRUE, LOW) 0.97, 0.01, 0.01, 0.01;
  (NORMAL, FALSE, LOW) 0.01, 0.29, 0.30, 0.40;
  (ESOPHAGEAL, FALSE, LOW) 0.01, 0.01, 0.08, 0.90;
  (ONESIDED, FALSE, LOW) 0.01, 0.01, 0.01, 0.97;
  (NORMAL, TRUE, NORMAL) 0.97, 0.01, 0.01, 0.01;
  (ESOPHAGEAL, TRUE, NORMAL) 0.01, 0.97, 0.01, 0.01;
  (ONESIDED, TRUE, NORMAL) 0.01, 0.01, 0.97, 0.01;
  (NORMAL, FALSE, NORMAL) 0.01, 0.01, 0.01, 0.97;
  (ESOPHAGEAL, FALSE, NORMAL) 0.97, 0.01, 0.01, 0.01;
  (ONESIDED, FALSE, NORMAL) 0.40, 0.58, 0.01, 0.01;
  (NORMAL, TRUE, HIGH) 0.20, 0.75, 0.04, 0.01;
  (ESOPHAGEAL, TRUE, HIGH) 0.20, 0.70, 0.09, 0.01;
  (ONESIDED, TRUE, HIGH) 0.97, 0.01, 0.01, 0.01;
  (NORMAL, FALSE, HIGH) 0.01, 0.90, 0.08, 0.01;
  (ESOPHAGEAL, FALSE, HIGH) 0.01, 0.01, 0.38, 0.60;
  (ONESIDED, FALSE, HIGH) 0.01, 0.01, 0.01, 0.97;
}

### Actual behaviour
Traceback (most recent call last):
  File "run.py", line 135, in <module>
    infer = VariableElimination(model)
  File "/home/shivani/python-env/pgmpy_env/lib/python3.5/site-packages/pgmpy-0.1.7-py3.5.egg/pgmpy/utils/state_name.py", line 41, in __call__
    f(*args, **kwargs)
  File "/home/shivani/python-env/pgmpy_env/lib/python3.5/site-packages/pgmpy-0.1.7-py3.5.egg/pgmpy/inference/base.py", line 61, in __init__
    model.check_model()
  File "/home/shivani/python-env/pgmpy_env/lib/python3.5/site-packages/pgmpy-0.1.7-py3.5.egg/pgmpy/models/BayesianModel.py", line 390, in check_model
    " is not equal to 1.".format(node=node))
ValueError: Sum or integral of conditional probabilites for node PRESS is not equal to 1.

**Comment by ankurankan** [comment]
@shivani1401 Thanks a lot for reporting this. This should be fixed in dev now. The problem was in the same code as with your last issue, I have now replaced it completely with simpler logic. So, I hope you wouldn't have any more problems with BIFReader.
