### ISSUE TITLE
Add is_imap method to BayesianModel and JointProbabilityDistribution classes

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#112]
Add these methods:
1. `BayesianModel.is_imap(JointProbabilityDistribution)`
2. `JointProbabilityDistribution.is_imap(BayesianModel)`

**Comment by khalibartan** [comment]
# TODO: refer to IMap class for explanation why this is not implemented
@ankurankan I cannot understand this TODO couldn't find anything related to it.

**Comment by khalibartan** [comment]
@ankurankan Can I work on this issue ?

**Comment by ankurankan** [comment]
@khalibartan Yes please go ahead.

**Comment by khalibartan** [comment]
Basically we just need to check for the product of factors and work accordingly.

**Comment by khalibartan** [comment]
@ankurankan Fixed. We can now close this issue
