### ISSUE TITLE
tqdm usage should be optional

### ISSUE THREAD

**Issue by robbymeals** [pgmpy/pgmpy#1120]
### Subject of the issue
I'm all for progress bars but having them enabled by default is pretty annoying. There should be a global on/off switch, at least. Preferably configurable verbosity levels. Output like this doesn't add much value, IMO...

```
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
```

Also thanks for all the work on this package. It's a wonderful tool!

**Comment by ankurankan** [comment]
@robbymeals Thanks for the feedback. This is definitely not the intended behaviour (I would expect a single progress bar in this case).

Fixes:
- [x] Add argument for disabling progress bars.
- [x] For methods which call other methods with progress bars, disable generating multiple bars.
