### ISSUE TITLE
ContinuousFactor normalize bug by typo

### ISSUE THREAD

**Issue by davenza** [pgmpy/pgmpy#1121]
### Subject of the issue

This line of `ContinuousFactor.normalize()` is wrong because of the typo.

https://github.com/pgmpy/pgmpy/blob/b2ea305e19779891f0d6543d1cbb3a1532a58c03/pgmpy/factors/continuous/ContinuousFactor.py#L303

Also, I don't know why it calls `phi.distribution.normalize()` with `inplace=False`. I think it would be better to call with `inplace=inplace`.

### Your environment
* pgmpy version: Last commit: b2ea305
* Python version: It does not matter
* Operating System: It does not matter

**Comment by ankurankan** [comment]
@davenza Yes, you are right. Would you like to open a Pull Request fixing this?
