### ISSUE TITLE
HillClimbSearch - new install does not reflect changes

### ISSUE THREAD

**Issue by karnatapu** [pgmpy/pgmpy#1125]
Hello, When am doing the PIP install, its not reflecting the fixes to HIllClimbSaerch to boost performance using LRU-cache and also accepting "epsilon and max_iter" as part of estimate method.

here is the reference issue.
https://github.com/ankurankan/pgmpy/commit/e5558fca055ebd942cb75910bdbe3b3c31ab7689

https://github.com/pgmpy/pgmpy/pull/944

Surendra

**Comment by ankurankan** [comment]
@karnatapu Yeah, LRU optimization hasn't been released yet and the pypi version is older. Try installing the `dev` branch to use it.

**Comment by karnatapu** [comment]
kool, Thank you.
I did checked the dev branch code and the method Hillclimb.estimate does not have the additional parameter epsilon and max_iter. 
Max iteration, will certainly useful to speed up the program. Thanks.

**Comment by ankurankan** [comment]
@karnatapu I have added those two parameters to Hill Climb now. You can try it by installing the latest dev.

**Comment by karnatapu** [comment]
Thank you. This helps.
