### ISSUE TITLE
dbnet.initialize_initial_state() is showing error while trying to do inference in Dynamic Bayesian Network

### ISSUE THREAD

**Issue by Priyabrata017** [pgmpy/pgmpy#1135]
### Subject of the issue
dbnet.initialize_initial_state() is showing error
error is-  
  File "c:\python\python36\lib\site-packages\pgmpy\models\DynamicBayesianNetwork.py", line 510, in <genexpr>
    if all(x[1] == parents[0][1] for x in parents):

TypeError: 'dict_keyiterator' object is not subscriptable

### Your environment
* pgmpy version- latest
* Python version- 3.6
* Operating System- Windows

### Expected behaviour
Tell us what should happen

### Actual behaviour
Error is showing

  File "c:\python\python36\lib\site-packages\pgmpy\models\DynamicBayesianNetwork.py", line 510, in <genexpr>
    if all(x[1] == parents[0][1] for x in parents):

TypeError: 'dict_keyiterator' object is not subscriptable

**Comment by Priyabrata017** [comment]
def initialize_initial_state(self):      
  for cpd in self.cpds:
            temp_var = (cpd.variable[0], 1 - cpd.variable[1])
            parents = self.get_parents(temp_var)
            if not any(x.variable == temp_var for x in self.cpds):
                if all(x[1] == parents[0][1] for x in parents):
                    if parents:
                        evidence_card = cpd.cardinality[:0:-1]
                        new_cpd = TabularCPD(temp_var, cpd.variable_card,
                                             cpd.values.reshape(cpd.variable_card, np.prod(evidence_card)),
                                             parents, evidence_card)
                    else:
                        if cpd.get_evidence():
                            initial_cpd = cpd.marginalize(cpd.get_evidence(), inplace=False)
                            new_cpd = TabularCPD(temp_var, cpd.variable_card, np.reshape(initial_cpd.values, (-1, 2)))
                        else:
                            new_cpd = TabularCPD(temp_var, cpd.variable_card, np.reshape(cpd.values, (-1, 2)))
                    self.add_cpds(new_cpd)
            self.check_model()

**Comment by ankurankan** [comment]
@Priyabrata017 Are you by any chance on networkx==1.x ?

**Comment by Priyabrata017** [comment]
No, The error was because of the wrong values of cpds given in the examples.
        >>> grade_cpd =  TabularCPD(('G',0), 3, [[0.3,0.05,0.9,0.5],
        ...                                      [0.4,0.25,0.8,0.03],
        ...                                      [0.3,0.7,0.02,0.2]], [('I', 0),('D', 0)],[2,2])


Correct it.
