### ISSUE TITLE
example 'learning from data' not working under 0.1.7

### ISSUE THREAD

**Issue by heldmoritz** [pgmpy/pgmpy#1136]
### Subject of the issue
following the example from **https://github.com/pgmpy/pgmpy/blob/dev/examples/Learning%20from%20data.ipynb**
I get an error message when I try to use the bayesian estimator [17].

### Your environment
* pgmpy 0.1.7
* Python 3.7
* Windows 10

### Steps to reproduce
The code in the example "Learning with Bayesian Estimator using dirichlet prior for each variable."

```
pseudo_counts = {'D': [300, 700], 'I': [500, 500], 'G': [800, 200], 'L': [500, 500], 'S': [400, 600]}
model.fit(data, estimator=BayesianEstimator, prior_type='dirichlet', pseudo_counts=pseudo_counts)
for cpd in model.get_cpds():
    print("CPD of {variable}:".format(variable=cpd.variable))
    print(cpd)
```

gives the following error message:
`ValueError: The shape of pseudo_counts must be: (2, 1)`

I found a similar problem here: https://github.com/pgmpy/pgmpy/issues/1042

But using
`pseudo_counts= {'D':[[300],[700]], 'I':[[500],[500]], 'G':[[800],[200]], 'L':[[500],[500]], 'S': [[400],[600]]}`

does not solve the issue. 
Error message: `ValueError: The shape of pseudo_counts must be: (2, 4)`

defining the state_names prior also doesn't fix it.

```
raw_data=np.random.randint(low=0, high=2, size=(1000, 5))
data = pd.DataFrame(raw_data, columns=['D', 'I', 'G', 'L', 'S'])
model=BayesianModel([('D', 'G'), ('I', 'G'), ('I', 'S'), ('G', 'L')])
estimator = BayesianEstimator(model, data, state_names={'D': [0, 1], 'I': [0, 1], 'G': [0, 1], 'L': [0, 1], 'S':[0, 1]})
pseudo_counts= {'D':[[300],[700]], 'I':[[500],[500]], 'G':[[800],[200]], 'L':[[500],[500]], 'S':[[400],[600]]}
cpd_I= estimator.estimate_cpd('I', prior_type='dirichlet', pseudo_counts=pseudo_counts)
```
Error message:
`ValueError: The shape of pseudo_counts must be: (2, 1)`

**Comment by ankurankan** [comment]
@heldmo Sorry, the notebook is a bit outdated. With the current version, you will need to provide the `pseudo_counts` such that it is exactly the same shape as the tabular CPD. Therefore, in this case, the shapes of pseudo counts should be: `D = (2, 1)`, `I = (2, 1)`, `G = (2, 4)`, `S=(2, 2)` and, `L=(2, 2)`. Each of these values should have the pseudo counts that you want to add to each specific state of the CPD. Hope this makes it clearer.
