### ISSUE TITLE
Update the "Learning form data" notebook

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#1139]
### Subject of the issue
In the current version of pgmpy, the pseudo counts for BayesianEstimator are supposed to be the exact shape as the Tabular CPD but the examples in the notebook are from the older version.
Ref #1136 #1042

**Comment by heldmoritz** [comment]
pseudo_counts = {'D': [[300],[700]], 'I':[[500],[500]], 'G':[[800,200,300,500],[600,400,700,500]], 'L':[[500,300],[500,700]], 'S':[[400,700],[600,300]]}

This is a possible fix. You might want to adjust the exact numbers, I just made them up. Not sure if they make sense.

**Comment by ankurankan** [comment]
Yeah, these values look good. You can open a PR with these changes if you would like.

**Comment by heldmoritz** [comment]
I just noticed that the values for G should be switched, so you end up with the same number of prior counts for each cpd. 
'G':[[800,600,300,500],[200,400,700,500]]

Apologies

**Comment by ankurankan** [comment]
@heldmo It shouldn't really be a problem as it will be interpreted as a ratio. But it would be nicer to have it sum to the same value. So, if you would like you can open another PR fixing it. Thanks.
