### ISSUE TITLE
state_name and state_no in reduce()

### ISSUE THREAD

**Issue by yujianll** [pgmpy/pgmpy#1141]
### Subject of the issue
The value argument in reduce() function for TabularCPD and DiscreteFactor. It looks like right now the argument should be (var_name, var_state_name), but previously it's (var_name, var_state_no). However, in pre_compute_reduce() of Sampling.py, this for loop
```python
for state_combination in itertools.product(
            *[range(self.cardinality[var]) for var in variable_evid]
        ):
            states = list(zip(variable_evid, state_combination))
            cached_values[state_combination] = variable_cpd.reduce(
                states, inplace=False
            ).values
```
seems to use (var_name, var_state_no) as argument. 

### Your environment
* newest dev branch
* 3.6.8
* Ubuntu 18.04.2 LTS

### Steps to reproduce
I have a BayesianModel that has variable_state_name as str (not the same with variable_state_no). If I call likelihood_weighted_sample() on the model, which will call pre_compute_reduce(), it gives me key error, because reduce() calls self.get_state_no() like self.get_state_no(var_name, 0)

**Comment by ankurankan** [comment]
@yujianll It should work with both state name and state numbers. Would it be possible for you to share your code so that I can reproduce this?

**Comment by yujianll** [comment]
@ankurankan  A simple reproducer:
```python
model = BayesianModel([('A', 'B'), ('A', 'C'), ('C', 'D'), ('B', 'D')])
d = {'A': ['1', '2', '3'], 'B': ['1', '2', '2'], 'C': ['1', '1', 'blank'], 'D': ['2', '1', '1']}
df = pd.DataFrame(data=d)
model.fit(df)
inference = BayesianModelSampling(model)
evidence = [State('A', 0)]
inference.likelihood_weighted_sample(evidence=evidence, size=2)
```
reduce() function gives me key error.

**Comment by yujianll** [comment]
@ankurankan Does the above code produce the error, or am I understanding the function wrong?

**Comment by ankurankan** [comment]
@yujianll Sorry for the late reply. I think there's some bug. I will try to figure it out why this is happening and will update you soon.

**Comment by yujianll** [comment]
@ankurankan Thanks! When you fix it, could you still keep the ability of reduce() to work on state_no? I think it's convenient to work with state_no because it's the index of the cps.values. And for many operations, it's more convenient to directly use index of arrays rather than converting from state_names.

**Comment by yujianll** [comment]
@ankurankan How's the fixing?
I encountered another problem. In VariableElimination of Bayesian Model, for variable `working_factors`, you use set to store the working factors. However, it's totally fine that two factors are the same (I met this case, which results in less elements in the set than expected). This could cause error to inference. Did you take this case into consideration?

**Comment by ankurankan** [comment]
@yujianll I haven't started working on this issue yet.
Regarding the other issue that you have pointed out, could you give me an example to reproduce? I am not sure how there can be two same intermediate factors.

**Comment by yujianll** [comment]
@ankurankan Here is an example.

```python
model = BayesianModel([('A', 'C'), ('B', 'C'), ('C', 'D'), ('C', 'E')])
d = {'A': ['0', '1', '0', '1'], 'B': ['0', '1', '0', '1'], 'C': ['0', '0', '1', '1'],
     'D': ['0', '1', '0', '1'], 'E': ['0', '0', '0', '1']}
df = pd.DataFrame(data=d)
model.fit(df)
evidence = {'A': '0', 'B': '0', 'D': '0', 'E': '1'}
inference = VariableElimination(model)
inference.query(['C'], evidence)
```

`working_factos['C']` should have 3 elements, but it only has 2 elements after function `_get_working_factors()`.

**Comment by yujianll** [comment]
@ankurankan 
I have another question. Why does every cpd and factor in BayesianModel have a copy of `name_to_no` and `no_to_name` (which contains state names for every node)? For large network, that takes a lot memory. Could it just hold one copy and reference it in other places?

**Comment by yujianll** [comment]
@ankurankan 
I noticed you updated some code. I'm wondering are they regarding to any of above issues?

**Comment by Kwanikaze** [comment]
Also have this KeyError issue when using VariableElimination's .query method and passing in an evidence dictionary.
Nevermind, it works when I pass the state_name instead of the state_no.
Does the evidence dictionary now take the state_name instead of the state_no now?
Using: pgmpy                     0.1.8.dev50

**Comment by ankurankan** [comment]
@Kwanikaze It should accept both state names and state numbers. But it seems to be throwing an error at the moment. I will have a look at it.
