### ISSUE TITLE
Malfunctioning ipynb tutorials

### ISSUE THREAD

**Issue by Wesserg** [pgmpy/pgmpy#1146]
###  ipynb tutorials are not displaying correctly.
For some reason I can't view the ipynb tutorials related to Bayesian Nets:
Inference in Bayesian Networks.ipynb
Learning from data.ipynb
Monty Hall Problem.ipynb

Is it just me?

### My environment
No, env - just github page

### Steps to reproduce
Click on one of the above listed tutorials via the documentation link in pgmpy.org
### Expected behaviour
See a nice tutorial:D
### Actual behaviour
Don't see a nice tutorial:D

**Comment by ankurankan** [comment]
@Wesserg Are you using the links on the docs website? In that case it might just be a broken link. Otherwise just try the examples folder in the repo.

**Comment by Wesserg** [comment]
Hi @ankurankan. I tried both - both don't work.

**Comment by ankurankan** [comment]
@Wesserg Yeah, it's not working for me either. I am not sure why this has happened. Thanks for reporting this and in the meanwhile, you can try the notebooks at https://github.com/pgmpy/pgmpy_notebook, if that helps.

**Comment by heldmoritz** [comment]
Monty Hall actually works for me. It's just the other two that I coincidentally edited that are not working. Maybe I did something wrong? There were definitely working before I made the edit

**Comment by ankurankan** [comment]
@heldmo I am not sure how but the notebooks are not valid jsons after your changes. How did you edit the notebooks?
