### ISSUE TITLE
Using predict function to compute same data is very slow

### ISSUE THREAD

**Issue by FANGOD** [pgmpy/pgmpy#1150]
### Subject of the issue
Using predict function to compute same data is very slow

### Your environment
* pgmpy version   pgmpy (0.1.6)
* Python version   3.7
* Operating System   ubuntu 16.04

### Steps to reproduce
```
cnt = 1000000
values = pd.DataFrame({"A":[0]*cnt, "B":[1]*cnt, "C":[0]*cnt, "D":[1]*cnt, "E":[0]*cnt})
train_data = values[:80]
predict_data = values[80:]
model = BayesianModel([('A', 'B'), ('C', 'B'), ('C', 'D'), ('B', 'E')])
model.fit(values)
predict_data = predict_data.copy()
predict_data.drop('B', axis=1, inplace=True)
y_prob = model.predict_probability(predict_data)
```
Take a long time...
I don't think it should be so slow, should use a cache to speed it up.

**Comment by ankurankan** [comment]
@FANGOD Caching could be a good idea for speeding up in cases when predicting over datasets with repeated data points. But I am not sure if such cases happen enough that we should implement something like this.

**Comment by FANGOD** [comment]
@ankurankan We have a lot of nodes in a model, and each node has a value of 0 or 1, and each node has 5w values.

**Comment by Ketki-Savle** [comment]
Hello, 

I am facing the same issue. It is taking forever for predicts to go through. I have also kept unique rows in test data as per this suggestion but no change. Could you please help. 

Thanks & Regards

**Comment by FANGOD** [comment]
@Ketki-Savle  you can do this.
```
        model = self.get_model()
        df = self.get_data().astype(int)
        df = df.reindex(columns=self.node_ids, fill_value=0)

        pre_df = df.copy().drop_duplicates()
        pre_df['scores'] = model.predict_probability(pre_df)['tar_colunms']

        df.reset_index(inplace=True)
        df = pd.merge(df, pre_df, how='left', on=self.node_ids)

        df = df.set_index(self.index_name).drop(self.node_ids, axis=1)
```
If you need to reduce your time I have a more radical way to do it.

**Comment by Ketki-Savle** [comment]
Thank you @FANGOD  sorry I missed this reply. I will try this as well and yes it would be nice if you could share what you have done to speed up the prediction. 

Regards, 

Ketki

**Comment by FANGOD** [comment]
@Ketki-Savle  If your factors result in finite combinations, you can directly calculate their results and then concatenate the data for you.
