### ISSUE TITLE
Cannot create inter-time CPD in DBN

### ISSUE THREAD

**Issue by BitaFarkhad** [pgmpy/pgmpy#1156]
### Subject of the issue
I tried creating the DBN using the example provided in the documentation, but I don't know why the inter-time CPDs do not connect to the model.

### Your environment
* pgmpy version: both v1.6.0, v0.1.8.dev42 tried.
* Python version: 3.7.3
* Operating System:Windows x86_64

### Steps to reproduce
```
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD
dbn = DBN()
dbn.add_edges_from([(('D', 0),('D', 1))])
diff_cpd = TabularCPD(('D', 0), 2, [[0.6, 0.4]])
d_i_cpd = TabularCPD(('D', 1), 2, [[0.6, 0.3],
                                   [0.4, 0.7]],
                      evidence=[('D', 0)],
                     evidence_card=[2])
dbn.add_cpds(diff_cpd, d_i_cpd)
dbn.get_cpds()
```

### Expected behaviour
[<TabularCPD representing P(('D', 0):2) at 0x209ae508780>,
<TabularCPD representing P(('D', 1):2 | ('D', 0):2) at 0xxxxxxxxxxxx>]

### Actual behaviour
[<TabularCPD representing P(('D', 0):2) at 0x209ae508780>]

I appreciate if you could help me solve this issue. Am I missing something?

**Comment by ankurankan** [comment]
@BitaFarkhad It is actually adding both the cpds to the model. The `get_cpds` method by default only shows the CPDs in the 0th time slice, that why you are only seeing the CPD for `('D', 0)`. You can see all the CPDs using the `.cpds` attribute:
```python3
>>> dbn.cpds
[<TabularCPD representing P(('D', 0):2) at 0x7efc84e05390>,
 <TabularCPD representing P(('D', 1):2 | ('D', 0):2) at 0x7efc84e053c8>]
```
or can also access them by node names:
```python3
>>> dbn.get_cpds(node=('D', 1))
<TabularCPD representing P(('D', 1):2 | ('D', 0):2) at 0x7efc84e053c8>
```
