### ISSUE TITLE
Using Data to estimate CPDs in DBN

### ISSUE THREAD

**Issue by BitaFarkhad** [pgmpy/pgmpy#1159]
### Subject of the issue
I have defined a DBN and now, I am trying to use MLE to fit the CPDs. I tried 
`mle = MaximumLikelihoodEstimator(dbn, data_pre)`
but it raises an error that
`Maximum Likelihood Estimate is only implemented for BayesianModel`

Is there any alternative way of doing this?

### Your environment
* pgmpy version: v0.1.8.dev42
* Python version: 3.7
* Operating System: Windows

**Comment by ankurankan** [comment]
@BitaFarkhad pgmpy currently doesn't have an implementation for learning algrorithms for DBNs.
