### ISSUE TITLE
Different results for VariableElimination and BeliefPropagation

### ISSUE THREAD

**Issue by umutsen** [pgmpy/pgmpy#1166]
### Subject of the issue

I am testing with a 4-node network with 3 observations and 1 target. I get different results with VariableElimination and BeliefPropagation inferences. What am I missing here? 

Code is below, thanks.

### Code

```python
from pgmpy.models import BayesianModel
from pgmpy.inference import VariableElimination, BeliefPropagation
from pgmpy.factors.discrete import TabularCPD

model = BayesianModel([
    ('A', 'B'),
    ('A', 'C'),
    ('A', 'D')
])

node_a = TabularCPD(variable='A', variable_card=2, values=[[0.5],[0.5]])

node_b = TabularCPD(variable='B', variable_card=2,
                   values = [[0.9,0.1],[0.1,0.9]],
                   evidence=['A'],
                   evidence_card=[2])

node_c = TabularCPD(variable='C', variable_card=2,
                   values = [[0.9,0.1],[0.1,0.9]],
                   evidence=['A'],
                   evidence_card=[2])

node_d = TabularCPD(variable='D', variable_card=3,
                   values = [[0.85,0.05],[0.05,0.85],[0.1,0.1]],
                   evidence=['A'],
                   evidence_card=[2])

model.add_cpds(node_a, node_b, node_c, node_d)

infer = VariableElimination(model)
infer.query(variables=['A'], evidence={'B': 0, 'D': 1, 'C': 0}).__dict__

infer2 = BeliefPropagation(model)
infer2.query(variables=['A'], evidence={'B': 0, 'D': 1, 'C': 0}).__dict__

```

Results:
VariableElimination: `[0.34615385, 0.65384615]`
BeliefPropagation: `[0.02025, 0.00425]`

**Comment by ankurankan** [comment]
@umutsen Thanks for reporting this. It shouldn't be happening. I will look into it.

**Comment by dliberat** [comment]
Do we have any updates on this?
I've been doing some manual calculations that don't seem to square up with the results of either the `VariableElimination` or `BeliefPropagation` results. Are both inference methods suspect?

EDIT: Apologies, I just noticed it's been added to the milestone due by end of March.
If you have any information about the reliability of the different methods or whether the issue can be worked around by downgrading to an earlier version, however, it would be helpful to have in the interim.

**Comment by ankurankan** [comment]
@dliberat The results were different in some cases because Belief Propagation wasn't normalizing the results. I have fixed that now. You mentioned that there were some cases when both the results were wrong. Could you give me an example, so that I figure out the bug?

**Comment by dliberat** [comment]
@ankurankan Sure thing. It's just as likely my math was off, though. I'll put together a test case, but I might not be able to get around to it for another day or two.

**Comment by dliberat** [comment]
@ankurankan 
After some digging around, it looks like my CPD construction was incorrect. Both `VariableElimination` and `BeliefPropagation` are now generating correct values for my queries. Sorry for the confusion!

**Comment by ankurankan** [comment]
@dliberat Thanks for checking. Hopefully both the methods now work as expected.
