### ISSUE TITLE
Update existing bayesian model with new data

### ISSUE THREAD

**Issue by ikarthikng** [pgmpy/pgmpy#1167]
### Subject of the issue
Is there a way to update existing bayesian model with new data without wiping out the old model

### Your environment
* pgmpy 0.1.8.dev45
* Python 3.6.8 :: Anaconda, Inc.
* Windows 8.1

### Steps to reproduce
1. I have 200 x 4 of data which I read from database. I successful created a model using the learning method. I saved the model to a XML file. 

2. I have new row of data which is saved to the same table in the database. The model has to be updated with new data. I read the XML file saved in step 1 and get the model. When I use `fit()` to fit the new data. It wipes out the previous model

3. I want it to update the existing model, not wipe or rewrite the existing model.

**My code**
Step 1

```
raw_data = get_all_data()
model = BayesianModel([('A', 'B'), ('B', 'C'), ('C', 'D')])
model.fit(raw_data, estimator=MaximumLikelihoodEstimator)

writer = XMLBIFWriter(model)
writer.write_xmlbif(filename = 'bif_file.xml')
```

Step 2

```
reader = XMLBIFReader("bif_file.xml")
read_model = reader.get_model()

save_data = pd.DataFrame([['1', '2', '2', '6']], columns = ['A', 'B', 'C', 'D'])
read_model.fit(save_data)

# I tried to predict some data below here
```

**_Step 2 overrides the entire model which was created in Step 1_**

### Expected behavior
Update the existing model in Step 1 with the new data from Step 2.

### Actual behavior
Wipes out the model in Step 1 and replaces with model with one single row from step 2.

**Comment by ankurankan** [comment]
@ikarthikng ML Estimator can't be used for updating the model parameters. You should be able to use the Bayesian Estimator for this though. You will need to pass in the current learned parameters as prior to the estimator and run the fit on the new data.
