### ISSUE TITLE
File "G:\anaconda3\lib\site-packages\pgmpy\estimators\HillClimbSearch.py", line 60, in _legal_operations     if nx.is_directed_acyclic_graph(nx.DiGraph(model.edges() + [(X, Y)])): TypeError: unsupported operand type(s) for +: 'OutEdgeView' and 'list'

### ISSUE THREAD

**Issue by R2h1** [pgmpy/pgmpy#1168]
### Subject of the issue
Describe your issue here.

### Your environment
* pgmpy version
* Python version
* Operating System

### Steps to reproduce
Tell us how to reproduce this issue. Please provide the complete code if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
@R2h1 This could be happening because of older version of networkx. Try upgrading it to the latest version.
