### ISSUE TITLE
Parallelize the predict methods of models

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#1172]
### Subject of the issue
The predict methods iterate over all the given data and individually does inference for it. Related #511

**Comment by ivanDonadello** [comment]
Dear all,

is there any progress about this?


Thanks

Ivan

**Comment by ankurankan** [comment]
@ivanDonadello Yes, this has already been implemented. You can specify `n_jobs` parameter in the `predict` method to specify the number of concurrent processes to run. The default is `-1` which uses all CPU cores. But one of the things to keep in mind is that parallelization has overhead costs, so it will only be faster when the models are complex. In simpler cases, a single process might be faster.

**Comment by ivanDonadello** [comment]
Thank you very much @ankurankan! Is there anything similar also for the map_query method? I would like to pass a matrix/batch of evidences to the method instead of iterating over each row.

**Comment by ankurankan** [comment]
@ivanDonadello The predict method uses `map_query` internally as it's predictions are the categories with the highest probability. If you are looking to get the probability values, you can checkout the `predict_probability` method: http://pgmpy.org/models.html#pgmpy.models.BayesianModel.BayesianModel.predict_probability

**Comment by ivanDonadello** [comment]
@ankurakan thanks for the link. In the prediction method the adopted `map_query` is the one of the `VariableElimination` algorithm. If I wanted to use the one of the `BeliefPropagation` algorithm should I modify the source code? Is there a way for switching one for another?

**Comment by ankurankan** [comment]
@ivanDonadello Currently, there is no way to use BeliefPropagation with the predict method. So, you will have to either modify the code or use the map_query directly from BeliefPropagation. Also, I think it would be a nice feature to have the option to select the inference method in the predict method, so in case you modify the source code, please consider opening a pull request for it. :)

**Comment by ivanDonadello** [comment]
Thank you very much! I'll do it! :)

**Comment by zhangtj1996** [comment]
> @ivanDonadello The predict method uses `map_query` internally as it's predictions are the categories with the highest probability. If you are looking to get the probability values, you can checkout the `predict_probability` method: http://pgmpy.org/models.html#pgmpy.models.BayesianModel.BayesianModel.predict_probability

Hi, I'd like to predict probabilities in parallel, but it seems no options in `predict_probability` function, where should I insert the `n_jobs` code?
