### ISSUE TITLE
can't learn model structure -returns no cpds

### ISSUE THREAD

**Issue by NikTheGeek1** [pgmpy/pgmpy#1173]
### Subject of the issue
Trying to replicate the code from chapter 5 of your book: Learning bayesian model structure, page 190

### Your environment
* pgmpy version =  'v0.1.8.dev46'
* Python version = Python 3.7.4
* Operating System = Windows 10

### Steps to reproduce
```
import numpy as np
import pandas as pd
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator
# generating random data
raw_data = np.random.randint(low=0, high=2, size=(1000, 2))
data = pd.DataFrame(raw_data, columns=['X', 'Y'])
coin_model = BayesianModel()
coin_model.fit(data, estimator=MaximumLikelihoodEstimator)
coin_model.get_cpds()
```

### Expected behaviour
Expected to get cpds for P(X) and P(Y) as described in page 190 of the book (Mastering pgm using python)

### Actual behaviour
It returns an empty list i.e., no cpds

**Comment by ankurankan** [comment]
@NikTheGeek1 There seems to be an error with the code. You need to specify the model structure to learn it's CPDs but here `coin_model` is an empty model. So, you will need to specify a model with something like this:
```python3
# Disconnected model
coin_model = BayesianModel()
coin_model.add_nodes_from(['X', 'Y'])

# Model with edge X -> Y
coin_model = BayesianModel([('X', 'Y')])
```
Then the rest of the code should work fine.
