### ISSUE TITLE
macOS conda install pgmpy error

### ISSUE THREAD

**Issue by ghtie** [pgmpy/pgmpy#1180]
### MacOs conda install pgpmy error
I installed the anaconda version for python 3.7 and above, and tried to install pgmpy using:
conda install -c ankurankan pgmpy

I don't quite understand the error I am getting from the installation

### Your environment
* Python version: 3.7
* Operating System: macOs Mojave 10.14.6

### Error Message
UnsatisfiableError: The following specifications were found                                                          
to be incompatible with the existing python installation in your environment:

Specifications:

  - pgmpy -> python[version='>=2.7,<2.8.0a0|>=3.4,<3.5.0a0|>=3.5,<3.6.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Package setuptools conflicts for:
python=3.7 -> pip -> setuptools
pgmpy -> networkx[version='>=1.8.1'] -> setuptools
Package pip conflicts for:
pgmpy -> python[version='>=3.5,<3.6.0a0'] -> pip
python=3.7 -> pip
Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
pgmpy -> networkx[version='>=1.8.1'] -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
Package wheel conflicts for:
pgmpy -> python[version='>=3.5,<3.6.0a0'] -> pip -> wheel
python=3.7 -> pip -> wheel
Package ca-certificates conflicts for:
pgmpy -> python[version='>=3.5,<3.6.0a0'] -> ca-certificates
python=3.7 -> openssl[version='>=1.0.2p,<1.0.3a'] -> ca-certificates

**Comment by ankurankan** [comment]
@ghtie The conda package is quite old. We are working on getting it to the latest version. In the meanwhile, please try to install the dev branch from github.
