### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by kiennguyen1101** [pgmpy/pgmpy#1184]
### Subject of the issue
ModuleNotFoundError: No module named 'torch'

### Your environment
* pgmpy version
0.1.9
* Python version
3.6.8
* Operating System
Debian Stretch
(Docker python:3.6-stretch)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide the complete code if possible.
```python
 from pgmpy.estimators import MaximumLikelihoodEstimator
```
### Expected behaviour
Tell us what should happen
it runs
### Actual behaviour
Tell us what happens instead
```
File "/usr/local/lib/python3.6/site-packages/pgmpy/__init__.py", line 1, in <module>
from .global_vars import HAS_PANDAS, device
File "/usr/local/lib/python3.6/site-packages/pgmpy/global_vars.py", line 3, in <module>
import torch
ModuleNotFoundError: No module named 'torch'
```
Was using version 0.1.7 fine without any issues

**Comment by ankurankan** [comment]
@kiennguyen1101 Did you install it using conda? In that case, seems like a problem with the build. I will fix it ASAP. In the meanwhile, you can just manually install pytorch (conda install pytorch) and it will work.

**Comment by kiennguyen1101** [comment]
Hi @ankurankan ,
We have a file of dependencies called requirements.txt and once in a while we build the system 
(using pip install -r requirements.txt). It looks like something like this:
```
tensorflow==1.14.0
tensorflow-probability==0.7.0
tensorflow-gpu==1.14
numpy==1.17.1
scipy==1.2.0
scikit-learn==0.20.0
jupyter==1.0.0
pandas==0.25.1
seaborn==0.9.0
click==7.0
watermark==1.7.0
pytest==3.10.0
scikit-plot==0.3.7
monotonic
netifaces
colorlog
hmmlearn
statsmodels
pgmpy
```

I tested the library and both 0.1.8 and 0.1.9 causes ModuleNotFoundError. Switched back to 0.1.7 and my program works correctly
```
pgmpy==0.1.7
```

**Comment by ankurankan** [comment]
@kiennguyen1101 We have added support for Structural Equation Models in 0.1.9 which uses pytorch for training models. The previous versions of pgmpy didn't have a dependency on pytorch.

**Comment by ankurankan** [comment]
Fixed in latest conda builds. Closing.

**Comment by niyatham** [comment]
I am unable to install torch or pytorch, I am using python environment to do it.
Do not have conda environment.
Can you please help me out?

**Comment by ankurankan** [comment]
@nishnik Have you tried installing using pip (`pip install torch`)?

**Comment by nishnik** [comment]
You meant @niyatham 
cc @ankurankan 
Also you can look at [https://pytorch.org/](https://pytorch.org/) for installation instructions specific to the OS.

**Comment by niyatham** [comment]
> @nishnik Have you tried installing using pip (`pip install torch`)?

Hey @ankurankan yes i had tried that. 
It worked fine in 64bit python.
Thanks btw :)
