### ISSUE TITLE
is it possible to use dependency between many features for learning from data

### ISSUE THREAD

**Issue by Sandy4321** [pgmpy/pgmpy#1190]
### Subject of the issue
is it possible to use dependency between many features for learning from data
for example referencing to 
model = BayesianModel([('D', 'G'), ('I', 'G'), ('I', 'S'), ('G', 'L')])
https://github.com/pgmpy/pgmpy/blob/dev/examples/Learning%20from%20data.ipynb

can it be
model = BayesianModel([('D', 'I', 'G', 'L', 'S'), ('I', 'G'), ('I', 'S'), ('G', 'L')])
or
model = BayesianModel([('D', 'I', 'S'), ('I', 'G'), ('I', 'S'), ('G', 'L')])

thanks
### Your environment
* pgmpy version
* Python version
* Operating System

### Steps to reproduce
Tell us how to reproduce this issue. Please provide the complete code if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
@Sandy4321 I am sorry but I am not sure what exactly do you mean by many features. In a Bayesian Network, each node is supposed to be a random variable and while initializing the network we specify the direction of effect. For example in the student model, the ('D', 'G') represents that the difficulty (D) of a course affects the grade (G) that the student gets. If you could give me details on what relationship are you expecting with something like: ('D', 'I', 'G', 'L', 'S'), I might be able to help.
