### ISSUE TITLE
is it possible to use for classification when variables are not dependent at all so it will be just naive Bayesian

### ISSUE THREAD

**Issue by Sandy4321** [pgmpy/pgmpy#1191]
### Subject of the issue
is it possible to use for classification when variables are not dependent at all so it will be just naive Bayesian
from this example 
# Generating radom data with each variable have 2 states and equal probabilities for each state
import numpy as np
import pandas as pd

raw_data = np.random.randint(low=0, high=2, size=(1000, 5))
data = pd.DataFrame(raw_data, columns=['D', 'I', 'G', 'L', 'S'])

just to use
model = BayesianModel([])
https://github.com/pgmpy/pgmpy/blob/dev/examples/Learning%20from%20data.ipynb

another example is from 
https://youtu.be/sCqpWCYaL5U?t=528
Bayesian Network -7 | Machine Learning-Python
so it would be 
model = BayesianModel([])
thanks

### Your environment
* pgmpy version
* Python version
* Operating System

### Steps to reproduce
Tell us how to reproduce this issue. Please provide the complete code if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
@Sandy4321 I think you might be slightly mistaken about the assumptions that the Naive Bayes model makes. It doesn't assume all the variables to be independent of each other (in that case it would be impossible to predict anything as the correlation between any two variables would be 0). The assumption made by Naive Bayes is rather that the feature variables are independent of each other given the variable to be predicted. You can check http://pgmpy.org/models.html#module-pgmpy.models.NaiveBayes for examples of Naive Bayes with pgmpy.
