### ISSUE TITLE
Setting of Semester Objectives

### ISSUE THREAD

**Issue by snigam3112** [pgmpy/pgmpy#12]
After the talk with NSR and his insistence on being able to show applications, I have come up with the following objectives for us. 

The basic course structure is divided into Representation, Inference and Learning. We will only finish the Representation part.
That means:
1. Watching of video lectures till (and including) module 8.
2. Completing the first three programming assignments. 
( https://class.coursera.org/pgm-003/assignment/index )
As you can see, completing the programming assignment will also give us an "application" to showcase.

**Comment by snigam3112** [comment]
@abinashpanda @ankurankan @gargshashank5 @pramttl @pgmpy Comment here, please.

**Comment by ankurankan** [comment]
Yes I agree with the objectives but since we are looking forward to presenting pgmpy at Scipy India we will need to at least complete all this before 24th nov.
