### ISSUE TITLE
Can the structure learning and parameter learning functions used to learn DBN?

### ISSUE THREAD

**Issue by yaowang1111** [pgmpy/pgmpy#1201]
Hi~

I'm wondering if pgmpy can learn DBN structures and parameters?
I'm new to this field and i looked at the code and see no such sign.
I think it would be helpful if there are some example showing how to solve this problem. 

Thanks

**Comment by ankurankan** [comment]
@yaowang1111 pgmpy currently only supports inference in DBNs. Parameter and Structure learning in DBN is not supported yet.

**Comment by yaowang1111** [comment]
Thanks for the reply!
Do you know if there were packages that can do the job ?
And are there plans for supporting it in pgmpy?

**Comment by ankurankan** [comment]
@yaowang1111 

> Do you know if there were packages that can do the job ?

To the best of my knowledge, there aren't any packages in python supporting that yet. But `bnlearn`(http://www.bnlearn.com/) in R has the functionality to learn dynamic networks, you can give it a try. 

> And are there plans for supporting it in pgmpy?


Yes, I would like to have algorithms for DBN but it is not a priority for me at the moment. But you are always welcome to contribute if you would like :)

**Comment by yaowang1111** [comment]
Really useful information, thanks!
I'm really new to this field, will try~
