### ISSUE TITLE
Excellent library but still at release 0.1.9 ?

### ISSUE THREAD

**Issue by ksachdeva** [pgmpy/pgmpy#1211]
This is not an issue. As a matter of fact I am quite impressed with the library. 

I am relatively new to PGM and have been reading Daphne Koller's iconic book and have found this repository to be extremely helpful in seeing a lot of concepts being realized with s/w.

That said, it seems like the library is in development for 5 years or so and yet the version is at 0.1.9. Even the repo has 1.3K stars which is not too bad.

Thanks for you this great  work but at the same time really curious to know the reason for not being bold and release version 1.0 !

Regards
Kapil

**Comment by ankurankan** [comment]
@ksachdeva Thanks for the kind words. Well, we wanted to have a very stable core codebase for version 1, and we are quite far from it right now as the core things (including the API) still change quite frequently. Also, if you compare to something like sklearn, it is still at 0.22 and we are nowhere close to it in terms of stability.

**Comment by ksachdeva** [comment]
Thanks @ankurankan.

Is there some sort of roadmap ? Identified list of features, test coverage etc that you envision or must have in order to reach 1.0. 

Regards
Kapil

**Comment by ankurankan** [comment]
@ksachdeva I don't have a very detailed roadmap towards 1.0 but for 0.2 we have a roadmap here: https://github.com/pgmpy/pgmpy/projects/4.
