### ISSUE TITLE
ValueError: Values array must be of size: 72

### ISSUE THREAD

**Issue by andreeairimia** [pgmpy/pgmpy#1213]
I'm creating a bayesian network using BayesianModel and trying to add the CPD for a child with two parents following the documentation:

```
c_cpd = TabularCPD('c', 2, [[0.5,0.5,0.5,0.5,0.5,0.5],
                                              [0.5,0.5,0.5,0.5,0.5,0.5]],
                                   evidence=['a', 'b'], evidence_card=[6, 6])  
```

The parents CPDs are:

```
a_cpd = TabularCPD('a', 6, [[0.35], [0.16], [0.21], [0.13], [0.07], [0.08]])
b_cpd = TabularCPD('b', 6, [[0.27], [0.22], [0.2], [0.07], [0.15], [0.09]])
```

However the `evidence` and `evidence_card` attributes trigger the following error:

```
/usr/local/lib/python3.6/dist-packages/pgmpy/factors/discrete/DiscreteFactor.py in __init__(self, variables, cardinality, values, state_names)
    105             raise ValueError(
    106                 "Values array must be of size: {size}".format(
--> 107                     size=np.product(cardinality)
    108                 )
    109             )
ValueError: Values array must be of size: 72
```

I installed pgmpy using `pip3 install pgmpy` which takes version 0.1.9 and should be the most updated version. 
I have tried both on macOS 10.15 and in google colab using python 3.7 and 3.6 

Is there another version I should use?

**Comment by ankurankan** [comment]
@axi672 I think the error is correct (though should be clearer). Since variable C has two parents A and B both with a cardinality of 6. The CPD shape for C should be (2, 6*6) i.e. (2, 36) but the values specified in cpd for C is of shape (2, 6), hence the error. 

I will improve the error message though to make it clearer.
