### ISSUE TITLE
Methods modifying Factor object

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#122]
Some of the factor class methods like: `reduce`, `normalize`  and `marginalize` modify the object on which they are called.
But we will sometimes be needing to get new objects without modifying the original object like in the case of `check_independence` and `get_independencies` methods in `JointProbabilityDistribution` class.

For making it work I had to do something like this:

``` python3
if JointProbabilityDistribution.marginal_distribution(deepcopy(self), variable_pair) == \
                    JointProbabilityDistribution.marginal_distribution(deepcopy(self), variable_pair[0]) * \
                    JointProbabilityDistribution.marginal_distribution(deepcopy(self), variable_pair[1]):
```

I think we will be doing more such operations in future.

Also I agree that the current behavior of  the methods of Factor class is what the user would be expecting.

One solution for this that comes to my mind is to have an additional argument for those methods which would control whether the function returns a new object or modifies itself. Like this:
`def marginalize(self, variables, inplace=True):`

`inplace = True` will modify the object itself and `False` will return a new object.

@abinashpanda @pramttl @gargshashank5 What do you think?

**Comment by abinashpanda** [comment]
@ankurankan I am fine with `def marginalize(self, variables, inplace=True)`.

**Comment by ankurankan** [comment]
Fixed
