### ISSUE TITLE
cannot import MaximumLikelihoodEstimator

### ISSUE THREAD

**Issue by Asferomo** [pgmpy/pgmpy#1229]
### Subject of the issue
Get an error when I import MaximumLikelihoodEstimator from pgmpy.estimators

### Your environment
* pgmpy version 0.1.1
* Python version 3.7
* Operating System Mac OS

### Steps to reproduce
Tell us how to reproduce this issue. Please provide the complete code if possible.

`from pgmpy.estimators import MaximumLikelihoodEstimator`

Traceback (most recent call last):

  File "<ipython-input-10-045cb40016a8>", line 1, in <module>
    from pgmpy.estimators import MaximumLikelihoodEstimator

  File "/Users/xxxx/opt/anaconda3/lib/python3.7/site-packages/pgmpy/estimators/__init__.py", line 6, in <module>
    from pgmpy.estimators.BDeuScore import BDeuScore

ImportError: cannot import name 'BDeuScore' from 'pgmpy.estimators.BDeuScore' (/Users/xxxx/opt/anaconda3/lib/python3.7/site-packages/pgmpy/estimators/BDeuScore.py)

### Expected behaviour
Expect to import MaximumLikelihoodEstimator successfully, with no errors

### Actual behaviour
Tell us what happens instead
Returned the error above instead

**Comment by Asferomo** [comment]
Just fixed it on my end:

I modified pgmpy/estimators⁩/__init__.py from 
`from pgmpy.estimators.BDeuScore import BDeuScore
`
to 

`from pgmpy.estimators.BDeuScore import BdeuScore`

**Comment by ankurankan** [comment]
@Asferomo Thanks for reporting this. Probably related to #1228

**Comment by darksheng** [comment]
ImportError: cannot import name 'BDeuScore' from 'pgmpy.estimators.BDeuScore' 
i found this error  BDeuScore should change to BdeuScore
![image](https://user-images.githubusercontent.com/22118981/75604507-30894f00-5b14-11ea-8b1c-96576563edac.png)

**Comment by ankurankan** [comment]
Ref #1228
