### ISSUE TITLE
Questions about the possibilities to apply different operators to inference algorithms (e.g. Belief Propagation)

### ISSUE THREAD

**Issue by garaud** [pgmpy/pgmpy#1233]
Hi,

### Subject of the issue
With @delhomer, we are working on a legacy code which uses a Probrabilistic Graph Model and depends on [opengm](https://github.com/opengm/opengm/) (the Python bindings). Unfortunately, this library is unmaintained and the Python bindings can compile only with old Boost::Python versions (and Python2).

We would like to use pgmpy and we have a few questions.

First, we have the following context:

* It's an undirected graph (so we'll use https://pgmpy.org/models.html#module-pgmpy.models.FactorGraph)
* The Belief Propagation inference algorithm is used
* It's not a sum-product (marginalization) but an optimization using some other operators

For the last item, OpenGM can use different operators, i.e. functions, and apply them for different inference algorithms.

If you take a look to the [OpenGM PDF documentation](http://hciweb2.iwr.uni-heidelberg.de/opengm/download/opengm-2.0.2-beta-manual.pdf) at the chapter 3 "Inference Algorithms", you can parametrize your inference algorithm with a sum-product, you can also maximize or minimize the energy of each node with the `opengm::Minimizer` and `opegm::Adder` operators. In other words, you can apply the well-known sum-product:

<a href="https://www.codecogs.com/eqnedit.php?latex=\sum_{x&space;\in&space;X}&space;\prod_{f&space;\in&space;F}&space;\phi(f)&space;(x_1,&space;\ldots,&space;x_N)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\sum_{x&space;\in&space;X}&space;\prod_{f&space;\in&space;F}&space;\phi(f)&space;(x_1,&space;\ldots,&space;x_N)" title="\sum_{x \in X} \prod_{f \in F} \phi(f) (x_1, \ldots, x_N)" /></a>

or carry out an energy minimization:

<a href="https://www.codecogs.com/eqnedit.php?latex=(\arg)\min_{x&space;\in&space;X}&space;\sum_{f&space;\in&space;F}&space;\phi(f)&space;(x_1,&space;\ldots,&space;x_N)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?(\arg)\min_{x&space;\in&space;X}&space;\sum_{f&space;\in&space;F}&space;\phi(f)&space;(x_1,&space;\ldots,&space;x_N)" title="(\arg)\min_{x \in X} \sum_{f \in F} \phi(f) (x_1, \ldots, x_N)" /></a>

Is it possible to parametrize pgmpy in that way to carry out other functions that the sum-product? We also saw a related issue at #966.

Thank you for your help

### Your environment
* pgmpy version : master
* Python version : python 3.6
* Operating System : GNU/Linux

**Comment by ankurankan** [comment]
@garaud The current implementation can only do sum-product and doesn't support energy minimization.

**Comment by garaud** [comment]
Thank you for your response.

* is a way to hack (monkey patch) this feature easily?
* Will you plan to implement this feature?

Thanks

**Comment by ankurankan** [comment]
@garaud 

> is a way to hack (monkey patch) this feature easily?

I think it should be possible to implement it without a lot of changes. From a quick look, I think we will mostly need to change the `BeliefPropagation._update_beliefs` and `BeliefPropagation._is_converged` methods. 

> Will you plan to implement this feature?

Sorry, but this is not a priority issue for me at the moment, so I won't be able to give a timeline for this.

**Comment by garaud** [comment]
Thanks @ankurankan
