### ISSUE TITLE
Bugs in the constraint checking of HillClimbSearch

### ISSUE THREAD

**Issue by jguan1** [pgmpy/pgmpy#1237]
### Subject of the issue
When specify black_list and white_list in the HillClimbSearch estimator, the "flip" operation does not correctly flip the two nodes in the edges of the constraint list. Therefore, the final results contain edges that are either inside the "black_list" or not in the "white_list"

### Your environment
* pgmpy  0.1.10dev
* python 3.7.6
* Operating System
Windows 10
### Steps to reproduce
`white_list = [('a', 'b'), ('a', 'c')]`
`hc = HillClimbSearch(data, scoring_method=BDeuScore(data_df))`
`model = hc.estimate(epsilon=1e-4, white_list=white_list)`

### Expected behaviour
The model should only contain the following edge combinations: `[('a', 'c')]`, or  `[('a', 'b')]`, or`[('a', 'c'), ('a', 'b')]`. 

### Actual behaviour
However, the model contains edge `('b', 'a')` or `('c', 'a')`

**Comment by jguan1** [comment]
Here's a simple fix in the HillClimbSearch.py (line 104 and 105) (switching X and Y) 
![image](https://user-images.githubusercontent.com/3431729/75840819-177be900-5e07-11ea-8bbf-5219e007edfd.png)

In the `dev` branch:
![image](https://user-images.githubusercontent.com/3431729/75840888-501bc280-5e07-11ea-989c-bc4923c8149b.png)

**Comment by ankurankan** [comment]
@jguan1 Thanks for reporting this. Would you like to open a pull request for the fix?

**Comment by jguan1** [comment]
Yes, I'd be happy to do that. However, when I tried to do a `git push origin my-branch-name`, I got some permission errors, not sure if I need to apply for some permission to open a pull request.

**Comment by ankurankan** [comment]
@jguan1 Since you don't have permission to push to this repo directly, it wouldn't work. You will need to first fork the repository (which will create a copy of this repo in your account), push your changes to your repository, and then you can open a pull request to merge changes from your repo to this repo. We also have a contributing guide (https://github.com/pgmpy/pgmpy/blob/dev/Contributing.md) where you can find more details.

**Comment by ankurankan** [comment]
Fixed in dev.
