### ISSUE TITLE
Imputation of missing values of continuous data from Bayesian network？

### ISSUE THREAD

**Issue by juweipku** [pgmpy/pgmpy#1238]
Hello, I am trying to impute the missing value of continuous data from Bayesian network using belief propagation or loop belief propagation algorithm. And the adjacency is known. Does pgmpy support this operation ？

**Comment by ankurankan** [comment]
@JuJuWei Sorry, I am not able to exactly understand what you are trying to do. Could you please explain in more detail or an example would also help?

**Comment by juweipku** [comment]
I'm sorry, maybe I did n' t make it clear. 
Suppose there is  a design matrix X(N*d), N samples, d features, which each item is continuous. But some items are missing. Each sample follows the same known Bayesian network, that is, the adjacency matrix is known. I'm trying to impute these missing values using belief propagation or loopy belief propagation algorithm.
So I what to know that whether pgmpy support this operation ？

**Comment by ankurankan** [comment]
@JuJuWei Sorry, but this is not possible for __continuous data__ at the moment with pgmpy.
