### ISSUE TITLE
hi, can give some books and papers about bayes network ,especially  inference part

### ISSUE THREAD

**Issue by darksheng** [pgmpy/pgmpy#1240]
### Subject of the issue
Describe your issue here.

### Your environment
* pgmpy version
* Python version
* Operating System

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a minimal reproducible code of
the issue you are facing if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by darksheng** [comment]
I want to study this field, but the Chinese books published in the field are always very cluttered. I would like to ask if there is a book with a clear enough system or some worthy thesis.

**Comment by ankurankan** [comment]
Hi,

For probabilistic inference using Bayesian Networks, Probabilistic
Graphical Models by Koller and Friedman is a comprehensive guide to the
basic theory.
For Causal Inference, I would suggest Causality by Judea Pearl. For a more
practical approach, you can also refer to my book, Mastering Probabilistic
Graphical Models using python. But I don't think there are any detailed
comprehensive practical books out there.

Hope this helps.
Ankur

**Comment by darksheng** [comment]
thans very much , this package give me some help ,i love this package.
