### ISSUE TITLE
bug, ValueError: Must have equal len keys and value when setting with an iterable

### ISSUE THREAD

**Issue by darksheng** [pgmpy/pgmpy#1241]
### Subject of the issue
when i use Hybrid Structure Learning in   9. Learning Bayesian Networks from Data.ipynb ,do some  test，Especially when I used 13,500 data, it ran for three days, and finally got this result, I felt very crash.

i hope i can get your help ,thanks very much.
### Your environment
* pgmpy 0.1.10
* Python 3.7
* numpy 0.18.1
* pandas 0.25.3
* Operating System:win10

### Steps to reproduce
First,i use small data ,this program can run successfully to get results.
But,When I used more than 10,000 data, a program error occurred. The previous consistent operation was successful, indicating that the data was insufficient, but after three days of operation, an error occurred.
![image](https://user-images.githubusercontent.com/22118981/76580172-f2276300-6509-11ea-99bf-811fa80af78e.png)
![image](https://user-images.githubusercontent.com/22118981/76580195-08cdba00-650a-11ea-9eec-53cb092d483f.png)
![image](https://user-images.githubusercontent.com/22118981/76580404-c658ad00-650a-11ea-8d53-b9da59a39686.png)
![image](https://user-images.githubusercontent.com/22118981/76580417-d1abd880-650a-11ea-8ddb-ba4f2004f7de.png)

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
@darksheng I am not sure why this is happening. Are you running the code in the notebook with a
larger simulated dataset? Else would it be possible for you to share you data and reproducible code?

**Comment by darksheng** [comment]
ok，i will give you data，but i am a newer  ，so i can  give my code and data by email，your email？ thanks you

**Comment by ankurankan** [comment]
@darksheng You can email me at: ankurankan@gmail.com

**Comment by darksheng** [comment]
i have send to you email and files ，thans very much.

**Comment by darksheng** [comment]
i am sorry ,Because of my negligence caused this error, the data processed in pandas exists nan，now i fixed it.
