### ISSUE TITLE
reorder_parents documentation incorrect?

### ISSUE THREAD

**Issue by BrettWitty** [pgmpy/pgmpy#1248]
My understanding was that reordering parents in a CPD should just reorder data. That is, be a permutation of the `values` data. The documentation does not reflect this:

https://github.com/pgmpy/pgmpy/blob/164b415df9bc74a34ddd807d0facfb41834a9133/pgmpy/factors/discrete/CPD.py#L419-L429

https://github.com/pgmpy/pgmpy/blob/164b415df9bc74a34ddd807d0facfb41834a9133/pgmpy/factors/discrete/CPD.py#L451-L461

In particular the reordered CPD has values of 0.7 when the original does not. The code just transposes data so this shouldn't happen.

**Comment by ankurankan** [comment]
@BrettWitty Thanks for reporting this. The documentation seems to be wrong. If you would like, please feel free to open a PR fixing this.
