### ISSUE TITLE
Broken dependencies when "pip install" of version 0.1.9

### ISSUE THREAD

**Issue by drorata** [pgmpy/pgmpy#1251]
### Dependencies broken when installing version 0.1.9 of `pgmpy` using pip

Due to #1228 I rolled back to version 0.1.9 after having version 0.1.10 installed. This worked smoothly. However, when rebuilding the environment from scratch I got broken dependencies (at least `torch`).

### Your environment
* pgmpy 0.1.9 and 0.1.10
* Python 3.8
* Operating System: macOS 10.15.4

### Steps to reproduce

1. Create fresh environment `conda create -n foo python=3.8` and activate it
1. Run `pip install pgmpy==0.1.9`
1. In the `python` shell run: `from pgmpy.estimators import BicScore`. This raises the error `ModuleNotFoundError: No module named 'torch'`.
1. Exit `python` shell.
1. Create a new environment and run `pip install pgmpy==0.1.10`. Note that many dependencies are installed!
1. Revert to version 0.1.9.
1. In the `python` shell run: `from pgmpy.estimators import BicScore`. Now it works.

### Expected behaviour
Installing version 0.1.9 should take care of dependencies

### Actual behaviour
The pip installation of version 0.1.9 doesn't install the dependencies.

### Remarks
* I wouldn't have discover this if it wasn't for the problem mentioned in #1228 
* This issue seems to impact whoever tries to install version 0.1.9 directly.

**Comment by ankurankan** [comment]
@drorata This is happening because our installation process was different for 0.1.9 and we asked users to manually install all the dependencies. But the setup has been revamped for 0.1.10 and can now automatically install the dependencies.
