### ISSUE TITLE
"Values array must be of size: 16384"

### ISSUE THREAD

**Issue by johncalabrese** [pgmpy/pgmpy#1268]
I'm getting the following error:

ValueError: Values array must be of size: 16384

With this code

```
cpd_SA_sn = TabularCPD(variable='SA', variable_card=128, 
                       values= exceltable,
                       evidence=['RR','IH','IS','TA','CE','IE'],
                       evidence_card=[2, 4, 2, 2, 2, 2],
                       state_names={'SA': ['BF', 'ES', 'SC', 'MC'],
                                   'RR': ['Agree', 'Disagree'],
                                    'IH': ['VeryShort', 'Short', 'Mid', 'Long'],
                                    'IS': ['Unstable', 'Stable'],
                                    'TA': ['Agree', 'Disagree'],
                                    'CE': ['Agree', 'Disagree'],
                                    'IE': ['Agree', 'Disagree']
                                   })
```
The product of the evidence_card = 128, and the len(exceltable) is 128. Each element is an array of 4 objects = 512

I'm not sure where pgmpy is getting 16384. 

### Your environment
* pgmpy version = 0.1.10
* Python version =3.7.7
* Mac OS

**Comment by ankurankan** [comment]
@johncalabrese Please have a look here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/factors/discrete/CPD.py#L38 for the shape of the values array that pgmpy expects. In your example, the values array shape should be `(128, 2*4*2*2*2*2) = (128, 128)`, hence total of 16384.
