### ISSUE TITLE
GPU acceleration / multiple CPU support

### ISSUE THREAD

**Issue by ir0nt0ad** [pgmpy/pgmpy#1277]
### Subject of the issue
Does pgmpy use GPU acceleration if you have a GPU-enabled installation of PyTorch? Also, does it support multiple CPUs? Thank you!

**Comment by ankurankan** [comment]
@sh0gg0th Currently, GPU is only used for learning parameters in Structural Equation Models as it can be formulated as an optimization problem. Multi CPU is used for quite a few functionalities, and you can usually find a `n_jobs` argument for the methods that can use multi CPU.

**Comment by ir0nt0ad** [comment]
@ankurankan thank you! One more question, is there a large number of operations that can potentially be moved to GPUs, i.e. will it be possible to dramatically improve overall performance in the future?

**Comment by ankurankan** [comment]
@sh0gg0th I am not very aware of research in that direction and will have to look into it. But of the top of my head and if I remember correctly, there is some work in the direction of formulating structure learning as an optimization problem. That I think could benefit from using GPUs. 

I will also look into latest research and will add here if I find anything interesting.

**Comment by ir0nt0ad** [comment]
@ankurankan thank you, appreciate it.

**Comment by ankurankan** [comment]
@sh0gg0th Here's the paper on the optimization approach to structure learning: https://papers.nips.cc/paper/8157-dags-with-no-tears-continuous-optimization-for-structure-learning.pdf

**Comment by ir0nt0ad** [comment]
@ankurankan great, thank you so much!
