### ISSUE TITLE
Implement the Chow-Liu algorithm for structure learning

### ISSUE THREAD

**Issue by loudly-soft** [pgmpy/pgmpy#1278]
Feature request ticket for adding the [Chow-Liu algorithm](https://en.wikipedia.org/wiki/Chow%E2%80%93Liu_tree#:~:text=Chow%20and%20Liu%20provide%20a,information%20pair%20to%20the%20tree.&text=The%20main%20idea%20in%20the,in%20the%20pairwise%20marginal%20distribution.) to `estimators`.

**Comment by loudly-soft** [comment]
I'll try to pick this up when I have the chance.

**Comment by 1021808202** [comment]
I see “from pgmpy.estimators import TreeSearch” in the Chow liu tree structure learning, but I cant import it in my lab.Can I use it now?

**Comment by 1021808202** [comment]
I have to get the BN which have 600+ nodes,you know,the leaning speed of hillclimb method is too slow.Could you please add the Chow liu tree structure learning to pgmpy as soon as possible,I will appeciate it a lot.

**Comment by loudly-soft** [comment]
@1021808202  FYI, the Chow-Liu algorithm has been merged to `dev`.  Here's an example [notebook](https://github.com/pgmpy/pgmpy/blob/dev/examples/Structure%20Learning%20with%20Chow-Liu.ipynb) on how to use it.

**Comment by ankurankan** [comment]
Fixed in #1289
