### ISSUE TITLE
Blacklist and whitelist logic in Hill Climb Search is mistaken

### ISSUE THREAD

**Issue by kyle-pena-nlp** [pgmpy/pgmpy#1282]
pgmpy 0.1.10
Python 3.8.1
Windows 10

## Expected Behavior
The whitelist edge is in the final network, the blacklist edge is not in the final network

## Actual Behavior
The whitelist edge is *not* in the final network, the blacklist edge *is* in the final network

I've isolated the problem to the conditions related to the flip operation in the _legal_operations method of HillClimbSearch.

```
import pgmpy
import pandas as pd
from pgmpy.estimators.HillClimbSearch import HillClimbSearch
from pgmpy.estimators import K2Score
from pgmpy.models import BayesianModel

blacklist = [("B", "A")]
whitelist = [("A", "B")]

# synthesize data
X = pd.DataFrame({ "A": [1, 0, 1, 0], "B": [0, 1, 0, 0], "C": [1, 1, 1, 1] })

# define starting graph
edges = [("A", "B"), ("A", "C")]


# Initialize the starting model and hill climb search
model = BayesianModel(edges)
search = HillClimbSearch(data = X, scoring_method=K2Score(X))

# Kick off the hill climb search
best_model = search.estimate(start = model, max_indegree = 2, max_iter = 100, white_list = whitelist, black_list = blacklist)

print(("B", "A") in best_model.edges()) # True
print(("A","B") not in best_model.edges()) # True
```

**Comment by ankurankan** [comment]
@kyle-pena-nlp Thanks for reporting this. It should be working fine in the latest dev branch. Will get fixed in the next release.

**Comment by kyle-pena-nlp** [comment]
@ankurankan --- I pulled dev/latest and ran some tests.  Something is still off with the whitelist. 

## Description
For a HillClimbSearch, specifying an empty whitelist does not reuslt in the same behavior as specifying no whitelist.  More generally, I *think* what's going on is that specifying an empty whitelist will cause HillClimbSearch to never do any flip operations.

I found this issue while attempting to show that the whitelist logic for the flip operation was still broken in dev.  Since this bug originates with the same line of code, I figured it's sufficient to post this test.

I'd be happy to submit a PR, but I'd like to discuss how the _legal_operations algorithm guarantees edges in the whitelist will be included (esp. if max_iters < len(whitelist) ) 

pgmpy 0.1.10dev
Python 3.8.0
Windows 10

## Expected Behavior
The networks should be identical whether you pass an empty whitelist or no whitelist at all.

## Actual Behavior
The networks are not identical



```
import pgmpy
import pandas as pd
from pgmpy.estimators.HillClimbSearch import HillClimbSearch
from pgmpy.estimators import K2Score
from pgmpy.models import BayesianModel
import numpy as np

X = np.asarray(["A", "B", "A", "B", "A",
    "B", "C", "C", "B", "A",
    "C", "B", "A", "C", "B",
    "D", "E", "D", "E", "D",
    "A", "B", "C", "D", "E"]).reshape((5,-1))

# synthesize data
X = pd.DataFrame({"A": X[:,0], "B": X[:,1], "C": X[:,2], "D": X[:,3], "E": X[:,4]})


# Initialize the starting model and hill climb search
model = BayesianModel([("A", "B"), ("C", "A"), ("E", "A"), ("D", "B"), ("D", "C"), ("D", "E")])
model.add_nodes_from(list(X.columns.values))
search = HillClimbSearch(data = X, scoring_method=K2Score(X))

# Kick off the hill climb search
m1 = search.estimate(start = model, max_indegree = 2, max_iter = 100, white_list = [])
print((m1.edges()))
m2 = search.estimate(start = model, max_indegree = 2, max_iter = 100)
print((m2.edges()))

assert set(m1.edges()) == set(m2.edges()) # Fails
```
