### ISSUE TITLE
Weighted Likelihood Sampling assumes the values range from 0 to n

### ISSUE THREAD

**Issue by harikc456** [pgmpy/pgmpy#1283]
### Subject of the issue
I'm getting a KeyError when I'm trying to perform a weighted likelihood sampling from BayesianModel. The model is fitted on a dataset where I have attribute age which is of range [3,18]. Going through the code in Sampling.py. I found out the `pre_compute_reduce()` assumes all the nodes have values ranging from 0 to the number of distinct values. In my case, the values generated were from [0,15] range. The CPD of my Age is
```
+-----------+-----------+
| Age(3.0)  | 0.013468  |
+-----------+-----------+
| Age(4.0)  | 0.0353535 |
+-----------+-----------+
| Age(5.0)  | 0.047138  |
+-----------+-----------+
| Age(6.0)  | 0.0319865 |
+-----------+-----------+
| Age(7.0)  | 0.0315657 |
+-----------+-----------+
| Age(8.0)  | 0.0420875 |
+-----------+-----------+
| Age(9.0)  | 0.0787037 |
+-----------+-----------+
| Age(10.0) | 0.0955387 |
+-----------+-----------+
| Age(11.0) | 0.132576  |
+-----------+-----------+
| Age(12.0) | 0.106481  |
+-----------+-----------+
| Age(13.0) | 0.0955387 |
+-----------+-----------+
| Age(14.0) | 0.0925926 |
+-----------+-----------+
| Age(15.0) | 0.0808081 |
+-----------+-----------+
| Age(16.0) | 0.0547138 |
+-----------+-----------+
| Age(17.0) | 0.0353535 |
+-----------+-----------+
| Age(18.0) | 0.0260943 |
+-----------+-----------+
```

### Your environment
pgmpy version 0.1.10
Python version 3.6.10
Windows 8.1

### Steps to reproduce
```
with open('bayes_pneumonia_model.pkl','rb') as f:
    bayes_model = pickle.load(f) 
inference = BayesianModelSampling(bayes_model)
evidence = [State('labels', 1)]
one_df = inference.likelihood_weighted_sample(evidence=evidence, size=10, return_type='dataframe')
```
[bayes_pneumonia_model.zip](https://github.com/pgmpy/pgmpy/files/4784338/bayes_pneumonia_model.zip)

### Expected behaviour
It should have returned a dataframe of samples.
### Actual behaviour

Throws a KeyError : 0

**Comment by ankurankan** [comment]
@harikc456 Thanks for reporting this. But I have fixed this recently (#1273), so it would work fine on the latest dev branch. And it will be out in the next release.
