### ISSUE TITLE
ImportError: cannot import name 'PseudoMomentMatchingEstimator'

### ISSUE THREAD

**Issue by JanineCHEN** [pgmpy/pgmpy#1286]
I am following the book Mastering Probabilistic Graphical Models Using Python, the section "Belief propagation and pseudo-moment matching" for Markov Model, the code `from pgmpy.estimators import PseudoMomentMatchingEstimator` throw out the error `ImportError: cannot import name 'PseudoMomentMatchingEstimator'`, so it seems like the 'PseudoMomentMatchingEstimator'` module hasn't been implemented at the moment?

**Comment by ankurankan** [comment]
@JanineCHEN No, it's not implemented yet. And the book is quite old now, so a lot of things would not work for the current version.
