### ISSUE TITLE
Missing `import` in `LinearGaussianBayesianNetwork.py`

### ISSUE THREAD

**Issue by sandeep-n** [pgmpy/pgmpy#1296]
### Subject of the issue
The `logging` module is used (in the `add_cpds` method) without being imported. This causes an error when attempting to replace 

### Your environment
* pgmpy version: 0.1.11
* Python version: 3.6 (but issue is version-agnostic)
* Operating System: macOS (but issue is OS-agnostic)

### Steps to reproduce
Using an example from `notebooks/Parameterizing with Continuous Variables.ipynb`:

```
from pgmpy.models import LinearGaussianBayesianNetwork

model = LinearGaussianBayesianNetwork([('x1', 'x2'), ('x2', 'x3')])
cpd1 = LinearGaussianCPD('x1', [1], 4)
cpd1.variables = [*cpd1.evidence, cpd1.variable]
model.add_cpds(cpd1)
# Attempt to add same CPD again
model.add_cpds(cpd1)
```

### Expected behaviour
The existing CPD should be replaced by the new CPD (with a WARNING message logged). 

### Actual behaviour
`NameError: name 'logging' is not defined`

**Comment by ankurankan** [comment]
Fixed in #1297
