### ISSUE TITLE
get_markov_blanket produces error for node with no children

### ISSUE THREAD

**Issue by kyle-pena-nlp** [pgmpy/pgmpy#1298]
### get_markov_blanket
get_markov_blanket on a node with no children produces an error. 

### Your environment
* 0.1.11
* Python version 3.8.1
* Windows 10

### Steps to reproduce
```
from pgmpy.models import BayesianModel
test_model = BayesianModel()
test_model.add_edge("A","B")
test_model.add_edge("C","B")
test_model.get_markov_blanket("B")
```

### Expected behaviour
We should get the markov blanked of B, which is nodes A and C, in this case.

### Actual behaviour
We have an exception, a KeyError.

**Comment by ankurankan** [comment]
@kyle-pena-nlp Thanks for reporting this. It has been fixed recently in #1293. If you install the latest `dev` branch from github, it should work fine.
