### ISSUE TITLE
Prettify graph viz with daft in documentation

### ISSUE THREAD

**Issue by loudly-soft** [pgmpy/pgmpy#1311]
@ankurankan What’s your take on the `daft` package?  I saw on the “Causal Games” notebook that it renders pretty nicely the DAG while other examples use static img or `networkx` for viz.  For a more uniform and polished look, perhaps everything could use `daft`?

**Comment by ankurankan** [comment]
@loudly-soft I agree, that's a good idea. I haven't personally tried out `daft` and am not sure what features it has but seems to work quite well at least for the simple cases.

**Comment by loudly-soft** [comment]
@ankurankan Okay, I’ll look into this.

**Comment by ankurankan** [comment]
I have added `pgmpy.base.DAG.to_daft` (https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/base/DAG.py#L830) method which can automatically generate a daft object from the current model. It also accepts parameters that are passed on to daft for creating the object.
