### ISSUE TITLE
 ImportError: cannot import name 'TreeSearch'

### ISSUE THREAD

**Issue by nalanishada** [pgmpy/pgmpy#1321]
Working in GoogleColab

Tried to execute the following line

`from pgmpy.estimators import TreeSearch`

and the error is in Title.

**Comment by ankurankan** [comment]
@nalanishada Could you try installing the dev version from github? TreeSearch was added recently and hasn't been released yet on pypi or conda.

**Comment by nalanishada** [comment]
Yeah, working now. Previously I installed using pip.
