### ISSUE TITLE
I think this is a bug for pgmpy of dbn_inference

### ISSUE THREAD

**Issue by MrYu001** [pgmpy/pgmpy#1322]
### Subject of the issue
this is my code:
```python
import numpy as np
from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.inference import DBNInference
dbnet = DBN()
dbnet.add_edges_from([(('Z', 0), ('X', 0)), (('X', 0), ('Y', 0)), (('W',0),('Z',0)),
                               (('Z', 0), ('Z', 1))])

W_cpd = TabularCPD(('W',0),2,[[0.4],[0.6]])

z_start_cpd = TabularCPD(('Z', 0), 2, [[0.5,0.6], [0.5,0.4]],
                                       evidence=[('W',0)],
                                        evidence_card=[2]) 

#z_start_cpd = TabularCPD(('Z', 0), 2, [[0.4],[0.6]])
x_i_cpd = TabularCPD(('X', 0), 2, [[0.6, 0.9],
                                   [0.4, 0.1]],
                              evidence=[('Z', 0)],
                              evidence_card=[2])

y_i_cpd = TabularCPD(('Y', 0), 2, [[0.2, 0.3],
                                   [0.8, 0.7]],
                              evidence=[('X', 0)],
                              evidence_card=[2])

z_trans_cpd = TabularCPD(('Z', 1), 2, [[0.4, 0.7, 0.2, 0.8],
                                       [0.6, 0.3, 0.8, 0.2]],
                              evidence=[('Z', 0),('W',1)],
                              evidence_card=[2,2]) 

""" z_trans_cpd = TabularCPD(('Z', 1), 2, [[0.4, 0.7],
                                       [0.6, 0.3]],
                              evidence=[('Z', 0)],
                              evidence_card=[2]) """
dbnet.add_cpds(W_cpd,z_start_cpd, z_trans_cpd, x_i_cpd, y_i_cpd)
dbnet.initialize_initial_state()
```
####
And the error is that:ValueError: values must be of shape (2, 1). Got shape: (1, 2)
but i think my procedure of that adding the 'W' prior [[0.4],[0.6]] is right
so thank you very much for someone can help me resolve this problem

**Comment by MrYu001** [comment]
i find out this problem  and the method is to add one more time-slice cpd  (like this  " W1_cpd = TabularCPD(('W',1),2,[[0.4],[0.6]]) 
"), for the 'W' Node int the 1 time_slice.

**Comment by ankurankan** [comment]
The error message should be clearer in this case.

**Comment by FelipeGiro** [comment]
I could not get this error with the given code. Is it possible that previous release already fixed that?

**Comment by ankurankan** [comment]
Yeah, I think this is fixed now. This was related to a bug in TabularCPD. Closing.

**Comment by harishkashyap** [comment]
this issue is coming up in the latest push to master. 

active_cpd = TabularCPD(variable='A',
                       variable_card=2,
                       values=[[.3, .7]])

schedule_cpd = TabularCPD(variable='S',
                       variable_card=2,
                       values=[[.9, .1]])

**Comment by ankurankan** [comment]
@harishkashyap Do you mean you are getting the error during the CPD definition? The values array should be of shape (2, 1) in this case. Something like this:
```python
In [4]: active_cpd = TabularCPD(variable='A',
   ...: variable_card=2,
   ...: values=[[.3], [.7]])
```
