### ISSUE TITLE
Can I learn the structure and parameters of Bayesian networks at the same time？

### ISSUE THREAD

**Issue by ysgncss** [pgmpy/pgmpy#1323]
There are 2 way of learning Bayesian Networks : Parameter learning and  Structure learning. Can it learn a model consisting of paramater and structure from data?

**Comment by ankurankan** [comment]
@ysgncss Yes, it will be a two-step process. First would be to learn the network structure from the and then learn the model parameters. You can have a look at examples for structure learning: https://github.com/pgmpy/pgmpy/blob/dev/examples/Structure%20Learning%20in%20Bayesian%20Networks.ipynb and for parameter learning:https://github.com/pgmpy/pgmpy/blob/dev/examples/Learning%20Parameters%20in%20Discrete%20Bayesian%20Networks.ipynb
