### ISSUE TITLE
automatic learning structure of Bayesian Networks

### ISSUE THREAD

**Issue by ysgncss** [pgmpy/pgmpy#1329]
Do I have to specify dependencies between variables when I learn network structure from data？When I annotate the relationship between variables, the output structure is empty. Here is my code:

    data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
    # data['A'] += data['B'] + data['C']
    # data['H'] = data['G'] - data['A']
    # data['E'] *= data['F']
    mmhc = MmhcEstimator(data)
    skeleton = mmhc.mmpc()
    # use hill climb search to orient the edges:
    hc = HillClimbSearch(data, scoring_method=BDeuScore(data))
    model = hc.estimate(tabu_length=10, white_list=skeleton.to_directed().edges())

this is output:
Part 1) Skeleton:  [('A', 'E'), ('B', 'D'), ('B', 'C'), ('B', 'H'), ('D', 'G'), ('E', 'F'), ('F', 'G')]
Part 2) Model:     []

**Comment by nihil21** [comment]
This affects me too

**Comment by ankurankan** [comment]
This seems to be happening because of the preference of structure scoring methods to choose simpler models. As in the case of completely random data, there is no information of dependence, hence it chooses the simplest model with no edges. But if we add some data dependency it starts to learn edges:
```python
>>> data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
>>> data['A'] += data['B'] + data['C']
>>> data['H'] = data['G'] - data['A']
>>> data['E'] *= data['F']

>>> mmhc = MmhcEstimator(data)
>>> skeleton = mmhc.mmpc()
>>> skeleton.edges()
EdgeView([('A', 'B'), ('A', 'H'), ('A', 'C'), ('A', 'G'), ('A', 'F'), ('B', 'C'), ('C', 'F'), ('C', 'D'), ('D', 'E'), ('D', 'F'), ('E', 'F'), ('E', 'G'), ('F', 'H'), ('G', 'H')])

>>> est = HillClimbSearch(data)
>>> dag = est.estimate(tabu_length=10, white_list=skeleton.to_directed().edges())
  0%|                                                   | 8/1000000 [00:00<9:09:39, 30.32it/s]
<pgmpy.base.DAG.DAG at 0x7fbe51020bb0>
>>> dag.edges()
OutEdgeView([('A', 'C'), ('A', 'B'), ('A', 'G'), ('C', 'B'), ('E', 'F'), ('H', 'A'), ('H', 'G')])

```
