### ISSUE TITLE
KeyError in DynamicBayesianNetwork.get_markov_blanket()

### ISSUE THREAD

**Issue by nihil21** [pgmpy/pgmpy#1331]
### Subject of the issue
The method `get_markov_blanket()` in class `DynamicBayesianNetwork` (inherited from class `DAG`) raises a `KeyError` when the `node` passed is a leaf node. The faulty instruction is `blanket_nodes.remove(node)`. 

### Your environment
* pgmpy version 0.1.11dev
* Python version 3.8.5
* Operating System Manjaro Linux x86_64

### Steps to reproduce
```
from pgmpy.models import DynamicBayesianNetwork

dyn_edges = [(('IC1', 0), ('IC1', 1)),
                       (('IC2', 0), ('IC2', 1)),
                       (('IC3', 0), ('IC3', 1)),
                       (('IC4', 0), ('IC4', 1)),
                       (('IC4', 0), ('IC1', 1)),
                       (('IC4', 0), ('IC7', 1)),
                       (('IC4', 0), ('IC13', 1)),
                       (('IC4', 0), ('IC15', 1))]
dyn_model = DynamicBayesianNetwork(dyn_edges)
blanket = dyn_model.get_markov_blanket(('IC1', 1))
```

### Expected behaviour
```
blanket = {('IC1', 0), ('IC4', 0)}
```

### Actual behaviour
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-36-0872f3e59c00> in <module>
      8              (('IC4', 0), ('IC15', 1))]
      9 dyn_model = DynamicBayesianNetwork(dyn_edges)
---> 10 dyn_model.get_markov_blanket(('IC1', 1))

./pgmpy/base/DAG.py in get_markov_blanket(self, node)
    580             blanket_nodes.extend(self.get_parents(child_node))
    581         blanket_nodes = set(blanket_nodes)
--> 582         blanket_nodes.remove(node)
    583         return list(blanket_nodes)
    584 

KeyError: ('IC1', 1)
```

### Possible fix
Replace `blanket_nodes.remove(node)` in `DAG.py` with `blanket_nodes.discard(node)` should solve the issue.

**Comment by ankurankan** [comment]
@nihil21 Sorry for the delay on this. I don't think `discard` solves the problem as the markov blanket would also contain children nodes (which would be in the next time slice) and their parents (which could be in the same time slice as the queried variable). I think the easiest way to fix this right now would be to unroll the dynamic network (the queried time slice and +-1) and then use the `get_markov_blanket` method on that to get the true blanket.

**Comment by nihil21** [comment]
Actually I tested the modified `get_markov_blanket` method (with `discard`) on query variables in the first time slice and the result is as expected. Under-the-hood it relies on the `DAG.get_markov_blanket` method, and if I've understood correctly the `DAG` class does not make any assumption on the "dynamicity" of the network, it treats it as a generic directed acyclic graph, am I right?

**Comment by ankurankan** [comment]
@nihil21 Yes you are right that the `DAG.get_markov_blanket` assumes the model to be a simple Bayesian Network and that is also the reason why your fix doesn't give the expected result. The expected markov blanket for (IC1, 1) in your example should be: (IC1, 0), (IC4, 0), (IC1, 2), (IC4, 1). The problem is that the Dynamic Bayesian Network class represents the model as a 2-TBN (just stores the first two time slices) and dynamically generates the rest of the time slices when required. So, in this case the 2-TBN representation is not enough as we need nodes from the 3rd time slice as well. To fix it, we will need to generate this additional time-slice before calling the `get_markov_blanket` method.

**Comment by nihil21** [comment]
I didn't think about the third time slice, you're right.
