### ISSUE TITLE
Error with initialize_initial_state() in Dynamic Bayesian Network

### ISSUE THREAD

**Issue by MrLatter** [pgmpy/pgmpy#1336]
### Subject of the issue

model.initialize_initial_state() is showing errorValueError: values must be of shape (2, 1). Got shape: (1, 2)

### Your environment
* pgmpy version - Latest
* Python version - 3.7
* Operating System - Mac

### Steps to reproduce
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD

    model = DBN()
    # Add nodes
    model.add_nodes_from(['Weather', 'Umbrella'])
    # Print nodes
    print('--- Nodes ---')
    print(model.nodes())
    # Add edges
    model.add_edges_from([(('Umbrella',0), ('Weather',0)),
                          (('Weather',0), ('Weather',1)),
                          (('Umbrella',0), ('Umbrella',1))])
    # Print edges
    print('--- Edges ---')
    print(model.edges())
    print()
    # Print parents
    print('--- Parents ---')
    print('Umbrella 0: {0}'.format(model.get_parents(('Umbrella', 0))))
    print('Weather 0: {0}'.format(model.get_parents(('Weather', 0))))
    print('Weather 1: {0}'.format(model.get_parents(('Weather', 1))))
    print('Umbrella 1: {0}'.format(model.get_parents(('Umbrella', 1))))
    print()
    # Add probabilities
    weather_cpd = TabularCPD(('Weather', 0), 2, np.reshape([[0.1, 0.8], 
                                                                        [0.9, 0.2]], (-1, 2)), 
                                                       evidence=[('Umbrella', 0)], 
                                                       evidence_card=[2])
    umbrella_cpd = TabularCPD(('Umbrella', 1), 2, [[0.5, 0.5], 
                                                                          [0.5, 0.5]], 
                                                     evidence=[('Umbrella', 0)], 
                                                     evidence_card=[2])
    transition_cpd = TabularCPD(('Weather', 1), 2, [[0.25, 0.9, 0.1, 0.25], 
                                                                           [0.75, 0.1, 0.9, 0.75]], 
                                                   evidence=[('Weather', 0), ('Umbrella', 1)], 
                                                   evidence_card=[2, 2])
    # Add conditional probability distributions (cpd:s)
    model.add_cpds(weather_cpd, umbrella_cpd, transition_cpd)
    # This method will automatically re-adjust the cpds and the edges added to the bayesian network.
    model.initialize_initial_state()

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Similar example to a problem I am facing in my own personal research. The author of the example gets results but I get the above error - perhaps this is bug as a result of Networkx 4.4.0 (as mentioned in a similar Issue) or something else?

**Comment by ankurankan** [comment]
@MrLatter There is a missing CPD for the initial state of Umbrella. Something like:
```
umbrella_cpd_0 = TabularCPD(('Umbrella', 0), 2, [[0.5], [0.5]])
```
And if you initialize the model after adding `umbrella_cpd_0` as well to the model, it should work.
