### ISSUE TITLE
Add MU+BDs for Bayesian network structure learning

### ISSUE THREAD

**Issue by mjmt05** [pgmpy/pgmpy#1337]
Add in the ability to use the Marginal Uniform and Bayesian Dirichlet sparse prior from http://proceedings.mlr.press/v52/scutari16.pdf for structure learning in Bayesian networks. 

I think this will be fairly straightforward by adding in a class that inherits from the BDeuScore class in `pgmpy.estimators.StructureScore`.

**Comment by ankurankan** [comment]
@mjmt05 Yes, this shouldn't be very difficult. If you would like to contribute this, you are most welcome else I will try to implement this :)
