### ISSUE TITLE
Anomaly scoring the same structure during learning

### ISSUE THREAD

**Issue by villamroland** [pgmpy/pgmpy#1343]
### Subject of the issue
The difference using two similar functions to score a structure with a dataframe

### Your environment
* pgmpy version: 0.1.10
* Python version: 3.7.6
* Operating System: ubuntu server

### Steps to reproduce
I would like to use the K2 score() function to get to score of a structure to my dataframe. Using the function: 

```
searcher = ExhaustiveSearch(df, scoring_method=K2Score(df))
for score, model in searcher.all_scores():
    print("{0}        {1}".format(score, model.edges()))
```

I get the following result:
-19168.236258732806        [('X', 'Y')]
-19168.2362587328        [('Y', 'X')]
-19165.495842793658        []
-19071.49054148657        [('X', 'Y'), ('Y', 'Z')]
-19071.490541486564        [('Y', 'Z'), ('Y', 'X')]
-19071.490541486557        [('Y', 'X'), ('Z', 'Y')]
-19068.75012554742        [('Y', 'Z')]
-19068.750125547413        [('Z', 'Y')]
-19056.66900381345        [('X', 'Y'), ('Z', 'Y')]
-18120.76876957119        [('X', 'Y'), ('X', 'Z')]
-18120.76876957119        [('X', 'Y'), ('Z', 'X')]
-18120.768769571183        [('X', 'Z'), ('Y', 'X')]
-18118.028353632042        [('X', 'Z')]
-18118.028353632042        [('Z', 'X')]
-18105.94723189808        [('Y', 'X'), ('Z', 'X')]
-18021.282636385804        [('Y', 'Z'), ('Z', 'X')]
-18021.282636385797        [('X', 'Z'), ('Z', 'Y')]
-18021.282636385797        [('Z', 'X'), ('Z', 'Y')]
-18009.201514651853        [('X', 'Y'), ('X', 'Z'), ('Y', 'Z')]
-18009.201514651846        [('X', 'Z'), ('Y', 'Z'), ('Y', 'X')]
-18009.201514651846        [('Y', 'Z'), ('Y', 'X'), ('Z', 'X')]
-18009.20151465184        [('Y', 'X'), ('Z', 'X'), ('Z', 'Y')]
-18009.201514651835        [('X', 'Y'), ('X', 'Z'), ('Z', 'Y')]
-18009.201514651835        [('X', 'Y'), ('Z', 'X'), ('Z', 'Y')]
-18006.4610987127        [('X', 'Z'), ('Y', 'Z')]

Which is okay, the best structure is [('X', 'Z'), ('Y', 'Z')], as i expected, and a get the same score using the function:

```
myscore = K2Score(df).score(BayesianModel([('X', 'Z'), ('Y', 'Z')]))
        print(myscore)
```

output:-18006.4610987127 
This one is also okay.

But if I score the structure when I only have one edge I get a very different score.

myscore = K2Score(df).score(BayesianModel([('X', 'Z')]))
        print(myscore)

output: -12298.858365943415

### Expected behavior
I should get the same score using these two similar methods. I suppose during the scoring the Y column is not used. If not that, I don't know what the source of the issue, but I really need to know the exact score.  Is this possible? Or should I use the single scoring function another way?

Thank you so much!

**Comment by ankurankan** [comment]
Ref: https://gitter.im/pgmpy/pgmpy?at=5f8d427aea6bfb0a9a4449ef
