### ISSUE TITLE
Issues with DAG produced by Hillclimbsearch pgmpy-0.1.12

### ISSUE THREAD

**Issue by Siniara** [pgmpy/pgmpy#1347]
### Subject of the issue
The DAG generated by the HillClimbSearch does not give the same results as stated in the pgmpy readme.
I'm new to Bayesian Networks so I may be missing something, but after some experimentation earlier versions of pgmpy seem to give results that align more with what I'd expect.

### My environment
* pgmpy version 0.1.12
* Python version 3.6.9 (Google Collab) and 3.8 (local)
* Operating System - Windows 10

### Steps to reproduce
This is the code provided in the official documentation at the HillClimbSearch entry, which does not produce the same results.
## Example 1
```
import numpy as np
import pandas as pd
from pgmpy.estimators import BicScore, HillClimbSearch
from pgmpy.models import BayesianModel

# create data sample with 9 random variables:
data = pd.DataFrame(np.random.randint(0, 5, size=(5000, 9)), columns=list('ABCDEFGHI'))
# add 10th dependent variable
data['J'] = data['A'] * data['B']
est = HillClimbSearch(data, scoring_method=BicScore(data))
best_model = est.estimate()
best_model.edges()
```
### Expected behaviour
As in the docs
[('B', 'J'), ('A', 'J')]  

### Actual behaviour
[('B', 'A'), ('J', 'B'), ('J', 'A')] or [('A', 'B'), ('J', 'B'), ('J', 'A')] 
Reverting to 0.1.11 gives the expected result

## Example 2
My own example; this performs worse also with v0.1.11
```
# create some data with dependencies
data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
data['A'] = data['B'] + data['C']
data['H'] = data['G'] - data['A']

hc = HillClimbSearch(data, scoring_method=BicScore(data))
best_model = hc.estimate()
print(best_model.edges())
```
### Expected behaviour
[('A', 'H'), ('B', 'A'), ('C', 'A'), ('G', 'H')]

### Actual behaviour
[('A', 'B'), ('A', 'C'), ('A', 'G'), ('C', 'B'), ('H', 'A'), ('H', 'G')]
Here Reverting to 0.1.11 sometimes gets to the expected result after rerunning the algorithm multiple times.
I get that this is local optimisation, but it seems that in the latest version it performs consistently worse not being able to find the expected graph at all. Then the question arises what would be the best practice when you don't know the expected structure beforehand.

**Comment by ankurankan** [comment]
@Siniara Thanks for reporting this. I am looking into it, will let you know once it's fixed.

**Comment by ankurankan** [comment]
@Siniara I think the difference you are seeing is because of using different scoring methods. There was an API change in 0.1.12 and the `scoring_method` argument was moved to the `estimate` method instead of specifying it while initializing. So, your code is using `K2Score` (the default scoring method) for v0.1.12 and `BicScore` for v0.1.11. If you change your code and specify the scoring_method in the estimate method, you will get similar results. I tried to compare both the versions on your second example by running them 1000 times and the latest version seems to be able to learn sparser structures.
```
# Number of edges in best model : Number of times
v0.1.11: { 4: 116, 5: 218, 6: 666 }
v0.1.12: { 4: 246, 5: 442, 6: 312 }
```
