### ISSUE TITLE
ValueError in HillClimbSearch().estimate()

### ISSUE THREAD

**Issue by Kuril951** [pgmpy/pgmpy#1348]
### Subject of the issue
It raises ValueError when estimating the graph with the HillClimbSearch model.

### Your environment
* pgmpy version : 0.1.12
* Python version : 3.7.7
* Operating System : Ubuntu 18.04.2 LTS

### Steps to reproduce
```python3
data = pd.DataFrame(
        [[1,0,0,1,0,0,1,1,0],
         [1,0,1,0,0,1,0,1,0],
         [1,0,0,0,0,1,0,1,1],
         [1,1,0,1,0,1,1,0,0],
         [0,0,1,0,0,1,1,0,0]],
        columns=list('ABCDEFGHI')
    )
est = HillClimbSearch(data)
best_model = est.estimate(
    fixed_edges=[('A','B'), ('B', 'C')],
    white_list=[('F','C')]
)
```

### Expected behaviour
1. return model with fixed edges
or
2. return model with fixed_edges and white_list edges

### Actual behaviour
![image](https://user-images.githubusercontent.com/23306402/98773788-01f69e80-242d-11eb-904f-9295b00fc147.png)

**Comment by ankurankan** [comment]
@Kuril951 If you install the latest `dev` branch this should work now.
