### ISSUE TITLE
About BN's Incremental update’

### ISSUE THREAD

**Issue by wadenash1** [pgmpy/pgmpy#1350]
### Subject of the issue
 If we had an established Bayesian Network, Now we have some datas about it, Can we use this datas update the established Bayesian Network, instead of re-learning all the datas(the original datas and the datas we just mentiond) to Caculate the Bayesian Network's parameters?

### Your environment
* pgmpy version
* Python version
* Operating System

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
@wadenash1 There is no direct method to do this but a workaround can be to use the `BayesianEstimator` with `dirichlet` prior. Also, the values might be slightly different when compared to fitting the whole dataset at the same time because of numerical differences because of the `psuedo_counts` computation.Here's an example:
```python
# Generate a bunch of datasets
In [50]: df = [pd.DataFrame(np.random.randint(low=0, high=3, size=(1000, 3)), columns=list('ABC')) for _ in range(5)]

# Train the initial model and maintain a variable with the total size of trained dataset
In [51]: n_train_samples = 0                   

In [52]: model = BayesianModel([('A', 'B'), ('C', 'B')])                                      

In [53]: model.fit(df[0])                      

In [54]: n_train_samples += df[0].shape[0]     

# Use BayesianEstimator to update the model.

In [55]: for i in range(1, 5): 
    ...:     pseudo_counts = {var: model.get_cpds(var).get_values() * n_train_samples for var in list('ABC')} 
    ...:     est = BayesianEstimator(model, df[i]) 
    ...:     params = est.get_parameters(prior_type='dirichlet', pseudo_counts=pseudo_counts) 
    ...:     model.add_cpds(*params) 
    ...:     n_train_samples += df[i].shape[0] 
    ...:                                       
WARNING:root:Replacing existing CPD for A
WARNING:root:Replacing existing CPD for B
WARNING:root:Replacing existing CPD for C
WARNING:root:Replacing existing CPD for A
WARNING:root:Replacing existing CPD for B
WARNING:root:Replacing existing CPD for C
WARNING:root:Replacing existing CPD for A
WARNING:root:Replacing existing CPD for B
WARNING:root:Replacing existing CPD for C
WARNING:root:Replacing existing CPD for A
WARNING:root:Replacing existing CPD for B
WARNING:root:Replacing existing CPD for C
```
