### ISSUE TITLE
About BN's incremental Learning's follow-up Question

### ISSUE THREAD

**Issue by wadenash1** [pgmpy/pgmpy#1352]
As your mentioned in https://github.com/pgmpy/pgmpy/issues/1350#issuecomment-726724566，my projects worked very well, thank u very much.  

But I've encountered another problem as follows:
ValueError: The shape of pseudo_counts for the node: A must be of shape: (1, 1)
 
Base on my experiment，I this might be casued by the missing status number.

For example:
      If the node A has tow status numbers: 0 and 1, but all the datas used for incremetal learining about A don't contains 0 or 1，the system will report above error.

the datas used for  incremetal learining as follows (as u see,  column A don's have the status number 1):
df = pd.DataFrame([[0, 0, 0], 
                                [0, 1, 1],
                                [0, 1, 1],
                                [0, 0, 0],], columns=list('ABC'))

Could u help me to fix this problem based on the condition of existing datas, thx a lot.

**Comment by ankurankan** [comment]
@wadenash1 In case of missing states, you can specify a `state_names` argument to the `fit` method and when initializing the `BayesianEtimator`. Here's an extension to the last example with the state number `2` missing this time in the data but I have used the `state_names` parameter to specify that:
```python
In [50]: df = [pd.DataFrame(np.random.randint(low=0, high=2, size=(1000, 3)), columns=list('ABC')) for _ in range(5)] 
  
# Train the initial model and maintain a variable with the total size of trained dataset 
In [51]: n_train_samples = 0                    
In [52]: model = BayesianModel([('A', 'B'), ('C', 'B')])                                       
In [53]: model.fit(df[0], state_names={'A': [0, 1, 2], 'B': [0, 1, 2], 'C': [0, 1, 2]})                         
In [54]: n_train_samples += df[0].shape[0]        
# Use BayesianEstimator to update the model. 
In [55]: for i in range(1, 5):  
    ...:     pseudo_counts = {var: model.get_cpds(var).get_values() * n_train_samples for var in list('ABC')}  
    ...:     est = BayesianEstimator(model, df[i], state_names={'A': [0, 1, 2], 'B': [0, 1, 2], 'C': [0, 1, 2]})  
    ...:     params = est.get_parameters(prior_type='dirichlet', pseudo_counts=pseudo_counts)  
    ...:     model.add_cpds(*params)  
    ...:     n_train_samples += df[i].shape[0] 
In [56]: print(model.get_cpds()[0])                                                                                                                                                           
+------+--------+
| A(0) | 0.5082 |
+------+--------+
| A(1) | 0.4918 |
+------+--------+
| A(2) | 0      |
+------+--------+

```
