### ISSUE TITLE
[Question] Can I use gradient descent for parameter learning of Bayesian networks through pgmpy?

### ISSUE THREAD

**Issue by lwgkzl** [pgmpy/pgmpy#1353]
As shown in the question, the structure of the Bayesian network has been determined, and I want to update the parameters of the Bayesian network using a negative log likelihood as loss.
Does pgmpy now support this implementation? Or how do I implement this function on top of pgmpy?
Thanks for any help!

**Comment by ankurankan** [comment]
@lwgkzl Yes, we currently have an implementation for optimization based parameter learning but only for the case of SEMs (which are equivalent to gaussian Bayesian networks with linear relations) here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/estimators/SEMEstimator.py#L193. You can specify the optimizer you want to use for the optimization (the default is adam).
