### ISSUE TITLE
Some bugs in PC -> skeleton_to_pdag

### ISSUE THREAD

**Issue by yzh211** [pgmpy/pgmpy#1359]
### Some bugs in PC -> skeleton_to_pdag
When I debug the module `PC`, I found that `node_pairs` in `skeleton_to_pdag` is defined as a `combination` iterator. So after first iteration, it will not yield any more. Check this answer:

https://stackoverflow.com/a/25336739

In another words, steps 2, 3, and 4 in `skeleton_to_pdag` are not performed in all circumstances. In addition, all codes inside of those `for` loop (steps 2, 3, and 4) have never been tested out. Bugs in there are not reflected by the tests results.

### Your environment
* pgmpy 0.1.12
* Python 3.6.11
* Operating System Ubuntu Linux x86_64

### Steps to reproduce
Using a simple example of `PC` estimation

```
from itertools import combinations
from pgmpy.estimators import PC
from pgmpy.utils import get_example_model
from pgmpy.sampling import BayesianModelSampling
import networkx as nx
import matplotlib.pyplot as plt

if __name__ == "__main__":
    model = get_example_model('asia')
    samples = BayesianModelSampling(model).forward_sample(size=int(1e5))
    est = PC(data=samples)
    dag = est.estimate(variant='stable', return_type="dag", max_cond_vars=5, significance_level=0.01)
    nx.draw_circular(dag, with_labels=True)
    plt.show()
```

### Expected behaviour
`node_pairs` in `PC` are desired to be iterated several times.

### Actual behaviour
In the first step's loop, everything is correct.
![Screenshot from 2020-12-08 09-01-02](https://user-images.githubusercontent.com/63798002/101494012-ca4c1b00-3934-11eb-8244-e5a1b42a2a8a.png)

In the second loop, `node_loop` will not yield, thus, step 2, 3, and 4 are all skipped in all cases. Some bugs inside of loop, too.
![Screenshot from 2020-12-08 09-02-40](https://user-images.githubusercontent.com/63798002/101494202-041d2180-3935-11eb-86b1-adc8747421d0.png)

I would like to open a pull request to fix this. Thanks!

**Comment by ankurankan** [comment]
@yzh211 Thanks a lot for pointing out this bug. A PR fixing this would be great :)
