### ISSUE TITLE
installation error on windows 64

### ISSUE THREAD

**Issue by mghanava** [pgmpy/pgmpy#1363]
Have been using pgmpy previously on Ubuntu with no issue. But now, I can't get it installed in windows. I have tried all three methods of conda, pip and even downloading direct source codes. When I go thru the conda path, I get this error:

Downloading and Extracting Packages
pgmpy-0.1.12         | 9.6 MB    |                                                                                                              |   0%

InvalidArchiveError('Error with archive C:\\Users\\<UserName>\\miniconda3\\pkgs\\pgmpy-0.1.12-py37_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')

![image](https://user-images.githubusercontent.com/52111431/102742721-cfd13a00-4312-11eb-8a47-5eeb4725c93b.png)

I am stuck several days. Any help appreciated. Thanks

**Comment by ankurankan** [comment]
@mghanava I don't think this is related to the package and seems to be a problem with conda or your env. Have you already tried this: https://stackoverflow.com/questions/59657306/invalidarchiveerror-when-executing-conda-install-notebook? Or maybe installing in a new conda environment?

**Comment by mghanava** [comment]
Thanks Ankurankan

I followed your link. A little bit of improvement as you can see, but again it does not install the specific pgmpy package. I have removed/create the environment several times. It is just a separate environment for this package to assure compatibility. I do not have any other issue with other environments that I am working, so I am not sure if it is related to conda. any other suggestion appreciated.  

Downloading and Extracting Packages
python_abi-3.7       | 4 KB      | ############################################################################################ | 100%
pytorch-1.3.1        | 50.8 MB   | ############################################################################################ | 100%
certifi-2020.12.5    | 143 KB    | ############################################################################################ | 100%
setuptools-49.6.0    | 919 KB    | ############################################################################################ | 100%
msys2-conda-epoch-20 | 3 KB      | ############################################################################################ | 100%
cffi-1.14.4          | 226 KB    | ############################################################################################ | 100%
blas-1.0             | 1 KB      | ############################################################################################ | 100%
wincertstore-0.2     | 15 KB     | ############################################################################################ | 100%
numpy-1.19.4         | 4.8 MB    | ############################################################################################ | 100%
_pytorch_select-1.1. | 2 KB      | ############################################################################################ | 100%
mkl-service-2.3.0    | 49 KB     | ############################################################################################ | 100%
networkx-2.5         | 1.2 MB    | ############################################################################################ | 100%
scipy-1.5.3          | 21.9 MB   | ############################################################################################ | 100%
vc-14.1              | 6 KB      | ############################################################################################ | 100%
pgmpy-0.1.12         | 9.6 MB    |                                                                                              |   0%
pandas-1.1.5         | 9.4 MB    | ############################################################################################ | 100%
statsmodels-0.12.1   | 10.5 MB   | ############################################################################################ | 100%

InvalidArchiveError('Error with archive C:\\Users\\mghan\\miniconda3\\pkgs\\pgmpy-0.1.12-py37_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')

**Comment by schaafjs** [comment]
I had the same issue and fixed it by using `pip` instead of `conda` to install `pgmpy` in my anaconda environment.
You can install `pgmpy` with the following command (using Anaconda Prompt): `pip install pgmpy`.

If you don't have `pip` installed in your anaconda environment, you have to install it first using Anaconda Prompt: `conda install pip` (may require a reboot before it can actually be used).

**Comment by mghanava** [comment]
thanks
