### ISSUE TITLE
get_example_model ConnectionRefuseError

### ISSUE THREAD

**Issue by 1589864500** [pgmpy/pgmpy#1369]
### Subject of the issue
Describe your issue here.

I installed pgmpy via pip (no other packages were installed).
A connection timeout problem was encountered while using the get_example_model function.(from pgmpy.utils import get_example_model)
Do I need to open the service in the console or download other third-party packages?
Or maybe it's because I have a bad Internet connection (which I personally think is low).

Thank you for any help!
![image](https://user-images.githubusercontent.com/42332285/103529271-54e65280-4ec0-11eb-9e02-bfd94bc915a0.png)

### Your environment
* pgmpy version 0.1.13
* Python version  3.6.6
* Operating System Win10

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

This is the ideal input and output:
![image](https://user-images.githubusercontent.com/42332285/103529887-6d0aa180-4ec1-11eb-9cd9-af73b937ab84.png)

**Comment by ankurankan** [comment]
@1589864500 The bnlearn.com website seems to be down. `get_example_model` fetches the model file from there, and that's the error. I think you will just have to wait or if you have a model file downloaded you can always load it using `pgmpy.readwrite` module.

**Comment by ankurankan** [comment]
@1589864500 bnlearn.com seems to be back up again. The code should work now.

**Comment by 1589864500** [comment]
@ankurankan Thank you very much. bnlearn.com is actually working
