### ISSUE TITLE
Bug in BayesianModel#getIndependencies(latex=True)

### ISSUE THREAD

**Issue by delvh** [pgmpy/pgmpy#1372]
### Subject of the issue
When calling `BayesianModel#getIndependencies(latex=True)` on such a model, an empty dependency separator will be displayed at the end of a latex string, even if there is no variable behind it.
This problem does not appear when using the normal representation.
To showcase this, please refer to the code below.

### Your environment
* pgmpy version: 0.1.13
* Python version 3.6
* Operating System: Ubuntu 18.04

### Steps to reproduce
`from pgmpy.utils import get_example_model`
`model = get_example_model('cancer')`
`print(model.get_independencies())`
`print(model.get_independencies(latex=True))`

### Actual behaviour
first line of latex string is:
`['Pollution \\perp Smoker \\mid ',`
The same applies for any other root variable.

### Expected behaviour
first line of latex string should be:
`['Pollution \\perp Smoker',`

### Comparison to normal representation:
first line is:
`(Pollution _|_ Smoker)`

**Comment by ankurankan** [comment]
@delvh Thanks for reporting the bug. It should be fixed now on the latest dev branch.
