### ISSUE TITLE
Displaying the independency symbol directly instead of using a workaround

### ISSUE THREAD

**Issue by delvh** [pgmpy/pgmpy#1374]
### Subject of the issue
Currently, `_|_` gets displayed instead of the actual symbol, `⟂` (U+27C2), when calling for example `<BayesianModel>.getIndependencies()` (I don't know if the `Independencies` object gets called anywhere else).
As far as I know, Python supports printing UTF-8 characters natively.
The only question is: Is there any reason that speaks against using `⟂` instead of `_|_` ?
Because if there is none, the workaround should be replaced by the actual symbol.
As far as I have seen, there are a few locations, where this would need to be changed, especially inside the documentation.

### Your environment
* pgmpy version 0.1.13
* Python version 3.6
* Operating System Ubuntu 18.04

### Expected behaviour
All occurrences of `_|_` should be replaced with `⟂` (and yes, you can just copy and paste that from here into any string).

**Comment by ankurankan** [comment]
@delvh Except for being easier to write there is no real reason for using the ascii characters. But I tested the UTF character and I think it looks much better in the rendered documentation. I can go ahead and replace it unless you would like to open a PR for it?

**Comment by delvh** [comment]
Yeah, go ahead :+1: .
