### ISSUE TITLE
cannot import name 'ConstraintBasedEstimator'

### ISSUE THREAD

**Issue by lewisscola** [pgmpy/pgmpy#1378]
### Subject of the issue
Can't import ConstraintBasedEstimator in this example: https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/9.%20Learning%20Bayesian%20Networks%20from%20Data.ipynb.

### Your environment
* pgmpy version 0.1.13
* Python version 3.8.3
* Operating System windows 10

### Steps to reproduce
```from pgmpy.estimators import ConstraintBasedEstimator

data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
data['A'] += data['B'] + data['C']
data['H'] = data['G'] - data['A']
data['E'] *= data['F']

est = ConstraintBasedEstimator(data)

print(est.test_conditional_independence('B', 'H'))          # dependent
print(est.test_conditional_independence('B', 'E'))          # independent
print(est.test_conditional_independence('B', 'H', ['A']))   # independent
print(est.test_conditional_independence('A', 'G'))          # independent
print(est.test_conditional_independence('A', 'G',  ['H']))  # dependent.
```

When I run the line 10 code, I encounter this error:
![image](https://user-images.githubusercontent.com/68086673/106661380-24511180-656f-11eb-9921-84ab5fd2e654.png)

Anyone can help me how to fix this?

Thank you!

**Comment by ankurankan** [comment]
@lewisscola That notebook is a bit outdated and needs to be updated. In the meanwhile, you can have a look at this one: https://github.com/pgmpy/pgmpy/blob/dev/examples/Structure%20Learning%20in%20Bayesian%20Networks.ipynb for examples on structure learning.
