### ISSUE TITLE
predict probability of a new sample

### ISSUE THREAD

**Issue by mahmoudibrahim98** [pgmpy/pgmpy#1379]
I want to calculate the probability of a sample under a Bayesian network( as the product of the probability of each variable given its parents, if it has any). So to do that, I'm making inference with no variables and all the attributes with their values are considered evidence.  My attributes are continuous
`evidence_dict={var1:val1,var2:val2,var3:val3}`
`infer.query(variables=[],evidence=evidence_dict,joint=True)`
However, I'm getting aMemoryError: Unable to allocate 9.34 TiB for an array with shape (938, 842, 2, 897, 906) and data type float64.

How can I calculate the probability of a new sample knowing my data contain continuous variables?

**Comment by ankurankan** [comment]
@mahmoudibrahim98 This is happening because the joint distribution is too huge. The joint distribution is exponential in the number of variables (and their cardinality), so I would suggest reducing the number of variables or their cardinalities.

**Comment by scku208** [comment]
@ankurankan Hi, I also want to calculate the probability of a sample under Bayesian network, from the example code with last line changed to:

```
from pgmpy.inference import VariableElimination
from pgmpy.models import BayesianNetwork
import numpy as np
import pandas as pd
values = pd.DataFrame(np.random.randint(low=0, high=2, size=(1000, 5)),
                      columns=['A', 'B', 'C', 'D', 'E'])
model = BayesianNetwork([('A', 'B'), ('C', 'B'), ('C', 'D'), ('B', 'E')])
model.fit(values)
inference = VariableElimination(model)
inference.query([], evidence={'A':0, 'B':1, 'C':1, 'D':1, 'E':0}) # all varibales are set to evidence.
```

but got an error: `ValueError: Number of einsum subscripts must be equal to the number of operands.
`
do I use the wrong method or which function should I use to achive this goal, like pomegranate's probability feature.
(e.g. https://pomegranate.readthedocs.io/en/latest/BayesianNetwork.html?highlight=probability#probability)
![image](https://user-images.githubusercontent.com/10119552/206692671-d0462531-325b-45a5-952a-2a6eb135aaaf.png)

Thanks.

**Comment by ankurankan** [comment]
@scku208 I just implemented a new method to compute this. If you use the dev branch from github the following example should work:
```python
from pgmpy.inference import VariableElimination
from pgmpy.models import BayesianNetwork
import numpy as np
import pandas as pd
values = pd.DataFrame(np.random.randint(low=0, high=2, size=(1000, 5)),
                      columns=['A', 'B', 'C', 'D', 'E'])
model = BayesianNetwork([('A', 'B'), ('C', 'B'), ('C', 'D'), ('B', 'E')])
model.fit(values)

model.get_state_probability({'A':0, 'B':1, 'C':1, 'D':1, 'E':0})
```
