### ISSUE TITLE
query evidence unable to have more than one possibility

### ISSUE THREAD

**Issue by Cby19961020** [pgmpy/pgmpy#1381]
### query evidence unable to have more than one possibility
Hi there, hope you and your loved ones are safe during this time. I am trying to perform variable elimination for inference and for my evidence I would like to have a few possibility(example, given yesterday's weather is sunny, rainy or windy, what is the probability of electricty consumption = High tomorrow?) But I could not perform such action because the evidence parameter can only take a single value, not a list. I am wondering if this can be fixed up real quick. Please let me know. Thank you very much for all your hard work. Your time and effort is much appreciate it! 

### Your environment
* pgmpy version 0.1.13
* Python version 3.6
* Operating System Windows 10

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import BayesianModel
from pgmpy.inference import BeliefPropagation
bayesian_model = BayesianModel([('A', 'J'), ('R', 'J'), ('J', 'Q'),
                                ('J', 'L'), ('G', 'L')])
cpd_a = TabularCPD('A', 2, [[0.2], [0.8]])
cpd_r = TabularCPD('R', 2, [[0.4], [0.6]])
cpd_j = TabularCPD('J', 2,
                   [[0.9, 0.6, 0.7, 0.1],
                    [0.1, 0.4, 0.3, 0.9]],
                   ['R', 'A'], [2, 2])
cpd_q = TabularCPD('Q', 2,
                   [[0.9, 0.2],
                    [0.1, 0.8]],
                   ['J'], [2])
cpd_l = TabularCPD('L', 2,
                   [[0.9, 0.45, 0.8, 0.1],
                    [0.1, 0.55, 0.2, 0.9]],
                   ['G', 'J'], [2, 2])
cpd_g = TabularCPD('G', 2, [[0.6], [0.4]])
bayesian_model.add_cpds(cpd_a, cpd_r, cpd_j, cpd_q, cpd_l, cpd_g)
belief_propagation = BeliefPropagation(bayesian_model)
belief_propagation.query(variables=['J', 'Q'],
                         evidence={'A': [0,1], 'R': 0, 'G': 0, 'L': 1})

### Expected behaviour
Tell us what should happen
I was expecting an array that tells me the probability of J and Q given the evidence mentioned above.

### Actual behaviour
Tell us what happens instead
List of evidence is not supported.

**Comment by ankurankan** [comment]
@Cby19961020 Currently, I don't think there is a way to specify multiple states of evidence. A simple solution, for now, could be to just run multiple inferences with one state of the evidence variable each and then combine the results together. So, in your example, you will need to do two inferences P(J, Q | A=0, R=0, G=0, L=1) and P(J, Q | A=1, R=0, G=0, L=1).

**Comment by Cby19961020** [comment]
Hi @ankurankan, 

Thank you very much for your prompt reply. Like you said this is what I plan to do. I tried to look up literature that talks about having more than one possibilities but could not find too many revelant information. I do think this is a very useful information to obtain and it doesn't seen to have a difficult derivation behind it (it might be lengthy but pretty straight forward). This is what I will end up doing. 

Example:

Say I have 3 variables, weather(sunny, rainy,windy), temperatre(below 15, 15 to 25 and 25/above) and electricty bill(high and low). Electricty bill is conditioned.

![image](https://user-images.githubusercontent.com/44323738/108938003-49401e00-761d-11eb-9c43-e4ff7767ce92.png)

 I want to know what is the **P(electricity bill | weather = sunny/rainy, temperature = 25 and above)**.

I first calculate **P(electricity bill | weather = sunny, temperature = 25 and above)**, say I end up with the following:

+------------------+-----+
| Electricity (High)   | 0.75 |
+------------------+-----+
| Electricity (Low)    | 0.25 |
+------------------+-----+

then I calculate **P(electricity bill | weather = rainy, temperature = 25 and above)**, say I get this:

+-----------------+-------+
| Electricity (High)   | 0.35 |
+-----------------+-------+
| Electricity (Low)    | 0.65 |
+-----------------+-------+

For **P(electricity bill | weather = sunny/rainy, temperature = 25 and above)**, isn’t it just the following(considering the likelihood for each event, normalize then add them up) ?

![image](https://user-images.githubusercontent.com/44323738/108939065-1dbe3300-761f-11eb-8aec-14f4aa208d8e.png)

![image](https://user-images.githubusercontent.com/44323738/108939273-755c9e80-761f-11eb-8417-e55dd30b65f4.png)

Do you think the calculation mentioned above will get me  P(electricity bill | weather = sunny/rainy, temperature = 25 and above)? If it is valid could it possibly be implemented to the package?

Thanks again for your time and expertise! <3

**Comment by ankurankan** [comment]
@Cby19961020 I don't think you need to do any weighting in this case as the inference algorithm has already marginalized out all the other variables, hence you have the true probability values now. In this example, you want to compute:
```
  P(E | W=S or R, T=T1) 
= P(E| W=S, T=T1) + P(E| W=R, T=T1)
= [0.75, 0.25] + [0.35, 0.65] 
= [1.1, 0.9] 
= [0.55, 0.45]
```
where E = Electricity, W=Weather, S=Sunny, R=Rainy, T=Temperature, T1=25 and above. Here the first step assumes that W=S, and W=R are mutually exclusive. The last step just does a normalization on the values.
