### ISSUE TITLE
Predicting values using Bayesian model and getting error

### ISSUE THREAD

**Issue by sj67076** [pgmpy/pgmpy#1382]
### Subject of the issue
I am predicting no_of_people values using bayesian model in python. I am using this dataset given in picture.my error is also attached in picture. 
![ycRSz](https://user-images.githubusercontent.com/79547954/109004631-d1c8c800-76ca-11eb-8e21-2f196d16f2ad.png)
![7w48v](https://user-images.githubusercontent.com/79547954/109004649-d7bea900-76ca-11eb-8f2c-f9e7b7aab2f5.png)
 my code is here
`import numpy as np`
`from pgmpy.models import BayesianModel`
`import pandas as pd`
`data = pd.read_csv('C:/Users/hp/Desktop/file3.csv')`
`train = data[:40]`
`test = data[40:].drop('no_of_people', axis=1)`
`restaurant_model = BayesianModel([('location', 'cost'), ('quality', 'cost'), ('location', no_of_people'), ('cost', 'no_of_people')])`
`restaurant_model.fit(train)`
`restaurant_model.get_cpds()`
`restaurant_model.predict(test).values.ravel()`

my dataset file is here[Dataset file](https://www.dropbox.com/s/ignlq1o11jgbkc8/file3.csv?dl=0) 

### Your environment
* pgmpy version 0.1.13
* Python version 3.8.5
* Operating System Windows 10

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

### Expected behavior
it should produce the predicted array of "no_of_people" attribute.

### Actual behaviour
I found IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by ankurankan** [comment]
Duplicate #1383
