### ISSUE TITLE
can't install pgmpy in anaconda:FileNotFoundError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by Anboboer** [pgmpy/pgmpy#1384]
package                    |            build
    ---------------------------|-----------------
    statsmodels-0.12.2         |   py36h2bbff1b_0        10.6 MB  defaults
    pgmpy-0.1.13               |           py36_0        19.0 MB  ankurankan
    openssl-1.1.1j             |       h2bbff1b_0         5.8 MB  defaults
    ------------------------------------------------------------
                                           Total:        35.4 MB

The following NEW packages will be INSTALLED:

    networkx:        2.5-py_0               defaults
    patsy:           0.5.1-py36_0           defaults
    pgmpy:           0.1.13-py36_0          ankurankan
    statsmodels:     0.12.2-py36h2bbff1b_0  defaults
    tqdm:            4.56.0-pyhd3eb1b0_0    defaults

The following packages will be UPDATED:

    ca-certificates: 2020.10.14-0           defaults   --> 2021.1.19-haa95532_0     defaults
    certifi:         2020.6.20-pyhd3eb1b0_3 defaults   --> 2020.12.5-py36haa95532_0 defaults
    openssl:         1.1.1h-he774522_0      defaults   --> 1.1.1j-h2bbff1b_0        defaults

Proceed ([y]/n)? y

Downloading and Extracting Packages
statsmodels-0.12.2   | 10.6 MB | ############################################################################## | 100%
pgmpy-0.1.13         | 19.0 MB | ###########################################################                    |  76%
openssl-1.1.1j       |  5.8 MB | ############################################################################## | 100%

FileNotFoundError(2, 'No such file or directory')

**Comment by ankurankan** [comment]
@Anboboer It seems to be a conda problem and not related to pgmpy. You can try these maybe:
1. https://stackoverflow.com/questions/57026355/conda-gives-no-such-file-or-directory-although-i-added-path-in-my-bash-prof
2. https://stackoverflow.com/questions/51524934/anaconda-bin-conda-no-such-file-or-directory
