### ISSUE TITLE
Bug: structure-learned Bayesian Network samples incorrect frequencies

### ISSUE THREAD

**Issue by mbaak** [pgmpy/pgmpy#1387]
### Subject of the issue
When one learns the structure of a Bayesian Network from data and fits the model parameters, then
the sampled frequencies of data points generated using forward_sampling are incorrect. The observed 
frequencies deviate significantly from the expected frequencies of a model. I see this with BNs constructed 
using HillClimbSearch and TreeSearch (and it may hold for more search algorithms). One can verify this 
behaviour with the new BayesianModelProbability class.
I do *not* see this discrepancy when forward sampling from a manually built ("theoretically known") 
Bayesian Network, where the sampled frequencies do agree with the expectations.

### Your environment
* pgmpy commit: 85d900cbaf25c141191973e2175ef92ebe408c23
* Python version: 3.8.5
* Operating System: MacOS

### Expected & Actual behaviour
See descriptions above.

### Steps to reproduce 

import numpy as np
import pandas as pd

import pgmpy
from pgmpy.models import BayesianModel
from pgmpy.utils import get_example_model
from pgmpy.sampling import BayesianModelSampling
from pgmpy.inference import BayesianModelProbability

# we want to compare *generated* frequencies with *true* probabilities from a model

# 1. starting off from an manually constructed model (alarm)

model = get_example_model('alarm')
samples = BayesianModelSampling(model).forward_sample(size=int(5e5))

# let's look at highest probabilities only
bmprob = BayesianModelProbability(model)
logp = bmprob.log_probability(samples)
p = np.exp(logp)
sortp = np.unique(p)[::-1]

# convert to numbers so np.unique works
df = pd.DataFrame(index = samples.index)
for c in samples.columns:
    codes, uniques = pd.factorize(samples[c])
    df[c] = codes

u, c = np.unique(df.values, return_counts=True, axis=0)
idc = np.argsort(c)[::-1]

# observed frequencies of model
sortc = c[idc] / 5e5
print(sortc[:10])

# expected frequencies of model
print(sortp[:10])

# ^^^ as one can see, in this case the sampled frequencies match well with the probabilities from the model

## 2. now recontruct a model from a dataset
# (we downsample to increase speed of HillClimbSearch)

sample = df.sample(10000)

from pgmpy.estimators import HillClimbSearch, ExhaustiveSearch, PC, TreeSearch

if True:
    est = TreeSearch(sample, root_node=df.columns[0])
    dag = est.estimate(estimator_type="tan", class_node='DISCONNECT')

if True:
    est2 = HillClimbSearch(sample)
    dag2 = est2.estimate(start_dag=dag)

from pgmpy.estimators import BayesianEstimator
model2 = BayesianModel(dag2.edges())
model2.fit(sample)

# now let's see what frequencies this reconsntructed model generates

inference = BayesianModelSampling(model2)
df_data = inference.forward_sample(size=500000, return_type='dataframe', seed=0)

u, c = np.unique(df_data.values, return_counts=True, axis=0)
idc = np.argsort(c)[::-1]
sortc = c[idc] / 500000

bmprob = BayesianModelProbability(model2)
logp = bmprob.log_probability(u[idc], ordering=df_data.columns.tolist())
p = np.exp(logp)

# observed frequencies of model2
print(sortc[:10])

# expected frequencies of model2
print(p[:10])

# ^^^ the sampled frequencies from the *structure learned* model2 do NOT match well with the probabilities from model2.
# the generated frequencies are too high. 
# (this is not a statistical fluctuation.)

# Both TreeSearch and HillClimbSearch shows this effect. 
# But it's worse for HillClimbSearch, where the generated frequencies are 50% too high.

# Note that the probabilities of model2 are quite close to those of the original model, as one would hope. 
# My suspicion is therefore that the failure is in the forwardsampling, and not in the assigned probabilities.

**Comment by mbaak** [comment]
One more thing: the probabilities found with model2 match the frequencies in the fitted "sample" dataset very well. So the problem must indeed be in the sampling.

**Comment by ankurankan** [comment]
Fixed in #1388
