### ISSUE TITLE
Data Files not getting included in the package

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#1399]
The datafiles for the example models are not getting included in the package resulting in an error when `get_example_model` is called. If installed through pip or conda, this throws an error:
 
```python
>>> from pgmpy.utils import get_example_model
>>> get_example_model('alarm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ankur/miniconda3/envs/test/lib/python3.8/site-packages/pgmpy/utils/utils.py", line 104, in get_example_model
    with gzip.open(filenames[model], "rb") as f:
  File "/home/ankur/miniconda3/envs/test/lib/python3.8/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/ankur/miniconda3/envs/test/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'pgmpy/utils/example_models/alarm.bif.gz'
>>> 




```

**Comment by zoenguyentm** [comment]
Hi, I installed the latest pgmpy and still see the same error. I've checked the pgmpy folder on my computer and see that the example_models is still missing.

**Comment by ankurankan** [comment]
@zoenguyentm Yeah, it's happening because this change will be included in the next release. In the meanwhile, you can install directly from the dev branch using: pip install git+https://github.com/pgmpy/pgmpy.git@dev

**Comment by zoenguyentm** [comment]
okay, thanks :):)
