### ISSUE TITLE
Participation in Scipy India 2013

### ISSUE THREAD

**Issue by abinashpanda** [pgmpy/pgmpy#14]
# Scipy India 2013 (scipy.in)

is from 13th December to 15th December. It is a conference providing opportunities to spread the use of the Python programming language in the Scientific Computing community in India.  

I was planning on giving a presentation on our library pgmpy. (http://scipy.in/2013/call-for-proposals/). Final date for submission of proposal in 24th November, 2013.

**Only submissions with an actual implementation will be considered for presentation (i.e. proposals to implement the code are not acceptable, partial implementations are acceptable so long as they demonstrate the features discussed).** 

So we have to complete the semester objectives and add some more features in both pgmpy and pgmpy_viz before 20th November.

**Comment by ankurankan** [comment]
Let's make a proper list of required features then. I still haven't
received any confirmation on the proposed objectives for the semester that
I put on GitHub.

Regards,
Shikhar Nigam
Fourth Year, B.Tech
IIT (BHU), Varanasi
