### ISSUE TITLE
Method for updating existing parameters with new set of data?

### ISSUE THREAD

**Issue by ronikobrosly** [pgmpy/pgmpy#1405]
Hello, thank you for putting together this fantastic package! I have a question related to parameter learning.

Let's say I have a fully-defined bayesian network with parameters / conditional probability tables that were generated by experts that I manually typed in (I didn't have any data initially). In the future I come across data, and I'd like to "update" the parameters with this new data. That doesn't mean throw away the the old parameters and do parameter learning with the new data only. I'd like to tweak the new parameters. 

Is there a way to do this in pgmpy? Or do you have a suggestion on how to do this another way? Thank you!

**Comment by ankurankan** [comment]
@ronikobrosly There is no direct method implemented to do this right now but there is a workaround using Bayesian Estimator. I have an example of doing that here: https://github.com/pgmpy/pgmpy/issues/1350#issuecomment-726724566. In your case, the sample size used in computing pseudo_counts can be interpreted as the relative weight of the initial parameters of the model.
