### ISSUE TITLE
MMHC method returns empty skeleton

### ISSUE THREAD

**Issue by CarolineMoreau** [pgmpy/pgmpy#1406]
### MMHC method returns empty skeleton even when executing the documentation example
Hello,
I was interested in using the MMHC method through pgmpy however it doesn't seem to work. When either running the documentation example or trying it on my data, the created skeleton is empty. It looks a bit like the code example of issue #1329, but at the first step of the method and not the second.

### My environment
* pgmpy version: 0.1.14
* Python version: 3.8.5 (with Anaconda and working on a Jupyter notebook)
* Operating System: Windows 10

### Steps to reproduce
Just like in the documentation [notebook](https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/9.%20Learning%20Bayesian%20Networks%20from%20Data.ipynb):
```python
from pgmpy.estimators import MmhcEstimator
import pandas as pd
import numpy as np

data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
data['A'] += data['B'] + data['C']
data['H'] = data['G'] - data['A']
data['E'] *= data['F']

mmhc = MmhcEstimator(data)
skeleton = mmhc.mmpc()
print("Part 1) Skeleton: ", skeleton.edges())
```

### Expected behaviour
Output should look like:
Part 1) Skeleton:  [('A', 'C'), ('A', 'H'), ('B', 'C'), ('E', 'F'), ('G', 'H')]

### Actual behaviour
Instead, I get (no error message output):
Part 1) Skeleton:  []

**Comment by ankurankan** [comment]
@CarolineMoreau This was a bug in the last release and has been fixed now (Ref https://github.com/pgmpy/pgmpy/issues/1403). If you install the latest `dev` branch from github, the code example should work.

**Comment by CarolineMoreau** [comment]
@ankurankan Thank you so much, I didn't see that issue !
