### ISSUE TITLE
ValueError using BayesianEstimation with pseudo_counts after updating to 0.1.14

### ISSUE THREAD

**Issue by MKurthen** [pgmpy/pgmpy#1411]
### ValueError using BayesianEstimation with pseudo_counts after updating to 0.1.14
Passing pseudo_counts to BayesianEstimator.estimate_cpd() leads to an ValueError: 

> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Your environment
* pgmpy 0.1.14, numpy 1.20.2, pandas 1.2.4
* Python 3.8.0
* Operating System: Ubuntu 20.04

### Steps to reproduce
Minimal reproducible code:

> 
> import numpy as np
> import pandas as pd
> import pgmpy.estimators
> import pgmpy.models
> 
> \# a small BayesianModel with one edge, x->y
> edges = [("x", "y")]
> \# assume x and y are categorical, each being either "a" or "b"
> state_names = {"x": ["a", "b"], "y": ["a", "b"]}
> 
> model = pgmpy.models.BayesianModel(edges)
> 
> \# create a DataFrame of x and y observations
> data = pd.DataFrame(
>     [["a", "b"], ["a", "a"], ["a", "b"], ["b", "a"]], columns=["x", "y"]
> )
> 
> \# assign some pseudo_counts
> pseudo_counts_x = np.array([[0], [0]])
> pseudo_counts_y = np.array([[1, 2], [1, 3]])
> pseudo_counts = {"x": pseudo_counts_x, "y": pseudo_counts_y}
> 
> \# use a bayesian estimation with the pseudo_counts provided
> model.fit(
>     data,
>     state_names=state_names,
>     estimator=pgmpy.estimators.BayesianEstimator,
>     prior_type="dirichlet",
>     pseudo_counts=pseudo_counts,
> )

### Expected behaviour
Bayesian Estimation should assign the pseudo_counts to the CPD

(probably the "sanity check" in line https://github.com/pgmpy/pgmpy/blob/afdcf6dfed299517345113298a67c7be23cbd557/pgmpy/estimators/BayesianEstimator.py#L155 should be evaluated to False, as I am passing non-empty pseudo_counts and prior_type="dirichlet" ) 

### Actual behaviour
A ValueError ("The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()") is raised as 
Line https://github.com/pgmpy/pgmpy/blob/afdcf6dfed299517345113298a67c7be23cbd557/pgmpy/estimators/BayesianEstimator.py#L155 leads to a ValueError as 

> (pseudo_counts and pseudo_counts != [] )

 is probably being evaluated as 

> np.array([[1, 2], [1, 3]]) and True

### Next Steps:
I would be happy to provide a bugfix PR if this is desired

**Comment by ankurankan** [comment]
@MKurthen Thanks for reporting the bug. Would be great if you could open a PR fixing it.

**Comment by MKurthen** [comment]
PR at https://github.com/pgmpy/pgmpy/pull/1423
