### ISSUE TITLE
Is there a way to show all interim calculations when inferring on Bayes network

### ISSUE THREAD

**Issue by nyck33** [pgmpy/pgmpy#1444]
### Subject of the issue
I have a Bayes network like the one described here:  https://github.com/nessalauren5/OMSCS-AI/blob/master/assignment_3/README.ipynb with nodes temp, faulty gauge, gauge, faulty alarm and alarm.  Alarm is the sink node so the bottom of the causal direction.  The question asks for a diagnostic inference of probability of it being hot (source node) given alarm=True, faulty gauge = False, faulty alarm = False.  
I can't paste any code because it's a school assignment but my imports look like this:
```
import pgmpy
from pgmpy.models import BayesianModel
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import VariableElimination

def get_temperature_prob(bayes_net):
    solver = VariableElimination(bayes_net)
    conditional_prob = solver.query(variables=['x'],
                                    evidence={'y':1, 'g':0,
                                              'z':0},joint=False)
    #returns [P(F),P(T)]
    temp_prob = conditional_prob['x'].values
    return temp_prob
```
and I get my probabilities but want to check that it is correct which I am having trouble with conceptually but can figure it out if I can see all the calculation steps pgmpy makes.  Is this possible?

### Your environment
* pgmpy version pgmpy==0.1.10

* Python version 3.7.10
* Operating System Ubuntu 20.04

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.
It is possible to reconstruct the function and network based on the probabilities in the link provided and code above but I cannot post directly.

### Expected behaviour
Show all the interim work that pgmpy performs.

### Actual behaviour
Tell us what happens instead
I just get two probabilities for hot = False, hot = True which is not as helpful when trying to learn the concepts.

**Comment by ankurankan** [comment]
@nyck33 It's not possible to get the intermediate states of the algorithm in the current implementation. But if you are trying to understand the implementation better, you can also check out the code (https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/inference/ExactInference.py). The code does have comments specifying the different steps the algorithm takes. Also, if you are looking to dive deeper you can also modify the code (put print statements / use a debugger) and step through the execution.
