### ISSUE TITLE
TREE AUGMENTED NAIVE BAYES DOUBT

### ISSUE THREAD

**Issue by PARODBE** [pgmpy/pgmpy#1457]
Hi everyone!

I need some of help. I new with this library, and I have a dataset with 70 categorical variables. I would like to apply TAN and FAN, build a model and obtain predictions with my test set, also i would like to obtain my networkx graph. But in the examples I see the relationships between variable adding the weights manually, but I would prefer that the model learns the relationships.

Could you help me with some of code please? 

Thanks!

**Comment by ankurankan** [comment]
@PARODBE Here's an example using the `alarm` model:
```python
# Simulate some data to learn the network structure from
from pgmpy.utils import get_example_model
data = get_example_model('alarm').simulate(n_samples=int(1e4))

# Learn the tree structure
from pgmpy.estimators import TreeSearch
est = TreeSearch(data)
dag = est.estimate(estimator_type='tan') # You can specify different parameters for estimator here.

# Learn the model parameters
from pgmpy.models import BayesianNetwork
bn = BayesianNetwork(dag.edges())
bn.fit(data) # Here also you can specify how to learn the parameter.

# Do predictions from the data.
data_for_prediction = data.drop('HISTORY', axis=1)
predictions = bn.predict(data_for_prediction)
```
If you are not using the `dev` branch, you can use `BayesianModel` instead of `BayesianNetwork` in the example.

**Comment by PARODBE** [comment]
Uoooo thank you very much @ankurankan !!! I have two questions. The first, what it would be the difference between bayesianmodel or bayesian network? As It bayesian model its assumption is the independence of variables regarding to target variable. And bayesian network has some correlation, no?

By the way, this tree search would be a tree augmented Naive Bayes, but Forest Naive Bayes? Are there any options?

Thank you some much!!

All best!

**Comment by ankurankan** [comment]
@PARODBE BayesianModel and BayesianNetwork are exactly the same right now. In the older versions, we were using the name BayesianModel, but I am trying to change it to BayesianNetwork in the future as BayesianModel is a slightly misleading name.

That's correct, TreeSearch has two estimator types implemented TAN and Chow-Liu. There's no estimator for learning a forest currently but for learning more complicated structures you can also use more general structure learning algorithms like PC or HillClimbSearch.
