### ISSUE TITLE
CausalInference: Same Variables in Variables/Evidence Error when not the same?

### ISSUE THREAD

**Issue by rokapre** [pgmpy/pgmpy#1459]
### Subject of the issue

Hi, I seem to be running into a bug where the CausalInference.query method complains that the variables in the "variables" and evidence arg are the same when they actually aren't. Below is the code: 

### Your environment
* pgmpy version:  0.1.15
* Python version: 3.8
* Operating System:MacOS Catalina

### Steps to reproduce

Here is some simulated data

```
import numpy as np
import pandas as pd
import pgmpy
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator,BayesianEstimator
from pgmpy.inference import VariableElimination,CausalInference


n = 10000

#P(W)

pW = 0.3
W = np.random.binomial(1,pW,n)

#P(X=1|W=0) = 0.3, P(X=1,|W=1) = 0.6
nW1 = np.sum(W==1)
nW0 = np.sum(W==0)

pX_W0 = 0.3
pX_W1 = 0.6
X = np.zeros(n)
X[:] = np.nan

X[W==0] = np.random.binomial(1,pX_W0,nW0)
X[W==1] = np.random.binomial(1,pX_W1,nW1)

#P(Y=1|X=1,W=0) = 0.3, P(Y=1|X=0,W=0) = 0.3, P(Y=1|X=1,W=1) = 0.9, P(Y=1|X=0,W=1) = 0.5

nX1W0 = np.sum((X==1) & (W==0))
nX0W0 = np.sum((X==0) & (W==0))
nX1W1 = np.sum((X==1) & (W==1))
nX0W1 = np.sum((X==0) & (W==1))

pY_X1W0 = 0.3
pY_X0W0 = 0.3
pY_X1W1 = 0.9
pY_X0W1 = 0.5

Y = np.zeros(n)
Y[:] = np.nan 
Y[(X==1) & (W==0)] = np.random.binomial(1,pY_X1W0,nX1W0)
Y[(X==0) & (W==0)] = np.random.binomial(1,pY_X0W0,nX0W0)
Y[(X==1) & (W==1)] = np.random.binomial(1,pY_X1W1,nX1W1)
Y[(X==0) & (W==1)] = np.random.binomial(1,pY_X0W1,nX0W1)

simdata = pd.DataFrame({"Y":Y,"X":X,"W":W})

bn = BayesianModel([("X","Y"),("W","X"),("W","Y")])
bn.fit(simdata)

VE = VariableElimination(bn)
VEres = VE.query(variables=["Y"],evidence={"X":1,"W":1})
VEres.values


ci = CausalInference(bn)
cires = ci.query(variables=["Y"],do={"X":1},evidence={"W":1}) #Error occurs here
cires.values

```

### Expected behaviour

I should be getting around 0.9 for cires[1] but instead I get the error below. The thing is the evidence has W and the variables has Y, so it makes no sense why it is complaining. 

### Actual behaviour

`ValueError: Can't have the same variables in both `variables` and `evidence`. Found in both: {'W'}`

**Comment by ankurankan** [comment]
@rokapre Thanks for reporting this, the error message should be clearer in this case. It is throwing an error because you are trying to compute `P(Y | do(X=1))` with evidence of `W=1`, but for computing `do(X=1)` we need to adjust on `W` and hence you can't specify any evidence on `W`. The error message that you are seeing is from VariableElimination as the CausalInference class isn't able to translate your causal query to a meaningful probabilistic query. I will make changes for such cases to throw a more meaningful error message.

**Comment by rokapre** [comment]
Thanks. From my understanding though (and I am still new to causal inference, especially the graphical framework) it should be possible to condition on W despite having the `do X=1` operator and essentially obtain the conditional average treatment effect  `(CATE)` right: `P(Y|do(X)=1,W=1)` ? 

It would just be looking at the effect of setting X to 1 in the subgroup of `W=1`.  Which in this case (since there are only 3 variables) I think this would be the same as `P(Y|X=1,W=1)`

https://en.wikipedia.org/wiki/Average_treatment_effect#Heterogenous_treatment_effects

**Comment by ankurankan** [comment]
@rokapre Sorry, my bad. You are correct, I was thinking only in terms of average treatment effect. Let me see if I can quickly fix this.

**Comment by ankurankan** [comment]
@rokapre This should be fixed now in the latest dev branch.
```python
In [2]: cires = ci.query(variables=["Y"],do={"X":1},evidence={"W":1})
In [3]: print(cires)
+--------+----------+
| Y      |   phi(Y) |
+========+==========+
| Y(0.0) |   0.1102 |
+--------+----------+
| Y(1.0) |   0.8898 |
+--------+----------+
```
Forgot to mention before but you can also get the same results using simulations:
```python
In [4]: samples = bn.simulate(n_samples=int(1e4), do={'X': 1}, evidence={'W': 1})
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 81839.60it/s]

In [5]: samples.Y.value_counts() / samples.shape[0]
Out[5]: 
1.0    0.8925
0.0    0.1075
Name: Y, dtype: float64
```

**Comment by rokapre** [comment]
@ankurankan 

Thanks! Didn’t know about the sampling either. I was also wondering, is there any way to get uncertainty estimates for the ATEs estimated by CausalInference on the BayesianModel fit to the data? Or would this be possible through the sampling approach? 

Or do the Inference methods in pgmpy assume that the PGM is “fixed” (ie not parameters that have been derived from data—like as if they were from TabularCPD even if they weren’t)

**Comment by ankurankan** [comment]
@rokapre Yeah, currently is assumes the parameters to be fixed and doesn't have any uncertainty measure.

**Comment by rokapre** [comment]
@ankurankan 

Oh ok, hmm I was wondering since you mentioned the sampling if the following approach may be ok for now:

1) Fit a “null” BN without the X->Y edge
2) Simulate data from this BN
3) Fit a BN with the X->Y edge of interest to this null data
4) Perform the causal inf queries and get ATE of the treatment
5) Compare the observed ATE to the “null” ATE and obtain a p-value

Essentially in stats what is known as a permutation test. It seems like something for now, although I don’t know the theoretical properties fully on PGMs.

**Comment by ankurankan** [comment]
Just to check if I am understanding your method correctly, you would be using the simulated datasets to estimate the ATE distribution under null and then use this estimated distribution to get the p-value for the observed ATE? From my understanding, this method should work. Another idea could be to use bootstrapping to estimate the distribution of observed ATE using sub-sampling and then maybe report the confidence interval.
