### ISSUE TITLE
Adding a dictionary of node:states to models

### ISSUE THREAD

**Issue by Jsevillamol** [pgmpy/pgmpy#1466]
I often find myself needing to iterate over the states of a node.
For this, it would be useful to have a dictionary that maps the names of the nodes of a model to 

I have resorted to the workaround of initializing this myself when loading a model.

```
from pgmpy.utils import get_example_model
model = get_example_model('asia')

def get_states(model, node):
  phi = model.get_cpds(node)
  n_states = phi.get_cardinality([node])[node]
  states = [phi.get_state_names(node, i) for i in range(n_states)]
  return states

model.states = {node : get_states(model, node) for node in model.nodes}
model.states
```

1. Is this the easiest way to get access to the states?
2. Can we add a `@property` method called `states` to the base `BayesianModel` class reproducing this functionality? I'd be happy to do the PR myself if this is agreed to be a good approach.

**Comment by ankurankan** [comment]
@Jsevillamol Sorry for the late reply. Yes, I think adding it as a property would be helpful. A simpler/faster way to access the state names though could be to use the `.state_names` attribute of cpds. Something like:
```
state_names_list = [cpd.state_names for cpd in model.cpds]
# state_names_list here would be a list of dicts, we will just need to join them in a single dict
```
Would be great if you could open a PR. :)
