### ISSUE TITLE
I meet some wrong when I import the module

### ISSUE THREAD

**Issue by LiYiyan-code** [pgmpy/pgmpy#1472]
### Subject of the issue
When I import TreeCPD,I get this info" ImportError: cannot import name 'TreeCPD' from 'pgmpy.factors' "

### Your environment
* pgmpy version: 0.1.16
* Python version:Python 3.8.8
* Operating System : Windows

**Comment by ankurankan** [comment]
@LiYiyan-code TreeCPD and RuleCPDs aren't supported anymore.
