### ISSUE TITLE
Latex equations not interpreted correctly by Sphinx

### ISSUE THREAD

**Issue by sean578** [pgmpy/pgmpy#1475]
### Subject of the issue
Latex equations not interpreted correctly by Sphinx.
[Example of incorrect equations in docs](https://pgmpy.org/examples/Monty%20Hall%20Problem.html#Probabilistic-Interpretetion:).

### Your environment
* pgmpy version = 0.1.16
* Python version =  3.6.13
* Operating System = Ubuntu 18.04.6 LTS

### Steps to reproduce
Build documentation: 
`cd pgmpy/docs`
`make html`
View html docs generated.

### Expected behaviour
Latex interpreted correctly in both Jupyter notebooks and html.

### Actual behaviour
Latex only interpreted correctly in Jupyter notebook.

### Problem
Sphinx requires no spaces between `$` characters and Latex expression.

### Solution
Remove the spaces. Renders correctly in Jupyter notebook and html.

### Notes
The majority of the errors of this type are in the `pgmpy/pgmpy_notebook` repo - a separate PR needs to be made there.

**Comment by sean578** [comment]
Created PR #1476 to fix this in `pgmpy/pgmpy` repo.
If happy with this then can create a similar PR in the `pgmpy/pgmpy_notebook` repo to fix the same type of error there.

**Comment by ankurankan** [comment]
@sean578 Thanks for the fixes. Would be great if you could open a PR for the other repo as well. Thanks
