### ISSUE TITLE
Causal Game.ipynb Errors, branch feature/causalmodel is not found to checkout ?

### ISSUE THREAD

**Issue by ghost** [pgmpy/pgmpy#1482]
### There is no branch feature/causalmodel as described in Causal Game.ipynb notebook.
I tried to run the Causal Games.ipynb in google colab. In the first code cell there is a line that tells me to clone the code from https://github.com/mrklees/pgmpy.git, then have to checkout to a branch named feature/causalmodel. When I try to checkout to this branch as mentioned it produces this error, error: pathspec 'feature/causalmodel' did not match any file(s) known to git. As a result I'm not able to run this notebook. What to do ?

**Comment by ankurankan** [comment]
@aswin4400 Sorry for the late reply, I was on holiday. That notebook has been merged into the dev branch now, so you can use this one: https://github.com/pgmpy/pgmpy/blob/dev/examples/Causal%20Games.ipynb. I have also just updated the notebook to work with the latest dev branch.

**Comment by ghost** [comment]
Thank you @ankurankan
