### ISSUE TITLE
Unexpected behaviour in generated docs

### ISSUE THREAD

**Issue by ghost** [pgmpy/pgmpy#1483]
### Documentation
HTML rendered docstring of the `DBNInference`'s method `forward_inference` looks weird.

See [here](https://pgmpy.org/exact_infer/dbn_infer.html#pgmpy.inference.dbn_inference.DBNInference.forward_inference).

**Comment by ankurankan** [comment]
@acac-io Thanks for reporting this. Is fixed now.
