### ISSUE TITLE
Bug in printing LinearGaussianCPD

### ISSUE THREAD

**Issue by dg46** [pgmpy/pgmpy#1487]
### Subject of the issue
Calling print on an instance of LinearGaussian CPD gives the wrong result.

### Your environment
* pgmpy version 0.1.16
* Python version 3.7.1
* Operating System Windows 10

### Steps to reproduce
Taken right from https://pgmpy.org/detailed_notebooks/7.%20Parameterizing%20with%20Continuous%20Variables.html:

from pgmpy.factors.continuous import LinearGaussianCPD
cpd = LinearGaussianCPD('Y',  [0.2, -2, 3, 7], 9.6, ['X1', 'X2', 'X3'])
print(cpd)

### Expected behaviour
Output should be P(Y | X1, X2, X3) = N(-2*X1 + 3*X2 + 7*X3 + 0.2; 9.6), as indicated in the documentation.

### Actual behaviour
Output is P(Y | X1, X2, X3) = N(0.2*X1 + -2*X2 + 3*X3 + 0.2; 9.6).

### Solution
Seems to be an off-by-one error. Replacing "zip(self.mean, self.evidence)" by "zip(self.mean[1:], self.evidence)" in [this line]( https://github.com/pgmpy/pgmpy/blob/caea6ef7c914464736818fb185a1d395937ed52f/pgmpy/factors/continuous/LinearGaussianCPD.py#L235) should fix it. The first entry of self.mean is the offset beta_0 and does not go with the first parent variable.

**Comment by dg46** [comment]
Seems that the issue is not only with the print command. E.g. [this line](https://github.com/pgmpy/pgmpy/blob/caea6ef7c914464736818fb185a1d395937ed52f/pgmpy/models/LinearGaussianBayesianNetwork.py#L176) prevents me from correctly converting a LinearGaussianBayesianNetwork to the corresponding joint gaussian distribution, apparently for the same reason (off-by-one error in scalar product).

**Comment by ankurankan** [comment]
@dg46 Linear Gaussian CPD isn't fully supported yet and you will probably find a bunch of bugs if you are working with them. I would be happy to help if you would like to open any PRs fixing them :).

**Comment by ankurankan** [comment]
Fixed.
