### ISSUE TITLE
TOFIX Documentation: Tutorial Notebooks; 7 - Bad Latex Rendering

### ISSUE THREAD

**Issue by gianfa** [pgmpy/pgmpy#1501]
### Subject of the issue
Documentation is not rendered well at https://pgmpy.org/detailed_notebooks/7.%20Parameterizing%20with%20Continuous%20Variables.html .
You can read `latex exited with error [stdout] This is pdfTeX, Version 3.14159265-2.6-1.40.21` there.

### Steps to reproduce
just follow the link https://pgmpy.org/detailed_notebooks/7.%20Parameterizing%20with%20Continuous%20Variables.html 

### Expected behaviour
Obviously to render it well :D 

Thank you for your work

**Comment by ankurankan** [comment]
@gianfa Thanks for reporting this. Should be fixed now.
