### ISSUE TITLE
Is there a way to compute the joint probability of a complete set of variables without enumerating the entire joint distribution?

### ISSUE THREAD

**Issue by asp2204** [pgmpy/pgmpy#1502]
So I noticed https://github.com/pgmpy/pgmpy/issues/848, where the answer to computing the joint probability of all of the variables of a bayesian network given every variable's value (a complete set of evidence) seems to be making this *.query() call, which is enumerating the *entire* joint distribution, and then letting us index into it as we wish.

Is there a method in pgmpy for computing this joint value for a particular set of values without enumerating the entire distribution? This seems like it could be very costly for larger networks. I wasn't sure if there's some way of doing it with VariableElimination.

**Comment by ankurankan** [comment]
@asp2204 Unfortunately, we don't have that functionality implemented yet using exact inference. But you can use a sampling based approach to compute an approximate solution. Essentially simulate some samples from the model, and compute the ratio of the number of samples which satisfy your query conditions to the total number of samples. Example:

```python
In [1]: from pgmpy.utils import get_example_model

In [2]: model = get_example_model('alarm')

In [3]: samples = model.simulate(int(1e5))
Generating for node: BP: 100%|█████████████████████████████████████████████| 37/37 [00:01<00:00, 29.92it/s]
In [4]: samples.head()
Out[4]: 
      CVP STROKEVOLUME  HRBP HREKG PVSAT      BP  ... LVEDVOLUME VENTALV ANAPHYLAXIS MINVOL  ARTCO2 ERRCAUTER
0  NORMAL       NORMAL  HIGH  HIGH   LOW  NORMAL  ...     NORMAL    ZERO       FALSE    LOW    HIGH     FALSE
1    HIGH          LOW  HIGH  HIGH   LOW  NORMAL  ...       HIGH    ZERO       FALSE   ZERO    HIGH     FALSE
2  NORMAL       NORMAL   LOW   LOW   LOW     LOW  ...     NORMAL  NORMAL       FALSE   ZERO  NORMAL     FALSE
3    HIGH          LOW  HIGH  HIGH   LOW    HIGH  ...       HIGH    ZERO       FALSE   ZERO    HIGH     FALSE
4  NORMAL       NORMAL  HIGH  HIGH   LOW    HIGH  ...     NORMAL    ZERO       FALSE   ZERO    HIGH     FALSE

[5 rows x 37 columns]

In [6]: p_CVP_normal_and_STROKEVOLUME_LOW = samples[(samples.CVP == "NORMAL") & (samples.STROKEVOLUME == "L
   ...: OW")].shape[0] / samples.shape[0]

In [7]: p_CVP_normal_and_STROKEVOLUME_LOW
Out[7]: 0.06938


```
