### ISSUE TITLE
remove_cpds causes issues in inference

### ISSUE THREAD

**Issue by HensJos** [pgmpy/pgmpy#1503]
### Subject of the issue
In short, I try to create a Naive Bayesian Network from a given General Bayesian Network. My first step is computing a marginal distribution over a variable of my choice, that will function as the class variable in the Naive BN. Sometimes this works, but sometimes it doesn't. The error has to with remove_cpds in the variable elimination as for some reason it says that my code wants to remove a cpd that is not in the list.

### Your environment
* pgmpy version: 0.1.17
* Python version: 3.9
* Operating System: Windows 10

### Steps to reproduce
Unfortunately, only passing some variables to the 'query' method leads to the bug. 
I have been working with random Bayesian Networks while this happens.

Code that could lead to the error:

NET = pgmpy.models.BayesianNetwork.get_random(n_nodes=10, edge_prob=0.5, n_states = [random.randint(2, 4) for i in range(n_nodes)])
infer = pgmpy.inference.VariableElimination(NET)
infer.query([any_var], show_progress=False)               #in the place of 'any_var' I have to play around a bit to find a node for which the bug appears

### Expected behaviour
Inference should work as intended, giving me a marginal condition over the variable of my choice.

### Actual behaviour
During the process of variable elimination a node that is being worked with is not in the list of cpds and causes the valueError: list.remove(x): x not in list in the function 'pgmpy.models.BayesianNetwork.remove_cpds()'

**Comment by ankurankan** [comment]
@HensJos Thanks for reporting this. I had a look and seems to me that this problem with inference only happens in the case when the variable names are integers and I am still trying to figure out a way to fix it. In the meanwhile, if you define your models uisng str variable names, it should work fine.

**Comment by HensJos** [comment]
Thanks for fixing! I will try it asap.
