### ISSUE TITLE
Cannot import PGMPY - Jupyter

### ISSUE THREAD

**Issue by arjunmanifc** [pgmpy/pgmpy#1505]
### Subject of the issue
I am not able to import pgmpy in Jupyter notebook. It is giving me the following error - 
_ModuleNotFoundError: No module named 'torch_

### Your environment
* pgmpy version - 0.1.9
* Python version - 3.10.2
* Operating System - Windoes 10 / 64 Bit

**Jupyter Version Details**
- IPython          : 8.0.1
- ipykernel        : 6.7.0
- ipywidgets       : 7.6.5
- jupyter_client   : 7.1.2
- jupyter_core     : 4.9.1
- jupyter_server   : not installed
- jupyterlab       : not installed
- nbclient         : 0.5.10
- nbconvert        : 6.4.0
- nbformat         : 5.1.3
- notebook         : 6.4.7
- qtconsole        : 5.2.2
- traitlets        : 5.1.1

### Steps to reproduce
`import pgmpy`
I ran the above code to import `pgmpy` module in the Jupyter notebook

### Expected behaviour
Modules should import properly.

### Actual behaviour
The import is failing with the below error - 
![PGMPY Error](https://user-images.githubusercontent.com/14234477/156477930-5d0b1115-af3f-4298-8a18-a3114b60fbe4.PNG)

**Comment by ankurankan** [comment]
@arjunmanifc You will need to install pytorch as well using either pip:
```
pip install torch
```
or conda
```
conda install -c pytorch pytorch
```

**Comment by arjunmanifc** [comment]
@ankurankan , Thanks for the comment. I tried this before I raised the issue. The thing is I am also not able to install torch. Throws the below error

![image](https://user-images.githubusercontent.com/14234477/156550524-52bdcef9-01ff-44ec-9a1f-30b0a1fa8ab7.png)

**Comment by ankurankan** [comment]
You can try following the installation instructions here: https://pytorch.org/get-started/locally/
