### ISSUE TITLE
ImportError: cannot import name 'ContinuousNode' from 'pgmpy.factors.continuous'

### ISSUE THREAD

**Issue by ahmedhassan554** [pgmpy/pgmpy#1513]
### Subject of the issue
The error comes up when I try to run an example from https://pgmpy.org/factors/discretize.html:
ImportError: cannot import name 'ContinuousNode' from 'pgmpy.factors.continuous'

### Your environment
* pgmpy version: 0.1.17
* Python 3.10
* Operating System: Windows 10, 64 bit

### Steps to reproduce
from scipy.stats import norm
import pgmpy
from pgmpy.factors.continuous import ContinuousNode
normal = ContinuousNode(norm(0, 1).pdf)
from pgmpy.discretize import BaseDiscretizer
class ChildDiscretizer(BaseDiscretizer):
    def get_discrete_values(self):
        pass
discretizer = ChildDiscretizer(normal, -3, 3, 10)

### Actual behaviour
ImportError: cannot import name 'ContinuousNode' from 'pgmpy.factors.continuous'

**Comment by ankurankan** [comment]
@ahmedhassan554 The `ContinuousNode` class has been renamed to `ContinuousFactor`. The continuous variable parts of the package are quite buggy and I don't think the discretizer works with ContinuousFactor.
