### ISSUE TITLE
KeyError in DAG.active_trail_nodes() when node is not str

### ISSUE THREAD

**Issue by THUzxj** [pgmpy/pgmpy#1514]
### Subject of the issue
When the graph has node with name that has a `list` or `tuple` type, invoking the `DAG` or `BayesianNetwork`'s 'active_trail_node()' or `get_independent` raises KeyError. Similar to #1334 .

### Your environment
* pgmpy 0.1.18dev
* Python 3.10.4
* Operating System windows 11 x64

### Steps to reproduce
```python
from pgmpy.base import DAG
student = DAG()
student.add_nodes_from(['diff', 'intel', ('grades', 0)])
student.add_edges_from([('diff', ('grades', 0)), ('intel', ('grades', 0))])
print(student.active_trail_nodes('diff'))
print(student.active_trail_nodes(('grades', 0)))
```

### Expected behaviour
Should return the active trails of the node.

### Actual behaviour
```bash
Traceback (most recent call last):
  File "~\AppData\Roaming\Python\Python310\site-packages\networkx\classes\digraph.py", line 835, in predecessors      
    return iter(self._pred[n])
KeyError: 'grades'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "A_PATH\crash.py", line 7, in <module>
    print(student.active_trail_nodes(('grades', 0)))
  File "B_PATH\pgmpy\base\DAG.py", line 743, in active_trail_nodes
    for parent in self.predecessors(node):
  File "~\AppData\Roaming\Python\Python310\site-packages\networkx\classes\digraph.py", line 837, in predecessors      
    raise NetworkXError(f"The node {n} is not in the digraph.") from err
networkx.exception.NetworkXError: The node grades is not in the digraph.
```

### Possible solution

This problem is caused by this line in `active_trail_nodes()`:

```
for start in variables if isinstance(variables, (list, tuple)) else [variables]:
```

I'm not sure if other places with similar logic will also produce similar errors.

**Comment by mowhammadrezaa** [comment]
change this line:
`for start in variables if isinstance(variables, (list, tuple)) else [variables]:`
to:
`for start in variables if isinstance(variables, list) else [variables]:`
it mustn't break anything.
