### ISSUE TITLE
pgmpy.estimators.PC.estimate does not run multithreaded.

### ISSUE THREAD

**Issue by bcwein** [pgmpy/pgmpy#1515]
### Subject of the issue

I am running the pgmpy [example](https://pgmpy.org/examples/Structure%20Learning%20in%20Bayesian%20Networks.html#) for structure learning in bayesian network and the estimate method in pgmpy.estimators.PC is not running multithreaded. I experience the same error with HillClimbSearch and parameter estimation method ExpectationMaximization. For now i limit the issue to pgmpy.estimators.PC.estimate

### Your environment
- pgmpy=0.1.18
- python=3.10.4
- OS: Ubuntu 20.04

### Steps to reproduce
I run the following code in a jupyter notebook

```python
from itertools import combinations

import networkx as nx
from sklearn.metrics import f1_score

from pgmpy.estimators import PC, HillClimbSearch, ExhaustiveSearch
from pgmpy.estimators import K2Score
from pgmpy.utils import get_example_model
from pgmpy.sampling import BayesianModelSampling
import numpy as np

# Funtion to evaluate the learned model structures.
def get_f1_score(estimated_model, true_model):
    nodes = estimated_model.nodes()
    est_adj = nx.to_numpy_matrix(
        estimated_model.to_undirected(), nodelist=nodes, weight=None
    )
    true_adj = nx.to_numpy_matrix(
        true_model.to_undirected(), nodelist=nodes, weight=None
    )

    f1 = f1_score(np.ravel(true_adj), np.ravel(est_adj))
    print("F1-score for the model skeleton: ", f1)

model = get_example_model("alarm")
samples = BayesianModelSampling(model).forward_sample(size=int(1e5))
samples.head()

est = PC(data=samples)
estimated_model = est.estimate(variant="stable", max_cond_vars=4)
get_f1_score(estimated_model, model)
```

### Expected behaviour
I would expect several cores being used when running the estimate method. 

### Actual behaviour
And this runs quite slow and when I check htop in Ubuntu it shows only 1 core running.

![bilde](https://user-images.githubusercontent.com/43122334/162431413-a4b7b8d5-9a1f-4636-8251-ef0e283bb961.png)

**Comment by ankurankan** [comment]
@bcwein In the code example, the estimate method is using the `stable` variant which doesn't have a multithreaded implementation. If you use `variant="parallel"` argument for the `estimate` method, it should run on multiple threads. For HillClimbSearch, I am not aware of any parallel variant of the algorithm. If you know of any, could you please share the link?
