### ISSUE TITLE
sampling doesn't work when nodes are types other than 'str'

### ISSUE THREAD

**Issue by mowhammadrezaa** [pgmpy/pgmpy#1516]
### Sampling doesn't work when nodes are types other than 'str'
When you want to make a sample of any size, in the 'Sampling' module, if the nodes of the network are of types other than 'str' it raises an error. While if you change this line:
`types = [(var_name, "int") for var_name in self.variables]`
to:
`types = [(str(var_name), "int") for var_name in self.variables]`
then it will work regardless of the node(variable) type. Ofcourse the specific type must have the \__str__  magical function defined.
### Your environment
* pgmpy version 0.1.18
* Python version 3.10
* Operating System macOS Monterey

### Steps to reproduce
Define a class for a Node:
<pre><code>class Node:
    def __init__(self, name, card, probabilities):
        self.name = name
        self.card = card
        self.probabilities = probabilities]
    def __str__(self):
        return self.name
</code></pre>
Create two nodes:
<pre><code>a = Node("A", 2, [
    [.5], 
    [.5],
    ])
b = Node("B", 2, [
    [.5, .5], 
    [.5, .5],
    ])
</code></pre>
Create a Bayesian Network and add cpds:
<pre><code>model = BayesianNetwork([
    (a, b)
])
cpds = [
    TabularCPD(
            node,
            node.card,
            node.probabilities,
            evidence=model.get_parents(node),
            evidence_card=[evidence.card for evidence in model.get_parents(node)],
        )
        for node in model.nodes()
]
model.add_cpds(*cpds)
</code></pre>
Generate samples:
<pre><code>gibbs_chain = GibbsSampling(model)
gibbs_chain.sample(seed=1)
</code></pre>
### Expected behaviour
<table>
<thead>
<tr>
<th></th>
<th>A</th>
<th>B</th>
</tr>
</thead>
<tbody>
<tr>
<th>0</th>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>

### Actual behaviour
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/mz/VSCode/Funda/Exam2.ipynb Cell 23' in <module>
     [26]()[ model.add_cpds(*cpds)
     ]()[27]()[ gibbs_chain = GibbsSampling(model)
---> ]()[28]()[ gibbs_chain.sample(seed=1)

File /usr/local/lib/python3.10/site-packages/pgmpy/sampling/Sampling.py:528, in GibbsSampling.sample(self, start_state, size, seed, include_latents)
    ]()[525]()[     np.random.seed(seed)
    ]()[527]()[ types = [(var_name, "int") for var_name in self.variables]
--> ]()[528]()[ sampled = np.zeros(size, dtype=types).view(np.recarray)
    ]()[529]()[ sampled[0] = tuple(st for var, st in self.state)
    ]()[530]()[ for i in tqdm(range(size - 1)):

TypeError: First element of field tuple is neither a tuple nor str]()
```

**Comment by ankurankan** [comment]
@mowhammadrezaa Thanks a lot for reporting this. Would you like to create a PR fixing this?
