### ISSUE TITLE
How to access to the variable that gives the max probability

### ISSUE THREAD

**Issue by DaniFra** [pgmpy/pgmpy#1517]
From a situation like this:

print(q['bronc'])
+---------+--------------+
| bronc | phi(bronc) |
|---------+--------------|
| bronc_0 | 0.6000 |
| bronc_1 | 0.4000 |
+---------+--------------+

how do i access "bronc_0" which is the most likely label?
I know that q.values[1] give me 0.6

**Comment by ankurankan** [comment]
@DaniFra You can use the `get_value` method of `DiscreteFactor` for getting the probability values corresponding to the states. Example:
```python
In [4]: phi = DiscreteFactor(['bronc'], [2], [0.6, 0.4])
Out[4]: <DiscreteFactor representing phi(bronc:2) at 0x7f67f7dc4340>

In [6]: phi
Out[6]: <DiscreteFactor representing phi(bronc:2) at 0x7f67f7dc4340>

In [7]: phi.state_names
Out[7]: {'bronc': [0, 1]}

In [8]: phi.get_value(bronc=0)
Out[8]: 0.6

In [9]: phi.get_value(bronc=1)
Out[9]: 0.4

In [10]: print(phi)
+----------+--------------+
| bronc    |   phi(bronc) |
+==========+==============+
| bronc(0) |       0.6000 |
+----------+--------------+
| bronc(1) |       0.4000 |
+----------+--------------+

```
