### ISSUE TITLE
Smooth param

### ISSUE THREAD

**Issue by PARODBE** [pgmpy/pgmpy#1518]
Hi,

Thank you for this amazing library. Do you think that could you incorporate a smooth parameter in order to do a gridsearch depending on score and smooth, like in bnclassify of R?

Thanks!
Pablo

**Comment by ankurankan** [comment]
@PARODBE Sorry for the late reply. If I am understanding correctly, the smooth parameter in bnclassify is equivalent to providing a pseudo_counts for each state when estimating the parameters. It should be equivalent to using `BayesianEstimator` with `dirichlet` prior in pgmpy. Here's an example with data generated from the alarm model and trying to learn the parameters of the model back from the simulated data. The `pseudo_counts` parameter should be equivalent to the smooth parameter in bnclassify.
```python
In [1]: from pgmpy.estimators import BayesianEstimator

In [2]: from pgmpy.utils import get_example_model

In [3]: from pgmpy.models import BayesianNetwork

In [4]: model = get_example_model('alarm')

In [5]: df = model.simulate(int(1e4))
Generating for node: BP: 100%|████████████████████████████████████████████| 37/37 [00:00<00:00, 299.29it/s]
/home/ankur/pgmpy/pgmpy/models/BayesianNetwork.py:1227: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  return samples.loc[:, set(self.nodes()) - self.latents]

In [6]: new_model = BayesianNetwork(model.edges())

In [7]: cpds = BayesianEstimator(new_model, df).get_parameters(prior_type='dirichlet', pseudo_counts=1)

In [8]: new_model.add_cpds(*cpds)
```
