### ISSUE TITLE
 Nan error in conditional probability calculation using VariableElimination's interface.

### ISSUE THREAD

**Issue by qinwenchuang** [pgmpy/pgmpy#1519]
### Subject of the issue
Describe your issue here.
nan errors occur in conditional probability calculations using VariableElimination's interface. This error is triggered in some cases, and not all calculations have nan.
Thanks.
__________________________________________________________
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
/home/qwc/.local/lib/python3.8/site-packages/pgmpy/factors/discrete/DiscreteFactor.py:466: RuntimeWarning: invalid value encountered in true_divide
  phi.values = phi.values / phi.values.sum()
+-------+----------+
| I     |   phi(I) |
+=======+==========+
| I(-1) |      nan |
+-------+----------+
| I(0)  |      nan |
+-------+----------+
| I(1)  |      nan |
+-------+----------+
______________________________

### Your environment
* pgmpy version:V0.1.18
* Python version:3.8
* Operating System:ubuntu20.04

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
@qinwenchuang It's a bit hard to say without looking at the code. Are the probability values in your network very small by any chance? Also, if you could possibly share your code/model, I can take a look at why this could be happening.

**Comment by qinwenchuang** [comment]
@ankurankan It is caused by the low value of probability.increasing the probability value will not cause this problem.
Thanks so much for response.
