### ISSUE TITLE
It seems spend too much time in VariableElimination._get_working_factors method when use bayesian newtork to predict

### ISSUE THREAD

**Issue by reeingal** [pgmpy/pgmpy#1525]
I build a `BayesianNetwork` and let i fit dataset to learn parameters.
And then I use it to `predict` and find that it is too slow because of spending too much time in `VariableElimination._get_working_factors()` method to build the `working_factors` variable (because there is a node have many edges from others in my network):

```python
working_factors = {
    node: {(factor, None) for factor in self.factors[node]}
    for node in self.factors
}
```

It seems take too much time in build a `set` about tuples of `DiscreteFactor` objects. Are there any methods to improve? Thank you.

**Comment by reeingal** [comment]
I found that the `__hash__()` method in `DiscreteFactor` spent too much time, because of the code:

```python
str(phi.values)
```

the type of `phi.values` is `numpy.ndarray`, when the shape of `phi.values` is big, it would take much time on `str()`.

**Comment by reeingal** [comment]
I am not sure, but it seems that `hash(phi.values.data.tobytes())` run much faster than `str(phi.values)`, and if two `numpy.ndarray` object have same values, they will get the same hash value. if I change the

```python
str(phi.values)
```

to

```python
str(hash(phi.values.data.tobytes()))
```

in `__hash__()` method of `DiscreteFactor`, it will still work?

**Comment by reeingal** [comment]
In my test, I get the same predict result after modifying the code, but I am still not sure whether it is just luck.

**Comment by ankurankan** [comment]
@reeingal Thanks for reporting this. It should return the same results and should improve the runtime as well. Would you like to create a PR for this as well?

**Comment by reeingal** [comment]
> 

It is my pleasure to report a pr.
