### ISSUE TITLE
The _compute_weights() method of ExpectationMaximization executes too long in large dataset

### ISSUE THREAD

**Issue by reeingal** [pgmpy/pgmpy#1526]
Hello, I use the `ExpectationMaximization` estimator to learn parameters of my `BayesianNetwork`. But it spend too much time on  `ExpectationMaximization._compute_weights()` method, because the method traverses all unique data in dataset:

```python
# pgmpy/estimators/EM.py ExpectationMaximization _compute_weights()
for i in range(data_unique.shape[0]):
    v = list(product(*[range(card) for card in latent_card.values()]))
    latent_combinations = np.array(v, dtype=int)
    df = data_unique.iloc[[i] * latent_combinations.shape[0]].reset_index(
        drop=True
    )
    for index, latent_var in enumerate(latent_card.keys()):
        df[latent_var] = latent_combinations[:, index]

    weights = df.apply(lambda t: self._get_likelihood(dict(t)), axis=1)
    df["_weight"] = (weights / weights.sum()) * n_counts[
        tuple(data_unique.iloc[i])
    ]
    cache.append(df)
```

I am wondering whether it can change to use `joblib.Parallel` to improve the speed. But I am not sure whether the `for` loop would use the result calculated by last loop. I am not familiar with the algorithm. Thank you.

**Comment by ankurankan** [comment]
@reeingal I think parallelization should work. But for smaller datasets, I see that the run time increases instead of decreasing because of parallelization overheads. Maybe you can try it on your dataset and see how that performs?

**Comment by reeingal** [comment]
> 

@ankurankan I make a test for a `DataFrame` with 50000 unique records. And it would save 80% time if I use `joblib.Parallel`. If the next loop would not use the result caculated by last loop in this `for` loop, I think it is maybe a good choice to use parallelization.

**Comment by ankurankan** [comment]
Hmm, interesting. Could you maybe create a PR for this as well in that case and then I can try it out on different dataset sizes? Thanks again for all the improvements :)

**Comment by reeingal** [comment]
> Hmm, interesting. Could you maybe create a PR for this as well in that case and then I can try it out on different dataset sizes? Thanks again for all the improvements :)

It is my pleasure to report a pr. I will make i soon.

**Comment by reeingal** [comment]
@ankurankan I create the PR. In my personal computer, I can not create the 50000 unique records with 30 nodes Because of the poor memory, so I have to change to 9994 unique records with 10 nodes. The CPU of my laptop is AMD Ryzen 5 5500U @ 2.1GHz. With parallelization, the time `_compute_weights()` costed was 103 seconds compare to 387 seconds use only `for` loop.

**Comment by reeingal** [comment]
@ankurankan There is a fault in the code I commit. I just tested one round the `_compute_weights()` and did not wait for finishing the learning. I find that the if I use process in `joblib.Parallel`, it will run out of memory of my laptop (Ubuntu, 16GB) when execute the `joblib.Parallel` in `get_parameters()` of `MaximumLikelihoodEstimator` which `prefer` is `threads`. If I change the `prefer` to `processes` in `MaximumLikelihoodEstimator`, it will not run out of memory of my laptop, but when I test the code in my school computer (Windows 10, 64GB), it will get `_pickle.PicklingError: Could not pickle the task to send it to workers` exception when executing the `joblib.Parallel` in `MaximumLikelihoodEstimator`. I have no idea how to improve it now.

**Comment by reeingal** [comment]
The problem in my school computer maybe I use a 60000 unique records dataset and the shape of `weighted_data` caculated in EM is 37518125x29, which might hit the memory limit when running `_send_bytes()` of `joblib`. In my laptop, I just constrcut a random dataset like:

```python
import numpy as np
import pandas as pd

from pgmpy.models import BayesianNetwork
from pgmpy.estimators import ExpectationMaximization

raw_data = np.random.randint(0, 5, (10000, 10))
df = pd.DataFrame(raw_data, columns=[f"feature_{i}" for i in range(1,11)])
edges = [(f"feature_{i}", "feature_10") for i in range(1, 10)]
model = BayesianNetwork(edges, latents={"feature_3", "feature_4", "feature_5"})
model.fit(
    df.drop(["feature_3", "feature_4", "feature_5"], axis=1),
    estimator=ExpectationMaximization,
    latent_card={"feature_3": 5, "feature_4": 5, "feature_5": 5}
)
```
