### ISSUE TITLE
Stable PC Algorithm is Incorrect

### ISSUE THREAD

**Issue by zacandcheese** [pgmpy/pgmpy#1536]
### Subject of the issue
I was using this algorithm to check the accuracy of my implementation and I noticed a discrepancy in the sepsets. After checking this code I discovered a potential bug. In the stable algorithm `neighbors` is precomputed so when edges get removed from the graph the order does not change the result. 
The original version:  [line 8 in pseudocode of original paper](https://arxiv.org/pdf/1211.3295.pdf#page=6)
8. Choose a (new) set $S \subseteq \text{adj}(C, X_i) \setminus \{X_j\}$
The stable version: [line 11 in pseudocode](https://arxiv.org/pdf/1211.3295.pdf#page=12) where $a$ is precomputed neighbors for the ''level'' or sepset size
11. Choose a (new) set $S \subseteq a(X_i)$

###  Code Currently
```python
elif variant == "stable":
                # In case of stable, precompute neighbors as this is the stable algorithm.
                neighbors = {node: set(graph[node]) for node in graph.nodes()}
                for (u, v) in graph.edges():
                    for separating_set in chain(
                        combinations(set(graph.neighbors(u)) - set([v]), lim_neighbors),
                        combinations(set(graph.neighbors(v)) - set([u]), lim_neighbors),
                    ):
```
### Expected Code
```python
elif variant == "stable":
                # In case of stable, precompute neighbors as this is the stable algorithm.
                neighbors = {node: set(graph[node]) for node in graph.nodes()}
                for (u, v) in graph.edges():
                    for separating_set in chain(
                        combinations(set(neighbors[u]) - set([v]), lim_neighbors),
                        combinations(set(neighbors[v]) - set([u]), lim_neighbors),
                    ):
```

This seems like a typo because `neighbors` does get precomputed, it is just never used.

**Comment by ankurankan** [comment]
@zacandcheese Thanks for reporting this. This indeed seems to be a bug. Would you like to open a PR fixing it?
