### ISSUE TITLE
Bug in EM when latent variables are present

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#1542]
### Subject of the issue
EM algorithm seems to be assigning equal probability values to all the states of latent variables. 

### Your environment
* pgmpy version: 0.1.18
* Python version
* Operating System

### Steps to reproduce
```python
from pgmpy.utils import get_example_model
from pgmpy.models import BayesianNetwork
from pgmpy.estimators import ExpectationMaximization as EM

model = get_example_model('cancer')
model_latent = BayesianNetwork(model.edges(), latents={'Smoker'})
model_latent.add_cpds(*model.cpds)
samples = model_latent.simulate(int(1e4))
est = EM(model_latent, samples)
cpds = est.get_parameters(seed=42, show_progress=False)
print(cpds[2])
+-----------+----------+
| Smoker(0) | 0.500001 |
+-----------+----------+
| Smoker(1) | 0.499999 |
+-----------+----------+

```

**Comment by zhangtj1996** [comment]
I also noticed the current EM estimator does not support `float` data. I have `np.nan` in my data entries. 

Error:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by zhangtj1996** [comment]
I also noticed that the current pgmpy version: 0.1.19 EM estimator doesn't support missing data.

## Steps to reproduce
```python
import numpy as np
import pandas as pd
from pgmpy.models import BayesianNetwork
from pgmpy.estimators import ExpectationMaximization as EM
data = pd.DataFrame(np.concatenate([np.zeros([500,2]),np.ones([500,2])]).astype(float),
                      columns=['A', 'B'])
data.iloc[0,0]=np.nan
model = BayesianNetwork([('A', 'B')])
estimator = EM(model, data)
print(estimator.get_parameters()[0])
```

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by JonathanOase** [comment]
@ankurankan 'EM algorithm seems to be assigning equal probability values to all the states of latent variables'. Has this problem been solved?

**Comment by ankurankan** [comment]
@JonathanOase Unfortunately, this hasn't been fixed yet.

**Comment by Yale69** [comment]
I noticed that there seems to be a problem with "ExpectationMaximization._parallel_compute_weights":
'''
weights = df.apply(lambda t: self._get_log_likelihood(dict(t)), axis=1)
weights = np.exp(weights)  # The probability statistic should be recovered by exponentiation
df["_weight"] = (weights / weights.sum()) * n_counts[
    tuple(data_unique.iloc[i])
]
'''

**Comment by Yale69** [comment]
I noticed that there seems to be a problem with "ExpectationMaximization._parallel_compute_weights":
```
weights = df.apply(lambda t: self._get_log_likelihood(dict(t)), axis=1)
weights = np.exp(weights) # The probability statistic should be recovered by exponentiation
df["_weight"] = (weights / weights.sum()) * n_counts[
tuple(data_unique.iloc[i])
]
```

**Comment by xixixiyou** [comment]
The EM algorithm should be assigned a large weight with a high probability, and a small weight with a small probability, and the opposite is true through the log.  
def _get_likelihood(self, datapoint): likelihood = 1.0 for cpd in self.model_copy.cpds: scope = set(cpd.scope()) likelihood *= cpd.get_value( **{ key: value for key, value in datapoint.items() if key in scope } ) return likelihood

**Comment by ankurankan** [comment]
@Yale69 @xixixiyou Thanks for reporting the issue. I think I have found the bug and have a PR in works for fixing it.
