### ISSUE TITLE
main thread of the c++(Qt)  project call BayesianNetwork.load()  will block

### ISSUE THREAD

**Issue by Jchaokai** [pgmpy/pgmpy#1545]
### Subject of the issue
i' writing a c++(Qt) project and wil call  `pgmpy`. 
when i call `BayesianNetwork.load('xxxxxx.bif')`  in c++(Qt) project,  the main thread will block, and the num of  `main window`  will from one to many(never seen this situation)

### Your environment
* pgmpy - 0.1.18
* Python version - 3.9.13 
* Operating System - win64

### Steps to reproduce

i will give some example code.

here is my c++ code:
```
// Python Interpreter has inited before

// 1. get the [load_model] func from the python script
auto func_load = PyObject_GetAttrString(_module, "load_model");
if (!func_load || !PyCallable_Check(func_load)) {
	return nullptr;
}

// 2. build args
auto args = Py_BuildValue("s", path.c_str());
// 3. call func and pass args
PyObject* pResult = PyObject_CallOneArg(func_load, args);

if (!pResult) {
	return nullptr;
}

return pResult;
```

here is python script:
```
def load_model(path: str):
    try:
        return BayesianNetwork.load(path)
    except Exception as err:
        return str(err)

```

### Expected behaviour
```
// 3. call func and pass args
PyObject* pResult = PyObject_CallOneArg(func_load, args);
```
the pResult will null or not , the main thread will not block , the num of `main window` should always one

### Actual behaviour
the main thread will block,  and  the num of `main window` will from one to  many

<br/>
can you give me some tips ? 

what happened in `BayesianNetwork.load('xxx.bif')`,   mutil thread ?

**Comment by ankurankan** [comment]
@Jchaokai Yes, the BIFReader is multi-threaded. If you want to run it in a single thread you can also load the model using:
```python
from pgmpy.readwrite import BIFReader
model = BIFReader(path, n_jobs=1).get_model()
```

**Comment by Jchaokai** [comment]
@ankurankan it's work !
so  so so so so so so so appreciate !!!
