### ISSUE TITLE
after load "xxx.bif",  VariableElimination.query() wil error

### ISSUE THREAD

**Issue by Jchaokai** [pgmpy/pgmpy#1552]
### Subject of the issue
after load model from "xxx.bif", VariableElimination.query() will error.
<br>
**here is the model ( not loaded from file), it will succ:**
```
 model = BayesianNetwork()

 model.add_nodes_from(['president', 'traffic', 'accident'])

 model.add_edge('president', 'traffic')
 model.add_edge('accident', 'traffic')

 cpd_president = TabularCPD('president', 2, [[0.9], [0.1]])

 cpd_accident = TabularCPD('accident', 2, [[0.7], [0.3]])

 cpd_traffic = TabularCPD('traffic', 2,
                          [[0.9, 0.5, 0.4, 0.1],
                           [0.1, 0.5, 0.6, 0.9]],
                          evidence=['president', 'accident'],
                          evidence_card=[2, 2])

 model.add_cpds(cpd_president, cpd_accident, cpd_traffic)


 infer = VariableElimination(model)
 vir_evidence = TabularCPD('accident', 2, [[0.33], [0.67]])
 print(infer.query(['traffic'], virtual_evidence=[vir_evidence]))
```

**here is the model loaded from `xxx.bif`, it will error:**
```
model = BIFReader('./demo2.bif', n_jobs=1).get_model()

infer = VariableElimination(model)
vir_evidence = TabularCPD('accident', 2, [[0.33], [0.67]])
print(infer.query(['traffic'], virtual_evidence=[vir_evidence]))

```
**here is `demo2.bif`:**
```
network unknown {
}
variable accident {
    type discrete [ 2 ] { 0, 1 };
    property weight = None ;
}
variable president {
    type discrete [ 2 ] { 0, 1 };
    property weight = None ;
}
variable traffic {
    type discrete [ 2 ] { 0, 1 };
    property weight = None ;
}
probability ( accident ) {
    table 0.7, 0.3 ;
}
probability ( president ) {
    table 0.9, 0.1 ;
}
probability ( traffic | president, accident ) {
    ( 0, 0 ) 0.9, 0.1;
    ( 0, 1 ) 0.5, 0.5;
    ( 1, 0 ) 0.4, 0.6;
    ( 1, 1 ) 0.1, 0.9;

}

```

during debug，error occurs when  `parent_cpd.state_names[node] != cpd.state_names[node]`
`parent_cpd.state_name` is `{'accident': ['0', '1']}`
`cpd.state_names` is `{'__accident': [0, 1], 'accident': [0, 1]}`

<br> 

**it's a bug ?**

### Your environment
* pgmpy version   3.9.13
* Python version   0.1.18
* Operating System  win64

**Comment by ankurankan** [comment]
@Jchaokai It's not really a bug. The problem is that there is a mismatch between the state names provided in vir_evidence and the loaded model.
```python
In [19]: vir_evidence.state_names
Out[19]: {'accident': [0, 1]}
In [21]: load_model = BayesianNetwork.load('test.bif')

In [22]: load_model.states
Out[22]: {'accident': ['0', '1'], 'president': ['0', '1'], 'traffic': ['0', '1']}
```
Since no state names were specified while creating the model, pgmpy by default assigns integer states starting from 0. But once the network is written to a file, there's no way of knowing whether the original state was an int or str. And while reading, the default assumption is that the state names are str as you can see in the code example above. To avoid this, you can specify an argument in the `get_model` method as:
```python
In [24]: load_model = BIFReader('test.bif').get_model(state_name_type=int)

In [25]: load_model.states
Out[25]: {'accident': [0, 1], 'president': [0, 1], 'traffic': [0, 1]}
```
And the query should work as expected with this model.
