### ISSUE TITLE
log info format issue

### ISSUE THREAD

**Issue by Jchaokai** [pgmpy/pgmpy#1556]
https://github.com/pgmpy/pgmpy/blob/e4953447727818f2d9cdd25607b0f9199f18dc4e/pgmpy/models/BayesianNetwork.py#L429

I haven't written Python before , but this error info can't give me some tips to solve it (i got this error)
should write like this?
```
 f"CPD for {node} doesn't have state names defined for all the variables." 
```

**Comment by ankurankan** [comment]
@Jchaokai Yes, that seems to be a typo in the code. It is supposed to be an f-string, exactly what you have suggested.
