### ISSUE TITLE
DBN inference

### ISSUE THREAD

**Issue by ChirsEdith** [pgmpy/pgmpy#1580]
Thanks for your code at first. If I have the DBN's structure and its parameters, what I need is the DBN's inference. Can your code deal with this problem? Thanks a lot.

**Comment by ankurankan** [comment]
@ChirsEdith The DBNInference class should be able to do that: https://pgmpy.org/exact_infer/dbn_infer.html. Code link: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/inference/dbn_inference.py
