### ISSUE TITLE
Some nodes for a DBN of more than 1 time slice are not detected 

### ISSUE THREAD

**Issue by ngobibibnbe** [pgmpy/pgmpy#1586]
### Subject of the issue
nodes are not identified 
### Your environment
* pgmpy 0.1.20
* Python 3.8
* ubuntu

### Steps to reproduce
dbnet.add_edges_from([ (('Z', 0), ('Z', 1)), (('Z', 0), ('X', 0)),(('Z', 1), ('X', 1)),   (('Z', 1), ('Z', 2)),   (('Z', 2), ('X', 2)),    (('Z', 2), ('Z', 3)) ,  
                      (('Y', 0), ('Y', 1)), (('Y', 0), ('X', 0)),  (('Y', 1), ('X', 1)), (('Y', 1), ('Y', 2)), (('Y', 2), ('X', 2)), (('Y', 2), ('Y', 3))])
print(dbnet.nodes)

### Expected behaviour
printing all the nodes existing here including (Z,2), (Y,2), (X,2)

### Actual behaviour
[<DynamicNode(Z, 0) at 0x7fb25915d0d0>, <DynamicNode(Z, 1) at 0x7fb25915d290>, <DynamicNode(X, 0) at 0x7fb25915d1d0>, <DynamicNode(X, 1) at 0x7fb25915d810>, <DynamicNode(Y, 0) at 0x7fb2eccbcd10>, <DynamicNode(Y, 1) at 0x7fb25915d090>]

And I am not able to add cpds of (Z,2), (Y,2), (X,2)

**Comment by ankurankan** [comment]
@ngobibibnbe As I mentioned in https://github.com/pgmpy/pgmpy/issues/1585#issuecomment-1357403270 , you need to only specify the first one and a half time slices and rest should be automatically generated with the assumptions of 2-TBN.
