### ISSUE TITLE
Update the edges based on some kind of loss

### ISSUE THREAD

**Issue by samanemami** [pgmpy/pgmpy#1590]
This is a question rather than an issue.
I was wondering if it is possible to update the edges and dag in a training procedure!
I could not find any related method if there is one.

Would you please help me with this question?

I appreciate it,
Thank you so much in advance.

**Comment by ankurankan** [comment]
@samanemami Sorry for the late reply. Could you please elaborate/an example of what you mean by updating edges? If it is about adding/deleting edges from the DAG, structure learning algorithms do that.

**Comment by samanemami** [comment]
@ankurankan Thank you for your kind reply.

For instance, we estimate the structure with chow-Liu.
And of course, these are not the ideal dependencies and edges between the variable, hence we need to optimize the edges and update the estimated DAG in sequential steps.

**Comment by ankurankan** [comment]
@samanemami Can you give me any examples of algorithms that can do this? One possible way I can think of doing this is through model testing. Essentially, we would get all the implied conditional independence of the model structure and test each of them in the data using a statistical test. If the test fails, we update the model structure.
