### ISSUE TITLE
BUG in Save & load model:Change of state(list[int] to list[string])

### ISSUE THREAD

**Issue by qinwenchuang** [pgmpy/pgmpy#1604]
### Subject of the issue
Describe your issue here.

### Your environment
* pgmpy version:0.1.20
* Python version:3.8
* Operating System:ubuntu20.04

### Steps to reproduce
Loading the post-training model, I encountered two problems:
1. Can't use VariableElimination.query (), the following error: The File "/ home/QWC/local/lib/python3.8 / site - packages/pgmpy/utils/state_name. Py", line 72, in get_state_no return self.name_to_no[var][state_name]
2. The following warning is displayed when the prediction function(model.predict) is used:UserWarning: Found unknown state name. Trying to switch to using all state names as state numbers.

I suspect that the state changed after loading the model. I verified my guess by printing the state (model. states). 
Original: model.states:
{'V0': [0, 1], 'V1': [0, 1], 'I': [0, 1], 'V2': [0, 1], 'V3': [0, 1], 'G': [0, 1], 'H': [0, 1]}
 --- Save(bif) & Load ---
After: model.states
{'G': ['0', '1'], 'H': ['0', '1'], 'I': ['0', '1'], 'V0': ['0', '1'], 'V1': ['0', '1'], 'V2': ['0', '1'], 'V3': ['0', '1']}

I hope to get attention and repair as soon as possible, thank you.

**Comment by ankurankan** [comment]
@qinwenchuang Thanks for reporting this. The problem with writing integer states is that once written to the file, there's no way to know whether the states were int or str. That's why the BIF reader class had a state_name_type argument to specify how to treat the state names. An example would be:
```python
In [1]: from pgmpy.utils import get_example_model
   ...: model = get_example_model('asia')
   ...: model.get_random_cpds(inplace=True)
   ...: model.save('asia.bif')

In [2]: model.states
Out[2]: 
{'asia': [0, 1],
 'bronc': [0, 1, 2, 3],
 'smoke': [0, 1, 2],
 'dysp': [0],
 'either': [0],
 'lung': [0, 1, 2],
 'tub': [0, 1, 2],
 'xray': [0, 1]}

In [3]: from pgmpy.readwrite import BIFReader
   ...: reader = BIFReader(path='asia.bif')
   ...: read_model = reader.get_model(state_name_type=int)
   ...: read_model.states
Out[3]: 
{'asia': [0, 1],
 'smoke': [0, 1, 2],
 'bronc': [0, 1, 2, 3],
 'either': [0],
 'dysp': [0],
 'lung': [0, 1, 2],
 'tub': [0, 1, 2],
 'xray': [0, 1]}
```
But this argument wasn't exposed in the `BayesianNetwork.load` method, but I have just added that, and if you use the latest dev branch, you should be able to do this as:
```python
BayesianNetwork.load('asia.bif', state_name_type=int)
```
