### ISSUE TITLE
Tests for local_independencies of BayesianModel

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#161]

**Comment by kshitij10496** [comment]
@ankurankan I was going through the example in the docstrings of both - the [`local-independecies()`](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/models/BayesianModel.py#L344) and the [`get_independencies()`](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/models/BayesianModel.py#L426).
I wanted to know whether the `get_independencies()` should display the local independencies of each node too ?

**Comment by ankurankan** [comment]
@kshitij10496 Ideally it should.

**Comment by kshitij10496** [comment]
@ankurankan I tried coded the given examples but didn't get that result.
Can you cross-check this ?

**Comment by ankurankan** [comment]
@kshitij10496 Yeah, I think that there is some bug. Can you fix this ?

**Comment by kshitij10496** [comment]
@ankurankan I would like to give it a try. 
Since, I am getting started with the codebase so I think I would need a few days. 
Is that fine ?

**Comment by ankurankan** [comment]
@kshitij10496 Yeah.. And feel free to ask if you get stuck somewhere.

**Comment by kshitij10496** [comment]
@ankurankan Yeah.
I am having some trouble deciding the class to which the `test_local_independencies()` should be added. 
I think adding to the [`TestBayesianModelCPD`](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/tests/test_models/test_BayesianModel.py#L125) would be the appropritate choice.
Can you tell me in which class should I add the test function ?

**Comment by ankurankan** [comment]
@kshitij10496 It should go in `TestBayesianModelMethods`.

**Comment by kshitij10496** [comment]
@ankurankan Thanks.
I am working on it

**Comment by kshitij10496** [comment]
@ankurankan I was trying to add the test function.
I think, ideally, the test should have passed but I am getting an `AssertionError`. 
Should I send a PR before discussing on the error ?

**Comment by ankurankan** [comment]
@kshitij10496 Yes. Will help me spotting the error.

**Comment by kshitij10496** [comment]
@ankurankan I think we can close this now.

**Comment by ankurankan** [comment]
Fixed..
