### ISSUE TITLE
XMLBIFReader fails parsing moderately large networks

### ISSUE THREAD

**Issue by systemssoperfect** [pgmpy/pgmpy#1634]
### Subject of the issue
XMLBIFReader fails parsing moderately large networks, with tables ~1M entries.

### Your environment
* pgmpy  0.1.22
* Python 3.8.10
* Ubuntu 20.04

### Steps to reproduce
Create a node TABLE with more than 1 million entries

### Expected behaviour
No error.

### Actual behaviour
lxml throws the exception below:

Traceback (most recent call last):
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "./Inferências/Modelos/Modelo5_BIF_2022_2t.xml", line 5765
lxml.etree.XMLSyntaxError: xmlSAX2Characters: huge text node, line 5765, column 10000791

**Comment by ankurankan** [comment]
@systemssoperfect Thanks for reporting this. Would it be by any chance, possible to share the model file so that I can reproduce the issue?

**Comment by systemssoperfect** [comment]
Dear Ankur,

Your library is great and this is a minor issue regarding lxml only.

As lxml has the same interface of xml.etree and you also provide it as an
alternative option, I've just commented lxml and copied the import of
xml.etree.

And xml.etree seems much faster than lxml.

Again, thanks a lot for your beautiful work.

Gerson


try:
# from lxml import etree
import xml.etree.ElementTree as etree
except ImportError:
try:
import xml.etree.ElementTree as etree
except ImportError:
# try:
# import xml.etree.cElementTree as etree
# commented out because xml.etree.cElementTree is giving errors with
dictionary attributes
print("Failed to import ElementTree from any known place")

**Comment by systemssoperfect** [comment]
Here we go.

[Modelo6_BIF_2022_2t.zip](https://github.com/pgmpy/pgmpy/files/11456213/Modelo6_BIF_2022_2t.zip)

**Comment by ankurankan** [comment]
@systemssoperfect Thanks for sharing the file. I hadn't realized that lxml's parser is much slower than xml.etree. I have changed everything to work with xml.etree now.
