### ISSUE TITLE
HillClimbSearch estimate issue

### ISSUE THREAD

**Issue by ghost** [pgmpy/pgmpy#1646]
### Subject of the issue
Hi, i was trying to replicate the same code in the documentation to do a HillClimbSearch, but I have an issue for that the model doesn't complete the estimation. Infact the progress bar is stuck on the 0% and it seems like the process is done, but it doesn't.

### Your environment
* pgmpy version = 0.1.23
* Python version = 3.11
* Operating System = macOS

### Steps to reproduce
```python
import pandas as pd
import numpy as np
from pgmpy.estimators import HillClimbSearch, BicScore

data = pd.DataFrame(np.random.randint(0, 5, size=(5000, 9)), columns=list('ABCDEFGHI'))

data['J'] = data['A'] * data['B']
est = HillClimbSearch(data)
best_model = est.estimate(scoring_method=BicScore(data))
```
### Expected behaviour
I should it could go forward until the 100%

### Actual behaviour
The model is stuck on 0%
<img width="569" alt="Screenshot 2023-07-08 alle 14 59 13" src="https://github.com/pgmpy/pgmpy/assets/92474201/8d425502-a2cf-4002-857b-9dd829240683">

**Comment by ankurankan** [comment]
@giovanniOfficioso It doesn't usually get to 100% but should be able to finish/output the estimated model before that. The 100% is based on the `max_iter` argument of the `estimate` method and the algorithm doesn't usually need that many iterations. 
```python
In [11]: import pandas as pd
    ...: import numpy as np
    ...: from pgmpy.estimators import HillClimbSearch, BicScore
    ...: 
    ...: data = pd.DataFrame(np.random.randint(0, 5, size=(5000, 9)), columns=list('ABCDEFGHI'
    ...: ))
    ...: 
    ...: data['J'] = data['A'] * data['B']
    ...: est = HillClimbSearch(data)
    ...: best_model = est.estimate(scoring_method=BicScore(data))
  0%|                                                  | 2/1000000 [00:00<32:18:27,  8.60it/s]

In [12]: best_model.nodes()
Out[12]: NodeView(('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'))

In [13]: best_model.edges()
Out[13]: OutEdgeView([('A', 'J'), ('B', 'J')])

```
