### ISSUE TITLE
TypeError in structure_score

### ISSUE THREAD

**Issue by yoshiakifukushima** [pgmpy/pgmpy#1650]
### Subject of the issue
I was trying to compute score the model structure with using [structure_score](https://pgmpy.org/metrics/metrics.html#pgmpy.metrics.metrics.structure_score) function, but I have an issue for that the function raise TypeError. 

### Your environment
* pgmpy version = 0.1.23
* Python version = 3.9.6
* Operating System = macOS

### Steps to reproduce
```
import pandas as pd
import numpy as np
from pgmpy.models import BayesianNetwork
from pgmpy.estimators import BDeuScore
# create random data sample with 3 variables, where B and C are identical:
data = pd.DataFrame(np.random.randint(0, 5, size=(5000, 2)), columns=list('AB'))
data['C'] = data['B']

# error case
score = structure_score(
    model=BayesianNetwork([['A','B'], ['A','C']]),
    data=data,
    scoring_method="bdeu",
    equivalent_sample_size=30)
```

### Expected behaviour
Expected to success as same as following result.

```
score = BDeuScore(
    data=data, 
    equivalent_sample_size=30).score(
        model=BayesianNetwork([['A','B'], ['A','C']])
    )
```

### Actual behaviour
Then following TypeError happen.

```
File /pgmpy/metrics/metrics.py:253), in structure_score(model, data, scoring_method, **kwargs)
    250     raise ValueError(f"scoring method not supported and not a callable")
    252 # Step 2: Compute the score and return
--> 253 return supported_methods[scoring_method](data).score(model, **kwargs)

TypeError: score() got an unexpected keyword argument 'equivalent_sample_size'
```

### Possible fix

The issue seems to be caused by the following line in the structure_score method:

https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/metrics/metrics.py#L253

Replacing it with the following could be a solution.

`return supported_methods[scoring_method](data, **kwargs).score(model)`

**Comment by ankurankan** [comment]
@yoshiakifukushima Thanks for reporting the issue. Would you like to create a PR with the fix?
