### ISSUE TITLE
Comments for UAI formats files

### ISSUE THREAD

**Issue by White-On** [pgmpy/pgmpy#1660]
### Comments for UAI formats files 
Currently, pgmpy can't handle **UAI** files with comments on it which is a shame because as I'm working with other libraries that generate UAI files with comments ( as simple notations for the label's name ) such as pyAgrum.

So, in order to make pgmpy handles those, I sugest a simple change in the `UAIReader` class : 
https://github.com/pgmpy/pgmpy/blob/9de4798ee754155b3bc139d5f743702898748312/pgmpy/readwrite/UAI.py#L10C1-L50C40

```Py
[...]
        if path:
            with open(path, "r") as f:
                self.network = f.read()
        elif string:
            self.network = string
        else:
            raise ValueError("Must specify either path or string.")
        
        if "#" in self.network:
            self.network = Regex("#.*").suppress().transformString(
                self.network
            )  # removing comments from the file

        self.grammar = self.get_grammar()
        self.network_type = self.get_network_type()
        self.variables = self.get_variables()
[...]
```
I've used the same method found in the BIFReader. 
This should makes files such as this one be readable:

```
BAYES
8
2 2 2 2 2 2 2 2 
8
1 0   # asia
2 0 1   # tub
1 2   # smoke
2 2 3   # lung
2 2 4   # bronc
3 3 1 5   # either
2 5 6   # xray
3 4 5 7   # dysp


2
  0.01 0.99 

4
  0.05 0.95 
  0.01 0.99 

2
  0.5 0.5 
[...]
```

**Comment by ankurankan** [comment]
@White-On Thanks for reporting the issue. Would you like to create a PR with the fix?

**Comment by White-On** [comment]
https://github.com/pgmpy/pgmpy/pull/1662#issue-1864913286

There you go ! Hopefully this will help
