### ISSUE TITLE
Could you please put add_cpds logging.info(f"Replacing existing CPD for {cpd.variable}")  under verbose control? thanks!

### ISSUE THREAD

**Issue by atcode99** [pgmpy/pgmpy#1670]
### Subject of the issue
there are too many INFO> Replacing existing CPD for when add_cpds dynamically.

### Your environment
* pgmpy version
* Python version
* Operating System

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
@atcode99 Thanks for the feedback. I will try to add a global variable to set whether to show warnings or not.

**Comment by ankurankan** [comment]
@atcode99 All the warnings are now (in the latest dev branch) using the logging module. You should be able to set the level that you would like to see:
```python
import logging
logging.getLogger('pgmpy').setLevel(logging.CRITICAL)
```
