### ISSUE TITLE
Constraints in structure learning

### ISSUE THREAD

**Issue by zzzrbx** [pgmpy/pgmpy#1681]
Hello,
is it possible to set constraints with structure learning? For example, one node has to be leaf node.

**Comment by ankurankan** [comment]
@zzzrpagliari There's no  direct way to specify a node to be a leaf node, but a workaround could be to use the `black_list` argument of HillClimbSearch. If you specify a list of all possible edges as: [(leaf_node, other_node1), (leaf_node, other_node2), ...], this should force the leaf_node to only have incoming edges, making it a leaf node.
