### ISSUE TITLE
Getting CPDs as a dataframe

### ISSUE THREAD

**Issue by zzzrbx** [pgmpy/pgmpy#1682]
Is it possible to convert TabularCPDs to pandas dataframe?

**Comment by ankurankan** [comment]
@zzzrpagliari This can be done by first writing the CPD to a csv file and then reading it back. Here's an example:
```python
In [3]: from pgmpy.utils import get_example_model

In [4]: model = get_example_model('alarm')

In [6]: model.get_cpds('HISTORY').to_csv('history_cpd.csv')

In [7]: pd.read_csv('history_cpd.csv', index_col=0)
Out[7]: 
                LVFAILURE(TRUE)  LVFAILURE(FALSE)
LVFAILURE                                        
HISTORY(TRUE)               0.9              0.01
HISTORY(FALSE)              0.1              0.99

```

**Comment by zzzrbx** [comment]
Hi,
`model.get_cpds` returns None while I can see the `.values` of the object. Any ideas?

**Comment by ankurankan** [comment]
@zzzrpagliari I can't think of any way that could happen.  Do you have a code example that I can maybe have a look at?

**Comment by zzzrbx** [comment]
I'm generating random data (as an example)

```
tmp = pd.DataFrame(np.random.randint(0, 2, size=(1000, 4)), columns=['A', 'B', 'C', 'D'])

final_model = BayesianNetwork(
    [
        ('A', 'B'),
        ('A', 'C'),        
        ('C', 'D'),
        ('B', 'D'),
    ]
)

print(MaximumLikelihoodEstimator(final_model, tmp).estimate_cpd('D'))
```

I can get the CPD for D using `estimate_cpd `from `MaximumLikelihoodEstimator`. However, `get_cpds `returns None object.

**Comment by ankurankan** [comment]
@zzzrpagliari So, the `estimate_cpd` just creates the CPD object but doesn't add it to the model, that's why you are not able to use the `get_cpds` method. Some options:
1. Estimate all CPDs and add them to the model.
```python
>>> final_model.fit(tmp, estimator=MaximumLikelihoodEstimator)
>>> final_model.get_cpds('D')
<TabularCPD representing P(D:2 | B:2, C:2) at 0x7fe775692d70>
```
2. Estimate just for variable `D` and add it to the network
```python
>>> cpd_d = MaximumLikelihoodEstimator(final_model, tmp).estimate_cpd('D')
>>> final_model.add_cpd(cpd_d)
>>> final_model.get_cpds('D')
<TabularCPD representing P(D:2 | B:2, C:2) at 0x7fe7755ecfa0>

```

**Comment by zzzrbx** [comment]
Thank you for the quick reply. TabularCPD appears not to have a to_csv method. 

```
final_model.get_cpds('D').to_csv('./temp.csv')
AttributeError: 'TabularCPD' object has no attribute 'to_csv'
```

Is there another way to cast it into a pandas dataframe?

**Comment by ankurankan** [comment]
@zzzrpagliari Could you check what version of pgmpy of installed using `pgmpy.__version__`. The `to_csv` method was added in v0.1.24. You can try updating, if an older version is installed.

**Comment by zzzrbx** [comment]
Thank you
