### ISSUE TITLE
log_likelihood_score with best model from hill climb

### ISSUE THREAD

**Issue by zzzrbx** [pgmpy/pgmpy#1683]
I'm running hill climb to estimate the structure of a network. I'm able to get both correlation and structure score. log_likelihood_score, however, is complaining that it's getting a pgmpy.base.DAG.DAG (as opposed to BayesianNetwork or DAG type). Is it a bug?

**Comment by ankurankan** [comment]
@zzzrbx Sorry for the late reply. It's not really a bug. A DAG represents just the network structure whereas Bayesian Network (BN) represents the structure + CPDs. I do agree that it is a bit confusing right now and the functions should be able to automatically handle this. Currently, to create a BN from the DAG you could do something like this:
```python
from pgmpy.models import BayesianNetwork

bn = BayesianNetwork(dag.edges())
bn.add_nodes_from(dag.nodes())
```
