### ISSUE TITLE
Handling error with exceptions with newest version

### ISSUE THREAD

**Issue by iameteore314** [pgmpy/pgmpy#1686]
### Subject of the issue

I just came across a new kind of error where the bif BN won't load... It worked perfectly yesterday though.
I set up the pip install pgmpy and also tried the latest dev branch but doesn't see, to work either.
Don't think it comes from the BN itself since it was working yesterday.

### Your environment
* pgmpy version==0.1.24
* Python version
* Operating System : Google Colab

### Steps to reproduce
Just loading a .bif BN

### Expected behaviour
Should load properly

### Actual behaviour
![Screenshot 2023-10-18 at 18 24 23](https://github.com/pgmpy/pgmpy/assets/72555726/723bfbee-48ff-4306-a54a-8e5629b88ddb)

**Comment by ankurankan** [comment]
@iameteore314 Could you try updating networkx: `pip install networkx -U`?

**Comment by iameteore314** [comment]
Thanks for the quick reply. It worked indeed but it seems to load faster with v 0.1.23....

**Comment by ankurankan** [comment]
@iameteore314 Yes, reading BIF is around 10x slower in v0.1.24 compared to v0.1.23. It's because of the added unicode support.

**Comment by iameteore314** [comment]
Thanks for the clarification
