### ISSUE TITLE
Learning Latent Variables

### ISSUE THREAD

**Issue by Jeffalltogether** [pgmpy/pgmpy#1692]
### Subject of the issue
I am working on the Alarm Model example where latent variables are created for `["HYPOVOLEMIA", "LVEDVOLUME", "STROKEVOLUME"]`

After following the example code and checking the cpds of the latent variables, I found they are all uniform [0.5, 0.5] for all states of the latent variables.

Here's the code:

```
from pgmpy.estimators import ExpectationMaximization as EM
from pgmpy.models import BayesianNetwork

# Define a model structure with latent variables
model_latent = BayesianNetwork(
    ebunch=alarm_model.edges(), latents=["HYPOVOLEMIA", "LVEDVOLUME", "STROKEVOLUME"]
)

# Dataset for latent model which doesn't have values for the latent variables
samples_latent = samples.drop(model_latent.latents, axis=1)
samples_latent

model_latent.fit(samples_latent, estimator=EM)

print(model_latent.get_cpds('STROKEVOLUME'))
```

e.g.:
+----------------+-----+
| HYPOVOLEMIA(0) | 0.5 |
+----------------+-----+
| HYPOVOLEMIA(1) | 0.5 |
+----------------+-----+

The same thing occurs, where latent variables are always uniform, when I build latent variables into models with my own data.  

I am pretty green when it comes to this type of thing, but it seems as though there may be an issue with the implementation of latent variables?

Please advise.

Thank you!

### Your environment
* pgmpy version 0.1.19
* Python version 3.8.18
* Operating System MAC os 13.4.1 (c)

**Comment by ankurankan** [comment]
@Jeffalltogether This was a bug and is fixed now: cab08b1. This should work if you install the latest dev branch: https://pgmpy.org/started/install.html. The algorithm implementation is a bit slow; I am still working on some optimizations.

Dup #1542
