### ISSUE TITLE
how to make inference using Gibbs or bayesian model sampling

### ISSUE THREAD

**Issue by hjyoon93** [pgmpy/pgmpy#1704]
After sampling using Gibbs or bayesian model sampling, how am I supposed to use these sampled data to make approximate inference?

After gaining sampled data using below codes, how to make inference using Gibbs or bayesian model sampling?

from pgmpy.factors.discrete import TabularCPD
>>> from pgmpy.models import BayesianNetwork
>>> intel_cpd = TabularCPD('intel', 2, [[0.7], [0.3]])
>>> sat_cpd = TabularCPD('sat', 2, [[0.95, 0.2], [0.05, 0.8]], evidence=['intel'], evidence_card=[2])
>>> student = BayesianNetwork()
>>> student.add_nodes_from(['intel', 'sat'])
>>> student.add_edge('intel', 'sat')
>>> student.add_cpds(intel_cpd, sat_cpd)
>>> from pgmpy.sampling import GibbsSampling
>>> gibbs_chain = GibbsSampling(student)
>>> gibbs_chain.sample(size=3)

**Comment by ankurankan** [comment]
@hjyoon93 Sorry for the late reply. You can directly use the `ApproximateInference` class (https://pgmpy.org/approx_infer/approx_infer.html)  that should automatically generate samples and give you the probability values for the query. This does not support Gibbs Sampling yet though.

**Comment by hjyoon93** [comment]
Thanks for getting back to me. But instead of using [Approximate Inference Using Sampling](https://pgmpy.org/approx_infer/approx_infer.html), how do I make inference using Gibbs Sampling or bayesian model sampling?

**Comment by ankurankan** [comment]
@hjyoon93 The ApproxInference class internally uses the BayesianModelSampling class to generate samples under various conditions and then computes the probabilities. If you would like to manually do this, you can have a look at the code of ApproxInference (https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/inference/ApproxInference.py) to get an idea of how to do this. In short, depending on the query, we do operations on the generated samples to compute the probabilities. 

The GibbsSampling class can not be used for all kinds of queries yet (specifically queries with evidence) as the class doesn't currently have the feature to generate samples under some given evidence.

**Comment by hjyoon93** [comment]
Hi, thanks for getting back to me.

Then can I think of ApproxInference as using BayesianModelingSampling to make inference then?

In other words, If I wanted to make inference using BayesianModelingSampling, I can simply use ApproxInference?

Thank you.

**Comment by hjyoon93** [comment]
Also I don't see a name class named "BayesianModelSampling" inside ApproxInference code. where in the code does it use bayesianmodelsampling?

**Comment by ankurankan** [comment]
@hjyoon93 

> In other words, If I wanted to make inference using BayesianModelingSampling, I can simply use ApproxInference?

Yes, exactly.

> Also I don't see a name class named "BayesianModelSampling" inside ApproxInference code. where in the code does it use bayesianmodelsampling?

The method calls the simulate method here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/inference/ApproxInference.py#L174 . The simulate method here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/models/BayesianNetwork.py#L1144 then calls the BayesianModelSampling class.
