### ISSUE TITLE
CausalInference get_minimal_adjustment_set fails with ValueError: not found in model

### ISSUE THREAD

**Issue by gweesip** [pgmpy/pgmpy#1710]
### Subject of the issue
`get_minimal_adjustment_set` doesn't work with models that include variables that are not single letters (e.g., `'X_y'`).

### Your environment
* pgmpy version 0.1.24
* Python version 3.8.10
* Operating System Ubuntu 20.04

### Steps to reproduce
``` python
from pgmpy.models import BayesianNetwork
from pgmpy.inference import CausalInference

dag = BayesianNetwork([("X_1", "X_2"), ("Z", "X_1"), ("Z", "X_2")])
infer = CausalInference(dag)
infer.get_minimal_adjustment_set(X="X", Y="Y")
```
> Traceback ...
> File "... CausalInference.py", line 513, in get_minimal_adjustment_set
> File "... CausalInference.py", line 433, in get_proper_backdoor_graph
> ValueError: X not found in the model

### Expected behaviour
Should return an adjustment set, or `None` if no adjustment is possible

### Actual behaviour
Raises ValueError when verifying that variables of interest are in the model

### Root cause
`CausalInference.get_minimal_adjustment_set` expects `str` inputs for X and Y and assumes that all variable names are single letters. The variables names get passed directly to  `get_proper_backdoor_graph` which expects `list (array-like)`. Variables with complex names (e.g., 'X_y', 'Word') get broken into individual letters when passed through `chain`, so `get_proper_backdoor_graph` searches the model for variables that don't exists (e.g., X='X_y' gives 'X' not found in model, or '_' not found in model if there is actually an X in the model as well)

### Related
`get_minimal_adjustment_set` docs in code doesn't have example. Docs on pgmpy.org has outdated example that fails (missing `infer = CausalInference(dag)` step in example provided above).

**Comment by ankurankan** [comment]
@gweesip Thanks a lot for reporting this, this indeed is a bug. Let me know if you would like to open a PR to fix it. Thanks :)

**Comment by gweesip** [comment]
Sure. Should be pretty straightforward and give me a good intro to the process! Thanks!

**Comment by gweesip** [comment]
First time contributing to a project like this, so if I did anything wrong, please let me know!

**Comment by utkarshani** [comment]
@ankurankan @gweesip 
the changes are not reflected in the package. I re-install the package and I am getting the same error. Please help.

**Comment by ankurankan** [comment]
@utkarshani This seems to be working fine for me. Would it be possible to share your code so that I can reproduce the error that you are getting? 
Also, in case you are trying to run the example in the first comment, the example is incorrect; it will throw an error.
