### ISSUE TITLE
Update Initial CPT Using EM Algorithm

### ISSUE THREAD

**Issue by John-Almardeny** [pgmpy/pgmpy#1714]
I have been trying to achieve this with your library, but no luck so far :(

```
import pandas as pd
from pgmpy.factors.discrete.CPD import TabularCPD
from pgmpy.models import BayesianNetwork

model = BayesianNetwork([('X1', 'Y'), ('X2', 'Y')])
cpd = TabularCPD('Y', 2, [[0.1, 0.1, 0.1, 0.1],
                          [0.9, 0.9, 0.9, 0.9]],
                 evidence=['X1', 'X2'], evidence_card=[2, 2],
                 state_names={'Y': ['0', '1'],
                              'X1': ['0', '1'],
                              'X2': ['0', '1']})
cpd_x1 = TabularCPD(variable='X1', variable_card=2, values=[[0.5], [0.5]], state_names={'Y': ['0', '1'],
                                                                                        'X1': ['0', '1'],
                                                                                        'X2': ['0', '1']})
cpd_x2 = TabularCPD(variable='X2', variable_card=2, values=[[0.5], [0.5]], state_names={'Y': ['0', '1'],
                                                                                        'X1': ['0', '1'],
                                                                                        'X2': ['0', '1']})
model.add_cpds(cpd_x1)
model.add_cpds(cpd_x2)
model.add_cpds(cpd)

model.check_model()
# Print the model to verify the CPT
for cpd in model.get_cpds():
    print(cpd)

+------+-------+-------+-------+-------+
| X1   | X1(0) | X1(0) | X1(1) | X1(1) |
+------+-------+-------+-------+-------+
| X2   | X2(0) | X2(1) | X2(0) | X2(1) |
+------+-------+-------+-------+-------+
| Y(0) | 0.1   | 0.1   | 0.1   | 0.1   |
+------+-------+-------+-------+-------+
| Y(1) | 0.9   | 0.9   | 0.9   | 0.9   |
+------+-------+-------+-------+-------+

```

I will provide data (i.e. evidence) later to the model, but I want the model not to start from scratch (as it does when I call the `fit` method) but rather to consider the initial CPT I provided for `Y` and start from there (i.e. update it).
 
I want to use the Expectation-Maximization Algorithm for that. 

Is there any way to achieve this? Your help is very appreciated!

**Comment by John-Almardeny** [comment]
Is this library not supported anymore?!

**Comment by ankurankan** [comment]
@John-Almardeny Sorry for the late reply, I was taking a break :D. With the current EM algorithm, specifying an initial CPD is not possible. But it should be fairly easy to implement, I will try to do that in next couple of days. I am not exactly sure about your usecase, and specifying an initial CPD for the EM algorithm might not have any effect on the final learned CPDs i.e. the algorithm would try to still find MLE estimate for the new dataset.

Another option could be BayesianNetwork.fit_update method that updates an existing BN's CPDs with new data.

**Comment by John-Almardeny** [comment]
> @John-Almardeny Sorry for the late reply, I was taking a break :D. With the current EM algorithm, specifying an initial CPD is not possible. But it should be fairly easy to implement, I will try to do that in next couple of days. I am not exactly sure about your usecase, and specifying an initial CPD for the EM algorithm might not have any effect on the final learned CPDs i.e. the algorithm would try to still find MLE estimate for the new dataset.
> 
> Another option could be BayesianNetwork.fit_update method that updates an existing BN's CPDs with new data.

Thanks for your reply. I want to use `fit_update` but with the `EM-algorithm`. It's based on the instruction of the research paper I am implementing using your library:

"_Using the EM-algorithm the prior BPN was updated to the posterior BPN based on observations of the risk indicating variables and response variables being recorded in so-called contingency tables which were established using the information of the development dataset. The parameter learning was performed assuming a value for the experience factor for the EM-algorithm of 0.1 which gives almost no weight to the prior information and hence, the posterior distribution represents essentially the observed data._"

**Comment by ankurankan** [comment]
@John-Almardeny Would it be possible to share the reference for this paper? I am not able to really understand what specifying the prior values for the CPDs acheive in the EM algorithm. My understanding is that if the likelihood function has multiple maximas, the prior could possilbly help in selecting/guiding to a specific one. Whereas the random initial CPD would randomly converge to one of the maximas.

**Comment by John-Almardeny** [comment]
> @John-Almardeny Would it be possible to share the reference for this paper? I am not able to really understand what specifying the prior values for the CPDs acheive in the EM algorithm. My understanding is that if the likelihood function has multiple maximas, the prior could possilbly help in selecting/guiding to a specific one. Whereas the random initial CPD would randomly converge to one of the maximas.

[Prediction of road accidents: A Bayesian hierarchical approach paper](https://www.sciencedirect.com/science/article/pii/S0001457512004101) - page 286
