### ISSUE TITLE
Questions about the Prior BPN

### ISSUE THREAD

**Issue by John-Almardeny** [pgmpy/pgmpy#1719]
I have a few questions, please:

**1. How is the initial CPT filled before training with the dataset?**

**2. Does the initial CPT represent the "Prior Bayesian Probability Network (BPN)? If so, do you know if we fill it out manually?**

Looking forward to hearing from you,
Cheers!

**Comment by ankurankan** [comment]
@John-Almardeny 
1. Currently, for any variable in the model, if the variable + variables' parents are all observed, the CPT is computed using the Maximum Likelihood Estimator. If any of them are latent, the CPT is initialized randomly.
2. I am assuming that BPN are simply Bayesian Networks representing prior knowledge. If that is the case, the EM algorithm does start with a BPN. Unfortunately, in the current implementation, we can not fill out the BPN's CPTs manually. But as I had mentioned, the currently implementation can be modified easily to accomodate that. If BPN is defined as something else, could you please tell me how it is defined, or share some reference for it?

**Comment by John-Almardeny** [comment]
> @John-Almardeny
> 
> 1. Currently, for any variable in the model, if the variable + variables' parents are all observed, the CPT is computed using the Maximum Likelihood Estimator. If any of them are latent, the CPT is initialized randomly.
> 2. I am assuming that BPN are simply Bayesian Networks representing prior knowledge. If that is the case, the EM algorithm does start with a BPN. Unfortunately, in the current implementation, we can not fill out the BPN's CPTs manually. But as I had mentioned, the currently implementation can be modified easily to accomodate that. If BPN is defined as something else, could you please tell me how it is defined, or share some reference for it?

Thanks very much for the reply.

I was asking, in general, if the "Prior Bayesian Network" is considered or worked on initially before training with data.

The problem is the paper I am working on [Prediction of road accidents: A Bayesian hierarchical approach paper](https://www.sciencedirect.com/science/article/pii/S0001457512004101) - page 286, mentions "Monte Carlo Simulations" to "fill" the Prior Bayesian Network. My colleague at work, however, said I don't need to work with any Prior; just go ahead and fit the data.

I am so confused because, in the paper, they use Monte Carlo Simulations for sure to get the "States" of each of the Target Node (i.e. the response variable in the network), but we are unsure whether they fill the CPTs initially with the results from Monte Carlo Simulations as a "Prior" then fit the model with data using the EM algorithm, or they do the latter immediately without any Prior. We sent the author of the paper many times; he saw the messages, but ironically, he did not respond to any!

Your opinion is very much appreciated!

**Comment by ankurankan** [comment]
@John-Almardeny Thanks for sharing the paper, I had a very quick look at it and I am still not sure about their motivation behind using this specific methodology. But I think you are correct about them initializing their network with CPTs computed using the regression model which they call Prior Bayesian Network (PBN). I also couldn't find any details on how exactly they learn the CPTs of these PBN. They cannot use a simple Maximum Likelihood Estimator as there are latent variables in the model. So, I think I am misunderstanding what the PBN is, and maybe the PBN and the final BN with latents are two different models? 

To recreate this methodology with pgmpy, I think we will need to specify the prior CPTs for the EM algorithm. This prior would be estimated somehow from the regression model. I still need to make the changes in the EM algorithm code such that it can accept user-defined intial CPTs.

**Comment by ankurankan** [comment]
@John-Almardeny The changes for specifying prior CPTs are in the dev branch now. You can install it using: `pip install git+https://github.com/pgmpy/pgmpy.git@dev`. Here's an example on how to use it:

```python
# Create a latent model and simulate some data.
In [1]: from pgmpy.utils import get_example_model       
In [2]: model = get_example_model('cancer')                                            
In [3]: from pgmpy.models import BayesianNetwork        
In [4]: model_latent = BayesianNetwork(model.edges(), latents={'Smoker'})                                                                                       
In [6]: model_latent.add_cpds(*model.cpds)                                             
In [7]: data = model_latent.simulate(int(1e4))  

# Use the simulated data to learn the network parameters.
In [9]: from pgmpy.estimators import ExpectationMaximization as EM
In [10]: est = EM(model_latent, data)
In [11]: from pgmpy.factors.discrete import DiscreteFactor
In [13]: smoker_init = TabularCPD('Smoker', 2, [[0.1], [0.9]], state_names={'Smoker': ["True", "False"]})
In [14]: cpds = est.get_parameters(seed=42, init_cpds={'Smoker': smoker_init})
In [15]: cpds
Out[15]: 
[<TabularCPD representing P(Xray:2 | Cancer:2) at 0x7ff27f9b83a0>,
 <TabularCPD representing P(Pollution:2) at 0x7ff27f9b8550>,
 <TabularCPD representing P(Dyspnoea:2 | Cancer:2) at 0x7ff29b6f0970>,
 <TabularCPD representing P(Smoker:2) at 0x7ff27fae8640>,
 <TabularCPD representing P(Cancer:2 | Pollution:2, Smoker:2) at 0x7ff27f9b8400>]

In [17]: print(cpds[-2])
+-----------+----------+
| Smoker(0) | 0.123153 |
+-----------+----------+
| Smoker(1) | 0.876847 |
+-----------+----------+

```

**Comment by John-Almardeny** [comment]
> @John-Almardeny The changes for specifying prior CPTs are in the dev branch now. You can install it using: `pip install git+https://github.com/pgmpy/pgmpy.git@dev`. Here's an example on how to use it:
> 
> ```python
> # Create a latent model and simulate some data.
> In [1]: from pgmpy.utils import get_example_model       
> In [2]: model = get_example_model('cancer')                                            
> In [3]: from pgmpy.models import BayesianNetwork        
> In [4]: model_latent = BayesianNetwork(model.edges(), latents={'Smoker'})                                                                                       
> In [6]: model_latent.add_cpds(*model.cpds)                                             
> In [7]: data = model_latent.simulate(int(1e4))  
> 
> # Use the simulated data to learn the network parameters.
> In [9]: from pgmpy.estimators import ExpectationMaximization as EM
> In [10]: est = EM(model_latent, data)
> In [11]: from pgmpy.factors.discrete import DiscreteFactor
> In [13]: smoker_init = TabularCPD('Smoker', 2, [[0.1], [0.9]], state_names={'Smoker': ["True", "False"]})
> In [14]: cpds = est.get_parameters(seed=42, init_cpds={'Smoker': smoker_init})
> In [15]: cpds
> Out[15]: 
> [<TabularCPD representing P(Xray:2 | Cancer:2) at 0x7ff27f9b83a0>,
>  <TabularCPD representing P(Pollution:2) at 0x7ff27f9b8550>,
>  <TabularCPD representing P(Dyspnoea:2 | Cancer:2) at 0x7ff29b6f0970>,
>  <TabularCPD representing P(Smoker:2) at 0x7ff27fae8640>,
>  <TabularCPD representing P(Cancer:2 | Pollution:2, Smoker:2) at 0x7ff27f9b8400>]
> 
> In [17]: print(cpds[-2])
> +-----------+----------+
> | Smoker(0) | 0.123153 |
> +-----------+----------+
> | Smoker(1) | 0.876847 |
> +-----------+----------+
> ```

Thanks very much.

Can I use it with `fit_update` ?

**Comment by ankurankan** [comment]
@John-Almardeny No, you can't use it with `fit_update`. The idea behind the `fit_update` method is to update the CPTs of the models with new data. In your case, we want to initialize the EM algorithm with predefined CPDs. For that, you would need to first define `TabularCPD` objects representing the Prior BN CPTs (for example `smoker_init` in the above example). Then you can use the EM algorithm passing the defined prior CPTs as `init_cpds` argument in `EM.get_parameters`.

**Comment by ebraun19** [comment]
Hi! First of all, a big thanks for this question and the quick implementation! I also was looking for this, so this is amazing. 
I have one small question about it. I am learning the parameters through data and have no other cpds than the initial_cpds called 'other' that I defined like this: 
prior_other = TabularCPD('Other', 2, [[0.9], [0.1]])
I learn the CPDS by the get_parameters function

The node 'other' has 4 parents and for the combinations of the options of the parents that are not present in the data, the learned cpds for my node 'other' has the distribution: 
'other'== 0 --> 0.5
'other'==1 --> 0.5

While I expected it to be :
'other'== 0 --> 0.9
'other'==1 --> 0.1 

Do you know why this is the case? And why the prior is not used in case of the combinations of variables that are not in de data so cannot be learned?

**Comment by ankurankan** [comment]
@ebraun19 If the node other has 4 parents you would need to specify that in the prior CPD. Have a look at the example here to see an example of how to define a CPD when parents are present: https://pgmpy.org/factors/discrete.html#pgmpy.factors.discrete.CPD.TabularCPD

**Comment by John-Almardeny** [comment]
> @John-Almardeny No, you can't use it with `fit_update`. The idea behind the `fit_update` method is to update the CPTs of the models with new data. In your case, we want to initialize the EM algorithm with predefined CPDs. For that, you would need to first define `TabularCPD` objects representing the Prior BN CPTs (for example `smoker_init` in the above example). Then you can use the EM algorithm passing the defined prior CPTs as `init_cpds` argument in `EM.get_parameters`.

Thanks for this @ankurankan 

I have a simple yet important last question.
What if there are new states or variables in the new data that did not exist in the `init_cpds`? Would that ruin the method?

This is the example I am working on that mimics the `fit_update` using the `EM` algorithm based on your work.


```
dataset = pd.read_csv(...)
states = {...}
bn_structure = [...]
batch_size = 100_000
cpds = {}
for i in range(0, len(dataset)):
    if i * batch_size >= len(dataset):
        break
    batch = dataset[i * batch_size: (i + 1) * batch_size]
    est = ExpectationMaximization(BayesianNetwork(bn_structure), batch, state_names=states)
    cpds = est.get_parameters(init_cpds={} if i == 0 else {cpd.variable: cpd for cpd in cpds})
```

Shall the `cpds` variable now  contain the final CPDs as if I used the model.fit(dataset, estimator=ExpectationMaximization) function on the entire dataset?

-----------------

Update:
--------

I tried the above code with a dataset after splitting it into two equal batches as a first model, then tried to fit the dataset as a whole using the `ExpectationMaximization` estimator in one go as a second model (i.e. the usual way).

The predictions of the two models are quite different, in which only the second model is predicting correctly.

So, empirically, there seems to be a bug in the implementation.

**Comment by ankurankan** [comment]
@John-Almardeny Sorry for the late reply. I think that is the expected behavior. In the case where you are splitting the dataset, you are essentially fitting the model to just the second half of the data. Specifying the prior only gives a starting point for the optimizer but it would still maximize the expectation of the data provided (i.e. the second half). Could you maybe help me understand what exactly are you trying to acheive with the Prior BNs, I might be able to help a bit better?

**Comment by John-Almardeny** [comment]
> @John-Almardeny Sorry for the late reply. I think that is the expected behavior. In the case where you are splitting the dataset, you are essentially fitting the model to just the second half of the data. Specifying the prior only gives a starting point for the optimizer but it would still maximize the expectation of the data provided (i.e. the second half). Could you maybe help me understand what exactly are you trying to acheive with the Prior BNs, I might be able to help a bit better?

Just trying to mimic `fit_update` using the `EM` algorithm, where I use the CPDs resulting from fitting `EM` in the previous iteration as `init_cpds` in the subsequent iteration. Of course, each iteration works on a batch of the dataset. Exactly as it's shown in the example I provided above.

The reason is that `pgmpy` is super slow when the dataset dimensionality is big as CPT space size expands exponentially. So, it can take up to many days to finish training.

But with the change in #1730, I can handle big data. I'm really looking forward to your PR for #1730. 

But regarding this, no problem, I gotchya!

Closing this issue.

**Comment by John-Almardeny** [comment]
> @John-Almardeny Sorry for the late reply. I think that is the expected behavior. In the case where you are splitting the dataset, you are essentially fitting the model to just the second half of the data. Specifying the prior only gives a starting point for the optimizer but it would still maximize the expectation of the data provided (i.e. the second half). Could you maybe help me understand what exactly are you trying to acheive with the Prior BNs, I might be able to help a bit better?

Just trying to mimic `fit_update` using the `EM` algorithm, where I use the CPDs resulting from fitting `EM` in the previous iteration as `init_cpds` in the subsequent iteration. Of course, each iteration works on a batch of the dataset. Exactly as it's shown in the example I provided above.

The reason is that `pgmpy` is super slow when the dataset dimensionality is big as CPT space size expands exponentially. So, it can take up to many days to finish training.

But with the change in #1730, I can handle big data. I'm really looking forward to your PR for #1730. 

But regarding this, no problem, I gotchya!

Closing this issue.
