### ISSUE TITLE
`fit_update()` Warning

### ISSUE THREAD

**Issue by John-Almardeny** [pgmpy/pgmpy#1728]
I have a smiple trained model where I use `fit_update()` function to update its parameters.

However, I am getting this warning which does not make sense. Did the developer mean `Updating` by saying `Replacing` ?

```
WARNING:pgmpy:Replacing existing CPD for x1
WARNING:pgmpy:Replacing existing CPD for x2
WARNING:pgmpy:Replacing existing CPD for x3
```

**Comment by ankurankan** [comment]
@John-Almardeny This is a side effect of calling the `add_cpds` method in the `fit_update` method. The `add_cpds` method warns the user if they try to add a CPD for a variable that already has a CPD. I agree that the warning message should be clearer.

**Comment by John-Almardeny** [comment]
> WARNING:pgmpy:Replacing existing CPD for x1

Alright, so the warning should be something like:

`WARNING:pgmpy: Updating existing CPD for x1`

**Comment by ankurankan** [comment]
I would rather just suppress the warning in this case as it is already clear from the fit_update method that it will update the parameters.
