### ISSUE TITLE
FactorGraph message passing

### ISSUE THREAD

**Issue by tillwenke** [pgmpy/pgmpy#1757]
### Subject of the issue
The are various things that I was wondering about when starting to use the message passing algorighm for FactorGraph

- [ ] BeliefPropagationWithMessageParsing shoud be called ...MessagePassing
- [ ] is not listed in the doc https://pgmpy.org/exact_infer/bp.html

### Your environment
* 0.1.25

**Comment by ankurankan** [comment]
@tillwenke Thanks for creating the issue.
> BeliefPropagationWithMessageParsing shoud be called ...MessagePassing

Yes, that is definitely a typo.

> not listed in the doc https://pgmpy.org/exact_infer/bp.html

I think we missed to add it to the documentation in the last release.

If you would like please feel free to create PR fixing these, else I will fix it ASAP.

**Comment by tillwenke** [comment]
I ll do it.
