### ISSUE TITLE
Add continuous variable models to examples

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#1787]
The `pgmpy.utils.get_example_model` function is able to load discrete variable models from the bnlearn repository: https://www.bnlearn.com/bnrepository/. However, loading the Gaussian Bayesian Networks is not supported yet. Add support for continuous variables as well.

**Comment by B3CODER** [comment]
I want to make a contribution.

**Comment by ankurankan** [comment]
The continuous variable models on the bnlearn repository are in rds format, so we can't directly read them in Python. I would suggest writing an R script that can export the required information from these objects into a file that is readable in Python. Then expand the `get_example_model` function to be able to read that file and create a Linear Gaussian Bayesian Network object.

**Comment by B3CODER** [comment]
i read this from https://www.bnlearn.com/bnrepository/gaussian-medium.html - [RDS (bn.fit)](https://www.bnlearn.com/bnrepository/ecoli70/ecoli70.rds) and write a script but what type of information we require to extract ?

**Comment by B3CODER** [comment]
I wrote a script and extracted data into .json format.

**Comment by ankurankan** [comment]
> i read this from https://www.bnlearn.com/bnrepository/gaussian-medium.html - [RDS (bn.fit)](https://www.bnlearn.com/bnrepository/ecoli70/ecoli70.rds) and write a script but what type of information we require to extract ?

You would need the information for defining the network structure and the Linear Gaussian CPD for each of the variables.

**Comment by jihyeseo** [comment]
@B3CODER Do you still have the script to convert RDS/RDA files to json? I need it for https://github.com/pgmpy/pgmpy/issues/1921. Thanks a lot!
