### ISSUE TITLE
LinearGaussianBayesianNetwork functions are implemented but not available in the source code of Release v0.1.25 

### ISSUE THREAD

**Issue by bbkjunior** [pgmpy/pgmpy#1796]
### Subject of the issue
I was really waiting for continuous variables support and was very happy to see that implemented. But after several attempts of pip install and reinstall, I found out that LinearGaussianBayesianNetwork.py has obviously not been updated in the source code of the latest version. So all newly implemented methods return NotImplementedError

### Your environment
* pgmpy version - 0.1.25
* Python version - 3.11.9

### Steps to reproduce
Install the last pgmpy version
Run the code from the function comment available in the line https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/models/LinearGaussianBayesianNetwork.py#L311

### Expected behaviour
I expect the function to work

### Actual behaviour
But it returns NotImplementedError. Obviously, because the file in the source code is not updated

**Comment by ankurankan** [comment]
@bbkjunior Did you install the version from pypi? The new Linear Gaussian BN features haven't been released yet, however you can install the github branch to use it: `pip install git+https://github.com/pgmpy/pgmpy.git@dev`

**Comment by bbkjunior** [comment]
I used `pip install pgmpy`
Ok, I will do like you recommend for now
