### ISSUE TITLE
change name of a node

### ISSUE THREAD

**Issue by jacowp357** [pgmpy/pgmpy#1811]
This is not really an issue. but I would like to know how a node's name can be changed.

For example,

I have a node in a Bayesian network called "A" and I would like to change its name to "newA" but keep all its other attributes the same.

**Comment by ankurankan** [comment]
@jacowp357 I don't see an easy way to change the node names in an already defined model. A super hackish way that I can think of would be to export the model to a file and use any text editor to replace the variable name everywhere, and then read it back. Something like:
```python
In [7]: from pgmpy.models import BayesianNetwork

In [8]: from pgmpy.utils import get_example_model

In [9]: model = get_example_model('alarm')

In [10]: model.save('alarm.bif')

# Replace HISTORY  with NEW_HISTORY in alarm.bif

In [11]: new_model = BayesianNetwork.load('alarm.bif')
Out[11]: <pgmpy.models.BayesianNetwork.BayesianNetwork at 0x73092e1ea420>

In [13]: 'NEW_HISTORY' in new_model.nodes()
Out[13]: True

In [14]: new_model.get_cpds('NEW_HISTORY')
Out[14]: <TabularCPD representing P(NEW_HISTORY:2 | LVFAILURE:2) at 0x73092a0eca70>

```

**Comment by jacowp357** [comment]
Thanks @ankurankan!
