### ISSUE TITLE
Using get_random with BayesianNetwork gives error when passing node_names parameter

### ISSUE THREAD

**Issue by kollisaisiddartha** [pgmpy/pgmpy#1832]
### Subject of the issue : Using get_random with BayesianNetwork gives error when passing node_names parameter as an argument.
Describe your issue here.
When creating model with BayesianNetwork, getting error as **got an unexpected keyword argument 'node_names'** when passing node_names as argument even though it is one of the parameter from the module.

### Your environment
* pgmpy version : 0.1.26
* Python version : 3.12.3
* Operating System : Windows 11

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

```
from pgmpy.models import BayesianNetwork
model = BayesianNetwork.get_random(n_nodes=10, edge_prob=0.3, latents=False, node_names=None)
print(model)
```

### Expected behaviour
BayesianNetwork with 10 nodes and 19 edges

### Actual behaviour
**TypeError:** BayesianNetwork.get_random() got an unexpected keyword argument 'node_names'

**Comment by ankurankan** [comment]
@kollisaisiddartha This works fine for me on the dev branch:
```python
In [1]: from pgmpy.models import BayesianNetwork
   ...: model = BayesianNetwork.get_random(n_nodes=10, edge_prob=0.3, latents=False, node_names=None)
   ...: print(model)
BayesianNetwork with 10 nodes and 17 edges

In [2]: from pgmpy.models import BayesianNetwork
   ...: model = BayesianNetwork.get_random(n_nodes=10, edge_prob=0.3, latents=False, node_names=None)
   ...: print(model)
BayesianNetwork with 10 nodes and 13 edges

In [3]: model
Out[3]: <pgmpy.models.BayesianNetwork.BayesianNetwork at 0x7b9c565813a0>
```
Any chance there are some local changes in your codebase because of which you are getting the error?

Edit: If you are using pgmpy installed using pip, you will get this error. The `node_names` in the argument has not released yet, so you would need to install the dev branch from GitHub to use it: https://pgmpy.org/started/install.html

**Comment by kollisaisiddartha** [comment]
Ok thank you
