### ISSUE TITLE
seed argument not available in DAG get_random module

### ISSUE THREAD

**Issue by kollisaisiddartha** [pgmpy/pgmpy#1837]
### Subject of the issue
Describe your issue here.
In `DAG.get_random()` seed argument is not available. Due to which each time random values maybe generated.

### Your environment
* pgmpy version 0.1.26
* Python version 3.12
* Operating System Windows 11

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ankurankan** [comment]
Fixed.
