### ISSUE TITLE
Learn bayesian network from data with fixed target

### ISSUE THREAD

**Issue by ivan-marroquin** [pgmpy/pgmpy#1876]
### Subject of the issue
Thanks for such great package!

I have a DataFrame with 7 features and 1 target. All data are continuous values. I would like to know if it is possible to learn a Bayesian network from data by searching how the 7 features relate to the target. 

I read the documentation about structure learning to estimate a DAG. It seems to be the answer to my question. However, I can't figure out how to limit the search space to only find the DAGs showing how the features are associated with the target.

Thanks for your help,
Ivan

### Your environment
* pgmpy version: 0.1.26
* Python version: 3.9.10
* Operating System: Ubuntu 22.04

**Comment by ankurankan** [comment]
@ivan-marroquin I am unsure if I understand the structure you are trying to learn. In the estimated DAG, do you want to constraint the structure learning to only edges from the feature variables to the target variable. Or once you have learned the structure, you want to extract the parents of the target feature?

**Comment by ivan-marroquin** [comment]
Hi @ankurankan ,

Thanks for the prompt reply. As you pointed out, I would like to do as you say:
1) Constraint the structure learning to only edges from the feature variables to the target variable
2) Once the best structure is found, extract the parents (and children) of the target feature

Thanks
Ivan

**Comment by ankurankan** [comment]
@ivan-marroquin I don't think you need structure learning in this case then. Depending on what you want to do with this model, 1) If you plan to do inference on it, I would suggest just manually creating a model with edges: Feature1 -> target, Feature2 -> target, ... The parameter learning and inference would automatically take care of the strength between each of the features and the target. 2) If you are using it for some kind of feature selection, you can simply look at the correlation coefficient between each feature and target, and select the features that have a correlation coefficient above some threshold.

**Comment by ivan-marroquin** [comment]
@ankurankan Thanks for the suggestions. I will compare the output from the parameter learning against the structure learning using the PC algorithm. As I think, the PC algorithm can tell me how the target and features relate to each other
