### ISSUE TITLE
how plot the weights of a DAG?

### ISSUE THREAD

**Issue by ivan-marroquin** [pgmpy/pgmpy#1880]
### Subject of the issue
I have a data set from which I capture the dependencies between the variables with this code:

 model= BayesianModel([('TEMP', 'RAIN'), ('TEMP', 'WIND'), 
                          ('TEMP', 'FFMC'), ('TEMP', 'DMC'), ('TEMP', 'DC'),  
                          ('TEMP', 'RH'), ('TEMP', 'AREA'), 
                          ('RAIN', 'FFMC'), ('RAIN', 'DMC'), ('RAIN', 'DC'), 
                          ('RAIN', 'RH'), ('RAIN', 'AREA'), 
                          ('WIND', 'AREA'), ('WIND', 'ISI'),
                          ('FFMC', 'AREA'), ('DMC', 'AREA'), ('DC', 'AREA'), ('ISI', 'AREA'),
                          ('RH', 'AREA')])
model.fit(data= efd_5_features_df, estimator= BayesianEstimator, prior_type= 'BDeu',
              equivalent_sample_size= 10, n_jobs= -1)

Then, I generate a graph plot as follows, were the 'node_colors' is used to assign a particular code to the nodes:
 
nx.draw_circular(model, with_labels= True, arrowsize= 30, node_size= 1200, 
                         node_color= node_colors, edge_color= 'black', alpha= 0.7, 
                         font_weight= "bold")

I get the plot as shown in the attached file.

My question is: can I get the weights of the edges? Although all nodes point to the node "area". I would like to plot them in the graph to show that not all the links denote a strong connection.

I used this code to get the weights, but the returned value is None
for u, v, data in model.edges(data= True):
        print(f"Edge ({u}, {v}: {model.get_edge_data(u,v)})")

Thanks for your help

### Your environment
* pgmpy version: 0.1.26
* Python version: 3.9.10
* Operating System: Ubuntu 22.04
![Bayesian_parametersearch](https://github.com/user-attachments/assets/25d317a3-633a-4a58-8cda-0551975221c6)

**Comment by ankurankan** [comment]
@ivan-marroquin Because the variables here are discrete, there is no straightforward way to define edge weight using a single value. A workaround is using canonical correlations. Here's an example using the alarm network.
```python
In [7]: from pgmpy.utils import get_example_model

In [8]: model = get_example_model('alarm')

In [9]: df = model.simulate(1000)
Generating for node: BP:   0%|                                                                                                                                         | 0/37 [00:00<?, ?it/s]WARNING:pgmpy:Probability values don't exactly sum to 1. Differ by: -2.220446049250313e-16. Adjusting values.
Generating for node: BP: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:00<00:00, 714.30it/s]

In [10]: from pgmpy.estimators.CITests import pillai_trace
In [11]: for u, v in model.edges():
    ...:     u_parent = set(model.get_parents(u))
    ...:     v_parent = set(model.get_parents(v))
    ...:     cond_vars = u_parent.union(v_parent)
    ...:     print(f"Edge {u} -> {v} weight: {pillai_trace(X=u, Y=v, Z=cond_vars, data=df, boolean=False)[0]}")
    ...: 
Edge HYPOVOLEMIA -> LVEDVOLUME weight: 2.8810900939807843e-06
Edge HYPOVOLEMIA -> STROKEVOLUME weight: 6.5546008480529146e-06
Edge LVEDVOLUME -> CVP weight: 2.9986980925301876e-06
Edge LVEDVOLUME -> PCWP weight: 1.856005839558033e-05
Edge LVFAILURE -> HISTORY weight: 4.982297539629375e-09
Edge LVFAILURE -> LVEDVOLUME weight: 6.199002108034396e-06

```

**Comment by ivan-marroquin** [comment]
@ankurankan thanks for the suggestion. For some reason, the function pillai_trace is cannot be imported:

from pgmpy.estimators.CITests import pillai_trace
ImportError: cannot import name 'pillai_trace' from 'pgmpy.estimators.CITests' (/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/pgmpy/estimators/CITests.py)

It is not available in my installed version of pgmpy. The available function is "ci_pillai"

**Comment by ivan-marroquin** [comment]
just in case someone may be interested in adding the weights to the graph plot, I used this code

# compute the weights of the graph
weights= {}
    
for u, v in dag.edges():
        u_parent = set(dag.get_parents(u))
        v_parent = set(dag.get_parents(v))
        cond_vars = u_parent.union(v_parent)
        
        res= ci_pillai(X= u, Y= v, Z= cond_vars, data= data, boolean= False)[0]
        
        print(f"Edge {u} -> {v} weight: {res}")
        
        weights[u,v]= f"{res:.2e}"
    
nx.set_edge_attributes(dag, weights, 'weight')
    
# get list of nodes
nodes= dag.nodes()
    
# get list of Markov blanket for target
markov_bn= dag.get_markov_blanket(target_node)
        
# define color map
color_map= {}
    
for inode in nodes: 
        if inode == target_node:
            color_map[inode]= 'orange'
            
        elif inode not in markov_bn:
            color_map[inode]= 'turquoise'
            
        else:
            color_map[inode]= 'salmon'

# assign color to nodes based on color map
node_colors= [color_map[x] for x in nodes]
    
# get edge weights
edge_labels= nx.get_edge_attributes(dag, 'weight')
    
# draw network using a circular layout
pos= nx.circular_layout(dag)
    
nx.draw(dag, pos, with_labels= True, arrowsize= 30, node_size= 1200, 
            node_color= node_colors, edge_color= 'black', 
            alpha= 0.7, font_weight= "bold")
    
nx.draw_networkx_edge_labels(dag, pos, edge_labels= edge_labels, font_size= 10)
    
plt.savefig(filename, dpi= 600)

**Comment by ankurankan** [comment]
@ivan-marroquin The `pillai_trace` is the new name (hasn't been released yet) of `ci_pillai`. Another way to plot it (and looks a bit nicer in my opinion) is using graphviz:
```python
In [16]: from pgmpy.utils import get_example_model

In [17]: model = get_example_model('alarm')

In [18]: model_graphviz = model.to_graphviz()

In [19]: for u, v in model_graphviz.edges():
    ...:     edge = model_graphviz.get_edge(u, v)
    ...:     edge.attr['label'] = 'w' #Edge weights go here
    ...: 

In [20]: model_graphviz.draw('model.png', prog='dot')

```
![model](https://github.com/user-attachments/assets/e7a1b88f-bad8-4330-95a7-29fd8fef4896)

**Comment by ivan-marroquin** [comment]
Thank you for the suggestion!
