### ISSUE TITLE
Travis using python 2.7

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#204]
https://travis-ci.org/pgmpy/pgmpy/builds/33866645#L35

**Comment by abinashpanda** [comment]
`python --version` shows the version of python before setting up the virtual environment. You could see the logs after the virtual environment is set up. Just look for `source continous_integration/install.sh`, you will find that we are using `Python 3.4`. I think we should remove `python --version` before installation. This is very ambigous. Thanks for pointing that.
