### ISSUE TITLE
FInding out if Coursera inference engine is available

### ISSUE THREAD

**Issue by snigam3112** [pgmpy/pgmpy#22]

**Comment by abinashpanda** [comment]
In the programming assignment 3, they have provided an inference engine **<code>libDAI</code>  -  A free/open source C++ library for Discrete Approximate Inference**. (http://staff.science.uva.nl/~jmooij1/libDAI/), The source code for <code>libDAI</code> is also available with the assignment. 
<code>libDAI</code> has a python interface (implemented using SWIG) but that is an experimental one. So what I suggest that we can **use the C++ implementation of this engine** in our python project or we could **build our own inference engine** (programming assignment 7). Any suggestions?

**Comment by snigam3112** [comment]
I vote, that for the time being, we use the C++ library, since this is
technically in the "application" part of our project and not part of the
library per se.

Regards,
Shikhar Nigam
Fourth Year, B.Tech
IIT (BHU), Varanasi

**Comment by abinashpanda** [comment]
@snigam3112 Now we can go for C++ library. It is **not only used in "application" part of our project, but it would be part of our library also.**

**Comment by gargshashank5** [comment]
We can use the C++ library for scipy. After that we will write our own inference engine.
