### ISSUE TITLE
Use numpy arrays in the whole codebase.

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#227]
Mixing of numpy arrays and python lists in the codebase is causing problems because of their different behaviors. Therefore move everything to numpy arrays.

**Comment by jaidevd** [comment]
Any progress on this? Is someone working on this actively? This seems like a (relatively) low hanging fruit I can deal with.

**Comment by ankurankan** [comment]
@jaidevd Nobody is actively working on this right now. You can go ahead with this.

**Comment by alekdimi** [comment]
Has this been done or is there still code to be fixed?

**Comment by ankurankan** [comment]
@alekdimi Still needs to be fixed.

**Comment by ankurankan** [comment]
Completely switching to numpy arrays will have huge effect on performance. So closing this.
