### ISSUE TITLE
Add feature for storing the state name of the random variables.

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#232]
Currently we store the state names of a variables as `variable_0`, `variable_1` etc. But this can get confusing for a user so add the optional feature to add the states of the variables in a model and instead of showing `variable_0` or `variable_1`, display the actual names of the states.

**Comment by yashu-seth** [comment]
Please tell me if this is still open. Is someone working on this?

**Comment by ankurankan** [comment]
@yashu-seth Yes, this is still open. But this a fairly big change so will need a lot of work. 
The way I have thought of implementing this is to add the functionality to store state names to the `DirectedGraph` and `UndirectedGraph` classes. And then write a decorator, such that it replaces the state names from function arguments to the internal representation. And also to replace the internal state names returned by the methods to the actual state name.

**Comment by yashu-seth** [comment]
@ankurankan Can you please recommend an issue which would be relatively easy to handle and is still open.

**Comment by khalibartan** [comment]
@ankurankan Instead of replacing the internal architecture I think we can have a one to one mapping of variables name to the current way we are storing the things and whenever a query is raised, we can use this mapping to get to the internal representation . Also the current implementation has its own ease because user don't have to explicitly name the states. So we don't have to write two different implementations for this. We can run one above the other,

**Comment by yashu-seth** [comment]
+1 for @khalibartan 's suggestion. @ankurankan  What do you think about this?

**Comment by ankurankan** [comment]
@yashu-seth @khalibartan Yeah, even I want to keep this completely separate. I was thinking of a writing a decorator for this which would do all the mapping for the arguments passed to a method or returned result.

**Comment by khalibartan** [comment]
@ankurankan  Yeah cool. +1 Decorator will keep things much cleaner.

**Comment by yashu-seth** [comment]
@ankurankan I would like to work on this. 
From what I infer we will have to give an optional parameter that stores variable state names in Factor. Then we can have an attribute that stores a one to one mapping which could be used by the decorator that replaces state names to internal representation and vice versa.

**Comment by ankurankan** [comment]
@yashu-seth Sure go ahead. Yes, but I don't want any part of code related to state names in any of the existing classes. So, I would suggest you to come up with exact implementation details and discuss it before starting to writing code.

**Comment by yashu-seth** [comment]
@ankurankan Okay. Here is what I have planned.
I will add the functionality to store the state names in the base classes i.e. `UndirectedGraph` and `DirectedGraph` as a dictionary attribute, with nodes as keys and a list of state names for each node as values. Mapping would be the index number of each state name in the state names list for each key in the dictionary attribute.
Now, I will write a separate decorator for each method that involves work with state names. For cases when the state names are not provided, the decorators will simply return the original method, thus retaining the previous behavior. All the code involving state names would be kept in the decorators, thus keeping the previous classes unchanged.

**Comment by yashu-seth** [comment]
@ankurankan The decorators should be in the same file as their respective methods. Shouldn't they?

**Comment by khalibartan** [comment]
I believe we can have two things separate mapping , for nodes to state name I believe list of strings is better, and for state name to node, we can have a dictionary. And we can add in a argument whether user wants to define state name, depending upon the argument decorator can do mapping or not. This will also save time in updating docstrings, past API will remain in workable state. Also I don't find any issues in doing so.

**Comment by yashu-seth** [comment]
@khalibartan I have the following mapping implementation in mind.

Suppose the user wants to have 'easy', 'medium' and 'hard' states for the variable 'diff'. 
Then the base class will have a dictionary attribute with the following values - 

``` python
state_names = {'diff': ['easy', 'medium', 'hard']}
```

Now for mapping the state names to the previous numerical values I think we can use the index of each state in the list. This would save us from having two separate mappings.
Which means,
easy - 0
medium - 1
hard - 2

**Comment by khalibartan** [comment]
@yashu-seth  Yeah I was thinking of something like that. Or we can have something like
```
state_names = {'diff': {'easy':0, 'medium':1, 'hard':2}}
```
to get `diff_0` we can use `state_names['diff'].keys()[0]`
and to get  node value of `diff easy` we can use `state_names['diff']['easy']`

**Comment by yashu-seth** [comment]
@khalibartan Indexing won't work directly on `state_names['diff'].keys()`, it has to be converted to an iterable. 
Both the methods would take O(n) in one case and O(1) in the other with respect to the cardinality of the variable. If we want O(1) for both, then maybe we can have two separate dictionaries.

**Comment by khalibartan** [comment]
@yashu-seth My bad, I just forgot it, and also it would be unordered too in python2.

**Comment by yashu-seth** [comment]
@ankurankan Should I proceed with this?

**Comment by yashu-seth** [comment]
@ankurankan I am beginning work on this. Please notify me if you feel something needs to be changed or should have a different implementation whenever you are free.
