### ISSUE TITLE
Remove boilerplate code for inplace operations in Factors, TabularCPDs.

### ISSUE THREAD

**Issue by abinashpanda** [pgmpy/pgmpy#244]
Currently, in both `Factor` as well as in `TabularCPD` class, methods like `normalize`, `reduce`, `marginalize` have a `inplace` as an input argument. But the way that is implemented in the methods is:

```
if inplace:
    factor = self
else:
    factor = Factor(.., ..., ...)
```

and this code is repeated in lot of the places. Replace the boilerplate code with something more clean and elegant.

**Comment by ankurankan** [comment]
We can have a look at how `pandas` implements `inplace`

**Comment by gokul-uf** [comment]
@abinashpanda We could do something like this https://gist.github.com/gokul-uf/c0439b874d681084ef6a
Other possibilities: http://stackoverflow.com/questions/394809/does-python-have-a-ternary-conditional-operator

**Comment by ankurankan** [comment]
Fixed already.
