### ISSUE TITLE
Parallel for loops in predict method

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#248]

**Comment by gokul-uf** [comment]
Hi @ankurankan, could you give me more info about this?

**Comment by ankurankan** [comment]
@gokul-uf: So there is still a pending PR for predict method for Bayesian Network (and I don't remember it's state whether it was working or not). And I think it was iterating over data to calculate predictions. So we want to either replace this with vectorization or at least make the iteration parallel by using `joblib`

**Comment by ankurankan** [comment]
Creating new issue for vectorizing predict. Closing this.
