### ISSUE TITLE
Feature to compute Joint Distribution over multiple variables using VariableElimination

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#250]

**Comment by Utkarshdevd** [comment]
Could you explain more on this topic?
In what way is the implementation of generalized variable elimination expanded by this?
Is there any specific implementation in consideration, could you point me to such a source, as I haven't gotten this far in my Machine Learning course?

**Comment by ankurankan** [comment]
@Utkarshdevd So currently when you pass a list as the argument for `variables` in `VariableElimination`'s `query` method you get a dictionary with the factor for each variable.

For example:

``` python3
In [1]: query_result = bayesian_inference.query(variables=['A', 'B'])
In [2]: query_result
{'A': <some factor>, 'B': <some factor>}
```

So we want to add the feature to have an option to return a Factor with scope both `A` and `B`. So in this case you will need the variable elimination algorithm to eliminate all the variables except for those in the argument `variables`.

**Comment by yashu-seth** [comment]
@ankurankan I would like to work on this. From what I understood the current <code>_variable_elimination</code> method output is a dictionary with variables (that are not to be eliminated) as keys and factors (with a scope of only the respective variable) as values. But we want to add the functionality where we get a factor that contains scope of all the variables (that are not to be eliminated). Correct me if I am wrong.

**Comment by ankurankan** [comment]
@yashu-seth Don't start working on this. I am fixing this and there is a PR for this already.

**Comment by yashu-seth** [comment]
@ankurankan okay

**Comment by ankurankan** [comment]
Closing as not relevant anymore.
