### ISSUE TITLE
Make changes to marginalize and reduce

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#255]
Marginalize and reduce methods have some redundant code that can be replaced with `_index_for_assignment`

**Comment by palashahuja** [comment]
I have tried to replace marginalize over single variable with _index_for_assignment method in the [following gist-](https://gist.github.com/palashahuja/488050fac7a03b4acfa8). Please have a look.
@ankurankan.,@abinashpanda

**Comment by abinash-panda** [comment]
@palashahuja Send a PR with the changes and make sure the tests pass. It is easier to review the code.

**Comment by palashahuja** [comment]
Sure I will send it.

**Comment by palashahuja** [comment]
@abinash-panda  What is the error ? Can you please explain ?

**Comment by ankurankan** [comment]
Fixed in #316
