### ISSUE TITLE
Add tests for Inference using Markov Models

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#263]
Currently tests for inference methods only use Bayesian Models. Add a few tests using markov models.

**Comment by sharangdhar** [comment]
Has this been done already? If not, I can work on this.

**Comment by ankurankan** [comment]
@sharangdhar Please go ahead.

**Comment by kshitij10496** [comment]
@ankurankan Is this issue still open ?

**Comment by ankurankan** [comment]
@kshitij10496 yes it's open.. You can start on this.

**Comment by anaviltripathi** [comment]
@ankurankan @kshitij10496 If this is still open, then I would like to work on this.

**Comment by ankurankan** [comment]
@anaviltripathi This is still open. You might find a few bugs in inference code while writing this.

**Comment by anaviltripathi** [comment]
@ankurankan Can you suggest some tool to cross verify the tests against. Like Samlam was used for bayesian tests.

**Comment by ankurankan** [comment]
@anaviltripathi I don't know any such tool. But I think a hackish way (won't be applicable for all networks) would be to use SamIam to get results on some bayesian network assuming it to be a markov network and assuming CPDs as Factors. And since with variable elimination we would just be dealing with the factors, the results should be same. What do you think ?

**Comment by anaviltripathi** [comment]
@ankurankan Yes, I was also thinking the same, but it seemed hackish so I avoided it. As we are only dealing with factors this should work. 
 One other thing that I came across while going through inference methods is that factor to CPD conversion is not yet supported in markov to bayesian.

**Comment by ankurankan** [comment]
@anaviltripathi I didn't get your point on factor to CPD conversion. Can you please elaborate a bit ?
Also everywhere we have tried to convert CPD to Factor for working with them.

**Comment by anaviltripathi** [comment]
@ankurankan See the second last line of to_bayesian_model method of MarkovModel.

**Comment by anaviltripathi** [comment]
@ankurankan Although the tests can be implemented without converting to bayesian explicitly.

**Comment by ankurankan** [comment]
@anaviltripathi Got it. Can you please create an issue for this? And we can write the tests without converting, so you can go ahead with this.

**Comment by ibrahim5253** [comment]
I am a newbie here. What does adding tests mean?

**Comment by anaviltripathi** [comment]
@ankurankan I think this can be closed now. #577 fixes this.

**Comment by yashu-seth** [comment]
@ibrahim5253 We write tests for automatically checking if everything is working fine. So, basically its like running some method and then comparing the results with the expected output. You can Google unittests for more information on this.

In pgmpy, all the tests are in the 'tests' folder. You can have a look at them to get a general idea of writing tests.

**Comment by ibrahim5253** [comment]
@yashu-seth Thanks of your patience and explanation.
