### ISSUE TITLE
Add a method to compute induced graph

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#268]

**Comment by gokul-uf** [comment]
Hi @ankurankan I would like to take this up

**Comment by ankurankan** [comment]
@gokul-uf Cool.. I have already written the docstring so you can see the details there.

**Comment by ankurankan** [comment]
@abinashpanda Shouldn't the user be able to call induced graph without even adding CPDs/ Factors to the model? But right now we have placed this method in `VariableElimination`, so the user will have to add CPDs/Factors to get an instance of `VariableElimination`. Any better solution or should we go with it this way only for now ?

**Comment by ankurankan** [comment]
@abinashpanda @gokul-uf Won't be possible to create induced graphs in the case of Markov models until we know the scopes of the factors. So @gokul-uf Please go ahead with this.

**Comment by pratyakshs** [comment]
@ankurankan Can close this for now..

**Comment by ankurankan** [comment]
@gokul-uf: This is fixed now.

**Comment by ankurankan** [comment]
Fixed in #349.
