### ISSUE TITLE
Modify BayesianModel's check_model method to work with RuleCPD and TreeCPD

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#273]
Currently check_model considers only TabularCPD. Modify it to work with Rule and Tree CPDs also.

**Comment by siteshjaiswal** [comment]
I want to work on this.Please add any furthur info needed.

**Comment by ankurankan** [comment]
@siteshjaiswal You can see that there's a `check_model` here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/models/BayesianModel.py#L213. You can read what it does in the docstrings. But currently it can only check the model if the associated CPDs are TabularCPD. We want to extend this to work with TreeCPD as well as RuleCPD.

**Comment by ankurankan** [comment]
Not relevant anymore.
