### ISSUE TITLE
Should check_model raise an error or just return False?

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#274]
@abinashpanda

**Comment by abinash-panda** [comment]
@ankurankan IMHO it should return False. But the question is how are you going to report to user why the check_model method failed? Any suggestions?

**Comment by ankurankan** [comment]
@abinash-panda @gokul-uf : So I think for now we should raise errors then.

**Comment by gokul-uf** [comment]
@ankurankan @abinash-panda ​​
I believe returning false would make more sense.  we are checking the model, a return value of false would make perfect sense if the model is not valid

For example, take the following test case:

#Snippet 1
if BN.check_model():
    print ( "model is fine")
else:
    print ("problem with model")

#Snippet 2
try:
    BN.check_model()
except ValueError:
    print ("Error!!")

I think the first snippet makes more sense and is in fact more intuitive than the second

To figure out what error has actually occured, we could
1. Print it out inside check_model ( )
2. Return a Tuple of (Bool, str)  with possible combinations (True, OK) and (False, relevant_error)

**Comment by ankurankan** [comment]
@gokul-uf Since a lot of things can go wrong in a model, the user will have to do a lot of work to just figure out what went wrong if we simply return `False`. So a descriptive error makes much sense.

**Comment by gokul-uf** [comment]
@ankurankan That's what I meant, relevant_error was just for an example.

**Comment by ankurankan** [comment]
@gokul-uf So why would you want to return two values. If you are throwing errors then returning `True` or `False` is redundant.

**Comment by gokul-uf** [comment]
@ankurankan, I did that to have uniformity.
The second value would make sense only when the method returns False
Possible return values:
(True, "OK")
(False, "CPD associated with %s doesn't have proper parents associated with it." % node) .etc

This would help in gracefully handling the error

**Comment by ankurankan** [comment]
@gokul-uf This is not anywhere near gracefully handling error. With throwing exceptions we can go into multiple try excepts:

``` python
try:
     model.check_model()
except ParentError:
     # do something
except CPDError:
     # do something
```

And I think this is much better. If you return a string you will not be able to programatically detect what happened.

**Comment by gokul-uf** [comment]
I got your point,
I think we would have to go ahead and add CPDError to pgmpy.exceptions.
but like you said before, check_model could fail for a variety of reasons,
could we collect them all into a manageable number of exceptions?

**Comment by ankurankan** [comment]
@gokul-uf I didn't mean to add to `CPDError`. I was just giving an example. So see for yourself what Exceptions need to be added.
And yes all the exceptions are definitely manageable. We should be able to deal with most of the exceptions using python's built in exceptions..

**Comment by gokul-uf** [comment]
@ankurankan On it, could you check my PR in the meantime? thanks

**Comment by gokul-uf** [comment]
@ankurankan Apart from the two errors mentioned in the code, I don't think there could be other error because we do test before adding a node or edge. Are there any situations I'm missing?

**Comment by liquidmetal** [comment]
Was this sorted out?

Instead of having a function named `check_model`, you could have something like `validate_model`. If the function executes fine, the model has no errors. If not, the function could raise a bunch of different exceptions like mentioned above.

**Comment by yashu-seth** [comment]
@liquidmetal check_model is currently doing exactly that. And I think it has been decided that check_model will raise an error.and not return False, at least for now.

**Comment by yashu-seth** [comment]
@ankurankan I think this can be closed.

**Comment by ankurankan** [comment]
Fixed. Should return `True` if the model is correct or raise an error.

**Comment by khalibartan** [comment]
I agree . It should return an error. If `false` is returned user will not understand that given data has some bugs in it. A proper error raised can save a lot of time for users .
