### ISSUE TITLE
Use prettytable for __repr__ methods

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#276]
prettytable: https://pypi.python.org/pypi/PrettyTable/0.7.2

**Comment by kislayabhi** [comment]
Hey @ankurankan , I am on it. 

Any nuances that you might want to add...

**Comment by abinash-panda** [comment]
@kislayabhi Just before you start working on it, lets discuss whether we want to add dependency for such a trivial task. Your views @ankurankan ?

**Comment by ankurankan** [comment]
I really think this dependency would be worth it. Right now we have hard coded spaces between the variables while printing the `Factors`. So in many cases the representation doesn't look good at all. Also we are using the same method for `TabularCPD`  which I think should have a separate method which could print it properly. And I don't think that there is a simple way to do that.

So, we could either write something similar to prettytable for our needs or use prettytable because we will be needing this at other places as well.

**Comment by abinash-panda** [comment]
My point against adding such trivial library as a dependency is that we don't want users to install another library just for printing `Factors` or `TabularCPD`. I have a good suggestion to use this library without asking the users to install it. The library is very small (21Kb), so we can add the code to our library. My proposal
- Create another submodule `extern` where we would add all the libraries that we would be using but we don't want users to install it such as `OpenGM` (if we are going to use it).
- Add the library over here.
- Import `prettytable` as `pgmpy.extern.prettytable`.

@ankurankan @kislayabhi Any suggestions?

**Comment by kislayabhi** [comment]
Yeah. That appears cool as in a way we are using the same code but without bothering the users. It satisfies @ankurankan points too, I think.

**Comment by ankurankan** [comment]
@abinash-panda @kislayabhi Only problem would be that we will have to manually update prettytables in our codebase but since it's nothing of much importance so I think we should be fine with that.

**Comment by kislayabhi** [comment]
Looks like the last update of that library is quite old. It dates back to 2013. https://groups.google.com/forum/#!forum/prettytable-announce

**Comment by ankurankan** [comment]
@kislayabhi Cool.. I think we can go with it then.

**Comment by ankurankan** [comment]
#55 can also be handled along with this.

**Comment by kislayabhi** [comment]
I am trying to get the pgmpy's way of handling TabularCPD. For creating something like this:

For a distribution of P(grade|intel, diff)

```
+-----------+--------------------+------------------+
|diff      |        easy         |    hard         |
+------------+-----+------+-------+------+----+------+
|intel     |dumb |  avg | smart | dumb |avg |smart |
+------------+-----+------+-------+------+----+------+
|gradeA    |0.1  |  0.1 |  0.1  | 0.1  |0.1 | 0.1  |
+------------+-----+------+-------+------+----+------+
|gradeB    |0.1  |  0.1 |  0.1  | 0.1  |0.1 | 0.1  |
+------------+-----+------+-------+------+----+------+
|gradeC    |0.8  |  0.8 |  0.8  | 0.8  |0.8 | 0.8  |
+------------+-----+------+-------+------+----+------+
```

Is the following correct?

`final_cpd=TabularCPD('grade', 3, [[0.1,0.1,0.1,0.1,0.1,0.1],
                                  [0.1,0.1,0.1,0.1,0.1,0.1],
                                  [0.8,0.8,0.8,0.8,0.8,0.8]],
                     evidence=['difficulty','intelligence'],
                     evidence_card=[2,3])`

**Comment by ankurankan** [comment]
@kislayabhi: It's correct. The important thing to note is just the order in which you provide the evidence variables as the same order is used for parents in the CPD.

**Comment by abinash-panda** [comment]
@kislayabhi Ah..this is wrong. I think I had fixed this in the latest README.md. 

``` python
final_cpd=TabularCPD('grade', 3, [[0.1,0.1,0.1,0.1,0.1,0.1], [0.1,0.1,0.1,0.1,0.1,0.1], [0.8,0.8,0.8,0.8,0.8,0.8]], evidence=['intel', 'diff'], evidence_card=[2,3])
```

The parent whose value changes fastest should be specified first.

**Comment by kislayabhi** [comment]
@abinash-panda :
but then why are you keeping `evidence_card=[2,3]`, the same as before. 
Won't it be reversed too?

P.S: https://github.com/pgmpy/pgmpy/blob/dev/README.md isn't updated.

**Comment by abinash-panda** [comment]
@kislayabhi Yeah, it should be reversed also.

**Comment by kislayabhi** [comment]
Hey @ankurankan, @abinash-panda 
I had a little caveat in working with PrettyTables.

There happens to be no way through which we can create two field names for a single table.

That is, if we intend to create something like this:

```
+-----------+--------------------+------------------+
|diff      |        easy         |    hard         |
+------------+-----+------+-------+------+----+------+
|intel     |dumb |  avg | smart | dumb |avg |smart |
+------------+-----+------+-------+------+----+------+
|gradeA    |0.1  |  0.1 |  0.1  | 0.1  |0.1 | 0.1  |
```

This would mean that we have `diff, easy and hard` as one field and the other is `intel, dumb, avg, smart, dumb, avg, smart`.

Moreover, PrettyTables doesn't allow two field names to be same. Hence we cannot use `dumb` or `avg` or `smart` multiple times. (In its issues list, a dirty fix was suggested where we have to use `intel, dumb_1, avg_1, smart_1, dumb_2, avg_2, smart_2`)

I think I may have to go for architectural changes in Prettytable Lib.
What are your views?

**Comment by abinash-panda** [comment]
@kislayabhi I looked the `PrettyTables` module and it seems to have very basic printing functionalities. What I am not sure is should we invest time in improving another library which is not a core part of our library? @ankurankan Your views.

**Comment by abinash-panda** [comment]
Ah..my bad. Sorry for mentioning about asciitable. It is not the library we want.

**Comment by abinash-panda** [comment]
@kislayabhi Look at the https://pypi.python.org/pypi/tabulate module. It seems to have support for multiple headers.

**Comment by kislayabhi** [comment]
I am able to get it like the following from tabulate module:

```
+--------+------+------+-------+------+------+-------+
| diff   | easy | easy | easy  | hard | hard | hard  |
+--------+------+------+-------+------+------+-------+
| intel  | dumb | avg  | smart | dumb | avg  | smart |
+--------+------+------+-------+------+------+-------+
| gradeA | 0.1  | 0.1  | 0.1   | 0.1  | 0.1  | 0.1   |
+--------+------+------+-------+------+------+-------+
| gradeB | 0.1  | 0.1  | 0.1   | 0.1  | 0.1  | 0.1   |
+--------+------+------+-------+------+------+-------+
| gradeC | 0.8  | 0.8  | 0.8   | 0.8  | 0.8  | 0.8   |
+--------+------+------+-------+------+------+-------+
```

Multiple headers are still not there so in the above format, I haven't assigned any headers at all. The feel of the table appears fine.

**Comment by ankurankan** [comment]
@kislayabhi I think this is okay. @abinash-panda What do you think?

**Comment by abinash-panda** [comment]
@kislayabhi Go ahead with it.
