### ISSUE TITLE
Add method to compute induced graph width

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#288]

**Comment by sharangdhar** [comment]
I would like to work on this.

**Comment by ankurankan** [comment]
@sharangdhar Please go ahead.

**Comment by alekdimi** [comment]
Is this is still open? Anyone working on it?

**Comment by ankurankan** [comment]
@alekdimi Still open.

**Comment by Shekharrajak** [comment]
Do you mean this ?
width of induced graph =  recursively connecting parents going from
last node to first.
 Induced-width w_(d) = the max induced-width over all nodes
 Induced-width of a graph=max w_(d) over all

So we need Induced width of graph ?

**Comment by ankurankan** [comment]
@Shekharrajak This is already implemented.

**Comment by ankurankan** [comment]
Closing.
