### ISSUE TITLE
Predict method should have an argument to provide algorithm

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#314]

**Comment by khalibartan** [comment]
@ankurankan DO you mean in case of `BayesianModel` user can chose from `VariableElimination` and `BeliefPropagation` ?

**Comment by ankurankan** [comment]
@khalibartan Yes. There should be an argument so that the user could pass any class which inherits `Inference` (https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/inference/base.py#L13). This will help in keeping things extensible and the user can quickly write his own inference algorithm and plug it in pgmpy.

**Comment by khalibartan** [comment]
@ankurankan I'll check the API of the inference class . And see on how to integrate it .

**Comment by khalibartan** [comment]
@ankurankan What should user send in as parameter the type of algorithm or an instance of algorithm
. Formally

```
>>> from pgmpy.inference import VariableElimination
>>> algo = VariableElimination # type of algorithm
>>> type(algo)
type
>>> algo1 = VariableElimination(model) # instance of alogrithm
>>> type(algo1)
pgmpy.inference.ExactInference.VariableElimination
>>> isinstance(algo, VariableElimination)
False
>>> isinstance(algo1, VariableElimination)
True
```

For second one user have to pass the model parameter, because `__init__` method of `Inference` requires that.

**Comment by khalibartan** [comment]
Also how do we plan on for API. Since Classes in `ExactInference.py` have same consistent API but user may not be knowing our API. I have also tried an implementation by passing a `type` and it worked fine without much changes .

**Comment by ankurankan** [comment]
@khalibartan We will need to pass in the class as a parameter. So, it would look something like:

``` python
from pgmpy.inference import VariableElimination
model = SomeModel()
model.fit(some_data)
model.predict(some_data, algo=VariableElimination, **kwargs)
```

**Comment by khalibartan** [comment]
@ankurankan Yes I was talking about this. But what should we do for API. If user names method differently then ours.

**Comment by ankurankan** [comment]
@khalibartan We will have to mention all this in docs. Like what variables are provided by the Base class and what methods need to be defined in each Inference Algo class.

**Comment by khalibartan** [comment]
Okay.
