### ISSUE TITLE
Add method in TabularCPD to reorder the parent's order

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#353]

**Comment by kislayabhi** [comment]
Please add some more info. I intend to work on this.

**Comment by palashahuja** [comment]
@kislayabhi Suppose if we have a tabular CPD like this 

```
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| C   | C_0 | C_0 | C_0 | C_0 | C_1 | C_1 | C_1 | C_1 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| B   | B_0 | B_0 | B_1 | B_1 | B_0 | B_0 | B_1 | B_1 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| A   | A_0 | A_1 | A_0 | A_1 | A_0 | A_1 | A_0 | A_1 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| J_0 | 0.9 | 0.3 | 0.9 | 0.3 | 0.8 | 0.8 | 0.4 | 0.4 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| J_1 | 0.1 | 0.7 | 0.1 | 0.7 | 0.2 | 0.2 | 0.6 | 0.6 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
```

then there should be a separate method to switch the tuples inside the tables(i.e for example if the user wants to switch B and A inside the table such that B is the most rapidly changing value)
Keep in mind the values also change accordingly. After switching A and B inside the table it should look something like this.

```
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| C   | C_0 | C_0 | C_0 | C_0 | C_1 | C_1 | C_1 | C_1 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| A   | A_0 | A_0 | A_1 | A_1 | A_0 | A_0 | A_1 | A_1 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| B   | B_0 | B_1 | B_0 | B_1 | B_0 | B_1 | B_0 | B_1 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| J_0 | 0.9 | 0.9 | 0.3 | 0.3 | 0.8 | 0.4 | 0.8 | 0.4 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| J_1 | 0.1 | 0.1 | 0.7 | 0.7 | 0.2 | 0.6 | 0.2 | 0.6 |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+
```

That's what is supposed to be done.

**Comment by kislayabhi** [comment]
Please continue it here: #358

**Comment by anaviltripathi** [comment]
@ankurankan What is the status of this?

**Comment by ankurankan** [comment]
@anaviltripathi It's still open. Kislay had done some work on this (#358) but wasn't merged.

**Comment by anaviltripathi** [comment]
@ankurankan I have written two approaches for this. One uses numpy's reshape and transpose with some tricks and another is plain one to one mapping. Could you check and suggest which approach would be better. Also, how do I go about the review. Do I send a PR or is there some other way.

**Comment by anaviltripathi** [comment]
@ankurankan I ran some timeit tests on both approaches and I have sent a PR (#571) for the approach that had better results.

**Comment by satrana42** [comment]
@anaviltripathi What's the status on this? I am looking for a first patch. Is this open? There have been multiple PRs which had not been merged on this thread.

**Comment by ankurankan** [comment]
@satwantrana #628 is a blocker for this.

**Comment by anaviltripathi** [comment]
@satwantrana Work for this is done. 
Just working on #628, once it is done, this will be merged.
