### ISSUE TITLE
printing cpd only shows values upto one decimal place

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#362]
``` python3
cpd = TabularCPD('X', 2, [[0.46, 0.54]])

print(cpd)
╒═════╤═════╕
│ X_0 │ 0.4 │
├─────┼─────┤
│ X_1 │ 0.5 │
╘═════╧═════╛

cpd.values
Out[16]: array([ 0.46,  0.54])
```

@kislayabhi Any idea what's happening here?

**Comment by palashahuja** [comment]
@ankurankan  The problem is with `np.column_stack`.
It is used in the [**str**](https://github.com/pgmpy/pgmpy/blob/707d3df7e0883a09d5143f467759da148d98d465/pgmpy/factors/CPD.py#L146) function. 

```
>>> a = np.array((1.12,2.25,3.26))
>>> b = np.array(('x','y','z'))
>>> np.column_stack((b,a))
array([['x', '1'],
       ['y', '2'],
       ['z', '3']], 
      dtype='<U1')
```

**Comment by kislayabhi** [comment]
@ankurankan @palashahuja Is this issue resolved. I am getting the correct outputs here.

**Comment by ankurankan** [comment]
@kislayabhi Nope.. Not working for me. @abinashpanda Can you check?

**Comment by kislayabhi** [comment]
@ankurankan :The weird thing is that `np.column_stack` is also working fine here.

The other one is as follows.

```
    cpd = TabularCPD('X', 2, [[0.46, 0.54]])
    print(cpd)

    ╒═════╤══════╕
    │ X_0 │ 0.46 │
    ├─────┼──────┤
    │ X_1 │ 0.54 │
    ╘═════╧══════╛
```

Could we be having some issues with numpy. (Mine's 1.9.1)

**Comment by palashahuja** [comment]
@kislayabhi not working for me either...

**Comment by ankurankan** [comment]
@kislayabhi Fixed now. Was because of numpy version. @palashahuja Try upgrading numpy.

**Comment by palashahuja** [comment]
@ankurankan ok...
