### ISSUE TITLE
Bayesian Parameter learning for Bayesian Networks

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#369]

**Comment by khalibartan** [comment]
@ankurankan Describe it a little more. What particular features are we looking to provide. I also wanted to discuss about this.

**Comment by shwetamore1295** [comment]
@khalibartan @ankurankan if this issue is small enough, I would like to take it up.

**Comment by ankurankan** [comment]
@shwetamore1295 No, it not. Wouldn't suggest you to start with this.

**Comment by khalibartan** [comment]
@shwetamore1295 I won't recommend you to work on this. This will require a lot of efforts and good knowledge of code base .

**Comment by yashu-seth** [comment]
@ankurankan This can be closed.
