### ISSUE TITLE
Factor reduce scope and variable ordering

### ISSUE THREAD

**Issue by sytham** [pgmpy/pgmpy#381]
**Problem 1: factor reduction makes an assumption on the order in which variables are passed in:**

Original factor:
╒═════╤═════╤════════════╕
│ 3   │ 2   │   phi(3,2) │
╞═════╪═════╪════════════╡
│ 3_0 │ 2_0 │     0.3900 │
├─────┼─────┼────────────┤
│ 3_0 │ 2_1 │     0.0600 │
├─────┼─────┼────────────┤
│ 3_1 │ 2_0 │     0.6100 │
├─────┼─────┼────────────┤
│ 3_1 │ 2_1 │     0.9400 │
╘═════╧═════╧════════════╛
Observed (2_0, 3_1):
╒═════════╕
│   phi() │
╞═════════╡
│  0.0600 │
╘═════════╛

Expected output: 0.61. The problem occurs because the evidence was passed in as (2_0, 3_1) instead of (3_1, 2_0).

**Problem 2: when a variable is passed in that is not in scope, an error occurs.**

Original factor:
╒═════╤═════╤════════════╕
│ 2   │ 1   │   phi(2,1) │
╞═════╪═════╪════════════╡
│ 2_0 │ 1_0 │     0.5900 │
├─────┼─────┼────────────┤
│ 2_0 │ 1_1 │     0.2200 │
├─────┼─────┼────────────┤
│ 2_1 │ 1_0 │     0.4100 │
├─────┼─────┼────────────┤
│ 2_1 │ 1_1 │     0.7800 │
╘═════╧═════╧════════════╛

Observed (2_0, 3_1):

ERROR: test_observe_evidence

Traceback (most recent call last):
  File "../pgmpy/factors/Factor.py", line 276, in reduce
    raise Exceptions.ScopeError('%s not in scope' % list(set(reduced_variables)-set(factor.scope())))
pgmpy.exceptions.Exceptions.ScopeError: "['3'] not in scope"

The error occurs because '3' is not in scope of the factor.

Problem 2 doesn't happen when the factor is used through one of the inference methods (variable elimination or belief propagation). I'm not sure about problem 1. However, in either case the implementation now couples the Factor class to the VE / BP implementations. If that's the intended use, i.e. if Factor shouldn't be used on its own, it should be a private class.

I propose to fix the above in the Factor class. It's not a difficult fix and shouldn't have performance impact.

**Comment by ankurankan** [comment]
Fixed in 6f3fad9e56dbb258925042720e0061639a1599a5
