### ISSUE TITLE
Naive Bayes

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#384]

**Comment by yashu-seth** [comment]
@ankurankan Please elaborate on this.

**Comment by ankurankan** [comment]
@yashu-seth As you know Naive Bayes model is a special condition of the Bayesian Model. So we want an implementation of this, in which the user can just create a class and fit data over this as structure can be directly interpreted from the data.

**Comment by yashu-seth** [comment]
@ankurankan I would like to work on this. So we basically want a subclass of Bayesian Model which can only store edges from a parent node to children and cpds only between the parent random variable and its respective children variables which would follow the appropriate naive bayes independence assumptions.

**Comment by ankurankan** [comment]
@yashu-seth Yes. And it should also have a `fit` and `predict` method so that it can directly learn from the data and predict missing values in new data.

**Comment by yashu-seth** [comment]
@ankurankan Okay. I have started working on this, but it will take some time. I have my end semester examinations next week.

**Comment by ankurankan** [comment]
@yashu-seth No problem. Just send a PR early so that I can have a track that you are working in the right direction.

**Comment by khalibartan** [comment]
@ankurankan Fixed. Close this

**Comment by yashu-seth** [comment]
@ankurankan I think this can be closed now.
