### ISSUE TITLE
Tests for add_cpds method of BayesianModel

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#395]

**Comment by kshitij10496** [comment]
@ankurankan I would like to work on this if this is still open.

**Comment by ankurankan** [comment]
@kshitij10496 Yes, it's still open. You can start working on this.

**Comment by kshitij10496** [comment]
@ankurankan I have a doubt though.
Doesn't the [`test_add_multiple_cpds()`](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/tests/test_models/test_BayesianModel.py#L188) do the same task ?

**Comment by ankurankan** [comment]
@kshitij10496 Sorry, my bad. I just checked for tests but looks like I missed these.
Closing this issue.

**Comment by kshitij10496** [comment]
@ankurankan No problem.
I will look for other issues
