### ISSUE TITLE
Bug in to_junction_tree() method in MarkovModel.

### ISSUE THREAD

**Issue by abinashpanda** [pgmpy/pgmpy#445]
Bug in converting the following Markov Model to Junction Tree.

``` python
from pgmpy.models import MarkovModel
from pgmpy.factors import Factor
import numpy as np
mm = MarkovModel()
mm.add_edges_from([('a','a1'),('b','b1'),('a1','c1'),('b1','c1'),('a','b'),('a1','b1')])
factor_dict = {}
factor_dict[1] = Factor(('a','b'), [2,2],np.random.rand(4))
factor_dict[2] = Factor(('a','a1'), [2,2], np.random.rand(4))
factor_dict[3] = Factor(('b','b1'), [2,2], np.random.rand(4))
factor_dict[4] = Factor(('a1','b1','c1'),[2,2,3], np.random.rand(12))
mm.add_factors(*[factor for key,factor in factor_dict.items()])
jt = mm.to_junction_tree()
```

**Comment by palashahuja** [comment]
@abinashpanda I was wondering whether we could split each of the factors having more than two variables into two or more factors by marginalizing each variable. This way the conversion could work.

**Comment by abinashpanda** [comment]
@palashahuja this might work for sure, but somehow I don't like this way because it increases the overhead cost of marginalizing a factor which is a costly operation. Think of cases when there would be large factors, we don't want to marginalize them in the junction tree creation part and do the same operation again when we are running inference. This would be equivalent of doing the same operation twice.

**Comment by palashahuja** [comment]
@abinashpanda How about this then?

```
from pgmpy.models import MarkovModel
from pgmpy.factors import Factor
import numpy as np
mm = MarkovModel([('a','b'),('b','c'),('c','d'),('d','a')])
factor1 = Factor(('a','b','c','d'),[2,2,2,2],np.random.rand(16))
mm.add_factors(factor1)
jt = mm.to_junction_tree()
```

All the factors may not have to be split up, but some of them really need to.

**Comment by abinashpanda** [comment]
@palashahuja The way the factors have been defined are inconsistent with the model. In Markov Model you need to define factors corresponding to a clique. The factor that you have defined is not corresponding to any clique because of which it is giving error. The `ValueError` thrown in this case is truly justified.

**Comment by palashahuja** [comment]
@abinashpanda Sorry about before. I actually wanted to tell you about this.

```
mm = MarkovModel([('a','b'),('b','c'),('c','d'),('d','a'),('b','d'),('a','c'),('a','e'),('c','f'),('e','f')])
factor1 = Factor(('a','b','c','d'),[2,2,2,2],np.random.rand(16))
factor2 = Factor(('a','e'),[2,2],np.random.rand(4))
factor3 = Factor(('c','f'),[2,2],np.random.rand(4))
factor4 = Factor(('e','f'),[2,2],np.random.rand(4))
mm.add_factors(factor1, factor2, factor3, factor4)
jt = mm.to_junction_tree()
```

**Comment by abinashpanda** [comment]
@palashahuja I looked more into this issue and I think I should go with the way that you suggested. Increasing the size of the clique would increase the computation in the inference step. So, we would be marginalizing the some factors

**Comment by abinashpanda** [comment]
@palashahuja Fixed this issue. We don't require to marginalize all the variables to compute clique potential. Instead, we can simply fix it by 
- First initializing the clique potential as unity factor
- Next, multiplying the formed clique potential with all the factors associated with the variables present in the clique.
