### ISSUE TITLE
python 2 support

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#448]

**Comment by khalibartan** [comment]
Could you elaborate the issue a bit more

**Comment by ankurankan** [comment]
@khalibartan Currently pgmpy only support python3. We need to add support for python 2.7. And it's almost done except for a few functionalities. And currently we are skipping tests for these. You can search for `@unittest.skipIf(six.PY2` in the project for checking which tests we are skipping because of compatibility issues. There is another issue listing the things which are not compatible yet: #493

**Comment by ankurankan** [comment]
Fixed
