### ISSUE TITLE
Add copy methods to all models and Factor class

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#489]
- [x] BayesianModel
- [x] TabularCPD
- [x] ClusterGraph
- [ ] DynamicBayesianNetwork
- [ ] FactorGraph
- [x] JunctionTree
- [x] MarkovChain
- [x] MarkovModel

**Comment by souravsingh** [comment]
I would like to work on this.How do I start?

**Comment by ankurankan** [comment]
@souravsingh We just need `copy` methods in these models/classes which should return an instance which is a copy of the instance on which it was called. For examples, you can check Factor's copy method here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/factors/Factor.py#L639 , `BayesianModel`'s copy method: https://github.com/pgmpy/pgmpy/pull/488/files#diff-5486bc43772bb0d18a7231f9496abcb7R658

**Comment by khalibartan** [comment]
@souravsingh  If you haven't gain any progress I can work on this issue.

**Comment by souravsingh** [comment]
@khalibartan I have made Progress and Currently Testing the functions.

**Comment by kshitij10496** [comment]
@souravsingh Are you still working on this ?

**Comment by souravsingh** [comment]
@kshitij10496 Yes,I am.It will take some time to make a PR since I am testing the methods.

**Comment by khalibartan** [comment]
@souravsingh you should send a patch. Testing can be done along. Small commits help in better review .

**Comment by khalibartan** [comment]
@souravsingh Can you send in a patch. I need these changes for some work . If you'll send a patch then I'll work with your branch, otherwise I'll  send a new PR for this because I need these for work for some fixes that needs to be done .

**Comment by khalibartan** [comment]
@ankurankan the copy method in Factors class is not actually returning a copy I think, numpy arrays are mutable objects and also a list return by a function.
```
In [1]: def x(i):
   ...:     return i
   ...: 

In [2]: a =[1,2,3]

In [3]: b = x(a)

In [4]: b[0]=2

In [5]: a
Out[5]: [2, 2, 3]

In [6]: b
Out[6]: [2, 2, 3]
```
Function is not doing what you are actually thinking .

**Comment by kshitij10496** [comment]
Ping @souravsingh

**Comment by Pratik151** [comment]
@souravsingh  If you are not working on this can I work on this?

**Comment by souravsingh** [comment]
Sorry @kshitij10496 for not responding.I was out of country.As for working on a patch,I am only working on MarkovChain and MarkovModel since sending a patch for all the classes is difficult.

**Comment by Pratik151** [comment]
@souravsingh  If you didn't started working on others, can I try to work on them? If you are not busy now maybe you can continue.

**Comment by souravsingh** [comment]
I believe @kshitij10496 is working on it.But feel free to send a PR.It will take some time for me to send a PR for the two classes.

**Comment by khalibartan** [comment]
@Pratik151 @kshitij10496 is not working feel free to send in a PR.

**Comment by kshitij10496** [comment]
@Pratik151 I haven't started working on this.
So you can take this. 

Thanks @khalibartan

**Comment by pdoongarwal** [comment]
@Pratik151 I would also like to work on it. Can you tell me on which classes you have worked on, I'll chose then few of the remaining .

**Comment by Pratik151** [comment]
@pdoongarwal  you can work on <code>DynamicBayesianNetwork</code>. I didn't looked into that. You can send PR for that separately and also add tests to that.

**Comment by anchitjain1234** [comment]
@Pratik151 @pdoongarwal I would also like to contribute, please tell me on which classes are you working.

**Comment by pdoongarwal** [comment]
@anchitjain1234  I have began working on `DynamicBayesianNetwork` , will send a PR ASAP.

**Comment by Pratik151** [comment]
@anchitjain1234  I am working on `MarkovModel` and `JunctionTree`. You can work on `MarkovChain` maybe. @souravsingh was working but I don't know if he made any progress.

**Comment by anchitjain1234** [comment]
@Pratik151 @pdoongarwal Thanks for information, I would work on `MarkovChain` then.

**Comment by souravsingh** [comment]
@Pratik151 I am facing problems in testing the method.I can send the PR right now but unit tests will be a problem

**Comment by Pratik151** [comment]
@souravsingh  Maybe send PR someone will be able to help you.

**Comment by yashu-seth** [comment]
@souravsingh I think you should send a PR do not worry about the tests for now. It will be helpful in tracking your progress and you can also discuss related problems there.

**Comment by mvnnn** [comment]
@Pratik151 @pdoongarwal @anchitjain1234 I would like to contribute, please tell me on which classes are you working.

**Comment by anchitjain1234** [comment]
@mvnnn I am not working on any class currently.

**Comment by ibrahim5253** [comment]
Which classes/models are remaining that I can work on?

**Comment by yashu-seth** [comment]
@ibrahim5253 I think FactorGraph and DynamicBayesianNetwork are left but @Pratik151 and @pdoongarwal are working on it.
I guess you can look into some other issue if you want to contribute, this is almost done.

**Comment by yashu-seth** [comment]
@ankurankan Please update the issue.

**Comment by anaviltripathi** [comment]
@ankurankan I can't find `copy` method for TabularCPD but it is check marked here. It is quite straight forward, should I add it?

**Comment by ankurankan** [comment]
@anaviltripathi Yes please.

**Comment by Ashutosh-Adhikari** [comment]
Hi , may I start working on adding copy for DBN , if anyone is not yet assigned for it??

**Comment by pdoongarwal** [comment]
@Ashutosh-Adhikari I have already send a PR for DBN, #613 .

**Comment by yashu-seth** [comment]
@Ashutosh-Adhikari You can work on copy method for DBN. @pdoongarwal is currently busy.

**Comment by aelnouby** [comment]
@yashu-seth Is anybody working on the DBN copy method right now or should i start working on it ?

**Comment by khalibartan** [comment]
@aelnouby You can start working on it. No one is working on it right now.

**Comment by aelnouby** [comment]
@khalibartan is there any model or factor that still need a copy method ?

**Comment by khalibartan** [comment]
@aelnouby  @Pratik151 Isn't able to add commits to his PR for factor graph. Maybe you can talk to him and continue the work.

**Comment by Harshvardhan1** [comment]
@khalibartan  Is this issue open for grabs? If yes, I would like to start working on it

**Comment by khalibartan** [comment]
@Harshvardhan1 Yes it is. You can create copy method for DynamicBayesian Network and FactorGraph . We did have pull requests for these two, but those developers aren't working on it anymore. Make sure that you go through other copy methods and there tests. That will help you a lot. If you face any issue ping me over your pull request.

**Comment by lohani2280** [comment]
Hi , i think right now no one is working on this issue , so can start working on it??

**Comment by khalibartan** [comment]
@lohani2280 Yeah sure go ahead and make a PR, but before that please go through the conversation thread and other copy method that will help you.

**Comment by lohani2280** [comment]
@khalibartan Yeah , i am reading them . Thanks.
