### ISSUE TITLE
Fix tests for python2

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#493]
- [x] MPLP
- [x] readwrite module (mostly unicode problems)
- [x] Gibbs Sampling

**Comment by khalibartan** [comment]
I just have to check the compatibility issues in these modules or there is some catch in it?

**Comment by ankurankan** [comment]
@khalibartan Better check for the tests that we are skipping and according to that will need to fix wherever there are issues.

**Comment by khalibartan** [comment]
Okay I'll give a try. I'm new to community so it might take me some time to send a pr as I have to understand some things. I think I can take up this issue. Do I need some background in probabilistic graphical models for this issue?

**Comment by ankurankan** [comment]
Not a problem, feel free to post to mailing list if you face any issues.

And except for MPLP, I don't think you will need any background in PGM.

**Comment by khalibartan** [comment]
Thanks

**Comment by khalibartan** [comment]
@ankurankan take a look at pr 507. I think issue can be closed now.
