### ISSUE TITLE
Cleaning up the tests for Independencies class

### ISSUE THREAD

**Issue by kshitij10496** [pgmpy/pgmpy#503]
The test cases are not properly implemented.
Moreover, with the an `__eq__` method in the `Independencies` and `IndependenceAssertion` classes, the code needs to be rewritten.

**Comment by kshitij10496** [comment]
Continuation of #498.

**Comment by kshitij10496** [comment]
@ankurankan What is the `test_init` supposed to do ? [[Link]](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/tests/test_independencies/test_Independencies.py#L76)

**Comment by ankurankan** [comment]
@kshitij10496 `test_init` is to test for the `__init__` methods of the classes.

**Comment by kshitij10496** [comment]
@ankurankan Should this issue be closed since the tests for `Independencies` have been modified ?

**Comment by ankurankan** [comment]
Fixed in #498
