### ISSUE TITLE
Add support for BIF file format

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#506]
Can get some file to test on from http://www.bnlearn.com/bnrepository/.

**Comment by khalibartan** [comment]
Does this require any background in Bayesian Learning .If it doesn't , then I'm onto it.

**Comment by ankurankan** [comment]
@khalibartan Not much. You will just need to know how to build a bayesian network in pgmpy.

**Comment by khalibartan** [comment]
Okay, I think there are examples in pgmpy for this? I'm will start working on this issue tomorrow .

**Comment by ankurankan** [comment]
@khalibartan Yeah, I think so.

**Comment by ankurankan** [comment]
@khalibartan Also there is a dirty implementation of this here: https://github.com/pgmpy/pgmpy/pull/488/files#diff-e84ca375a827eebb64245fbfa41835caR1. And we would like to have the API as we have for other formats (check how other file formats are implemented). You can also check this notebook (might be helpful): https://github.com/pgmpy/pgmpy_notebook/blob/master/Reading%20and%20Writing%20from%20pgmpy%20file%20formats.ipynb

**Comment by khalibartan** [comment]
Okay thanks.

**Comment by khalibartan** [comment]
@ankurankan Now we can close this issue .

**Comment by ankurankan** [comment]
Fixed in #512
