### ISSUE TITLE
Removing pyparsing as dependency from pgmpy

### ISSUE THREAD

**Issue by khalibartan** [pgmpy/pgmpy#513]
I think that pyparsing can be removed form pgmpy dependency if we work on UAI reader. Only UAI reader is using pyparsing.
So I think there is no need to make pgmpy dependent of pyparsing just for one script and that too can be work around using regex.
@ankurankan what are your views over this?

**Comment by ankurankan** [comment]
@khalibartan Right now only UAI is using it but we will need it for some other file formats also.
