### ISSUE TITLE
Need for a method to store and load the readed files in readwrite modules.

### ISSUE THREAD

**Issue by khalibartan** [pgmpy/pgmpy#515]
I think we should give store a method in reader classes of our readwrite modules. If somebody wants to work on same data files again, he have to go through process again which I think is time wasting .
User should have option to store this readed information and reuse it again. We can use pickle library of python.
@ankurankan What are you views regarding this.

**Comment by ankurankan** [comment]
@khalibartan This is why we have the writer classes. So, that the user can write the models in whatever format he want and share/use it.

**Comment by khalibartan** [comment]
@ankurankan Writer class is something different than this. That class writes in exportable format. One have to parse that written class once again to get information. I'm thinking of method that stores data like we do in pickling . Once user have parsed the file he doesn't have to parse it once again. He can just use pickling and reuses the info.

**Comment by ankurankan** [comment]
@khalibartan I don't see any benefits of using a pickle based solution. Our current solution is a much more stable thing. Try googling problems with python pickle.

**Comment by ankurankan** [comment]
Closing this.
