### ISSUE TITLE
Use of isinstance(event, str) causes errors in python2.7

### ISSUE THREAD

**Issue by Erotemic** [pgmpy/pgmpy#519]
The use of isinstance(event, str) in In dependencies.py causes an error in python2.7 code using __future__.unicode_literals. This is because unicode is not str in python2.7. 

I'm not sure if this project wants to support python2.7, but the use of the six module indicates that there is at least some interest in doing so. 

If supporting python2.7 and python3 is a development goal then changing all mentions of 

```
isinstance(\(.*\), str)
```

to

```
isinstance(\1, six.string_types)
```

and ensuring 

```
from pgmpy.extern import six
```

is at the top of each relevant file should solve the issue.

**Comment by ankurankan** [comment]
@Erotemic Thanks for pointing this out.
