### ISSUE TITLE
add tests for _get_ancestors_of method in BayesianModel

### ISSUE THREAD

**Issue by yashu-seth** [pgmpy/pgmpy#522]

**Comment by kshitij10496** [comment]
I am working on this.

**Comment by yashu-seth** [comment]
@kshitij10496 cool

**Comment by lohani2280** [comment]
The issue has been solved in the PR https://github.com/pgmpy/pgmpy/pull/830 . So , i think we should close this. .

**Comment by ankurankan** [comment]
@lohani2280 Thanks. :+1:
