### ISSUE TITLE
Making IndependenceAssertion object hashable

### ISSUE THREAD

**Issue by kshitij10496** [pgmpy/pgmpy#531]
The current `IndepedenceAssertion` object has the `__eq__` method and adding a suitable `__hash__` function is needed in order to make it a hashable object.

**Comment by kshitij10496** [comment]
Ping @ankurankan 

Have a look at this [SO](http://stackoverflow.com/q/4005318/4927751) question.
Should we use the tuples implementation or the XOR one ?

**Comment by khalibartan** [comment]
@kshitij10496 XOR hash is depreciated because of its commutativity , [see here](http://stackoverflow.com/questions/5889238/why-is-xor-the-default-way-to-combine-hashes/27952689#27952689).
What are your views regarding this ?

**Comment by kshitij10496** [comment]
@khalibartan +1.Thanks for the link
 I think we should use either `tuples` or any more suitable hashing technique.

**Comment by ankurankan** [comment]
@khalibartan @kshitij10496 The simplest hashing function I think would be: 

``` python
hash(str(sorted(self.event1)) + str(sorted(self.event2)) + str(sorted(self.event3)))
```

This might not be very fast but since we would hardly be using it, it wouldn't make a difference.

**Comment by kshitij10496** [comment]
This seems fine to me.
@khalibartan What are your views on this ?

**Comment by khalibartan** [comment]
@kshitij10496  If speed is not an issue then this is fine, but it is really computationally slow, I believe there is an internal implementation for `tuples` hash, not sure though . But since we are rarely going to use hash method , this seems to fine to me.

**Comment by kshitij10496** [comment]
@khalibartan Exactly.
I think this will do for now.
Moreover, we can always improve upon this if need be.
