### ISSUE TITLE
Logical Error during Inference

### ISSUE THREAD

**Issue by Erotemic** [pgmpy/pgmpy#534]
I've come across what looks like a serious issue. Exact Inference seems to be producing incorrect results for map_query. I've provide a small test case that reproduces this error in both python 2 and python 3. 

**For context**: 
In this section I'm going to describe the context of the problem I'm working on. This will hopefully provide an intuition about the model that is causing the error. 

I am applying Bayesian networks to photographic zebra identification. I have 3 zebras pictures: a, b, and c. I want to know the "name" of each zebra (who each zebra is). For the purposes of this test I'm given an oracle that tells me whether each pair of pictures  (ab, bc, ac) depicts either the same individual or shows different individuals. 

**Network Setup**
I've encoded this knowledge in a Bayesian network with two types of nodes: name nodes and matching nodes. 
- There are 3 name nodes, each representing a different zebra picture. Each of these nodes has a uniform probability distribution over 3 possible name labels. 
- There are also 3 matching nodes for each pair of name nodes. These nodes denote if each pair of pictures matches. The parents of these matching nodes are two name nodes. In this test case two pictures match if and only if they have the same name. 

**The Bug**
In this test case I'm given that a and b are different, a and c are different and b and c are the same. 
More concisely this is what the oracle tells me about each pair of images: ab=different, ac=different, bc=same

Therefore the MAP state assignment of (Na, Nb, and Nc) must be one where Nb and Nc have the same state and Na has a different state from the previous two. There will be an ambiguity between which name is which as a name is simply a label. I would expect the only possible assignments of Na, Nb, and Nc to be: (1, 0, 0), (1, 2, 2), (0, 1, 1), (0, 2, 2), (2, 0, 0), and (2, 1, 1).

However, the MAP probability given by VariableElimination and VariableElimination is Na, Nb, and Nc are assigned to same name state. ie. (0, 0, 0) 

Furthermore, if I manually compute the joint probability distribution by multipling the factors and then reduce over the states where Mab=0, Mac=0, and Mbc=1, and then take the state with the maximum value it gives me a valid assignment of names: (Na=1, Nb=0, Nc=0). Unless I'm incorrect about what map_query is supposed to do, it should return the same value as this brute force method. 

**Code to Reproduce Bug**

``` python
import numpy as np
import pgmpy
from itertools import product
import pgmpy.inference
import pgmpy.factors
import pgmpy.models
import pgmpy.extern

print('Testing map_query bug')

# Factors for the "Name" for 3 entities "a", "b", and "c".
# Initially these are uniform over name 0, 1, and 2
Na = pgmpy.factors.TabularCPD(
    variable='Na',
    variable_card=3,
    values=np.array([[ 0.33333333],
                     [ 0.33333333],
                     [ 0.33333333]]),
    evidence=None,
    evidence_card=None,
)
Nb = pgmpy.factors.TabularCPD(
    variable='Nb',
    variable_card=3,
    values=np.array([[ 0.33333333],
                     [ 0.33333333],
                     [ 0.33333333]]),
    evidence=None,
    evidence_card=None,
)
Nc = pgmpy.factors.TabularCPD(
    variable='Nc',
    variable_card=3,
    values=np.array([[ 0.33333333],
                     [ 0.33333333],
                     [ 0.33333333]]),
    evidence=None,
    evidence_card=None,
)

# Factors denoting whether entity "a" matches entity "b"
# State 0 indiciates "a" does not match "b"
# State 1 indiciates "a" does match "b"
# This is a pairwise factor. One for each pair of name variables.
# If the name of "a" is equal to the name of "b" the probability of match is 1
# All other probabilities are 0
Mab = pgmpy.factors.TabularCPD(
    variable='Mab',
    variable_card=2,
    values=np.array([[ 0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.],
                     [ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.]]),
    evidence=['Na', 'Nb'],
    evidence_card=[3, 3],
)
Mac = pgmpy.factors.TabularCPD(
    variable='Mac',
    variable_card=2,
    values=np.array([[ 0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.],
                     [ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.]]),
    evidence=['Na', 'Nc'],
    evidence_card=[3, 3],
)
Mbc = pgmpy.factors.TabularCPD(
    variable='Mbc',
    variable_card=2,
    values=np.array([[ 0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.],
                     [ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.]]),
    evidence=['Nb', 'Nc'],
    evidence_card=[3, 3],
)

cpd_list = [Mab, Mac, Mbc, Na, Nb, Nc]
input_graph = [
    ('Na', 'Mab'),
    ('Na', 'Mac'),
    ('Nb', 'Mab'),
    ('Nb', 'Mbc'),
    ('Nc', 'Mac'),
    ('Nc', 'Mbc'),
]
model = pgmpy.models.BayesianModel(input_graph)
model.add_cpds(*cpd_list)
print('cpd_list = %r' % (cpd_list,))
print('model = %r' % (model,))

# We observe that "a" and "b" do not match
# We observe that "a" and "c" do not match
# We observe that "b" and "c" DO match
evidence = {'Mab': 0, 'Mac': 0, 'Mbc': 1}

# Therefore the only possible states that shoule exist are
# ones where Nb and Nc are the same and Na is different from both of them.
query_vars = ['Na', 'Nb', 'Nc']


# HOWEVER, this is not what happens.
infr1 = pgmpy.inference.VariableElimination(model)
map_assign1 = infr1.map_query(query_vars, evidence=evidence)

infr2 = pgmpy.inference.BeliefPropagation(model)
map_assign2 = infr2.map_query(query_vars, evidence=evidence)

print('\nINFERENCES SAYS THE ARGMAX ASSIGNMENT IS:')
print('map_assign1 = %r' % (map_assign1,))
print('map_assign2 = %r' % (map_assign2,))


# Incorrectly outputs:
# map_assign1 = {'Nb': 0, 'Na': 0, 'Nc': 0}
# map_assign2 = {'Nb': 0, 'Na': 0, 'Nc': 0}

# The correct MAP estimation of the states can be computed correctly by hand.
joint = pgmpy.factors.factor_product(*model.cpds)
# Remove states that do not agree with the evidence
joint.reduce(evidence)
joint.normalize()

# We can see that the only states that recieve any probability are those where
# nb == nc and na != nb
#print(joint)

# We can show this easilly by removing the non 0 values.
#statenames_list = [['{var}_{i}'.format(var=var, i=i) for i in range(card)]
statenames_list = [[i for i in range(card)]
                   for var, card in zip(joint.variables, joint.cardinality)]
row_labels = list(product(*statenames_list))
row_values = joint.values.ravel()

row_lbl2 = [lbl for lbl, flag in zip(row_labels, row_values > 0) if flag]
row_val2 = row_values.compress(row_values > 0)

factor_table = [list(lbls) + [val]
                for lbls, val in zip(row_lbl2, row_val2)]

# Even easier
print('THE BRUTE FORCE ARGMAX ASSIGNMENT IS:')
maxx = row_val2.argmax()
correct_argmax = dict(zip(joint.variables, row_lbl2[maxx]))
print('correct_argmax = %r' % (correct_argmax,))

print('\nThe brute force method found these probabilities')
string_header = list(joint.scope())
string_header.append('phi({variables})'.format(variables=','.join(string_header)))
print(pgmpy.extern.tabulate(factor_table, headers=string_header, tablefmt='psql', floatfmt=".4f"))
```

The output of this script is 

```
Testing map_query bug
cpd_list = [<TabularCPD representing P(Mab:2 | Na:3, Nb:3) at 0x7fae4ffdedd0>, <TabularCPD representing P(Mac:2 | Na:3, Nc:3) at 0x7fae4ffdee10>, <TabularCPD representing P(Mbc:2 | Nb:3, Nc:3) at 0x7fae4ffdee50>, <TabularCPD representing P(Na:3) at 0x7fae50041e50>, <TabularCPD representing P(Nb:3) at 0x7fae4ffdec50>, <TabularCPD representing P(Nc:3) at 0x7fae4ffde690>]
model = <pgmpy.models.BayesianModel.BayesianModel object at 0x7fae4ffdee90>

INFERENCES SAYS THE ARGMAX ASSIGNMENT IS:
map_assign1 = {'Na': 0, 'Nb': 0, 'Nc': 0}
map_assign2 = {'Na': 0, 'Nb': 0, 'Nc': 0}
THE BRUTE FORCE ARGMAX ASSIGNMENT IS:
correct_argmax = {'Na': 1, 'Nb': 0, 'Nc': 0}

The brute force method found these probabilities
+------+------+------+-----------------+
|   Nb |   Na |   Nc |   phi(Nb,Na,Nc) |
|------+------+------+-----------------|
|    0 |    1 |    0 |          0.1667 |
|    0 |    2 |    0 |          0.1667 |
|    1 |    0 |    1 |          0.1667 |
|    1 |    2 |    1 |          0.1667 |
|    2 |    0 |    2 |          0.1667 |
|    2 |    1 |    2 |          0.1667 |
+------+------+------+-----------------+
```

Does anybody have any clue as to why this is happening? Do I have a huge misconception about what map_query is doing, or is this actually as serious of a bug as I think it is? Can anyone confirm that this is truly a bug?

**Comment by Erotemic** [comment]
Has anybody looked at this / been able to confirm this behavior?

**Comment by ankurankan** [comment]
@Erotemic I am sorry for the delay, I am a bit busy these days. But I will try my best to look into both this and the Belief Propagation issue by end of the day.

**Comment by Erotemic** [comment]
Understood. I'm all too aware of how much work it is to keep up with issues and requests in addition to the many other tasks that must be accomplished in a day. I'm very gratuitous for the help. Having these answers is critical for my work, so I'll see what I can to make it easier to answer these questions. 

That being said, I've done some delving into the code base (and I must say that this is a very well designed library, it's quite a pleasure to work with) to further investigate this problem. **I found that map_query is performing MAP inference over each variable individually**  instead of maximizing over all the query variables jointly. Is this the expected behavior? 

If this is expected,  the documentation of the variables parameter is confusing. It is consistent with the normal query function, but not with my understanding of what a MAP query is used for. From what I understand, MAP is more suited for finding joint assignments to sets of variables, whereas the normal query function  finds the probabilities for a single random variable. Is there a function to perform a "joint MAP query?". (from looking at the different functions it seems likely the answer is no). 

Does all of this make sense? I worry that I misuse terminology or have misunderstandings because I only started using PGM a few weeks ago. If it does, would it be useful to have a joint/multi-variable MAP query function? Having looked looked at ExactInference.py in some detail, I think I would be able and willing to write that patch (with some direction on how it should be incorporated. ie, as a new function with <name> or as added functionality to existing map_query function using a boolean flag named <?>).

**Comment by ankurankan** [comment]
@Erotemic You are right. MAP query should return values for joint assignments to a set of variables. And that is the expected behavior. I think I had done some changes in `_variable_elimination` method recently and this is a side effect of that. I will check this and will fix if I can think of some quick fixes.

**Comment by Erotemic** [comment]
@ankurankan Excellent, its always good to have one's own sanity checked. 

From what I was in the code it looked like there was some potential issues with variable names that get changed between functions. Even if they are not problems they did cause me confusions. From what I recall the offenders are: 
- elimination_variables and variables. This is between map_query and _variable_elimination
- final_distribution and query_var_factor. _variable_elimination has its own variable named final_distribution and returns query_var_factor, but all the functions that call it set the returned value to a variable named final_distribution.

Some other notes that I had while looking at this ExactInference.py: 
- on line 85: it looks like phi = factor_product(*final_distribution) is being computed multiple times for no reason and could simply be moved outside of the for loop. 
- and on line 86: there is an operation phi.marginalize and I was wondering if that should be getattr(phi, operation) instead. Very unsure of this one.

**Comment by khalibartan** [comment]
@ankurankan Updates on this.
