### ISSUE TITLE
pgmpy on pypi?

### ISSUE THREAD

**Issue by saketkc** [pgmpy/pgmpy#537]
Is there a reason to not host pgmpy on pypi? 
For an end user, `pip3 install pgmpy` would be more useful.

**Comment by saketkc** [comment]
Even on conda for that matter.

**Comment by kshitij10496** [comment]
Absolutely.
Ping @ankurankan

**Comment by khalibartan** [comment]
@saketkc There is pip installation available for pgmpy.

```
pip install pgmpy
```

Did you tried this?

**Comment by kshitij10496** [comment]
@khalibartan I am not sure if we do this.
PgmPy is not hosted on PyPi.
We need to build it from source itself.
Although, all the requirements can be downloaded via pip.

**Comment by khalibartan** [comment]
@kshitij10496 Okay, I thought we can install pgmpy with it.

**Comment by kshitij10496** [comment]
@khalibartan Right now, we cant.
But it would be really cool if we could have.

**Comment by ankurankan** [comment]
@saketkc @kshitij10496 @khalibartan We really need to host on both pypi and conda. I will try to do this ASAP.

**Comment by kshitij10496** [comment]
@ankurankan That's really good.
If you need any assistance with this, just let me know

**Comment by khalibartan** [comment]
this works
`pip install https://github.com/pgmpy/pgmpy/archive/dev.zip`

**Comment by kshitij10496** [comment]
@ankurankan Can you please update the status of this ?

**Comment by ankurankan** [comment]
@kshitij10496 I haven't started working on this yet.

**Comment by khalibartan** [comment]
@ankurankan What's the status of this. If you are busy, then I can work on this if you want.

**Comment by pdoongarwal** [comment]
@ankurankan @khalibartan  Whats the status of this?

**Comment by khalibartan** [comment]
@ankurankan Label it as an priority issue. We need its support ASAP.

**Comment by khalibartan** [comment]
@saketkc @kshitij10496 @pdoongarwal We finally have pgmpy on PyPI , https://pypi.python.org/pypi/pgmpy/0.1.2 :smile:

**Comment by ankurankan** [comment]
Actually the latest link is https://pypi.python.org/pypi/pgmpy/0.1.2. And closing this.
