### ISSUE TITLE
Remove all local import statements

### ISSUE THREAD

**Issue by yashu-seth** [pgmpy/pgmpy#546]
[PEP8](http://www.python.org/dev/peps/pep-0008/)
Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.

**Comment by khalibartan** [comment]
@ankurankan I'm going through pgmpy codes , so I'll remove this local import statements and also remove bugs in doc-strings . I found that some Examples in doc-strings were not working examples, and some had bugs in it . So I'll send a pull for this . Also in many doc strings examples outputs are not shown , should I add outputs of them ?

**Comment by ankurankan** [comment]
@khalibartan Yes please do add the outputs.

**Comment by khalibartan** [comment]
@ankurankan And for local import statments, should I remove them and add to the starting or let it remain as such ?

**Comment by ankurankan** [comment]
@khalibartan Yes please do that. Also keep in mind that there might be some local imports to avoid cyclic imports. Just don't change those, the rest you can put at the top of the files.

**Comment by kshitij10496** [comment]
@khalibartan Can you share the status of this issue ?
If you are not working on this currently, I can give this a try.

**Comment by khalibartan** [comment]
@kshitij10496 I have paused the work because I have already opened two PR and ankur wasn't active. I'll resume the work back now.
Can you remove local import statements from BayesianModel class , since you are working on it .

**Comment by khalibartan** [comment]
@kshitij10496 Actually You can fix this issue, if you want. Currently I'm gaining some background in PGM's so reading codebase before will not help much.You can leave factor and related classes. I have fixed bugs in them.

**Comment by kshitij10496** [comment]
@khalibartan Cool.
I will try to fix the rest of the codebase

**Comment by ankurankan** [comment]
@kshitij10496 @khalibartan What's the status of this ?

**Comment by kshitij10496** [comment]
I am currently working on `models` module.
Will update soon

**Comment by piyushsoni27** [comment]
@ankurankan @yashu-seth @khalibartan Hello, I am a new developer. I would like to work on this.Is this still open?

**Comment by khalibartan** [comment]
@piyushsoni27 Sure go ahead. But before committing anything read the this [comment](https://github.com/pgmpy/pgmpy/issues/546#issuecomment-166850200)
