### ISSUE TITLE
New issues need to be labelled

### ISSUE THREAD

**Issue by yashu-seth** [pgmpy/pgmpy#559]
There are many issues that have not been tagged. It would be very useful for newcomers if they find issues labelled.

**Comment by kshitij10496** [comment]
Absolutely.
The issues need to be labelled for better issue tracking

**Comment by ankurankan** [comment]
@yashu-seth @kshitij10496 Can you guys come up with a list of issues which need to be tagged? And also let's move this discussion to the mailing list.

**Comment by yashu-seth** [comment]
@ankurankan okay. will do it.
