### ISSUE TITLE
Bug in hash method for factor class

### ISSUE THREAD

**Issue by khalibartan** [pgmpy/pgmpy#574]
The current implementation takes order into account in the case where it shouldn't

```
In [10]: phi1 = Factor(['x2','x1'], [2,2], [1,3,2,4])

In [11]: phi = Factor(['x1','x2'], [2,2], [1,2,3,4] )

In [12]: hash(phi)
Out[12]: -8224978590549700758

In [13]: hash(phi1)
Out[13]: 851726010497848334

In [14]: phi1 == phi
Out[14]: True

In [18]: print(phi)
╒══════╤══════╤══════════════╕
│ x1   │ x2   │   phi(x1,x2) │
╞══════╪══════╪══════════════╡
│ x1_0 │ x2_0 │       1.0000 │
├──────┼──────┼──────────────┤
│ x1_0 │ x2_1 │       2.0000 │
├──────┼──────┼──────────────┤
│ x1_1 │ x2_0 │       3.0000 │
├──────┼──────┼──────────────┤
│ x1_1 │ x2_1 │       4.0000 │
╘══════╧══════╧══════════════╛

In [19]: print(phi1)
╒══════╤══════╤══════════════╕
│ x2   │ x1   │   phi(x2,x1) │
╞══════╪══════╪══════════════╡
│ x2_0 │ x1_0 │       1.0000 │
├──────┼──────┼──────────────┤
│ x2_0 │ x1_1 │       3.0000 │
├──────┼──────┼──────────────┤
│ x2_1 │ x1_0 │       2.0000 │
├──────┼──────┼──────────────┤
│ x2_1 │ x1_1 │       4.0000 │
╘══════╧══════╧══════════════╛

```

As per my understanding it should have been the same.

**Comment by khalibartan** [comment]
@ankurankan @yashu-seth Am I wrong here ?

**Comment by yashu-seth** [comment]
@khalibartan I also think that it should not take order into account.

**Comment by ankurankan** [comment]
@khalibartan You are right. Both should give the same hash value. @khalibartan @yashu-seth Would any of you like to fix this ?

**Comment by khalibartan** [comment]
@ankurankan I can think of only one implementation and that happens to be quite slow. I'll try to replicate what ` _str ` does and then optimally apply the hash function. But since `__hash__` method has to be used frequently I want its implementation to be robust and fast too. This implementation will be as good as python hash methods in terms of robustness but will be slow. Do you have any other implementation in mind .

**Comment by yashu-seth** [comment]
@khalibartan I can work on this. Please tell me if you are not working on it.

**Comment by khalibartan** [comment]
@yashu-seth I have begin working on it. And was about to send a PR.

**Comment by yashu-seth** [comment]
@khalibartan Fine.

**Comment by khalibartan** [comment]
Fixed,
