### ISSUE TITLE
Update README.md and AUTHORS.rst

### ISSUE THREAD

**Issue by khalibartan** [pgmpy/pgmpy#583]
The current README.md is not interactive . Also it doesn't contain a section refering to our [contributing guide](https://github.com/khalibartan/pgmpy/blob/dev/Contributing.md) for new developers. Apart from it change the **dependencies section of python versions** , we now have support for **2.7, 3.3 and 3.4** . And add a better guide on **how to install**. Break the examples section into small parts. Add a section on how to test the code base . In the last section of README.md add which particular **lisence** we use, also **links to tutorials and books** etc for probabilistic graphical models. You can take a reference from [scikit-learn](https://github.com/scikit-learn/scikit-learn) or [sympy](https://github.com/sympy/sympy) for some of the later points .

AUTHORS.rst also needs to update. Relabel the core-contributors section by organisation admins , and put all other contributors to an another section named Contributors .

**Comment by ankurankan** [comment]
@kshitij10496 @khalibartan @yashu-seth Can any one of you guys work on this ?

**Comment by yashu-seth** [comment]
@ankurankan @khalibartan I'll send a PR.

**Comment by khalibartan** [comment]
@yashu-seth Okay cool. I just began working on it, but you can send a PR. I'll be obliged if you fix this. Do add welcoming message , and write a line that our community is welcoming and helpful . Also create and download section and add a line that we are not yet hosted on pypi or conda. Add link to zip file and line on how to clone it.

**Comment by yashu-seth** [comment]
@khalibartan I am planning to put the contributors in order of the date of their first contribution.

**Comment by khalibartan** [comment]
@yashu-seth here is a git command that can help you 
`git log --topo-order --reverse --format="%aN <%aE>" | awk ' !x[$0]++'`.
Though this will need some edits.
Also there might be other options instead of mails and name.

**Comment by khalibartan** [comment]
@yashu-seth http://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History
Here is the options. If you want to add, you can add links to their github profile.

**Comment by yashu-seth** [comment]
@khalibartan thanks.

**Comment by khalibartan** [comment]
Fixed.
