### ISSUE TITLE
Landscape not working.

### ISSUE THREAD

**Issue by yashu-seth** [pgmpy/pgmpy#587]
Landscape is checking code quality forever.

**Comment by ankurankan** [comment]
@yashu-seth Looks like a bug in landscape. There's nothing that we can do. Closing this.

**Comment by liquidmetal** [comment]
@ankurankan What do you think about disconnecting landscape.io until it gets fixed?

**Comment by ankurankan** [comment]
@liquidmetal I don't think we need to. Not affecting us in any way.
