### ISSUE TITLE
Remove pandas dependency

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#594]
We are using pandas just to keep a track on which column of the array correspond to which variable. 
For example in the case of sampling we return a pandas dataframe with the samples generated. Something like this:

``` python
    A    B    C
0   1    0    1
1   0    0    1
2   1    1    1
.....
```

We should replace it with just a numpy array and a list of variable names. We can define an object which has two properties `variables` and `values`. Something like this:

``` python
sampling_results.variables = ['A', 'B', 'C']
sampling_results.values = [[1, 0, 1],
                           [0, 0, 1],
                           [1, 1, 1]
                           ....    ]
```

**Comment by khalibartan** [comment]
@ankurankan I believe you can label it as an easy issue.

**Comment by yashu-seth** [comment]
@ankurankan I can look into this. So instead of pandas dataframe we want a complete class to hold such data only using numpy arrays. I was thinking something similar with `MaximumLikelihoodEstimator.get_parameters()` mentioned in #579. Can you please have a look at that too.

**Comment by yashu-seth** [comment]
@ankurankan I believe pandas dependency can be removed in a lot of other places as well. We can keep it as an optional input type for methods.

**Comment by khalibartan** [comment]
@yashu-seth I don't think we are highly dependent on pandas. So yes we can easily do that.

**Comment by khalibartan** [comment]
@ankurankan I think we can close this issues as it is similar to #703

**Comment by yashu-seth** [comment]
@ankurankan @khalibartan Yes. And I think #596 can be closed too.

**Comment by ankurankan** [comment]
Ref #703
