### ISSUE TITLE
Refactor TabularCPD

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#595]
Currently `TabularCPD` has the these attributes: `variable`, `variable_card`, `evidence`, `evidence_card`.
And since it inherits `Factor`, it also has: `variables`, `cardinality` and `values`. 

`evidence` and `evidence_card` can be easily derived if we know other attributes. And since we are not directly using `evidence` or `evidence_card` too many times, we can remove these two and compute these when needed. Right now `evidence` and `evidence_card` is adding overhead in a lot of operations because we need to update these as well as `variables` and `cardinality`.

**Comment by ankurankan** [comment]
@anaviltripathi Would you like to work on this ?

**Comment by anaviltripathi** [comment]
@ankurankan Yeah sure. If you want to add something else, i.e., some other property that was not there before now would be a good time to make that change. Suggest if you something else also in mind.
Also some methods are using these redundant variables in some peculiar ways. I will tell about those in this thread only.

**Comment by khalibartan** [comment]
@anaviltripathi Updates on this.

**Comment by anaviltripathi** [comment]
@khalibartan I have been a little busy the past week. I have started working on this now.

**Comment by anaviltripathi** [comment]
@ankurankan @khalibartan  
I noticed that we are accepting `set` also as data type of `evidence` and `evidence_card`. I don't think that it is correct as there won't be any way to evidence and its corresponding cardinality due the unordered nature of set. 
Should I remove this?

**Comment by khalibartan** [comment]
@anaviltripathi You are right, there is ambiguity here. In my views you can remove but you can leave it till @ankurankan  gives his views.
Can you tell me, what implementation you have in your mind, about how you are going to tackle this issue ? I believe there will be some design issues to be taken.

**Comment by anaviltripathi** [comment]
@khalibartan No, I think it is not that big change. I was considering of just removing the `set` support, it won't affect any other part of the code. 
Other than this removing `evidence` and `evidence_card` as suggested by @ankurankan is a design choice which involves overhead of calculation in some methods that mostly deal with [representing](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/factors/CPD.py#L184) the table in a particular way or format. 
I was of the opinion of removing these two parameters too. But now after starting working on this I am not too sure. Overhead of calculating these from `self.variables` and `self.cardinality` is not that much as we just need simple slicing of lists. But, having separate `self.evidence` and `self.evidence_card` makes things cleaner. 
What do you think?
One more thing, when do you think [this](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/factors/CPD.py#L167) condition would not be true. Considering how we initialize I can't think of anyway this would ever be false. I also couldn't find any other method that would make this condition check necessary.

**Comment by khalibartan** [comment]
@anaviltripathi I haven't seen the code of CPD earlier. I don't there is a lot of overhead attached with these arguments (`evidence` and `evidence_card`) . And actually I didn't wanted to remove the `evidence` and `evidence_card` as input, because we would have to do changes in quite a few other places. 
The condition mentioned by that line wouldn't be false, unless someone try to `reduce` the `self.variable` inplace.

**Comment by anaviltripathi** [comment]
@khalibartan I am not going forward on this then, until @ankurankan comments.

**Comment by ankurankan** [comment]
@anaviltripathi @khalibartan We shouldn't be supporting set. 
I want to remove `evidence` and `evidence_card` because right now we have change 4 properties: `evidence`, `evidence_card`, `variables` and `variable_card` whenever there is some change in the variables and this adds unnecessary overhead. What do you guys think?

**Comment by anaviltripathi** [comment]
@ankurankan I am of the opinion that we should leave it as it is. As I said in a previous comment, it is a trade-off, in some methods you will need to calculate `evidence`, `evidence_card` and at others you need to update this. But, considering what a Tabular CPD represents in the real world, I think it makes more sense to have separate attributes `evidence` and `evidence_card`, even if they are redundant due to inheritance from `Factor`.
It is just a matter of choice. But, I don't know that how much overhead it really costs in actual usage scenarios. If it is too much we should definitely not keep these. It is a waste of space and time both.

**Comment by ankurankan** [comment]
@anaviltripathi Yes it makes it more clearer but we are hardly using these attributes directly (used 4 times directly in our whole current codebase) but we are adding the overhead to update these in `marginalize` and `reduce` methods which are used much more often than that. So, I strongly feel like we should remove both `evidence` and `evidence_card`.  What do you think?

**Comment by anaviltripathi** [comment]
@ankurankan Alright then. I will work on this. Also, I had noticed that error in #627 but as these parameters will be removed that issue be implicitly resolved along with this right?

**Comment by ankurankan** [comment]
@anaviltripathi Yes, have mentioned it there.

**Comment by anaviltripathi** [comment]
@ankurankan Can be closed.
