### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by pdoongarwal** [pgmpy/pgmpy#601]
I used setup.py to install pgmpy after installing the dependencies and following packages were not 
installed automatically and and were not marked in dependencies
- mock
- pyparsing

**Comment by Ashutosh-Adhikari** [comment]
Hi , @pdoongarwal ..
I faced a similar problem..
Check whether you have the same version of Libraries(especially scipy) installed as per the "requirements.txt" ..
As a result , it will also fail some of the nosetests.

**Comment by pdoongarwal** [comment]
@Ashutosh-Adhikari I switched to python3.4, installed all the dependencies once again including mock and pyparsing.
After that it installed successfully.

**Comment by mvnnn** [comment]
check your mock version `mock==1.3.0`.if you install using `conda` env then it's very easy for you
because it's include all necessary dependency so you not need to install that dependency sepratly. any version of scipy (>0.16.0) are working fine.

**Comment by khalibartan** [comment]
@ankurankan This can be closed now.

**Comment by khalibartan** [comment]
Refer #616
