### ISSUE TITLE
TypeError raised on my windows 64 platform with python3.4

### ISSUE THREAD

**Issue by pheman** [pgmpy/pgmpy#602]
I test the simple example on the tutorials, however a fatal TypeError raised, associated with int int32 and int64. 
If I comment the corresponding TypeError check in Factor.py Line 99, no errors will occur although the final results is completely wrong. I guess there is some serious bugs behind this simple TypeError.

Same error can be also find in 
Bugs in MaximumLikelihoodEstimator.get_parameters() #579
Any comments is welcome!

My environment is:
Windows 7 64
python 3.4
numpy 1.10,1
pandas 0.16.2

The traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 705, in debugfile
    debugger.run("runfile(%r, args=%r, wdir=%r)" % (filename, args, wdir))
  File "D:\Anaconda3\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)
  File "D:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "d:/onebox/pythonprojects/bayesian/bayesian_test.py", line 18, in <module>
    model.fit(values)
  File "D:\Anaconda3\lib\site-packages\pgmpy\models\BayesianModel.py", line 570, in fit
    cpds_list = estimator.get_parameters()
  File "D:\Anaconda3\lib\site-packages\pgmpy\estimators\MLE.py", line 75, in get_parameters
    evidence_card=parent_card.astype('int'))
  File "D:\Anaconda3\lib\site-packages\pgmpy\factors\CPD.py", line 139, in **init**
    super(TabularCPD, self).**init**(variables, cardinality, values.flatten('C'))
  File "D:\Anaconda3\lib\site-packages\pgmpy\factors\Factor.py", line 100, in **init**
    raise TypeError("Values: Expected type int or type float, got ", values.dtype)
TypeError: ('Values: Expected type int or type float, got ', dtype('int64'))

**Comment by khalibartan** [comment]
@pheman Please give more details of environment and the example you were using. If it is a similar error to what mentioned in #579 we didn't got it. But let me build a new env from scratch because now two people have reported it.

**Comment by pheman** [comment]
@khalibartan Thanks for your prompt reply.
My environment:
Windows 7 SP1 win32
Python 3.4.3 | Anaconda 2.3.0 (64-bit) MSC v.1600 64 bit (AMD64)
numpy=1.10,1
pandas=0.16.2
networkx=1.9.1
scipy=0.16.0
pyparsing=2.0.3
mock==1.0.1

The simple script is like this:
#################################
import numpy as np
import pandas as pd
from pgmpy.models import BayesianModel

values = pd.DataFrame(np.random.randint(low=0, high=2, size=(1000, 5)),
                      columns=['A','B','C','D','E'])
train_data = values[:800]
predict_data0 = values[800:]

model = BayesianModel([('A','B'),('C','B'),('A','B'),('C','D'),('B','E')])
model.fit(values)
predict_data = predict_data0.copy()
predict_data.drop('E', axis=1, inplace=True)
y_pred = model.predict(predict_data)
y_pred

**Comment by khalibartan** [comment]
@pheman  Okay I installed pgmpy from scratch. Here is my conda env configurations

```
 packages in environment at /home/utgup/anaconda3/envs/pgmpy:
#
anaconda-client           1.2.2                    py34_0    defaults
clyent                    1.2.0                    py34_0    defaults
coverage                  4.0.3                     <pip>
coveralls                 1.1                       <pip>
decorator                 4.0.6                    py34_0    defaults
docopt                    0.6.2                     <pip>
funcsigs                  0.4                      py34_0    defaults
ipython                   4.0.3                    py34_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py34_0    defaults
libgfortran               1.0                           0    defaults
mock                      1.3.0                    py34_0    defaults
networkx                  1.10                     py34_0    defaults
nose                      1.3.7                    py34_0    <unknown>
numpy                     1.9.2                    py34_2    defaults
openblas                  0.2.14                        3    defaults
openssl                   1.0.2e                        0    defaults
pandas                    0.16.2               np19py34_0    defaults
path.py                   8.1.2                    py34_1    defaults
pbr                       1.3.0                    py34_0    defaults
pexpect                   3.3                      py34_0    defaults
pgmpy                     0.1.0                     <pip>
pickleshare               0.5                      py34_0    defaults
pip                       8.0.1                    py34_0    defaults
pyparsing                 2.0.3                    py34_0    <unknown>
python                    3.4.4                         0    defaults
python-dateutil           2.4.2                    py34_0    <unknown>
pytz                      2015.7                   py34_0    defaults
pyyaml                    3.11                     py34_1    <unknown>
readline                  6.2                           2    <unknown>
requests                  2.9.1                    py34_0    defaults
scipy                     0.16.0               np19py34_1    defaults
setuptools                19.4                     py34_0    defaults
simplegeneric             0.8.1                    py34_0    defaults
six                       1.10.0                   py34_0    defaults
sqlite                    3.9.2                         0    defaults
tk                        8.5.18                        0    <unknown>
traitlets                 4.1.0                    py34_0    defaults
wheel                     0.26.0                   py34_1    defaults
xz                        5.0.5                         0    <unknown>
yaml                      0.1.6                         0    <unknown>
zlib                      1.2.8                         0    <unknown>
```

I ran you script and I didn't found any issues at all. Here is the output

```
     E
800  0
801  0
802  0
803  0
804  0
805  0
806  0
807  0
808  0
809  0
810  0
811  0
812  0
813  0
814  0
815  0
816  0
817  0
818  0
819  0
820  0
821  0
822  0
823  0
824  0
825  0
826  0
827  0
828  0
829  0
..  ..
970  0
971  0
972  0
973  0
974  0
975  0
976  0
977  0
978  0
979  0
980  0
981  0
982  0
983  0
984  0
985  0
986  0
987  0
988  0
989  0
990  0
991  0
992  0
993  0
994  0
995  0
996  0
997  0
998  0
999  0
```

**Comment by pheman** [comment]
@khalibartan What's your system version? Windows or Unix? 32bit or 64bit? I'm quite sure that the dtype on my environment is np.int64,. Since np.int64 != int, there raised a TypeError in Factor.py.

Besides, all the output are 0? Is it reasonable? I means the supposed output is random integer among [0, 1].

**Comment by khalibartan** [comment]
My system version is Ubuntu -15.04 64-bit. And for eg it is working, okay I re ran it and it gave a different output 

```
     E
800  1
801  1
802  1
803  0
804  0
805  0
806  1
807  0
808  1
809  1
810  0
811  0
812  1
813  0
814  0
815  1
816  0
817  0
818  1
819  0
820  0
821  0
822  0
823  0
824  1
825  0
826  0
827  0
828  1
829  0
..  ..
970  0
971  0
972  1
973  1
974  0
975  1
976  1
977  0
978  1
979  0
980  0
981  0
982  0
983  1
984  1
985  1
986  0
987  0
988  1
989  0
990  1
991  1
992  1
993  0
994  1
995  0
996  1
997  0
998  0
999  0
```

**Comment by pheman** [comment]
I think it's the key point. According to my test, values.dtype = np.int64 after the sentence in Line72, MLE.py,
values = self.data.groupby([node] + parents).size().unstack(parents).fillna(0).

It seems that pandas returns int64 data type automatically after this sentence. 
As well as Line 64,
state_counts = state_counts.reindex(sorted(state_counts.index)).

Anyway, I think it's a minor bug for Windows system. But we should make sure the result is correct.

**Comment by khalibartan** [comment]
We are facing some issues with pandas, so we are removing it from our dependency . You can issue #594 . We will get the support ASAP. But I don't find any errors mentioned by you.
Ping @ankurankan Can you try it ?

**Comment by pheman** [comment]
You are right. I get the correct results after I re-run the script.
It's quite strange that it seems that we will always get the incorrect results when we first run the code.
Is it?

**Comment by pheman** [comment]
Something problems related to the random seed? @khalibartan

**Comment by pheman** [comment]
Since the dataset is generated randomly, maybe the model can not learn any useful information from the dataset. It's not so terrible for the all zeros results.

**Comment by khalibartan** [comment]
Yes. Random numbers generated are psudo random, there is covariance attached with them. So sometimes with high covariance , we might be able to learn a relation. But you cannot comment on the results to be correct or incorrect because we don't know whether there is something to learn or not.

**Comment by yashu-seth** [comment]
@pheman I get the same error on my windows system. But I could not get a proper solution. Anyways we will be soon removing the pandas dependency.

**Comment by khalibartan** [comment]
I'll run the example on a windows machine and let you know if I got the same error.

**Comment by pheman** [comment]
@yashu-seth  I suggest you re-run the same script in the same console, then it's supposed to get the proper solution. Or try to load a real dataset, since the dataset in my script is generated randomly. The model can not learn any useful information from the random dataset.

**Comment by pheman** [comment]
@yashu-seth  Of course, you should first comment the Data Type check sentence which can be located according to the traceback information.

**Comment by pheman** [comment]
You can check & test my fork version.

**Comment by yashu-seth** [comment]
@pheman Thanks. I'll look into it.

**Comment by khalibartan** [comment]
@ankurankan Fixed, can be closed now.
