### ISSUE TITLE
Unable to run `nosetests` inside a `virtualenv` because of missing dependencies in requirements.txt

### ISSUE THREAD

**Issue by liquidmetal** [pgmpy/pgmpy#615]
To enable running `nosetests` within virtual environments, we need to add new dependencies to requirements.txt. Here is the list:
- nose==1.3.1
- coverage==4.0.3 (if you want to generate coverage reports)

This would ensure that running `nosetests` will run nose from the current virtualenv.

However, I'm not sure if we should have dev dependencies within `requirements.txt`. I can see `mock==1.3.0` in there which does not seem appropriate. I think we should have a separate file called `test-requirements.txt` that contains such secondary requirements[1].

[1] http://nvie.com/posts/pin-your-packages/

**Comment by ankurankan** [comment]
Fixed.
