### ISSUE TITLE
pgmpy examples

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#620]
Need to add examples on using pgmpy using some real data (something like what scikit has: https://github.com/pgmpy/pgmpy/tree/dev/examples).

**Comment by viswaraavi** [comment]
Can I work on this?

**Comment by yashu-seth** [comment]
@viswaraavi I think yes. Although get it confirmed with @ankurankan. You will need to have a sound knowledge of the inference algorithms and other parts of the library as well. So it might not be an easy issue if you are new to PGMs.

**Comment by viswaraavi** [comment]
I am not new to PGMs but I am new to pgmpy. so I will give a try

**Comment by yashu-seth** [comment]
@viswaraavi Fine.

**Comment by AMAN3003** [comment]
@ankurankan  AND @yashu-seth  i have a good knowledge of algorithms can  I work on this issue

**Comment by yashu-seth** [comment]
@AMAN3003 Yes, you can. Just check with @viswaraavi, if he has also started working maybe then you can work on separate examples.

**Comment by viswaraavi** [comment]
I did not start working but I am thinking to work on example related to image segmentation

**Comment by yashu-seth** [comment]
@AMAN3003 @viswaraavi You can discuss your example ideas with @ankurankan.

**Comment by khalibartan** [comment]
There is kaggle dataset available for image denoising, https://www.kaggle.com/c/denoising-dirty-documents . It would be great if some can demonstrate an example using the dataset available.

**Comment by AMAN3003** [comment]
@ankurankan  here is the first application which I added from your case study please review it and merge it
https://github.com/AMAN3003/pgmpy/commit/ba336cee53113049e37ed2eb8833f6e435c08f6c
It getting coverage error could you suggest how to correct it

**Comment by AMAN3003** [comment]
@yashu-seth @khalibartan  provide me some documentation related to pgmpy application so that I can make real examples .and also how pgmpy can be used

**Comment by khalibartan** [comment]
@AMAN3003   We have document at http://pgmpy.org/ you can go there and look at it.
