### ISSUE TITLE
Questions on TabularCPD

### ISSUE THREAD

**Issue by harrywang** [pgmpy/pgmpy#632]
Hi guys, I bought your book and I have two questions as follows:
- how can I add labels instead of 0, 1, 2 for nodes, such as easy for 0 and hard for 1:
  `cpd_difficulty = TabularCPD('difficulty', 2, [[0.6], [0.4]])`

![screenshot 2016-02-16 17 38 03](https://cloud.githubusercontent.com/assets/595772/13093571/1058073c-d4d4-11e5-8e01-9781636786fb.png)

Given the CPDs as follows:

```
cpd_difficulty = TabularCPD('difficulty', 2, [[0.6], [0.4]])
cpd_intelligence = TabularCPD('intelligence', 2, [[0.7], [0.3]])
cpd_sat = TabularCPD('sat', 2, [[0.95, 0.2], 
                                [0.05, 0.8]], evidence=['intelligence'], evidence_card=[2])
cpd_grade = TabularCPD('grade', 3, [[0.3, 0.05, 0.9, 0.5],
                                    [0.4, 0.25, 0.08, 0.3],
                                    [0.3, 0.7, 0.02, 0.2]],
                       evidence=['difficulty', 'intelligence'], evidence_card=[2, 2])
cpd_letter = TabularCPD('letter', 2, [[0.1, 0.4, 0.99], [0.9, 0.6, 0.01]], evidence=['grade'], evidence_card=[3])
```

![screenshot 2016-02-16 17 32 11](https://cloud.githubusercontent.com/assets/595772/13093634/75b9af5e-d4d4-11e5-88a9-fe07dd0b56bd.png)
- how can I get the answer for the following question: what's the probability that an applicant is intelligent, received a strong letter from a professor in a difficult class where he got an "A" and has a high SAT score. 

I only know how to query certain variables as follows:

`prob_grade_easy_smart = student_infer.query(['grade'], {'difficulty':0, 'intelligence':1})`

Thanks!

Harry

**Comment by yashu-seth** [comment]
@harrywang Unfortunately, we do not support adding labels to variables for now. It is a feature that we would like to have in the near future. You can have a look at [Add feature for storing the state name of the random variables.](https://github.com/pgmpy/pgmpy/issues/232)

**Comment by harrywang** [comment]
Thanks @yashu-seth , any idea on my second question above?

**Comment by harrywang** [comment]
FYI, there is gRain package for R https://cran.r-project.org/web/packages/gRain/index.html and I am trying to use pgmpy to do what gRain can do in R.

**Comment by yashu-seth** [comment]
@harrywang 
This has to be done by assuming particular states for particular variable types.
In the example above, I will assume that lower states represent lesser intensity features. Which means difficulty_0 is the least difficult and difficulty_1 is the most. Similarly, for intelligence, sat, letter and grade variables too. (Of course you might have assigned representation differently.  Any initial assumption is fine but you will have to stick with your initial choice.)

intelligent (assuming high) state-1.
strong letter (state-1)
difficult (assuming high difficulty) (state-1)
grade A (grade-2)
high SAT (sat-1)

Hence the required evidence dictionary would be - 

``` python
evidence_dict = {'letter':1, 'difficulty':1, 'grade':2, 'sat':1}
```

And the required query is being done for the `intelligence` variable. Hence,

``` python
phi_query = student_infer.query(['intelligence'], evidence=evidence_dict)
```

This will return a dictionary with keys as variables given in the query, in this case it will have `intelligence` as a key.
Hence,

``` python
phi_query['intelligence']
```

It will give you a factor from which you can have the required variable state probability.
