### ISSUE TITLE
Page 97 example error

### ISSUE THREAD

**Issue by pwaila** [pgmpy/pgmpy#633]
From the book mastering Probablistic model using python

when i am running following program 

`import numpy as np
import pandas as pd
from pgmpy.models import BayesianModel

data = np.random.uniform(low=0, high=2, size=(1000, 4)).astype('float')
data

data = pd.DataFrame(data, columns=['cost', 'quality',
'location',
'no_of_people'])

train = data[:750]
test = data[750:].drop('no_of_people', axis=1)

restaurant_model = BayesianModel(
[('location', 'cost'),
('quality', 'cost'),
('location', 'no_of_people'),
('cost', 'no_of_people')])

restaurant_model.fit(train)`

The following error is being generated:

> SEEMS SOME TYPE ERROR (TypeError: ('Values: Expected type int or type float, got ', dtype('int64')))

---

TypeError                                 Traceback (most recent call last)
<ipython-input-33-8e3a85cb8b56> in <module>()
----> 1 restaurant_model.fit(train)

C:\Users\pranav.waila\AppData\Local\Continuum\Anaconda3\lib\site-packages\pgmpy\models\BayesianModel.py in fit(self, data, estimator_type)
    568         estimator = estimator_type(self, data)
    569 
--> 570         cpds_list = estimator.get_parameters()
    571         self.add_cpds(*cpds_list)
    572 

C:\Users\pranav.waila\AppData\Local\Continuum\Anaconda3\lib\site-packages\pgmpy\estimators\MLE.py in get_parameters(self)
     64                 state_counts = state_counts.reindex(sorted(state_counts.index))
     65                 cpd = TabularCPD(node, self.node_card[node],
---> 66                                  state_counts.values[:, np.newaxis])
     67                 cpd.normalize()
     68                 parameters.append(cpd)

C:\Users\pranav.waila\AppData\Local\Continuum\Anaconda3\lib\site-packages\pgmpy\factors\CPD.py in **init**(self, variable, variable_card, values, evidence, evidence_card)
    137             raise TypeError("Values must be a 2D list/array")
    138 
--> 139         super(TabularCPD, self).**init**(variables, cardinality, values.flatten('C'))
    140 
    141     def **repr**(self):

C:\Users\pranav.waila\AppData\Local\Continuum\Anaconda3\lib\site-packages\pgmpy\factors\Factor.py in **init**(self, variables, cardinality, values)
     98 
     99         if values.dtype != int and values.dtype != float:
--> 100             raise TypeError("Values: Expected type int or type float, got ", values.dtype)
    101 
    102         if len(cardinality) != len(variables):

TypeError: ('Values: Expected type int or type float, got ', dtype('int64'))

**Comment by khalibartan** [comment]
@pwaila Are you on windows platform, same error has been reported, when user were using windows platform, PR #604 is dealing with it.

**Comment by pwaila** [comment]
yes i am on windows platform

**Comment by ankurankan** [comment]
@pwaila This should be fixed now. Please try installing the latest version.
