### ISSUE TITLE
IndependenceAssertion('X','Y','Z') == IndependenceAssertion('X','Z','Y')

### ISSUE THREAD

**Issue by chrisittner** [pgmpy/pgmpy#639]
```
>>> from pgmpy.independencies import IndependenceAssertion
>>> IndependenceAssertion('X','Y','Z') == IndependenceAssertion('X','Z','Y')
True
```

This should evaluate to `False`.

**Comment by khalibartan** [comment]
Yeah, bug is at here https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/independencies/Independencies.py#L209 , we should only consider `self.event1` and `self.event2` in unordered form, not `self.event3` too. Can you fix it. Fix is fairly easy.

**Comment by chrisittner** [comment]
Yep :).

**Comment by khalibartan** [comment]
Close this issue.
