### ISSUE TITLE
Another Marginalize and reduce issue.

### ISSUE THREAD

**Issue by anaviltripathi** [pgmpy/pgmpy#652]
As I have mentioned this particular issue in some other PRs. I think marginalize and reduce should not be allowed to modify the CPD inplace if the user wants to reduce/marginalize with respect to the main variable itself.
I think so because after such operation I am not able to comprehend the meaning of the new CPD. Also, it would give errors on further operations if this allowed. I think @khalibartan agrees with me on this.
@ankurankan If you could give your views on this.

**Comment by ankurankan** [comment]
@anaviltripathi Yes you are right we shouldn't allow operations on the variable on which it's defined as it makes no sense. Please go ahead with this.
