### ISSUE TITLE
Bug in hash method of Factor

### ISSUE THREAD

**Issue by abhilashrj** [pgmpy/pgmpy#661]
In test_Factor.py, the following test gives the error.

``` python
var1 = Test(1, 2)
var2 = ('x2', 1)
var3 = frozenset(['x1', 'x2'])
phi3 = Factor([var1, var2, var3], [2, 4, 3], range(24))
phi4 = Factor([var2, var1, var3], [4, 2, 3],
              [0, 1, 2, 12, 13, 14, 3,
              4, 5, 15, 16, 17, 6, 7,
              8, 18, 19, 20, 9, 10, 11,
              21, 22, 23])
self.assertEqual(hash(phi3), hash(phi4))
```

The error:

```
Traceback (most recent call last):
  File "/home/abhilash/FOSS/pgmpy/pgmpy/tests/test_factors/test_Factor.py", line 452, in test_hash
    self.assertEqual(hash(phi3), hash(phi4))
  File "/home/abhilash/FOSS/pgmpy/pgmpy/factors/Factor.py", line 786, in __hash__
    variables = sorted(self.variables)
TypeError: unorderable types: tuple() < Test()
```

**Comment by ankurankan** [comment]
@abhi95 Can you please add what `Test` is ?

**Comment by abhilashrj** [comment]
```
class Test:
            def __init__(self, x, y):
                self.x = x
                self.y = y

            def __hash__(self):
                return hash(str(self.x)+str(self.y))

            def __eq__(self, other):
                return isinstance(other, self.__class__) and self.x == other.x and self.y == other.y
```

**Comment by abhilashrj** [comment]
@ankurankan I have the following implementation in mind.
Sort the variables based on their datatype first, later sort them based on values they have. Something like this.

```
var_data_types = [(str(type(var)), var) for var in self.variables]
var_data_types = sorted(var_data_types, key=lambda element: (element[0], element[1]))
variables = [var[1] for var in var_data_types]

```

But this wont work if two custom hashable objects have not implemented cmp method.

**Comment by abhilashrj** [comment]
@ankurankan What can be done regarding custom objects of same class which cannot be ordered?

**Comment by ankurankan** [comment]
@abhi95  We are sorting all the variables here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/factors/Factor.py#L783. One possible solution can be convert everything into a string before doing the sort. And for a custom object we can use it's hash value. Just think if this fails in some case.

**Comment by khalibartan** [comment]
It will fail if our tuples are like `(1, '1')` and `('1', 1)` , but since its not gonna happen, I think this will work fine

**Comment by abhilashrj** [comment]
@khalibartan I don't see how it fails in the case u mentioned, I checked by altering positions of those two tuples seems to work fine.
@ankurankan Thanks for the input.
Regarding distinguishing objects as built in or custom. Can I use the following output 
`type(custom-obj) = <class  '__main__.class_name'`
`type(built-in) = <class 'class_name'>`
I mean the extra `__main__`  part can be used.

**Comment by khalibartan** [comment]
@abhi95 `(1, '1')` and `('1', 1)` are two different things and should return a different hash value. Consider if you convert everything to string , than it should be `('1', '1')` and `('1', '1')` (both of them will have same hash values), or I'm thinking wrong here, did you guys mean `'('1', 1)'` and `'(1, '1')'` things will be fine like this.

**Comment by abhilashrj** [comment]
@khalibartan They do return different hash values. Since `'('1', 1)'` and `'(1, '1')'` are different.

**Comment by khalibartan** [comment]
Yes they are different. Read the first line of comment. I was confused of how things are being impelemented

**Comment by khalibartan** [comment]
@ankurankan I believe better thing would be get hash value of everything, and sort these hash values.
Am I right or wrong here. It will be collision free, and also no need of typecasting, and since our variables are any hashable objects. I don't see any issues.

**Comment by abhilashrj** [comment]
@khalibartan That seems to be a good idea. I agree here.

**Comment by ankurankan** [comment]
@khalibartan Yes, that's the simplest way I can think of. @abhi95 Please go ahead with this.

**Comment by yashu-seth** [comment]
@ankurankan This can be closed.
