### ISSUE TITLE
Features related to I-Equivalence

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#67]
1. Check if two models are I-Equivalent.
2. List all the set of graphs over _X_ with same I-Equivalence.

**Comment by navinchandak** [comment]
@ankurankan I have implemented 1 . Kindly take a look.

Also, do you really want all the graphs with same I-equivalence. The number of such graphs could be exponential in the size of the edges. Also what purpose does it serve?

**Comment by ankurankan** [comment]
@navinchandak Yes I want all the graphs with the same I-equivalence. We are
writing a library so we should provide each and every functionality that is
possible. It is the user who decides whether he wants to use it or not.

**Comment by navinchandak** [comment]
@ankurankan  Okay.. Do you want a list of all the directed graph objects as the return value?
What I was trying to ask was if this functionality would be useful. As in, I was not able to think of a situation where this would be useful. Can you give me an example?

**Comment by ankurankan** [comment]
No, not a list of graph objects.
@abinashpanda @gargshashank5 : What do you think should be the return value?

One simple situation might be while learning someone simply wants to see all graphs.

**Comment by ankurankan** [comment]
PR: #85

**Comment by khalibartan** [comment]
@ankurankan I'm working on this one. I'll use isomorphism to check for similar skeleton.
