### ISSUE TITLE
Method for building a minimal I-Map

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#68]
Implement a method to construct a minimal I-Map given a Probability distribution and an ordering of random variables.

**Comment by navinchandak** [comment]
I am onto it. 
Just had a small query. What should be the way of taking the input for the distribution. We can't possibly ask the user to enter m^n values where m=number_of_values_for_each_node and n = number of nodes.
Maybe the user can enter the factors of the distribution one after the other? (We can take factors , the variables associated with it and the m^n1 values where n1 = number of variables in that factor)

**Comment by ankurankan** [comment]
@navinchandak : I would like to have this function to be a method of `ProbabilityDistribution` class which should be inheriting the `Factor` class. And we can surely ask the user for m^n values for constructing the `ProbabilityDistribution` class. Whenever the user inputs these many values it's always from a file so it wouldn't really be a problem.

**Comment by khalibartan** [comment]
@ankurankan JointProbabilityDistribution has this implementation. Though I don't know much but till now I have encountered it only for joint probability distributions , so I think this issue can be closed . Or do other classes have I-map construction ? If so then I'll like to work on them .

**Comment by ankurankan** [comment]
Fixed

**Comment by khalibartan** [comment]
@ankurankan Reopen this. Minimal I map has a bug in it. I'm trying to fix it. Look at PR #560

**Comment by khalibartan** [comment]
@ankurankan Fixed in #560 Can be closed now.
