### ISSUE TITLE
learning network structure

### ISSUE THREAD

**Issue by ghost** [pgmpy/pgmpy#680]
Is there an API to learn the structure of a bayesian network, given the variables?

**Comment by khalibartan** [comment]
@rpagliarix We are working on getting this done. We have accepted a GSOC project that deals with it , so you can expect it to be in working condition by august. For any other API, there might be some in R but I don't know about them, you can search for them.

**Comment by eran-str** [comment]
There is a python library called libpgm,  having pgmlearner, implementing the structure learning as well as parameter learning. A good starting point ...
