### ISSUE TITLE
Wrong iPython Notebook Representation

### ISSUE THREAD

**Issue by dstuck** [pgmpy/pgmpy#688]
CPD headers are incorrectly displayed in ipython by _repr_html (and not displayed at all in with print) when there is more than one evidence variable.
Ex:

``` python
cpd_table = pgmpy.factors.TabularCPD('grade', 2,
                       [[0.7, 0.6, 0.4, 0.2],[0.3, 0.4, 0.6, 0.8]], 
                       ['intel', 'diff'], [2, 2])
cpd_table
```

Displays:
TabularCPD for grade

```
diff        diff_0          diff_1
intel    intel_0   intel_1  intel_0 intel_1
grade_0 0.7000  0.6000  0.4000  0.2000
grade_1 0.3000  0.4000  0.6000  0.8000
```

but `cpd_table.variables` returns ['grade', 'intel', 'diff'] and `cpd[1,0,1]` returns 0.4 rather than 0.6 as indicated by the display.
Removing the list reversal in _repr_html gives the proper column labels, but I haven't tested it for higher dimensional CPDs.

This list reversal was commented out in 2c816fb307a95908facd11b62e26f7b745c86415, then reverted in 2d53e30b8a0f9f2adcd064453929105e91c6ce6b so it seems someone is aware of this, but I'm quite sure ended up on the wrong solution.

As a side note, it would be better to change the marginalization examples in the docstrings to the inputs I used here since otherwise you won't catch this bug due to the symmetry of marginalizing over diff or intel.

**Comment by dstuck** [comment]
Oh, also wanted to see why not just return a pandas DataFrame and use its print functionality rather than rewriting their _repr_html? Having access to CPDs as data frames seems like it would be much more convenient.

**Comment by yashu-seth** [comment]
@dstuck There seems to be a bug in the CPD representation. It would be great if you can send a PR to fix this. Else we will look into this as soon as possible.
You can also discuss the specific changes you are proposing there.

**Comment by ankurankan** [comment]
@dstuck @yashu-seth I don't think we need `_repr_html` since tabulate is able to render the table in notebooks.
