### ISSUE TITLE
Faster nosetests?

### ISSUE THREAD

**Issue by chrisittner** [pgmpy/pgmpy#695]
Nosetests take more than 30s to run (on my machine), due to a few large test cases. One should check if the slow test cases need to be so slow or if they can be modified to work with smaller models.

**Comment by khalibartan** [comment]
I don't think 30 sec is too much of time, I was once running theano tests and took me about an hour or so. We can specifically run tests which are relevant to the changes. Though one should write test cases which are not slow, but it can't be really helped in many places.
