### ISSUE TITLE
Move all internal pandas computation to recarrays

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#703]
Currently we accept and return pandas DataFrame wherever we need to deal with data. Also our internal computations use pandas. Replace these internal computations with recarray.

**Comment by sahithikilaru** [comment]
I would like to work on this.

**Comment by khalibartan** [comment]
@sahithikilaru You can reference my pr #719 to see how are we doing things in case of sampling algorithms. I think most of the work remains in estimator classes and its methods.

**Comment by sahithikilaru** [comment]
@khalibartan ok thanks!
