### ISSUE TITLE
GibbsSampling on BayesianModel not working

### ISSUE THREAD

**Issue by eran-str** [pgmpy/pgmpy#704]
Hi,
I added to the example code for GibbsSampling one more node connection 'doc', and it fails,
The following code produce error:

```
from pgmpy.factors import TabularCPD
from pgmpy.models import BayesianModel
intel_cpd = TabularCPD('intel', 2, [[0.7], [0.3]])
sat_cpd = TabularCPD('sat', 2,  [[0.95, 0.2,0.95, 0.2], [0.05, 0.8,0.95, 0.2]], evidence=['intel','doc'], evidence_card=[2,2])
doc_cpd = TabularCPD('doc', 2, [[0.7], [0.3]])
student = BayesianModel()
student.add_nodes_from(['intel', 'sat','doc'])
student.add_edge('intel', 'sat')
student.add_edge('doc', 'sat')
student.add_cpds(intel_cpd, sat_cpd,doc_cpd)

from pgmpy.inference import GibbsSampling
gibbs_chain = GibbsSampling(student)

t= gibbs_chain.sample(size=1000)

```

The error:

```
Traceback (most recent call last):
  File "C:\projects\pgm\Random Generation of BN\test gibsSampling.py", line 13, in <module>
    gibbs_chain = GibbsSampling(student)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\inference\Sampling.py", line 253, in __init__
    self._get_kernel_from_bayesian_model(model)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\inference\Sampling.py", line 280, in _get_kernel_from_bayesian_model
    prod_cpd_reduced = prod_cpd.reduce(states, inplace=False)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\utils\state_name.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\factors\CPD.py", line 335, in reduce
    raise ValueError("Reduce not allowed on the variable on which CPD is defined")
ValueError: Reduce not allowed on the variable on which CPD is defined

```

**Comment by khalibartan** [comment]
@eran-str 

```
sat_cpd = TabularCPD('sat', 2,  [[0.95, 0.2,0.95, 0.2], [0.05, 0.8,0.95, 0.2]], evidence=['intel','doc'], evidence_card=[2,2])
```

It is not a valid cpd,

```
╒═══════╤═════════╤═════════╤═════════╤═════════╕
│ intel │ intel_0 │ intel_0 │ intel_1 │ intel_1 │
├───────┼─────────┼─────────┼─────────┼─────────┤
│ doc   │ doc_0   │ doc_1   │ doc_0   │ doc_1   │
├───────┼─────────┼─────────┼─────────┼─────────┤
│ sat_0 │ 0.95    │ 0.2     │ 0.95    │ 0.2     │
├───────┼─────────┼─────────┼─────────┼─────────┤
│ sat_1 │ 0.05    │ 0.8     │ 0.95    │ 0.2     │
╘═══════╧═════════╧═════════╧═════════╧═════════╛

```

Take a look at column `intel_1`, `doc_0` and `intel_1`, `doc_1`. They both don't sum to one.
After correction

```
from pgmpy.factors import TabularCPD
from pgmpy.models import BayesianModel
intel_cpd = TabularCPD('intel', 2, [[0.7], [0.3]])
sat_cpd = TabularCPD('sat', 2,  [[0.95, 0.2,0.95, 0.2], [0.05, 0.8, 0.05, 0.8]], evidence=['intel','doc'], evidence_card=[2,2])
doc_cpd = TabularCPD('doc', 2, [[0.7], [0.3]])
student = BayesianModel()
student.add_nodes_from(['intel', 'sat','doc'])
student.add_edge('intel', 'sat')
student.add_edge('doc', 'sat')
student.add_cpds(intel_cpd, sat_cpd,doc_cpd)

from pgmpy.inference import GibbsSampling
gibbs_chain = GibbsSampling(student)

t= gibbs_chain.sample(size=1000)
```

Output is:

```
     intel  doc  sat
0        0    0    0
1        0    0    0
2        0    1    0
3        0    0    0
4        0    0    0
5        0    0    0
6        0    1    0
7        0    1    0
8        0    0    0
9        1    1    0
10       0    0    0
11       0    0    0
12       0    1    0
13       0    1    0
14       1    0    1
15       1    1    1
16       1    0    1
17       1    1    1
18       1    1    1
19       1    0    1
20       0    1    0
21       0    0    0
22       0    0    0
23       0    0    0
24       0    0    0
25       0    0    0
26       0    0    0
27       1    0    0
28       0    0    0
29       0    0    0
..     ...  ...  ...
970      0    0    0
971      0    1    0
972      0    0    0
973      0    0    0
974      0    0    0
975      1    0    0
976      0    1    0
977      0    0    0
978      0    1    0
979      0    0    0
980      0    1    0
981      0    0    0
982      0    0    0
983      0    0    0
984      0    0    0
985      1    0    1
986      1    0    1
987      1    1    0
988      0    0    0
989      1    0    1
990      1    0    1
991      1    0    1
992      1    1    1
993      1    1    1
994      1    0    0
995      1    0    1
996      1    1    0
997      0    0    0
998      0    1    0
999      0    0    0

[1000 rows x 3 columns]
```

If your doubt is clear, you can close this issue than

**Comment by yashu-seth** [comment]
@khalibartan I think we should have a `BayesainModel.check_model` call before Gibbs Sampling begins this would raise the required exception. Since, we have a method (`check_model`) to check such inconsistencies. What do you think?

**Comment by khalibartan** [comment]
@yashu-seth Yes. I was about to make that point on our gitter channel. Though here error was clearly visible, but with large number of nodes it can be difficult to find the correct origin because error is really misguiding and lot of computational time will be spend even before this error is raised(here less number of nodes, so kernel was constructed in no time but with dense and big graphs things can be time consuming). @ankurankan views ?

**Comment by ankurankan** [comment]
@khalibartan @yashu-seth Yes we should call `check_model` before doing sampling.

**Comment by eran-str** [comment]
After updating and using `check_model` to verify correctness, I still get the same error,
It yields on the **reduce** procedure as before,

```
Traceback (most recent call last):
  File "<module2>", line 14, in <module>
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\inference\Sampling.py", line 253, in __init__
    self._get_kernel_from_bayesian_model(model)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\inference\Sampling.py", line 280, in _get_kernel_from_bayesian_model
    prod_cpd_reduced = prod_cpd.reduce(states, inplace=False)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\utils\state_name.py", line 167, in wrapper
    return f(*args, **kwargs)
  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\factors\CPD.py", line 335, in reduce
    raise ValueError("Reduce not allowed on the variable on which CPD is defined")
ValueError: Reduce not allowed on the variable on which CPD is defined
```

I'm working on a windows environment with the latest pgmpy,
I will get back to you soon, I want to check the reduction procedure against the book algorithm

**Comment by ankurankan** [comment]
@eran-str Is the code that @khalibartan has posted in the above comment working for you ?

**Comment by eran-str** [comment]
Hi Ankur Ankan,
The code from  @khalibartan is not working for me,I'm doing a copy paste of the exact code, but it fail on the same error, see log below.I tried to debug the problem,From the stack I see that the method _get_kernel_from_bayesian_model is being called (C:\python27\Lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\inference\Sampling.py)
Basically it fails while trying to call a reduce procedure: prod_cpd.reduce(states, inplace=False) I added a couple of prints for debug,I  see that it fails on the first loop while trying to reduce a CPD: P(sat | intel, doc) over states: SAT,INTEL.
The code is in loop @ VAR= 'DOC' , inner loop tup= (0, 0) ,reduce <bound method TabularCPD.scope of <TabularCPD representing P(sat:2 | intel:2, doc:2) at 0x13bf6668L>> states: [State(var='intel', state=0), State(var='sat', state=0)]

I will read the algorithm from Koller  Section 12.3.3 pp 512-513 to better understand the situation.
Thank you for your time and interest.Eran.
Log:Traceback (most recent call last):  File "<module3>", line 13, in <module>  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\inference\Sampling.py", line 253, in **init**    self._get_kernel_from_bayesian_model(model)  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\inference\Sampling.py", line 280, in _get_kernel_from_bayesian_model    prod_cpd_reduced = prod_cpd.reduce(states, inplace=False)  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\utils\state_name.py", line 167, in wrapper    return f(_args, *_kwargs)  File "C:\python27\lib\site-packages\pgmpy-0.1.0-py2.7.egg\pgmpy\factors\CPD.py", line 335, in reduce    raise ValueError("Reduce not allowed on the variable on which CPD is defined")ValueError: Reduce not allowed on the variable on which CPD is defined

```
  From: Ankur Ankan <notifications@github.com>
```

 To: pgmpy/pgmpy pgmpy@noreply.github.com 
Cc: eran-str eran_str@yahoo.com; Mention mention@noreply.github.com
 Sent: Sunday, June 26, 2016 8:46 AM
 Subject: Re: [pgmpy/pgmpy] GibbsSampling on BayesianModel not working (#704)

@eran-str Is the code that @khalibartan has posted in the above comment working for you ?—

**Comment by khalibartan** [comment]
@eran-str @ankurankan On latest dev  it is indeed not working. My system was using a different installation (don't know maybe 2 months old atleast, used pip installation) it was running fine on it,  but when I tried running on latest dev I also got an error.

**Comment by harishkashyap** [comment]
hey @khalibartan, this isn't resolved still?

**Comment by ankurankan** [comment]
Fixed already in dev.
