### ISSUE TITLE
DBNInference error with minimal graph

### ISSUE THREAD

**Issue by jamieforth** [pgmpy/pgmpy#714]
Hi,

I am trying to become familiar with the DBN inference capabilities of pgmpy, and have run into a problem that seems related to PR #663 (DBN initialze_intial_state method).

I am currently at commit e85706c9.

Based on the example in PR #663:

```
from pgmpy.factors import TabularCPD
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.inference import DBNInference

model = DBN()

model.add_edges_from([(('a', 0), ('b', 1)), (('c', 0), ('b', 1))])

a_cpd = TabularCPD(('a', 0), 2, [[0.5, 0.5]])

c_cpd = TabularCPD(('c', 0), 2, [[0.5, 0.5]])

b_cpd = TabularCPD(('b', 1), 2, [[0.5, 0.5, 0.5, 0.5],
                                 [0.5, 0.5, 0.5, 0.5]],
                   [('c', 0), ('a', 0)], [2, 2])

model.add_cpds(a_cpd, c_cpd, b_cpd)
model.initialize_initial_state()

dbn_inf = DBNInference(model)
```

Results in `ValueError: ('CPD defined on variable not in the model', <TabularCPD representing P(('a', 0):2) at 0x7efe297007d0>)`

```
/home/jamie/src/python/src/pgmpy/pgmpy/inference/dbn_inference.pyc in 
__init__(self, model)
     64         query
     65         """
---> 66         super(DBNInference, self).__init__(model)
     67         self.interface_nodes_0 = 
model.get_interface_nodes(time_slice=0)
     68         self.interface_nodes_1 = 
model.get_interface_nodes(time_slice=1)

/home/jamie/src/python/src/pgmpy/pgmpy/utils/state_name.pyc in 
wrapper(*args, **kwargs)
     38                 args[0].state_names = kwargs['state_names']
     39                 del kwargs['state_names']
---> 40             f(*args, **kwargs)
     41         return wrapper
     42 

/home/jamie/src/python/src/pgmpy/pgmpy/inference/base.pyc in __init__(self, 
model)
     86         elif isinstance(model, DynamicBayesianNetwork):
     87             self.start_bayesian_model = 
BayesianModel(model.get_intra_edges(0))
---> 88             
self.start_bayesian_model.add_cpds(*model.get_cpds(time_slice=0))
     89             cpd_inter = [model.get_cpds(node) for node in 
model.get_interface_nodes(1)]
     90             self.interface_nodes = model.get_interface_nodes(0)

/home/jamie/src/python/src/pgmpy/pgmpy/models/BayesianModel.pyc in 
add_cpds(self, *cpds)
    157             if set(cpd.variables) - set(cpd.variables).intersection(
    158                     set(self.nodes())):
--> 159                 raise ValueError('CPD defined on variable not in 
the model', cpd)
    160 
    161             for prev_cpd_index in range(len(self.cpds)):

```

As I understand it, the error at line 159 of BayesianModel.py is thrown because 'a' and 'c' are not variables in the BayesianModel constructed on line 88 in base.py, which is initialised with an empty array returned from `get_intra_edges(0)`.

I've tried making sure the variables are present prior to adding the CPDs, but that just results in related errors further down. So I'm not quite sure how best to approach fixing this, or whether I am doing something wrong?

Cheers,
Jamie

**Comment by ankurankan** [comment]
@jamieforth Sorry for the late reply. I think you have misunderstood the way we define Dynamic Bayesian models in pgmpy. In pgmpy, we have to add all the edges in the first time slice. For example if you want to define this network:

![untitled drawing 1](https://cloud.githubusercontent.com/assets/1461453/17766522/ce82843e-652b-11e6-924a-32234effa5ae.png)

we will need to add 5 edges:

``` python
model = DBN([(('a', 0), ('a', 1)), (('a', 0), ('b', 0)), (('c', 0), ('b', 0)), (('c', 0), ('c', 1)), (('b', 0), ('b', 1))])
```

And after this we will have to add 6 cpds for this: 
1. P(('a', 0))
2. P(('c', 0)),
3. P(('b', 0) | ('a', 0), ('c', 0))
4. P(('a', 1) | ('a', 0))
5. P(('c', 1) | ('c', 0))
6. P(('b', 1) | ('b', 0), ('a', 1), ('c', 1))

I hope this helps. Please let me know if you have any other issues.

**Comment by jamieforth** [comment]
@ankurankan thank you for the helpful clarification.

For future reference I experimented a little further with minimal graphs and have created #745 which I believe addresses an issue I came across when trying to represent simple Markov Chains as DBNs.
