### ISSUE TITLE
Inconsistent behaviour of query in VariableElimination when passing a single variable

### ISSUE THREAD

**Issue by finnhacks42** [pgmpy/pgmpy#715]
If query is passed a single variable rather than a list, it works if the variable name is a single character and fails with an obtuse error otherwise. 

The documentation does say to pass a list but there are many examples, ie in the notebooks where a single variable is passed. 

Can we either handle passing single variables (ie check and insert them into a list) or check and throw an informative error?

Simple code to reproduce an error below. It occurs because the set subtraction (on line 57 of ExactInference) happens to work if the single variable is one character long because set('x')==set(['x'])

`
from pgmpy.inference import VariableElimination
from pgmpy.models import BayesianModel
from pgmpy.factors import TabularCPD
model = BayesianModel([('Z', 'Xx')])
cpd_z = TabularCPD(variable='Z', variable_card=2, values=[[0.7, 0.3]])
cpd_x = TabularCPD(variable='Xx', variable_card=2, 
                   values=[[0.6, 0.2],
                           [0.4, 0.8]],evidence=['Z'],evidence_card=[2])

model.add_cpds(cpd_z, cpd_x)
model.check_model()

infer = VariableElimination(model)
infer.query('Xx')['Xx']`

**Comment by yashu-seth** [comment]
@finnhacks42 I think `query` should always take a list as an input parameter, even for queries on single variables.
@ankurankan @khalibartan What do you think?

**Comment by finnhacks42** [comment]
I would lean slightly towards allowing string (single-variable) or array-like as the input parameter for `query`. This would make it consistent with ie `TableCPD` which accepts string, list, tuple or np.array for the `evidence` parameter and would mean existing code & examples would continue to work.

The alternative of throwing a TypeError if the input is not a list would break existing examples ie in  https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/2.%20Bayesian%20Networks.ipynb

**Comment by khalibartan** [comment]
I don't think we should be allowing both strings (for single variable) and list. We should only accept lists. Accepting strings is also adding unnecessary type checks. We can change the functionality and documentation too.

**Comment by finnhacks42** [comment]
Ok then, how about I throw a TypeError for string types and leave the rest to duck typing (eg sets, numpy arrays, lists, tuples should all work without issues - and we let whatever errors other random things generate bubble up).

**Comment by yashu-seth** [comment]
@finnhacks42 That seems fine. I think you can go ahead with the PR.
