### ISSUE TITLE
How to fit the parameters of DBNs?

### ISSUE THREAD

**Issue by ghost** [pgmpy/pgmpy#724]
Hi, I found that the estimators can only handle BayesianModel, how could I estimate or learn the parameters for a DBNs. 

Is there anyone know?
Thank you very much.

**Comment by chrisittner** [comment]
Yes, learning is so far only implemented for `BayesianModel`s. I'm not sure if there is any python library that supports any learning for DBNs. Matlab's [BNT](https://github.com/bayesnet/bnt) should have it, at least [this](https://github.com/bayesnet/bnt/blob/master/BNT/learning/learn_params_dbn.m) and [this](https://github.com/bayesnet/bnt/blob/master/BNT/learning/learn_params_dbn_em.m) suggests so.

**Comment by ghost** [comment]
Thanks for your reply. @chrisittner 
I know Matlab's BNT and I am using it. However, I'd like use python to clean data and something others, and this makes the problem much more complicated using two different langue. So I want a python library that can learn the parameters of DBNs.

Will pgmpy support DBNs learning?

**Comment by ankurankan** [comment]
@quantpy2016 Unfortunately pgmpy doesn't support learning DBNs right now. We will definitely work on implementing that but we currently don't have a timeline for that.

**Comment by ghost** [comment]
@ankurankan OK. Thanks.

**Comment by mazensalous** [comment]
Hello @ankurankan ,
is this now available in the latest version of pgmpy? Can we now fit a DBN from data? and then can we predict a variable in the DBN at a specific time-stamp?

**Comment by ankurankan** [comment]
@mazensalous Sorry for the late reply. Unfortunately, we still don't have an implementation for this. Although for prediction you can look at: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/inference/dbn_inference.py#L9

**Comment by JarvisIsFriday** [comment]
> @mazensalous Sorry for the late reply. Unfortunately, we still don't have an implementation for this. Although for prediction you can look at: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/inference/dbn_inference.py#L9

so pgmpy support DBNs learning now?  
I noticed  the fit function in DBN class, I use the fit function , unfortunately, I got this:

`AttributeError                            Traceback (most recent call last)
<ipython-input-17-a29840b75f9f> in <module>()
     19     colnames.extend([("A", t), ("B", t), ("C", t), ("D", t)])
     20 df = pd.DataFrame(data, columns=colnames)
---> 21 model.fit(df)

AttributeError: 'DynamicBayesianNetwork' object has no attribute 'fit'
`

**Comment by ankurankan** [comment]
@JarvisIsFriday The fit method was implemented recently and isn't available in the released version. If you would like to use it, you can install the `dev` branch using: `pip install git+https://github.com/pgmpy/pgmpy.git@dev`

**Comment by JarvisIsFriday** [comment]
> @JarvisIsFriday The fit method was implemented recently and isn't available in the released version. If you would like to use it, you can install the `dev` branch using: `pip install git+https://github.com/pgmpy/pgmpy.g
Thank you very much!  I have installed it and the fit method can work!

**Comment by JarvisIsFriday** [comment]
@ankurankan Thank you very much! I have installed it and the fit method can work!
