### ISSUE TITLE
Directory structure change

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#729]
- [x] Create a new `discrete` dir in factors and move `CPD.py`, `Factor.py` and `JointProbabilityDistribution.py` in it. The idea is to separate things related to discrete and continuous into individual directories and keep the common things (like `FactorSet`) in the current factor dir.
- [x] Move `discretize.py` into `factors/continuous` dir
- [x] Remove `ContinuousNode.py`. I don't see the point of having it.
- [x] Create a new directory at top level for sampling methods since they really don't belong to the inference part.
- [ ] Two new directories in `inference` directory namely `exact_inference` and `approximate_inference`. (Not required right now)
- [x] Rename `Factor` to `DiscreteFactor`
- [x] Common name for `NoUTurnSamplerDA` and `HamiltonianMCda`.  
- [x] Change the tests directory structure according to the above changes.  
  @khalibartan @yashu-seth Opinion ?

**Comment by khalibartan** [comment]
@ankurankan I agree with the decision of separating discrete and continuous part. I had suggested it earlier. It is much needed. All points are nice and agree with them. But can you elaborate a bit what  you meant by this:

> Create a new directory at top level for sampling methods since they really don't belong to the inference part.

Yes sampling method doesn't belong to inference but where should we move them?

**Comment by ankurankan** [comment]
@khalibartan I am thinking of having a `sampling` directory inside the main `pgmpy` directory.
