### ISSUE TITLE
Markov Chain should also accept a transition matrix for the transition model.

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#748]
Currently just accepts dict.

**Comment by kris-singh** [comment]
@ankurankan i just looked at this my idea is to convert the given numpy array to dict this would O(n^2) time but i think this would be simplest solution do you have anything better to suggest. 
Can you look at this
https://github.com/pgmpy/pgmpy/pull/784
which tests should i add

**Comment by ankurankan** [comment]
@kris-singh Yes it would be `O(n^2)` in the number of states. But the number of states isn't going to be too huge, so it's okay. Your PR looks okay (I have a few comments though). Why did you close it ?

You will need to add tests in which you will need to pass numpy arrays instead of the dict. You can look at: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/tests/test_models/test_MarkovChain.py for the current tests for MarkovChain.

**Comment by kris-singh** [comment]
@ankurankan Ya closed it by mistake. I would to PR tomorrow with updated code.

**Comment by khalibartan** [comment]
@ankurankan Can we remove the tests that are using mock ? Tests using mock makes its difficult (at-least for me) to read the tests.

**Comment by ankurankan** [comment]
@khalibartan Yeah I agree. @kris-singh Can you also see if you fix the tests using mock ?

**Comment by kris-singh** [comment]
@ankurankan we can close this now

**Comment by ankurankan** [comment]
Fixed in #788
