### ISSUE TITLE
Investigate issue with Belief propagation

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#771]
Investigate why this happened (happens in v0.1.2 also: https://pypi.python.org/pypi/pgmpy/0.1.2):
http://stats.stackexchange.com/questions/240878/belief-propagation-using-pgmpy-lib-algorithm-understanding

And add tests for it.

**Comment by sahithikilaru** [comment]
I would like to work on this.

**Comment by yashu-seth** [comment]
@sahithikilaru This has bee fixed. Please check the second answer on the thread.
@ankurankan This can be closed.
