### ISSUE TITLE
Decorator for state names should preserve the actual method signature

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#773]
http://stackoverflow.com/questions/147816/preserving-signatures-of-decorated-functions

**Comment by yashu-seth** [comment]
@ankurankan I looked into the thread. Using ```functools.wraps``` seems an option, but it won't preserve the functions's arguments list. Should we use this for now and keep the issue open?

**Comment by ankurankan** [comment]
@yashu-seth Yes, we should wait for a better solution. There's no point in changing the current code if it doesn't get better.

**Comment by raghavg7796** [comment]
@ankurankan @yashu-seth How about this?
http://stackoverflow.com/questions/147816/preserving-signatures-of-decorated-functions

**Comment by yashu-seth** [comment]
@raghavg7796 We looked into this but could not find anything feasible. Do you have any ideas?

**Comment by ankurankan** [comment]
@raghavg7796 @yashu-seth Have you guys looked into wrapt: https://pypi.python.org/pypi/wrapt ? They mention something about preserving signatures here: http://wrapt.readthedocs.io/en/stable/decorators.html. But I haven't checked it out in detail.

**Comment by raghavg7796** [comment]
@ankurankan @yashu-seth I checked it out and it is giving perfect results. Should I make a PR adding the changes?

**Comment by ankurankan** [comment]
@raghavg7796 Yeah sure.

**Comment by raghavg7796** [comment]
@ankurankan @yashu-seth Although using wrapt gives proper documentation, it is failing nosetests because wrapt has different method of defining decorators. I am trying to look into this but still is getting problems. Please someone look.

**Comment by yashu-seth** [comment]
@raghavg7796 Do you have a PR for this?

**Comment by raghavg7796** [comment]
@yashu-seth I have a PR but it is giving like 290 errors, i.e. wherever it is being called.

**Comment by yashu-seth** [comment]
@raghavg7796 I have not used the wrapt module before. Just make sure you have studied python decorators a bit.

**Comment by raghavg7796** [comment]
@yashu-seth I studied the wrapt module and used it but it have some changed implementation like it doesn't allows *args, **kwargs in its wrapper but allows them as args and kwargs which are not editable then etc. So it is creating problems but I will still try to use it in our code.

**Comment by ankurankan** [comment]
@raghavg7796 I find Graham Dumpleton's blog series on decorators quite useful: http://blog.dscpl.com.au/search/label/decorators. Maybe have a look if you have any doubts.

**Comment by raghavg7796** [comment]
@ankurankan This can be closed now.

**Comment by ankurankan** [comment]
@raghavg7796 This isn't merged. Right ?

**Comment by raghavg7796** [comment]
@ankurankan  You have merged the PR for this issue adding wrapt.

**Comment by ankurankan** [comment]
Fixed.
