### ISSUE TITLE
VariableElimination error

### ISSUE THREAD

**Issue by qillbel** [pgmpy/pgmpy#776]
I tried to use VariableElimination(restaurant), but it gives me error
Traceback (most recent call last): 

> File "C:\Users\User\Downloads\BitBucket\python\Session4.py", line 26, in <module>
>     restaurant_inference = VariableElimination(restaurant)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pgmpy-0.1.0-py3.5.egg\pgmpy\inference\base.py", line 57, in __init__
>     if not model.check_model():
>   File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pgmpy-0.1.0-py3.5.egg\pgmpy\models\BayesianModel.py", line 243, in check_model
>     if not np.allclose(cpd.marginalize(node, inplace=False).values,
>   File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pgmpy-0.1.0-py3.5.egg\pgmpy\factors\CPD.py", line 265, in marginalize
>     super(TabularCPD, tabular_cpd).marginalize(variables)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pgmpy-0.1.0-py3.5.egg\pgmpy\factors\Factor.py", line 209, in marginalize
>     marginalized_values.append(np.sum(factor.values[factor._index_for_assignment(assign)]))
>   File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pgmpy-0.1.0-py3.5.egg\pgmpy\factors\Factor.py", line 416, in _index_for_assignment
>     card_cumprod = np.delete(np.concatenate((np.array([1]), np.cumprod(self.cardinality[::-1])), axis=1)[::-1], 0)
> IndexError: axis 1 out of bounds [0, 1)

any idea how the error is? I tried to install from both dev and book-v0.1 branch, but still do not work. Thank you for the help.

**Comment by khalibartan** [comment]
@qillbel Can you share the code snippet that gave this error so that we can look into. Also did you use `pip install pgmpy` for installation or installed it from latest dev branch on git using setup.py. Installation available at pip is stale one we changed at a lot of things since then. Directory structure shown in the error is old one. Please see to that.

**Comment by qillbel** [comment]
@khalibartan 
Here is the code I use. It takes from the book titled "Mastering Probabilistic Graphical Models using Python". 

> from pgmpy.models import BayesianModel
> from pgmpy.inference import VariableElimination
> from pgmpy.factors import TabularCPD
> 
> > # Now first create the model.
> > 
> > restaurant = BayesianModel(
> > [('location', 'cost'),
> > ('quality', 'cost'),
> > ('cost', 'no_of_people'),
> > ('location', 'no_of_people')])
> > cpd_location = TabularCPD('location', 2, [[0.6, 0.4]])
> > cpd_quality = TabularCPD('quality', 3, [[0.3, 0.5, 0.2]])
> > cpd_cost = TabularCPD('cost', 2,
> > [[0.8, 0.6, 0.1, 0.6, 0.6, 0.05],
> > [0.2, 0.1, 0.9, 0.4, 0.4, 0.95]],
> > ['location', 'quality'], [2, 3])
> > cpd_no_of_people = TabularCPD(
> > 'no_of_people', 2,
> > [[0.6, 0.8, 0.1, 0.6],
> > [0.4, 0.2, 0.9, 0.4]],
> > ['cost', 'location'], [2, 2])
> > restaurant.add_cpds(cpd_location, cpd_quality, cpd_cost, cpd_no_of_people)
> > 
> > # Creating the inference object of the model
> > 
> > restaurant_inference = VariableElimination(restaurant)

I use setup.py to install it because I run it on Windows machine (I assume pip install pgmpy can only be applied in Linux machine-correct me if I'm wrong). If the stable one is not in dev brach or book-v0.1, where can I download the sable version of pgmpy?

Thank you so much for helping. Sorry if the question is a trivial one.

**Comment by khalibartan** [comment]
@qillbel I don't think you are using the current dev actually. Because this line
`from pgmpy.factors import TabularCPD`
should have raised an **import error**. The examples from the books will not work with current dev. Because we just changed our directory structure.

Our dev branch is stable and latest one.
please try install once again by cloning the repo or downloading the zip file.

**Comment by qillbel** [comment]
@khalibartan 
in that case, which version that works with the examples on the book?

**Comment by khalibartan** [comment]
@qillbel Examples will work but you just have to import from right directory. API is pretty much same.
Like for this example the import statements must be 

```
from pgmpy.models import BayesianModel
from pgmpy.inference import VariableElimination
# Changed from pgmpy.factors to pgmpy.factors.discrete
from pgmpy.factors.discrete import TabularCPD
```

rest of the code should work fine.
Another solution is to go back in commit history and use any commit before may. Not recommended though.

**Comment by qillbel** [comment]
@khalibartan Thank you so much. It works now. Btw, on remain question is where can I find the documentation about the changes that are being made? For instance, importing these modules (import TreeCPD, Factor, RuleCPD) seem produce an error as they are not in factors anymore (not in discrete and continuous folder).

Thank you very much @khalibartan

**Comment by khalibartan** [comment]
@qillbel You should see our documentation. You can do this by seeing our code inside the directory or by generating the documentation locally using sphinx. See our README page for information about how you can generate the documentation , and you can ask us simple question anytime on our gitter channel.
Also if issue has been resolved you can close it now.

**Comment by khalibartan** [comment]
@qillbel You should see our documentation. You can do this by seeing our code inside the directory or by generating the documentation locally using sphinx. See our README page for information about how you can generate the documentation , and you can ask us simple question anytime on our gitter channel.

**Comment by ankurankan** [comment]
@qillbel You can see our API reference online at: http://pgmpy.org/
