### ISSUE TITLE
Reducing a joint gaussian distribution created from a LinearGaussianBayesianNetwork shows unstable behaviour.

### ISSUE THREAD

**Issue by chriskamphuis** [pgmpy/pgmpy#780]
Reducing a joint gaussian distribution created from a linear gaussian bayesian network shows different outcomes when running the same program multiple times This [example](http://termbin.com/vzos) shows this behaviour. 
I suspect that either the joint gaussian distribution is not created the same in all runs, or there is a small error in the reduce function. I checked the math with a book I have, and I think the reduce function is working properly. 
It is harder to check if the joint distribution is created properly, because it changes the order of variables in different runs. This gives different orders of rows and columns in the covariance matrix. (Which should not be a problem)

**Comment by yashu-seth** [comment]
@Chriskamphuis Can you reproduce the different outcomes you got? It would be easier to look into the bug.

**Comment by ankurankan** [comment]
@yashu-seth Just try running it multiple times ( in different instances of python), it will give different results.

**Comment by chriskamphuis** [comment]
@yashu-seth 
I just ran it twice and got respectively: `[[ 1.052213]]` and `[[ 0.367078]]`

**Comment by khalibartan** [comment]
@Chriskamphuis I'm not able to open the link. It is blocked for Indian users by Department of Telecommunications, Government of India. Maybe you can put that up in a github gist and post the link or comment it here.

**Comment by ankurankan** [comment]
@khalibartan Here you go: https://gist.github.com/ankurankan/3077a0b0cffa7c733790d55eb83028b7

**Comment by khalibartan** [comment]
Yes indeed, it gives different results each time, but one thing when I ran this in ipython (in same session) it gave same output. :/

**Comment by yashu-seth** [comment]
@ankurankan @khalibartan @Chriskamphuis I get the same value for ```jgd.mean``` for different instances of python 2. ( ```[[ 0.960813]]```) . While it changes for python 3.  The ```jgd.covariance``` remains same throughout. I also noticed that ```nx.topological_sort``` gives different order of variables for different instances of python 3.

**Comment by ankurankan** [comment]
@yashu-seth But all the different topological sorts are correct. And the algorithm ideally shouldn't be dependent on different topological sorts.

**Comment by yashu-seth** [comment]
@ankurankan This can be closed now.
