### ISSUE TITLE
Remove mock from tests

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#789]
Currently some tests in `MarkovChain` use mock. Remove it as it's not very readable.

**Comment by kris-singh** [comment]
@ankurankan i read about mock test. So my question is for something like the start_state_test it is in some cases intialized to random state. I think this things can only be checked by using a mock object.
So how would we check something like that

**Comment by ankurankan** [comment]
@kris-singh I don't think we can remove it then. I would suggest you to add some tests for the long term behavior of the `MarkovChain`.

**Comment by kris-singh** [comment]
@ankurankan Can you explain the long term behaviour ?

**Comment by ankurankan** [comment]
@kris-singh Read about the convergence of Markov Chains to stationary distributions.

**Comment by kris-singh** [comment]
@ankurankan yes i know about it. What sort of test did you had in mind. Is is something like  the transition matrix had to ergodic or something else

**Comment by ankurankan** [comment]
@kris-singh No, just run the chain for a while and see if it converges to the stationary distribution.

**Comment by kris-singh** [comment]
@ankurankan 
prob_from_sample method returns a list of zeros which is strange when the expected output given in the docs is array([ 0.27,  0.4 ,  0.18,  0.23, ..., 0.29])

```python
from pgmpy.models.MarkovChain import MarkovChain as MC
from pgmpy.factors.discrete import State
model = MC(['intel', 'diff'], [3, 2])
intel_tm = {0: {0: 0.2, 1: 0.4, 2:0.4}, 1: {0: 0, 1: 0.5, 2: 0.5}, 2: {2: 1}}
model.add_transition_model('intel', intel_tm)
diff_tm = {0: {0: 0.5, 1: 0.5}, 1: {0: 0.25, 1:0.75}}
model.add_transition_model('diff', diff_tm)
model.prob_from_sample([State('diff', 0)])
```

**Comment by ankurankan** [comment]
@kris-singh Can you try debugging and find what the problem is ?

**Comment by kris-singh** [comment]
@ankurankan I think i figured it out. I will try to explain.If you look at the sample funciton in markovchain.
We pass a parameter size=k which indicates we should do a random walk k from the all the var and all the states but we do not do this k times we generate sample_discrete only var*cardinalities times which can be much less than say 1000. Hence we need to change this. I think this should be added as seprate issue.
`for var in self.transition_models.keys():`
` ....for st in self.transition_models[var]:`
`........var_states[var][st] = list(self.transition_models[var][st].keys())`
`........var_values[var][st] = list(self.transition_models[var][st].values())`
`........samples[var][st] = sample_discrete(var_states[var][st], var_values[var][st])[0]`
Thats what i got. Were you able to follow the arguments.

**Comment by ankurankan** [comment]
@kris-singh Can you create an issue for it and maybe a PR ?

**Comment by kris-singh** [comment]
Okay i will do this

**Comment by kris-singh** [comment]
@ankurankan i fixed the sampling method but even for something like this the output is something like this for 
`diff_tm = {0: {0: 0.5, 1: 0.5}, 1: {0: 0.5, 1:0.5}}`
`print model.prob_from_sample([State('diff', 0)])`
the output with window size = 100 is
[ 0.51  0.51  0.5   0.51  0.5   0.52  0.43  0.53  0.57  0.5   0.47  0.43
  0.5   0.55  0.63  0.56  0.5   0.5   0.54  0.55  0.46  0.33  0.5   0.44
  0.41  0.54  0.53  0.57  0.52  0.5   0.47  0.53  0.51  0.57  0.54  0.56
  0.47  0.44  0.47  0.51  0.54  0.56  0.53  0.47  0.47  0.54  0.56  0.55
  0.51  0.49  0.51  0.59  0.44  0.48  0.52  0.63  0.47  0.62  0.55  0.47
  0.49  0.46  0.49  0.47  0.48  0.46  0.6   0.54  0.5   0.48  0.48  0.58
  0.5   0.53  0.53  0.52  0.51  0.46  0.5   0.46  0.52  0.44  0.49  0.47
  0.5   0.5   0.54  0.46  0.49  0.51  0.56  0.56  0.43  0.56  0.37  0.5
  0.46  0.47  0.45  0.5 ]
with window size 10
[ 0.477  0.521  0.475  0.519  0.503  0.478  0.481  0.468  0.494  0.486]
with window size 5
[ 0.4985  0.4875  0.4985  0.4975  0.492 ]
So to test_stationarity we would have define some epsilon value to check that the values are indeed convergin also the window size would have to smaller than 100 what do you think?

**Comment by kris-singh** [comment]
@ankurankan can you tell how to solve this. How should we say that in the long term the values of Markov chain converge.
should use something like the rabbes test for series cgt

**Comment by ankurankan** [comment]
@kris-singh Just start with a converging Markov Chain and write tests according to that.

**Comment by kris-singh** [comment]
@ankurankan please see https://github.com/pgmpy/pgmpy/pull/796

**Comment by kris-singh** [comment]
This can be closed
