### ISSUE TITLE
Issue with Markov Chain Sampling Method

### ISSUE THREAD

**Issue by kris-singh** [pgmpy/pgmpy#791]
from pgmpy.models.MarkovChain import MarkovChain as MC
from pgmpy.factors.discrete import State
model = MC(['intel', 'diff'], [3, 2])
intel_tm = {0: {0: 0.2, 1: 0.4, 2:0.4}, 1: {0: 0, 1: 0.5, 2: 0.5}, 2: {2: 1}}
model.add_transition_model('intel', intel_tm)
diff_tm = {0: {0: 0.5, 1: 0.5}, 1: {0: 0.25, 1:0.75}}
model.add_transition_model('diff', diff_tm)
model.prob_from_sample([State('diff', 0)])
this could should produce an output like
array([ 0.27, 0.4 , 0.18, 0.23, ..., 0.29])
but it produces an ouptut like [0, 0, 0, ....0]

**Comment by kris-singh** [comment]
I will reimplement the sample method for markovchain network. I will create a PR soon

**Comment by raghavg7796** [comment]
@kris-singh Running it first time, it gives [0, 0, 0, .....0] and second time it gives [0.99, 1, 1, .......1]. I think it somewhat depends on start_state which we have not initialized and is set to random. This is just a possible guess but I don't know what's the actual reason.

**Comment by raghavg7796** [comment]
@ankurankan Please confirm.

**Comment by kris-singh** [comment]
@raghavg7796  the mehod is not correctly implemented you can look at #789 for a more clear explanation. @ankurankan I have made the changes and will create a PR today

**Comment by kris-singh** [comment]
@ankurankan 
 For the stationarity condition i have implemented it as 
```python
def test_prob_from_sample(self):`
        model = MC(['a'], [4])
        transition_mat = np.array([[.95, .05, 0, 0], 
                                    [0, 0.9, 0.09, 0.01], 
                                    [0, 0.05, 0.9, 0.05], 
                                    [0.8, 0, 0.05, 0.15]])
        model.add_transition_model('a', transition_mat)
        S, U = eig(transition_mat.T)
        stationary = np.array(U[:, np.where(np.abs(S - 1.) < 1e-8)[0][0]].flat)
        stationary = stationary / np.sum(stationary)
        probabilites = []
        for k in range(0, transition_mat.shape[0]):
            probabilites.append(round(model.prob_from_sample([State('a', k)],window_size=10000),4))
        print probabilites,stationary
        for i in range(0, transition_mat.shape[0]):
            self.assertTrue(math.fabs(probabilites[i] - stationary[i]) <= 0.4)
```
I want to implement this as check_stationarity condition in MarkovChain.py what do you think? should i go ahead with that

**Comment by kris-singh** [comment]
This can be closed
