### ISSUE TITLE
Add test for NaiveBayes._get_ancestors_of method

### ISSUE THREAD

**Issue by raghavg7796** [pgmpy/pgmpy#802]
I will file a PR but need to confirm that we need this method? And if, then if we need to create new tests.

**Comment by yashu-seth** [comment]
@raghavg7796 You can rename this issue to "Add tests for NaiveBayes._get_ancestors_of method".
Coverage basically shows which parts of the code aren’t covered by the test suite.

**Comment by raghavg7796** [comment]
@yashu-seth Should I file a PR creating tests for this method

**Comment by yashu-seth** [comment]
@raghavg7796 Yes, you can go ahead.

**Comment by raghavg7796** [comment]
This can be closed now.

**Comment by ankurankan** [comment]
Fixed.
