### ISSUE TITLE
Changes to LinearGaussianCPD

### ISSUE THREAD

**Issue by kris-singh** [pgmpy/pgmpy#808]
i would like to make changes to the LinearGaussianCPD

1. It should accept JointGaussianDistribution or scipy.stats.normal Distribution

2. Should have the marginalize method that marginalizes the Gaussian Distribution

Also a question wont it make more sense to make LinearGaussianCPD to inherit from JointGaussianDistribution rather than ContinousCPD

**Comment by yashu-seth** [comment]
@kris-singh A linear gaussian CPD defines a linear relationship between mean of parents and mean of variable. It does not always need a gaussain distribution to be defined. 

Yes It should have a marginalize method. Do you have an implementable in mind?

Do you have any particular reasons to make it the child of ```JointGaussianDistribution```?

**Comment by kris-singh** [comment]
@yashu-seth 7.2 Daphne Koller Book says that a Gaussian Bayesian network to be a Bayesian network whose variables are continuous and where all cpds are linear Gaussian. Look at Thm 7.3

**Comment by yashu-seth** [comment]
@kris-singh That theorem discusses ```LinearGaussainBayesianNetwork``` which is equivalent to ```JointGaussianDistribution``` . Here, we are talking about ```LinearGaussianCPD```. Lets take this conversation to gitter.

**Comment by ankurankan** [comment]
@kris-singh @yashu-seth Do we need to keep this open ?

**Comment by yashu-seth** [comment]
@ankurankan This can be closed.
