### ISSUE TITLE
Prediction don't work for small evidence set. IndexError: only integers, slices (`:`)...

### ISSUE THREAD

**Issue by Maryia-M** [pgmpy/pgmpy#813]
Hi, I'm sorry if similar question was already asked, I'm new to python and pgmpy.
My network consists of approximately 576 nodes. If I put almost all columns values to predict it works, but If set of known values is small IndexError appears. ( IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices)
notebook link: http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/alvtvyb8nkeywiv/Untitled2.ipynb
training set link: https://www.dropbox.com/s/omluzgdfzb7dgfm/train1.csv?dl=0

**_Code_**

> 
> import pgmpy
> import numpy as np
> import pandas as pd
> 
> from pgmpy.estimators import ConstraintBasedEstimator
> from pgmpy.models import BayesianModel
> from pgmpy.estimators import MaximumLikelihoodEstimator, BayesianEstimator
> 
> # Model definition
> data = pd.DataFrame.from_csv("train1.csv", 0, ';', None)
> data.astype(int)
> values_dict ={}
> col =[]
> for column in data:
>      col.append(column)
>      imax = data.loc[data[column].idxmax()]
>      values_dict[column] = range(0, imax[column] + 1)
> data2 = data.ix[:,'floor_count':'loft']	
> model = pd.DataFrame.from_csv("model.csv", None, ';', None)
> est = ConstraintBasedEstimator(data2)
> skel, sep_sets = est.estimate_skeleton()	
> 
> topology_model = BayesianModel()
> topology_model.add_nodes_from(col)
> topology_model.add_edges_from(skel.edges())
> 
> 	
> topology_model.fit(data, state_names = values_dict)
> columns_list = ['lr', 'bath', 'nook', 'entry', 'dr','kch','grg']
> test =data[:1].drop(columns_list, axis=1, inplace=False).copy()
> print test
> # This prediction works
> result = topology_model.predict(test)
> print result
> values_list = [1, 2, 1, 0, 1, 1, 2]
> evid = pd.DataFrame([values_list], index=range(0,1), columns=columns_list)
> print evid
> # This prediction don't work
> result2 = topology_model.predict(evid)
> print result2

**_Error_**

>

> ---------------------------------------------------------------------------
> ...
> C:\Python27\pgmpy-dev\pgmpy\factors\discrete\DiscreteFactor.pyc in product(self, phi1, inplace)
>     585                 slice_ = [slice(None)] * len(phi.variables)
>     586                 slice_.extend([np.newaxis] * len(extra_vars))
> --> 587                 phi.values = phi.values[slice_]
>     588 
>     589                 phi.variables.extend(extra_vars)
> 
> 

>  IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by ankurankan** [comment]
@Maria-MM Was this a bug ?

**Comment by Maryia-M** [comment]
I think it was because of memory. I can't predict if (net_size-evidence_size)>=15.

**Comment by ahmedhassan554** [comment]
Hi, I am using predict method for 4 node model and around 150 observations. I have tried many things but it's not working. What could be the solution?

**Comment by ankurankan** [comment]
@ahmedhassan554 Would it be possible to share the full traceback of the error that you are getting and if possible also your code so that I can reproduce it?
