### ISSUE TITLE
check_model for Markov Model does not check factors for all variables

### ISSUE THREAD

**Issue by raghavg7796** [pgmpy/pgmpy#816]
In Markov Model, get_cardinality is used to check if factors are defined for all variables but I think check_model should serve that purpose.

**Comment by khalibartan** [comment]
@raghavg7796 Yes it is checking that, but I don't see any problem with that. `check_model` is also performing that check. On a side note `get_cardinality` doesn't mention return type in its docstring. Can you add this ?
@ankurankan I was thinking if model has both cardinality issue and inconsistency of discrete factor then we can raise both error together in check_model. But I'm also having second thoughts about this.
Views would be helpful @ankurankan  @yashu-seth.

**Comment by raghavg7796** [comment]
@khalibartan check_model is not checking whether factors for all nodes are defined.

1. from pgmpy.models import MarkovModel
2. from pgmpy.factors.discrete import DiscreteFactor
3. student = MarkovModel([('Alice', 'Bob'), ('Bob', 'Charles')])
4. factor = DiscreteFactor(['Alice', 'Bob'], cardinality=[2, 3], values=np.random.rand(6))
5. student.add_factors(factor)
6. student.get_cardinality(check_cardinality=True)
OUTPUT -> ValueError: Factors for all the variables not defined
7. student.check_model()
OUTPUT -> True

**Comment by khalibartan** [comment]
@raghavg7796 Sorry, my bad! Yeah check_model should check that. Can you create a PR that deals with the issue ?

**Comment by raghavg7796** [comment]
@khalibartan @ankurankan  I will add that in my current PR. Also I was thinking to remove that from get_cardinality and add that to check_model only. Will it be fine?

**Comment by khalibartan** [comment]
@raghavg7796 Updates on this?

**Comment by lohani2280** [comment]
@khalibartan @ankurankan I think currently, no one is working on this issue . Can i take this up?
