### ISSUE TITLE
Cant install in anaconda python 2.7 due to pyparsing version mismatch

### ISSUE THREAD

**Issue by MarkPinches** [pgmpy/pgmpy#824]
I have had real troubles installing pgmpy in a python2.7 anaconda installation. It throws an error when installing the requiement.txt file, where pyparsing==2.1.8. However the latest version for this package available in anaconda is 2.1.4.

I am going to try installing on python 3.5 so hopefully that should work.

**Comment by ankurankan** [comment]
@MarkPinches Yes, we are having issues with both pyparsing and networkx dependencies on anaconda. But you can always use pip to install those.

**Comment by MarkPinches** [comment]
It installs fine on the anaconda version using python 3.5

**Comment by jz2575** [comment]
used requirement-dev.txt file and it was fine.
