### ISSUE TITLE
BaseEstimator

### ISSUE THREAD

**Issue by Mary-Kul** [pgmpy/pgmpy#832]
If I run code from Chapter 5 of your book 
`import numpy as np`
`import pandas as pd`
`from pgmpy.models import BayesianModel`
`from pgmpy.estimators import BaseEstimator`

`raw_data = np.random.randint(low=0, high=2,`
`size=(1000, 6))`
`print(raw_data)`

`data = pd.DataFrame(raw_data, columns=['A', 'R', 'J',`
`'G', 'L', 'Q'])`

`student_model = BayesianModel([('A', 'J'), ('R', 'J'),
('J', 'Q'), ('J', 'L'),('G', 'L')])`
`student_model.fit(data, estimator_type=BaseEstimator)`
`student_model.get_cpds()`

I get the following issue:
`Traceback (most recent call last):
  File "test.py", line 37, in <module>
    student_model.fit(data, estimator_type=BaseEstimator)
  File "python/site-packages/pgmpy/models/BayesianModel.py", line 569, in fit
    raise TypeError("Estimator object should be a valid pgmpy estimator.")
TypeError: Estimator object should be a valid pgmpy estimator.`

As I saw in the fit function the 'problem' line
`if not isinstance(estimator_type, BaseEstimator):`
should I pass smth else to the estimator_type?

**Comment by khalibartan** [comment]
@Mary-Kul The code example of book will no longer function with current version of pgmpy. Please install latest version of pgmpy and try running the following code:
```
import numpy as np
import pandas as pd
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator

raw_data = np.random.randint(low=0, high=2,
size=(1000, 6))
print(raw_data)

data = pd.DataFrame(raw_data, columns=['A', 'R', 'J',
'G', 'L', 'Q'])

student_model = BayesianModel([('A', 'J'), ('R', 'J'), ('J', 'Q'), ('J', 'L'),('G', 'L')])
student_model.fit(data, estimator=MaximumLikelihoodEstimator)

student_model.get_cpds()
```
Here is the output on my system
```
[<TabularCPD representing P(A:2) at 0x7fdcc9d02320>,
 <TabularCPD representing P(G:2) at 0x7fdcc9d024e0>,
 <TabularCPD representing P(J:2 | A:2, R:2) at 0x7fdcc9d02898>,
 <TabularCPD representing P(L:2 | G:2, J:2) at 0x7fdcc9d02b70>,
 <TabularCPD representing P(Q:2 | J:2) at 0x7fdcd513add8>,
 <TabularCPD representing P(R:2) at 0x7fdcc9d02c18>]
```
Please note that argument `estimator_type` has been replaced with `estimator` in latest dev branch.
