### ISSUE TITLE
Maximum Likelyhood structure learning

### ISSUE THREAD

**Issue by Mary-Kul** [pgmpy/pgmpy#833]
I am working through your book chapter 5

there is a code from your book:
```
import numpy as np
import pandas as pd
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator

# Generating random data
raw_data = np.random.randint(low=0, high=2,
size=(1000, 2))
data = pd.DataFrame(raw_data, columns=['X', 'Y'])
print(data.head())
coin_model = BayesianModel([])
coin_model.fit(data)
coin_model.get_cpds()
```

It gives empty cpds as output -but structure learning should have given cps X and X|Y, and add an edge
what should be done to make it work right?

**Comment by kris-singh** [comment]
I think you should use latest pgmpy version. I think you are using 0.1.0. You shoud update it to 0.1.3

**Comment by Mary-Kul** [comment]
When I try to update to the latest version I get this - can you help me with it?

  
Could not find a version that satisfies the requirement pgmpy==0.1.3 (from versions: 0.1.0, 0.1.1, 0.1.2)
No matching distribution found for pgmpy==0.1.3
