### ISSUE TITLE
Score based structure learning approaches for bayesian network with continuous variables 

### ISSUE THREAD

**Issue by faeahi** [pgmpy/pgmpy#836]
Hello.
I want to learn bayesian network from a dataset with continuous values and i need to use score based approachs for structure learning.
I want to know is there score based structure learning approachs for this in this package?
Thanks.

**Comment by ankurankan** [comment]
Hi,

We currently don't have support for learning continuous variables.

Cheers
Ankur

**Comment by faeahi** [comment]
Thank you so much for your reply

**Comment by khalibartan** [comment]
Duplicate to #772 .
