### ISSUE TITLE
Learning: Parameter Estimator not found

### ISSUE THREAD

**Issue by jayurbain** [pgmpy/pgmpy#842]
I've been getting different errors experimenting with parameter and structure learning using the example notebooks. I've tried the examples in the book and the notebooks referenced below (available in the pgmpy and pgmpy_notebook distributions).

I've cloned the latest version of the software (with earlier releases I've received different errors).

Notes: 
- I've also tried the API in the book.
- The instructions for compatibility in the README.md file on gitbut do not march requirements.txt in the distribution.
- I've tried multiple python environments.

Here is my current environment:
name: pgmpy35
channels: !!python/tuple
- !!python/unicode
  'defaults'
dependencies:
- cython=0.25.2=py35_0
- mkl=11.3.1=0
- numpy=1.11.0=py35_0
- openssl=1.0.2k=0
- pandas=0.19.2=np111py35_1
- pip=9.0.1=py35_1
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- readline=6.2=2
- scipy=0.17.0=np111py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3

Here are the current errors:

In the pgmpy_notebook/Learning Bayesian Networks from Data, I receive:
```python
from pgmpy.estimators import ParameterEstimator
pe = ParameterEstimator(model, data)

print("\n", model.state_counts('fruit'))  # unconditional
print("\n", model.state_counts('tasty'))  # conditional on fruit and size
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-004159b6cebd> in <module>()
----> 1 from pgmpy.estimators import ParameterEstimator
      2 pe = ParameterEstimator(model, data)
      3 
      4 print("\n", model.state_counts('fruit'))  # unconditional
      5 print("\n", model.state_counts('tasty'))  # conditional on fruit and size

ImportError: cannot import name 'ParameterEstimator'
```

In the pgmy/examples notebook Learning from data, I receive:
```python
from pgmpy.estimators import ParameterEstimator
pe = ParameterEstimator(model, data)

print("\n", model.state_counts('fruit'))  # unconditional
print("\n", model.state_counts('tasty'))  # conditional on fruit and size
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-004159b6cebd> in <module>()
----> 1 from pgmpy.estimators import ParameterEstimator
      2 pe = ParameterEstimator(model, data)
      3 
      4 print("\n", model.state_counts('fruit'))  # unconditional
      5 print("\n", model.state_counts('tasty'))  # conditional on fruit and size

ImportError: cannot import name 'ParameterEstimator'
```

Any assistance would be appreciated. 

Thanks,
Jay

**Comment by khalibartan** [comment]
@jayurbain Our README.md needs an update we no longer need cython as dependency. How did you install pgmpy?
Please follow the instructions given in README (don't look at dependencies mentioned in README dependency section we will update that). You can use conda or miniconda for installing dependencies (recommended). If you still face issues ping me back.

**Comment by khalibartan** [comment]
@jayurbain Our README.md needs an update we no longer need cython as dependency. How did you install pgmpy?
Please follow the instructions given in README (don't look at dependencies mentioned in README dependency section we will update that). You can use conda or miniconda for installing dependencies (recommended). If you still face issues ping me back.

**Comment by jayurbain** [comment]
First, I tried to install pgmpy in an existing python 3.5 conda environment with the latest Scipy, Pandas, NumPy, etc.
$ git clone https://github.com/pgmpy/pgmpy
$ cd pgmpy
$ conda install --file requirements.txt <- this failed due to the versions in requirements.txt
$ sudo python setup.py install <- basically worked, but I received the errors above.

Then I uninstalled pgmpy

Second, I created a new conda environment with python 3.5, activated this environment and tried to install packages as close as possible as listed on the README. This is the environment I have listed above. Note that some of the packages are newer than the README. Conda would give me unavailable or incompatible type error messages if I tried to match it.
$ git clone https://github.com/pgmpy/pgmpy
$ cd pgmpy
$ sudo python setup.py install <- basically worked, but still receive the errors above.

I do not fully understand your comment "Please follow the instructions given in README (don't look at dependencies mentioned in README dependency section we will update that)."

To the best of my knowledge, I am following the instructions. Please let me know, specifically, what steps and package versions required.

Thanks,
Jay

**Comment by jayurbain** [comment]
Follow up: I went through the entire process again, except when I created a conda environment I installed the latest version of each required package. I was getting errors with an estimator and also had to install the wrapt package, so you should add this to your list.

Much better results. 

pgmpy/examples/Learning from data.ipynb ran without any errors

pgmpy_notebook/notebooks/Learning Bayesian Networks from Data.ipynb two errors, one of which happens with what you have posted online. Below I've included my configuration and the two errors below.

Impressive piece of software.

```python

Here is my configuration:
name: pgmpy35x1
channels: !!python/tuple
- !!python/unicode
  'defaults'
dependencies:
- cython=0.25.2=py35_0
- decorator=4.0.11=py35_0
- mkl=2017.0.1=0
- networkx=1.11=py35_0
- numpy=1.11.3=py35_0
- openssl=1.0.2k=0
- pandas=0.19.2=np111py35_1
- pip=9.0.1=py35_1
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- readline=6.2=2
- scipy=0.18.1=np111py35_1
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- wrapt=1.10.8=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - pgmpy==0.1.3
prefix: /Applications/anaconda/envs/pgmpy35x1

```

pgmpy_notebook/notebooks/Learning Bayesian Networks from Data.ipynb had the following errors, one of which happens with what you have posted online.

```python
>>> # Calibrate all CPDs of `model` using MLE:
... model.fit(data, estimator_type=MaximumLikelihoodEstimator)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/jayurbain/Dropbox/pgmpy/pgmpy/models/BayesianModel.py", line 695, in fit
    cpds_list = estimator.get_parameters(**kwargs)
TypeError: get_parameters() got an unexpected keyword argument 'estimator_type'


>>> from pgmpy.estimators import MmhcEstimator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'MmhcEstimator'
>>> 
>>> data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
>>> data['A'] += data['B'] + data['C']
>>> data['H'] = data['G'] - data['A']
>>> data['E'] *= data['F']
>>> 
>>> mmhc = MmhcEstimator(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'MmhcEstimator' is not defined
>>> skeleton = mmhc.mmpc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mmhc' is not defined
>>> print("Part 1) Skeleton: ", skeleton.edges())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'skeleton' is not defined
>>> 
>>> # use hill climb search to orient the edges:
... hc = HillClimbSearch(data, scoring_method=BDeuScore(data))
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'BDeuScore' is not defined
>>> model = hc.estimate(tabu=10, white_list=skeleton.to_directed().edges())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'skeleton' is not defined
>>> print("Part 2) Model:    ", model.edges())
Part 2) Model:     [('A', 'D'), ('B', 'D'), ('C', 'D')]
>>> 
>>> 

```

Thanks,
Jay

**Comment by ankurankan** [comment]
@jayurbain The first error that you are getting is because we have updated the argument name. So, just replace `estimator_type` with `estimator` and it should work. For the second error, we still don't have an implementation of Mmhc.

**Comment by jayurbain** [comment]
_Thanks_
Jay

**Comment by jayurbain** [comment]
Actually I have an error I did not report earlier in 'Learning from data' notebook

Unexpected keyword argument 'prior_type' (when calling fit() )

Here's the full error:

# Learning with Bayesian Estimator using dirichlet prior for each variable.

pseudo_counts = {'D': [300, 700], 'I': [500, 500], 'G': [800, 200], 'L': [500, 500], 'S': [400, 600]}
model.fit(data, estimator=BayesianEstimator, prior_type='dirichlet', pseudo_counts=pseudo_counts)
for cpd in model.get_cpds():
    print("CPD of {variable}:".format(variable=cpd.variable))
    print(cpd)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-5a82ced763de> in <module>()
      2 
      3 pseudo_counts = {'D': [300, 700], 'I': [500, 500], 'G': [800, 200], 'L': [500, 500], 'S': [400, 600]}
----> 4 model.fit(data, estimator=BayesianEstimator, prior_type='dirichlet', pseudo_counts=pseudo_counts)
      5 for cpd in model.get_cpds():
      6     print("CPD of {variable}:".format(variable=cpd.variable))

TypeError: fit() got an unexpected keyword argument 'prior_type'

Thanks,
Jay
