### ISSUE TITLE
Updating notebooks to new API

### ISSUE THREAD

**Issue by khalibartan** [pgmpy/pgmpy#843]
API used in many ipython notebooks in pgmpy_notebooks doesn't match with current API of pgmpy. We must update them.

**Comment by ankurankan** [comment]
Let's keep the issues for pgmpy and pgmpy_notebooks separate. Can you please open this in pgmpy_notebooks repo ?

**Comment by khalibartan** [comment]
@ankurankan I opened it up because it links here.New users many times uses the pgmpy book and our notebooks for understanding the API and its quite difficult for the to understand whats wrong is happening. Also fixes made here are not regularly updated in pgmpy_notebooks because new contributors don't go to pgmpy_notebooks that often.

**Comment by ankurankan** [comment]
@khalibartan We should have a different way to linking then. It will get too complicated in future to separate issues otherwise. I have already put a link to notebooks in our read me. Maybe I will put it in our examples folder also.
