### ISSUE TITLE
Estimating probability given complete set of evidence

### ISSUE THREAD

**Issue by RamonBeast** [pgmpy/pgmpy#848]
I'm sorry in advance if questions are not allowed, and if so please remove this.

I learned a network from data and I was wondering: given a complete set of evidence (so I don't need inference) how can I calculate the probability that this set has been generated by my learned model?

Thank you.

**Comment by ankurankan** [comment]
@RamonBeast So, if you consider you data to be i.i.d., the total probability should be the product of the probabilities of getting each individual data point. And each fully observed data point's probability can be found directly from the joint distribution over all the variables. We don't have a direct function for that in pgmpy but should be fairly easy to compute.

**Comment by RamonBeast** [comment]
Thank you @ankurankan that's the kind of lead I was looking for!

**Comment by khalibartan** [comment]
@ankurankan Do we want to implement this functionality ? If not then we can close this issue.

**Comment by ankurankan** [comment]
@khalibartan Yes, I think we should have a features something like this.

**Comment by RamonBeast** [comment]
If you'll need help testing the feature when implemented, I'll be happy to help of course!

**Comment by MrManager17** [comment]
Is there any word on this functionality?  It would be incredibly useful for me.

**Comment by ankurankan** [comment]
@srskoch15 I am working on this. Should be fixed in the next couple of weeks. 
In the meanwhile, if you would like to have a temporary solution, you can simply multiply the specific states of the CPDs in the network.

**Comment by marchezinixd** [comment]
Is there any word on this functionality? It would be incredibly useful for me.

**Comment by changjie98** [comment]
Is this problem solved？ I think this function is great, it is necessary

**Comment by ankurankan** [comment]
@changjie98 Yes, if the `query` methods now get the parameter `joint=True`, it will automatically compute the joint distribution over all the variables in the `variables` parameter. Here's an example:

```python
In [1]: >>> import pandas as pd 
   ...: >>> from pgmpy.models import BayesianModel 
   ...: >>> from pgmpy.inference import VariableElimination
   ...: >>> values = pd.DataFrame(np.random.randint(low=0, high=2, size=(1000, 5)), 
   ...: ...                       columns=['A', 'B', 'C', 'D', 'E']) 
   ...: >>> model = BayesianModel([('A', 'B'), ('C', 'B'), ('C', 'D'), ('B', 'E')]) 
   ...: >>> model.fit(values) 
   ...: >>> inference = VariableElimination(model)         

In [2]: inference.query(variables=['A', 'B', 'C'], evidence={'D': 0, 'E':0}, joint=True)                               
Finding Elimination Order: : : 0it [00:00, ?it/s]
0it [00:00, ?it/s]
Out[2]: <DiscreteFactor representing phi(C:2, A:2, B:2) at 0x7fab22430240>

In [3]: print(_)                                           
+------+------+------+--------------+
| C    | A    | B    |   phi(C,A,B) |
+======+======+======+==============+
| C(0) | A(0) | B(0) |       0.1357 |
+------+------+------+--------------+
| C(0) | A(0) | B(1) |       0.1303 |
+------+------+------+--------------+
| C(0) | A(1) | B(0) |       0.1172 |
+------+------+------+--------------+
| C(0) | A(1) | B(1) |       0.1275 |
+------+------+------+--------------+
| C(1) | A(0) | B(0) |       0.1237 |
+------+------+------+--------------+
| C(1) | A(0) | B(1) |       0.1313 |
+------+------+------+--------------+
| C(1) | A(1) | B(0) |       0.1135 |
+------+------+------+--------------+
| C(1) | A(1) | B(1) |       0.1209 |
+------+------+------+--------------+

```
