### ISSUE TITLE
Extend BayesianModel to accept ContinuousFactor?

### ISSUE THREAD

**Issue by linzhp** [pgmpy/pgmpy#850]
@ankurankan @khalibartan

I need to construct a Bayesian network to performance inference on non-Gaussian continuous distributions. Looks like the current implementation doesn't support that. What's the best way to do it?

Should I extend BayesianModel to accept ContinuousFactor, and update the inference algorithms?

**Comment by khalibartan** [comment]
@linzhp We are actually having discussion over the fact that should we allow adding continuous factors in our bayesian model or not and how will it affect the performance and maintainability of existing BayesianModel. If you have any ideas in mind you can discuss, also pgmpy currently doesn't support inference algorithms for continuous models (even for linear Gaussian nets) you will need to add that also. Refer #751 .

**Comment by linzhp** [comment]
I'd love to contribute. What are the main obstacles that you are aware of?

**Comment by linzhp** [comment]
Of the top of my head, learning the dependency structure and conditional probability would be hard for continuous distributions, but inferences with known dependency structure and conditional probability shouldn't be too hard, right? Maybe we could start with inference?

I just came across [this paper](http://scottdavies.net/uai2000.pdf) about learning mixture of Gaussian for Bayes net.

**Comment by csbuja** [comment]
@linzhp - That paper seems like a good approach for learning the joint distribution in a subgraph of the PGM, but in order for that to be useful, we need to be able to do continuous inference.

Thus, I think it makes sense to do prioritize implementation of inference over continuous variables, for arbitrary joint pdfs.

**Comment by linzhp** [comment]
Totally agree

**Comment by ankurankan** [comment]
@linzhp @csbuja You should look at #782 and #837  for getting the bigger picture and what we are planning to do. In short we are trying to have a common api over DiscreteFactor and ContinuousFactor so that our current inference algorithms work on ContinuousFactors also without much change.
