### ISSUE TITLE
Support for deterministic node?

### ISSUE THREAD

**Issue by linzhp** [pgmpy/pgmpy#858]
If the value of a node is a deterministic function (e.g., max) of its parents', which are all continuous variable, does pgmpy support such node? 

@ankurankan @yashu-seth ?

**Comment by ankurankan** [comment]
@linzhp: No you won't be able to do inference on such models right now with pgmpy. We are working on adding this feature.

**Comment by BartekSzpak** [comment]
Hi, the question above is 3 years old, wonder if there were some changes in the meantime and if this is now possible?

**Comment by ankurankan** [comment]
@BartekSzpak No, it hasn't been implemented yet. It's mostly stuck on having a functional representation of CPDs but I can't think of a way to implement a generic inference algorithm that could work for all cases.

Though in some cases, you should be able to define the CPD in a way that it behaves like a deterministic variable. For example if you want some fixed state, define it's probability to be 1 and rest to be 0.
