### ISSUE TITLE
New installer error

### ISSUE THREAD

**Issue by michaelrempel** [pgmpy/pgmpy#859]
I installed successfully a few days ago, but now I get an error installing.
no lapack/blas resources found

running either 3.5 or 2.7.12 on a fresh install.
This happens on ubuntu 16.04 and debian 8.x

I would appreciate a quick fix if available.

**Comment by ankurankan** [comment]
@michaelrempel You need to install lapack or blas. Just Google for installation instructions for your operating system.

**Comment by michaelrempel** [comment]
I did that. The error message could be clearer. The way it is suggests a bug in the installer.

**Comment by ankurankan** [comment]
@michaelrempel That's actually an error from scipy.
