### ISSUE TITLE
Can not find BicScore, HillClimbSearch in estimators

### ISSUE THREAD

**Issue by Henrilin28** [pgmpy/pgmpy#868]
I successfully install pgmpy in python 2.7 and 3.5, but I can not find BicScore, HillClimbSearch in estimators. It would be great if someone can answer my question!

**Comment by ankurankan** [comment]
Hi Henry,

All the estimators are here:
https://github.com/pgmpy/pgmpy/tree/dev/pgmpy/estimators. You can just
import it using:

from pgmpy.estimators import BicScore
Or:
from pgmpy.estimators import HillClimbSearch

Cheers
Ankur

**Comment by Henrilin28** [comment]
Hi I found out that 0.1.2 when using pop install may have problem to import those estimators. I solved this problem by cloning the repo. 

Best,
Henry

**Comment by ankurankan** [comment]
I am sorry, I forgot to mention that. The pip version is a bit old.
