### ISSUE TITLE
ModuleNotFoundError: No module named 'pgmpy.factors.discrete'

### ISSUE THREAD

**Issue by pwichmann** [pgmpy/pgmpy#871]
I cannot explain why I get the error:

> ModuleNotFoundError: No module named 'pgmpy.factors.discrete'

Even though pgmpy is installed and other modules get imported.
It occurs for the following import statement:
`from pgmpy.factors.discrete.CPD import TabularCPD`

**Comment by ankurankan** [comment]
@pwichmann Did you install pgmpy from pip or built the latest code from github ?

**Comment by pwichmann** [comment]
I used pip.

And Python 3.6.1.

**Comment by ankurankan** [comment]
@pwichmann The pip version is a bit old and that's why you are getting that error. You can follow the instructions here: https://github.com/pgmpy/pgmpy/blob/dev/README.md for installing the latest version.

**Comment by pwichmann** [comment]
This is probably a stupid question. But how do I install pgmpy in a specific conda environment? Does it work the same way - by running the install.py?

**Comment by ankurankan** [comment]
@pwichmann Yes, just run `python setup.py install` inside the conda environment.
