### ISSUE TITLE
ImportError: cannot import name 'BayesianEstimator'

### ISSUE THREAD

**Issue by MikeDT** [pgmpy/pgmpy#879]
Executing the following example code (as provided by the pgmpy site and help files) fails

```
import pandas as pd
from pgmpy.models import BayesianModel
from pgmpy.estimators import BayesianEstimator
data = pd.DataFrame(data={'A': [0, 0, 1], 'B': [0, 1, 0], 'C': [1, 1, 0]})
model = BayesianModel([('A', 'C'), ('B', 'C')])
estimator = BayesianEstimator(model, data)
cpd_C = estimator.estimate_cpd('C', prior_type="dirichlet", pseudo_counts=[1, 2])
print(cpd_C)
```

I get the following error

Traceback (most recent call last):

  File "<ipython-input-10-db37e08a24d3>", line 1, in <module>
    runfile('C:/Users/Mike/.spyder-py3/temp.py', wdir='C:/Users/Mike/.spyder-py3')

  File "C:\Users\Mike\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Mike\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Mike/.spyder-py3/temp.py", line 3, in <module>
    from pgmpy.estimators import BayesianEstimator

ImportError: cannot import name 'BayesianEstimator'

**Comment by MikeDT** [comment]
I worked through the precise install instructions, all seems above board.  Any and all examples appear to fail, I simply can't import anything other than the MaximumLikelihoodEstimator, and when I do I'm greeted with

TypeError: ('Values: Expected type int or type float, got ', dtype('int64'))

which appears to be "resolved"  elsewhere, but I'm not getting the benefit :(

**Comment by MikeDT** [comment]
All - the solution to this appears to be a thorough (possibly manual) install of all associated apps, **then** install pgmpy

**Comment by ankurankan** [comment]
@MikeDT Ideally a simple pip/python setup.py install should automatically install all the required packages. Can you please share which OS you are using and the python version, so that we can debug this?

**Comment by MikeDT** [comment]
Hi chaps, keeping this closed for the time being, but the general findings appear to be that the installation of prereqs for the package is somewhat precarious (I'm currently tying to find the sweet spot where Tensorflow/Theano + Keras AND PGMPY works. When I work out the sweet spot I will repost formally.

As an aside, thanks for the rapid responses, very encouraging :)
