### ISSUE TITLE
TypeError: Estimator object should be a valid pgmpy estimator.

### ISSUE THREAD

**Issue by onlycjp** [pgmpy/pgmpy#880]
I use the same code,but have bugs
# mLikelihoodEstimator)Generate data
import numpy as np
import pandas as pd

raw_data = np.array([0] * 30 + [1] * 70) # Representing heads by 0 and tails by 1
data = pd.DataFrame(raw_data, columns=['coin'])
print(data)

# Defining the Bayesian Model
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator,BaseEstimator

model = BayesianModel()
model.add_node('coin')
print(model.check_model())
model.fit(data,estimator_type=BaseEstimator)

**Comment by khalibartan** [comment]
@onlycjp Which version are you using? Actually `estimator_type` argument has been replaced with `estimator` so above code sample would raise an error in current version. Other than that you haven't added CPD to the model so `print(model.check_model('coin'))` statement would raise value error.

You can use following code sample it would run just fine.

```
import numpy as np
import pandas as pd

data = pd.DataFrame(data={'coin':np.array([0]*30+[1]*70)})
print(data)

from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator

model = BayesianModel()
model.add_node('coin')
model.fit(data, estimator=MaximumLikelihoodEstimator)
print(model.get_cpds())
print(model.get_cpds()[0])
```
Output:
```
In [18]: print(model.get_cpds())
[<TabularCPD representing P(coin:2) at 0x7fb20216fb38>]

In [19]: print(model.get_cpds()[0])
╒═════════╤═════╕
│ coin(0) │ 0.3 │
├─────────┼─────┤
│ coin(1) │ 0.7 │
╘═════════╧═════╛
```
