### ISSUE TITLE
installing pgmpy in anaconda

### ISSUE THREAD

**Issue by faeahi** [pgmpy/pgmpy#881]
hello 

my operating system is windows 7  and i'm using anaconda for python 2.7.
i have install pgmpy with "conda install pgmpy" but the problem is, this installed package doesn't have many features that i need such as structure learning approach, BayesianEstimator parameter learning and so on.
Is there any solution for solving this problem?
Is there every one who can help me?

thanks.

**Comment by ankurankan** [comment]
@faeahi We haven't hosted the package on conda repo so you can't use `conda install pgmpy`. The best way to get the latest version is to clone/download our repo and install from there. Something like this:
```
git clone https://github.com/pgmpy/pgmpy.git
cd pgmpy; python3 setup.py install
```

**Comment by ankurankan** [comment]
Update: We have an anaconda package now and can be installed using `conda install -c ankurankan pgmpy`

**Comment by basavarajuise** [comment]
> Update: We have an anaconda package now and can be installed using `conda install -c ankurankan pgmpy`

Not working

**Comment by ankurankan** [comment]
@basavarajuise What error are you getting?

**Comment by basavarajuise** [comment]
Failed to find in  environment after executing the command in annoconda
prompt
And no module found error when I am using this in my program
