### ISSUE TITLE
HillClimbSearch removed?

### ISSUE THREAD

**Issue by petacube** [pgmpy/pgmpy#896]
python pgmpy/tests/test_estimators/test_HillClimbSearch.py
Traceback (most recent call last):
  File "pgmpy/tests/test_estimators/test_HillClimbSearch.py", line 6, in <module>
    from pgmpy.estimators import HillClimbSearch, K2Score
ImportError: cannot import name 'HillClimbSearch'

**Comment by petacube** [comment]
looks like its not installed correcty. from  pgmpy.estimators import HillCllimbSearch only works in pgmpy source directory

**Comment by lohani2280** [comment]
@petacube Its working fine on my system. I would recommend you to create a freshly new  `virtual environment` and then install the `dependencies` in that environment using `pip install -r requirements.txt` and then do `sudo python setup.py install` . After this run `python pgmpy/tests/test_estimators/test_HillClimbSearch.py` from the `virtual environment` itself . I think following these steps won't throw any ImportError.

**Comment by petacube** [comment]
i tried without luck

**Comment by ankurankan** [comment]
@petacube Sorry for the late reply. I just pushed a new version on pypi (0.1.4). Try installing it again and it should work.

**Comment by petacube** [comment]
tried new version, same problem

**Comment by ankurankan** [comment]
@petacube Could you please share what operating system you are using and the output for `pip freeze` ?

**Comment by petacube** [comment]
Ankur,
python 3.5 anaconda 
MacOS Siera 10.12.6

freeze | grep pgmpy
pgmpy==0.1.2

**Comment by ankurankan** [comment]
@petacube So, there's some problem with pgmpy installation. The latest version should be 0.1.4.

**Comment by petacube** [comment]
do you have different versions on github vs pypi?

**Comment by ankurankan** [comment]
@petacube No, it's both the same. The `dev` branch and pypi.

**Comment by petacube** [comment]
ok
i had to manually remove old version 0.1.2 (pip uninstall pgmpy) and install 0.1.4 
now it works

what was the issue and how did you fixed?

most interestly, how did version 0.1.2 worked in your environment but not mine

**Comment by ankurankan** [comment]
It was already fixed in 0.1.3. And we were all actually using 0.1.3 that's why it was working for us,

**Comment by petacube** [comment]
got it
btw install from git works without a problem

install from pip fails
pip install pgmpy
fails saying no such file “AUTHORS.rst"

**Comment by ankurankan** [comment]
Thanks for pointing that out. It's all fixed now. That was something weird with pypi.
