### ISSUE TITLE
Install requirement pyparsing package missing

### ISSUE THREAD

**Issue by jingsliu** [pgmpy/pgmpy#902]
### Subject of the issue
When I run conda install --file requirements.txt, got package missing error for pyparsing 2.1.8. 

Error message:
```
pgmpy-dev jshliu$ conda install --file requirements.txt
Fetching package metadata .........

PackageNotFoundError: Packages missing in current channels:
            
  - pyparsing ==2.1.8

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

### Your environment
I'm using Mac and python 2.7 and am trying to install the dev version of pgmpy. Removing the version requirement solves the issue by updating pyparsing to version 2.2.0

**Comment by ankurankan** [comment]
@jingsliu Thanks for reporting the issue. I have updated the version in `requirements.txt`.
