### ISSUE TITLE
 No need of using defaultdict for implementing get_cardinality method of various models.

### ISSUE THREAD

**Issue by lohani2280** [pgmpy/pgmpy#904]
I think a normal dict would also suffice this implementation.Its because, defaultdict is similar to the usual dictionary (dict) container, but it has one difference: that it is initialized with a function that takes no arguments and provides the default value for a nonexistent key. Thus , a defaultdict will never raise a KeyError if you try to get an item with a key that is not currently in the dictionary unlike usual dict container.
Now ,here in this method we are always appending variables and its corresponding cardinality into the dict container.We are never retrieving a value using a key(either an existing or non-existing key). So ,if their is no retrieval then a normal dict would itself suffice .

**Comment by ankurankan** [comment]
@lohani2280 We are not retrieving values in these methods, but we will need to do that in the inference methods. But even in that case I would prefer to get an error rather than returning some default value.

> Errors should never pass silently. - Zen of Python

**Comment by lohani2280** [comment]
@ankurankan As you said ,inference methods needs retrieving values from get_cardinality method , therefore, `defauldict` is a better way of implemention. We now just need to get an error rather than returning some default value. Therefore, closing this issue.

**Comment by ankurankan** [comment]
@lohani2280 I didn't mean to say that `defaultdict` is a better option. I think `dict` would be better option because it will automatically throw a `KeyError` if we try to retrieve some unknown node.
