### ISSUE TITLE
'TestXMLBIFReaderMethods' and 'TestXMLBIFWriterMethodsString' test cases are failing on Python 3

### ISSUE THREAD

**Issue by dasayan05** [pgmpy/pgmpy#909]
a `nosetests -v` is failing with

> ERROR: test_get_edges (pgmpy.tests.test_readwrite.test_XMLBIF.TestXMLBIFReaderMethods)
> Traceback (most recent call last):
>   File "/home/spyder/Desktop/pgmpy/pgmpy/tests/test_readwrite/test_XMLBIF.py", line 130, in setUp
>     self.reader = XMLBIFReader(string=TEST_FILE)
>   File "/home/spyder/Desktop/pgmpy/pgmpy/readwrite/XMLBIF.py", line 55, in \_\_init\_\_
>     self.network = etree.fromstring(string).find('NETWORK')
>   File "src/lxml/lxml.etree.pyx", line 3228, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79609)
>   File "src/lxml/parser.pxi", line 1843, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119069)
> ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

and

> ERROR: test_write_xmlbif_statefull (pgmpy.tests.test_readwrite.test_XMLBIF.TestXMLBIFWriterMethodsString)
> Traceback (most recent call last):
>   File "/home/spyder/Desktop/pgmpy/pgmpy/tests/test_readwrite/test_XMLBIF.py", line 281, in setUp
>     reader = XMLBIFReader(string=TEST_FILE)
>   File "/home/spyder/Desktop/pgmpy/pgmpy/readwrite/XMLBIF.py", line 55, in \_\_init\_\_
>     self.network = etree.fromstring(string).find('NETWORK')
>   File "src/lxml/lxml.etree.pyx", line 3228, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79609)
>   File "src/lxml/parser.pxi", line 1843, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119069)
> ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
>

**Comment by khalibartan** [comment]
@dasayan05 They are failing on my system too. This is because of lxml, its installation is not being tested on travis.
@ankurankan Can you verify this, please?

**Comment by ankurankan** [comment]
@khalibartan Yes, I am also getting the error with xml. Not sure why though. 
@dasayan05 Thanks for reporting this.

**Comment by dasayan05** [comment]
It is because `XMLBIFReader(string)` and in turn `lxml.etree.fromstring(string)` take `bytes` as argument not `str`, but the `TEST_FILE` variable (in `pgmpy/tests/test_readwrite/test_XMLBIF.py`) is an `str`. A simple `.encode('utf-8')` would fix it.

Please see #910
