### ISSUE TITLE
Doc problem with DynamicBayesianNetwork class

### ISSUE THREAD

**Issue by javierlorenzod** [pgmpy/pgmpy#917]
### Subject of the issue
In the [documentation webpage](http://pgmpy.org/) the documentation of the DBN class is missing. 

### Your environment
* version of pgmpy
0.1.2
* Operating System
Ubuntu 16.04
### Steps to reproduce
Click on DynamicBayesianNetwork class in the index.

### Expected behaviour
Redirect to DBN class documentation

### Actual behaviour
Redirect to FactorGraph class documentation

**Comment by ankurankan** [comment]
@JavierLordi815 Thanks for reporting this. I will fix this ASAP.
