### ISSUE TITLE
TypeError: object of type 'dict_keyiterator' has no len()

### ISSUE THREAD

**Issue by MrManager17** [pgmpy/pgmpy#927]
### Subject of the issue
The ExactInference.py file in line 592 references len(subtree.neighbors(x).  This method is of the subtree which is a JunctionTree object.  the neighbors method returns an iterator from the networkx package which doesn't have length.

### Your environment
* pgmpy version 0.1.6
* Python version 3.6.3
* Operating System Windows 10

### Steps to reproduce
Tell us how to reproduce this issue. Please provide the complete code if possible.
Take any Bayesian model, call the to_junction_tree() method.  Then send that to the BeliefPropagation constructor and query with variables and evidence.

### Expected behaviour
Should be able to complete the query.

### Actual behaviour
Throws a type error.

**Comment by MichaelNecio** [comment]
I was having this error, but was able to fix it by making sure I was using networkx 1.11. Somewhere I had updated to networkx 2.0 which caused this error.

**Comment by ankurankan** [comment]
Yes, this is an issue with the latest version of networkx. Closing this.

**Comment by gnerzic** [comment]
in networkx 2.0 you will get this error with code like this:
len(_somegraph_.neighbors(_somenode_))
You fix it like this:
len(list(_somegraph_.neighbors(_somenode_)))

As discussed here:
https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

**Comment by CurtisRose** [comment]
How was this closed? You say you should be using networkx 2.x. Yet this bug persists? 2 years later? Fix the bug or set the required version of networkx to 1.x.

**Comment by ankurankan** [comment]
@CurtisRose It's fixed in the dev branch. The conda package hasn't been updated in a while, that's why you are getting the error. Try building it from the codebase.
