### ISSUE TITLE
Reading a XML BIF with isolated nodes

### ISSUE THREAD

**Issue by davenza** [pgmpy/pgmpy#936]
The XMLBIFReader class doesn't allow to return the model from a BIF XML file where there are isolated nodes. 

I can create the XMLBIFReader:
`bif = pgmpy.readwrite.XMLBIF.XMLBIFReader('diabetes.xml')`

but when trying to return the model:
`bif_model = bif.get_model()`

It returns an exception because is trying to load the CPD of the isolated node, but this node is not included in the BayesianModel:
 `ValueError: ('CPD defined on variable not in the model', <TabularCPD representing P(skin:1) at 0x7f669d905c10>)` arises.

Reviewing the  `XMLBIFReader.get_model()`, we can see that the Bayesian model is created from the edges: 

`model = BayesianModel(self.get_edges())`

As an isolated node has no edge by definition, I think that the BayesianModel can't know that an isolated node exists when adding the cpds to the BayesianModel.

I provide the following XML BIF as a MWE. It is a XML BIF learnt using WEKA BayesNet class.
[diabetes.zip](https://github.com/pgmpy/pgmpy/files/1449591/diabetes.zip)

I think that even when an isolated node is not the most useful thing to do, it is a nuisance that we can't load the rest of the network.

Execution environment.
pgmpy: 0.1.3
Python: 2.7
OS: Ubuntu 16.04

**Comment by ankurankan** [comment]
@davenza Thanks a lot for reporting the issue. I have fixed it in #937. If you would like you can pull that PR and it should work for your network. Or you can wait for it to be merged and then update your installation of pgmpy.

**Comment by louMon** [comment]
which one is the library to XMLBIFWriter and XMLBIFReader?
