### ISSUE TITLE
Add tests for reading and writing files with disconnected nodes

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#938]
### Subject of the issue
Ref #936 for the complete issue. Got fixed in #937.
Need to add tests for this specific case as well as tests for writing networks with disconnected nodes for all supported formats.

**Comment by lohani2280** [comment]
@ankurankan I have gone through the file `XMLBIF.py` and I want to work on this issue. We need to add test for reading and writing network file in XMLBIF format(initially, for this specific case) with disconnected nodes. I see a `TEST_FILE` in `test_XMLBIF.py` file and using them all the tests are performed. However, it doesn't contain disconnected nodes. So shall i use another `TEST_FILE` inside the `test_XMLBIL.py` file which contains disconnected nodes? . Can you please suggest me a standard source where i can find those network files with disconnected nodes?.

**Comment by ankurankan** [comment]
@lohani2280 I don't think you will find any real world models with disconnected nodes since having disconnected nodes doesn't make much sense. So, I would just suggest you to add a new disconnected node to the current network file and write tests based on that.

**Comment by lohani2280** [comment]
@ankurankan Thanks for your reply. I will try to follow as you suggested and will soon send a PR

**Comment by ankurankan** [comment]
Fixed in #970
