### ISSUE TITLE
Joint Distribution over multiple variables using VariableElimination

### ISSUE THREAD

**Issue by huisophiewang** [pgmpy/pgmpy#945]
### Your environment
* pgmpy version: 0.1.6
* Python version: 2.7
* Operating System: Windows 

### Steps to reproduce
VariableElimination query function
For example, if I want to get Pr(A,B,C|D,E), it returns 3 factors, which I assume are marginalized probabilities. I think returning one joint probability makes more sense. We can get compute marginal probability from joint probability but not vice versa. 

I saw a previous post about the same issue. (https://github.com/pgmpy/pgmpy/issues/250). Have you already added this feature? If so, could you please point me to the place?

Thanks!
Hui

**Comment by ankurankan** [comment]
@sophiewxh Thanks for reporting this. Yes, it makes more sense to return a joint distribution instead of marginals for each variable and we still need to fix this. I will try to get this done ASAP

**Comment by namitjuneja** [comment]
Has this been implemented yet?

**Comment by ankurankan** [comment]
Fixed in 94a59f4d631d27ebcb456a1f90b2d3017e33070b 
@namitjuneja

**Comment by MathijsPost** [comment]
Hi Ankur, does this mean that when `joint=True` it returns P(A,B,C | D) and when `joint=False` it return the dict for every variable in the form of: P(A|D), P(B|D) and P(C|D)? Additionally, I am not sure how to interpret the result of the query when `joint=True`.

**Comment by ankurankan** [comment]
@MathijsPost Yes, that's correct. The difference between joint=True, and False is just how the `variables` argument is treated. So, when joint=True, it returns a joint distribution over the variables, and when it's false it treats each variable in `variables` as a separate query (but saves some computation by reusing intermediate results) and hence returns a distribution for each of them.

**Comment by MathijsPost** [comment]
@ankurankan Thank you so much once again for your fast and clear reply! You are really helping my thesis getting along, thank you!

**Comment by FishofJLlake** [comment]
thanks，This is also  helpful for me.
