### ISSUE TITLE
Example Incorrect?

### ISSUE THREAD

**Issue by njwhite** [pgmpy/pgmpy#950]
https://github.com/pgmpy/pgmpy/blob/3959d60562fb07121441bfd36b2cd536882325cb/pgmpy/models/BayesianModel.py#L747 should be `train_data`?

**Comment by ankurankan** [comment]
@njwhite Thanks for reporting this. You are right, it should be `train_data` instead of `values`. If you would like to create a PR for this, we would be happy to accept that. :smile:
