### ISSUE TITLE
Error using predict_probability 

### ISSUE THREAD

**Issue by mannou08** [pgmpy/pgmpy#955]
### Subject of the issue
Hello,

I have learned a Bayesian Network structure from data. Now I am using this model to estimate some probabilities. For this I am using a pandas data frame for the training data and the function predict_probability. But I get the following error:
"values: must contain tuples or array-like elements of the form (hashable object, type int)"
What could be the problem with the data frame "values" to generate this error?
I have verified that it does not contain nan or inf values.

Thanks a lot for your help!

##### Create Data frame 
values = pd.DataFrame(data)

###### Load Model
loaded_model = pickle.load(open('learned_model.p',"rb"))

##### Build BN
model = BayesianModel(loaded_model.edges())

##### Model fit
model.fit(values)
predict_data = values[:5]
predict_Hypothesis = predict_data.copy()
predict_Hypothesis.drop('Hypothesis', axis=1, inplace=True)
H_prob = model.predict_probability(predict_Hypothesis)

### Error
  File "C:\Users\q438848\AppData\Local\Continuum\anaconda3\lib\site-packages\pgmpy\factors\discrete\DiscreteFactor.py", line 418, in reduce
    raise TypeError("values: must contain tuples or array-like elements of the form "

TypeError: values: must contain tuples or array-like elements of the form (hashable object, type int)

**Comment by ankurankan** [comment]
@mannou08 Thanks for reporting the issue. I tried running this with random data and it works for me. Would it be possible for you to share your model and data, so that we can reproduce the issue ?

**Comment by mannou08** [comment]
[issue.zip](https://github.com/pgmpy/pgmpy/files/1534415/issue.zip)
@ankurankan Thanks a lot for your reply!
Here is the code and the data. Hope you could help me :)

**Comment by mannou08** [comment]
hey,
any idea where the error is coming from?
I think that the method has problems dealing with float values because the same model works with random integer values. But with random float values, I get the same error.

**Comment by mannou08** [comment]
hey,
could you reproduce the issue?
please I need some help...

**Comment by pjbqb** [comment]
I have the same problem:  models.BayesianNetwork supports the different states as text but DiscreteFactor reduce does not. They're passed from BNs to reduce in inference.ExactInference.VariableElimination when you have evidence:

        # Dealing with evidence. Reducing factors over it before VE is run.
        if evidence:
            for evidence_var in evidence:
                for factor in working_factors[evidence_var]:
                    factor_reduced = factor.reduce([(evidence_var, evidence[evidence_var])], inplace=False)


(evidence[evidence_var] will be text if BN values are text, or float, etc etc, where as factor_reduced only accepts ints).

I'm not exactly sure what would be the proper fix though :(

**Comment by zachguo** [comment]
@pjbqb I ran into the exact same problem, did you find a fix?

**Comment by zachguo** [comment]
@pjbqb Nevermind, I converted text values to ints using `LabelEncoder` from `sklearn`.

**Comment by zachguo** [comment]
It seemed to be working when I was using a small dataset, but it turned out to be a dead end(#1071 ) when I used real-world data.
