### ISSUE TITLE
Self looping not allowed and other queries

### ISSUE THREAD

**Issue by brindakrish** [pgmpy/pgmpy#960]
### Subject of the issue
Thank you for this amazing library. It is very useful. I am trying to use pgmpy to generate markov and hidden markov models. I have tried using MarkovModel() to create a basic markov model with three nodes and I want to add a self-loop in a node.

### Your environment
* pgmpy version: latest
* Python version: python 3
* Operating System: mac OS

### Steps to reproduce
student = MarkovModel([('Alice', 'Bob'), ('Alice', 'Alice'), ('Bob', 'Charles')])

### Expected behaviour
Successfully create a markov model.

### Actual behaviour
ValueError: Self loops are not allowed.

### Additional queries
•	I am currently using TabularCPD to add transition probabilities to my model. Is this valid? If so, how can I specify the direction of transition?
•	I could not find a function to add the initial probabilities in the markov model. Please advice.
•	I would also like to know if there is a function available to add observation probabilities for a hidden markov model.

**Comment by ankurankan** [comment]
@brindakrish I am guessing that you want to create a `MarkovChain` not a `MarkovModel`. Please have a look at `pgmpy.models.MarkovChain`.

**Comment by brindakrish** [comment]
@ankurankan Thanks for your immediate response. I am trying to use MarkovChain. But the documentation is not very clear on how the probabilities are assigned. I still cannot add observation probabilities to create hidden markov models. In the transition_model code below, what does 0, 1, and 2 represent? Are 'intel' and 'diff' states or the system producing states 0,1,2?

Add transition models
    >>> intel_tm = {0: {0: 0.25, 1: 0.75}, 1: {0: 0.5, 1: 0.5}}
    >>> model.add_transition_model('intel', intel_tm)
    >>> diff_tm = {0: {0: 0.1, 1: 0.5, 2: 0.4}, 1: {0: 0.2, 1: 0.2, 2: 0.6 }, 2: {0: 0.7, 1: 0.15, 2: 0.15}}
    >>> model.add_transition_model('diff', diff_tm)

Thanks for the help.
Brinda
Tagging @vsathwikm

**Comment by khalibartan** [comment]
@brindakrish For modelling you can use Dynamic Bayesian Network class, since HMMs are a special case of DBNs, I think there shouldn't be any problem in that.

**Comment by brindakrish** [comment]
Thanks. I will look into this.
