### ISSUE TITLE
Dependency conflict with python 3.6.x (x = 2,3,4)

### ISSUE THREAD

**Issue by shivariyer** [pgmpy/pgmpy#965]
### Subject of the issue
pgmpy installation using conda doesn't work when version of python is 3.6.2 or 3.6.3 or 3.6.4

### Your environment
* Python version
3.6.2, 3.6.3, 3.6.4
* Operating System
GNU/Linux (Ubuntu)

### Steps to reproduce
Create a new environment for installing pgmpy with python 3.6.4 (replace with 3.6.2 or 3.6.3 for same results)
`conda create -n pgm python=3.6.4`
Install pgmpy as instructed
`conda install -c ankurankan pgmpy`

### Expected behaviour
Conda should detect and resolve dependencies automatically and propose a list of packages to be installed, including pgmpy and the packages mentioned under requirements in the pgmpy project github landing page. Example output when installation is attempted with python 3.5:

```
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/shivar/.conda/envs/pgm:

The following NEW packages will be INSTALLED:

    decorator:       4.1.2-py35h3a268aa_0             
    intel-openmp:    2018.0.0-hc7b2577_8              
    libgfortran-ng:  7.2.0-h9f7466a_2                 
    mkl:             2018.0.1-h19d6760_4              
    networkx:        2.0-py35hc690e10_0               
    numpy:           1.13.3-py35hd829ed6_0            
    pandas:          0.22.0-py35hf484d3e_0            
    pgmpy:           0.1.6-py35h8fcecb5_0   ankurankan
    pyparsing:       2.2.0-py35h041ed72_1             
    python-dateutil: 2.6.1-py35h90d5b31_1             
    pytz:            2017.3-py35hb13c558_0            
    scipy:           1.0.0-py35hcbbe4a2_0             
    six:             1.11.0-py35h423b573_1            
    wrapt:           1.10.11-py35hfdafd39_0           

Proceed ([y]/n)?
```

### Actual behaviour
This is the output instead:

```
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pgmpy -> python >=2.7,<2.8.0a0
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

The installation goes through fine if python 3.5 is chosen instead of 3.6, as noted above.

**Comment by ankurankan** [comment]
@shivariyer That's happening because we haven't uploaded conda packages for python > 3.5. I will try to do that ASAP. In the meanwhile if you would like to use pgmpy on python 3.6, you can simply build from the source.

**Comment by shivariyer** [comment]
Thanks @ankurankan ! I am happy using Python 3.5 for now. Just wanted to bring this up.

**Comment by AmitaiPerlstein** [comment]
@ankurankan thak you for your reply. 
I get a similar behaviour when trying to create an environment with python 2.7. The conflict I get is with six 1.11.0 py36h372c433_1 
I see though that six is a package for python 2 - 3 compatability utilities. May I build the whole environment without it, given that I wish the environment to be 2.7 ?

**Comment by ankurankan** [comment]
@AmitaiPerlstein There shouldn't be any problem in running on python 2.7. Could you please share the whole traceback of the error you are getting ?

**Comment by AmitaiPerlstein** [comment]
@ankurankan I'm afraid I haven't explained myself properly. 
I use Ananconda3. I try to create an environment, named 'Detectron', that will run software with python2.7:

```
(Detectron) administrator@ALGO-Amitai:~$ conda install python=2.7
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - defaults/linux-64::six==1.11.0=py36h372c433_1 -> python[version='>=3.6,<3.7.0a0']
  - python=2.7
Use "conda info <package>" to see the dependencies for each package.

(Detectron) administrator@ALGO-Amitai:~$ 
```
