### ISSUE TITLE
MLE for Markov Network

### ISSUE THREAD

**Issue by RishabGoel** [pgmpy/pgmpy#974]
### Subject of the issue
Is there MLE for Markov Model? If not, is there some place where I can get the code for the same?

**Comment by ankurankan** [comment]
@RishabGoel No we don't have support for learning in `Markov Models` yet.

>  If not, is there some place where I can get the code for the same?

I am not sure about that and it will depend on your application. But you can look into: https://github.com/jmschrei/pomegranate
