### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by fcole90** [pgmpy/pgmpy#981]
### Subject of the issue
If you go on [http://pgmpy.org/](http://pgmpy.org/) and click on *Learning Bayesian Networks from data* you find the link to be broken. 

The correct link should be: [https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/9.%20Learning%20Bayesian%20Networks%20from%20Data.ipynb](https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/9.%20Learning%20Bayesian%20Networks%20from%20Data.ipynb)

### Steps to reproduce
Go on [http://pgmpy.org/](http://pgmpy.org/) and click on *Learning Bayesian Networks from data*, you find the link to be broken. 

### Expected behaviour
The link should bring to [https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/9.%20Learning%20Bayesian%20Networks%20from%20Data.ipynb](https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/9.%20Learning%20Bayesian%20Networks%20from%20Data.ipynb) instead.

### Actual behaviour
The link brings to: [https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/Learning%20Bayesian%20Networks%20from%20Data.ipynb](https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/Learning%20Bayesian%20Networks%20from%20Data.ipynb)

**Comment by ankurankan** [comment]
@fcole90 Thanks for reporting this. I will fix this ASAP.

**Comment by JustinTervala** [comment]
If this issue is resolved, can we close it?

**Comment by khalibartan** [comment]
Resolved in #992
