### ISSUE TITLE
Errors running tests on fresh clone

### ISSUE THREAD

**Issue by JustinTervala** [pgmpy/pgmpy#999]
### Subject of the issue
I encounter a lot of errors running the tests on the dev branch on a fresh clone of the project Python 2.7 
I get 92 errors and 34 failures and 8 skips.

### Your environment
* dev branch
* 2.7, but could be on other versions too
* Ubuntu 16.04

### Steps to reproduce
Clone the repo and run the tests

### Expected behaviour
I expect the tests to pass, so I know if a feature I am working on can pass

### Actual behaviour
I get 92 errors and 34 failures

**Comment by khalibartan** [comment]
@JustinTervala I'm not seeing any errors. Yes, we are skipping 8 tests, but I don't see any test failures or errors while running tests on python2.7. Can you please check your env dependencies.

**Comment by ankurankan** [comment]
@JustinTervala Could you share the output of `pip freeze` ?

**Comment by JustinTervala** [comment]
My pip freeze outputs
```
decorator==4.2.1
funcsigs==1.0.2
mock==2.0.0
networkx==1.11
nose==1.3.7
numpy==1.11.3
pandas==0.19.2
pbr==4.0.1
pyparsing==2.2.0
python-dateutil==2.7.2
pytz==2018.3
scipy==0.18.1
six==1.11.0
wrapt==1.10.8
```
Edited after I installed requirements-dev.txt and got similar results

**Comment by ankurankan** [comment]
@JustinTervala The versions of requirements seem to be the same in my env. Could you share the errors that you were getting in the failing tests ?
